shell/app/modules/project/common/components/issue/issue-relation.tsx
1.The view related with the task in the requirement can remain the original view after clicking OK, and only refresh the list below, keeping the query criteria area 
Fixes #
onOk(val) is not a Promise, so use async ... await wrapped it
=> feat: keep displaying issue form after saving related issue

shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
Fixed setting up test set the first time and showing it
Fixes #
Fixed setting up test set the first time and showing it
currentTestSet is reassigned with the same value, causing the TreeData to be incorrectly overwritten after the rerender
=> fix: show test set after first adding it

shell/app/modules/application/common/yml-editor/pipeline-yml/pipeline-editor.tsx, shell/app/modules/application/pages/pipeline/config-detail/index.tsx, shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx, shell/app/modules/application/pages/repo/components/audit-template-manager.tsx, shell/app/modules/application/pages/repo/components/repo-editor.tsx, shell/app/modules/application/pages/repo/components/repo-file-container.tsx, shell/app/modules/application/pages/repo/components/repo-mr-form.tsx, shell/app/modules/application/pages/repo/components/repo-nav.tsx, shell/app/modules/application/pages/repo/components/yml-editor.tsx, shell/app/modules/application/types/repo.d.ts
For warning user when create same name file or folder.
Fixes #
=> feat: add enum 'update' in commit api action field

shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx, shell/app/modules/project/stores/test-set.ts
To optimize the fix of  [fix: show test set after first adding it #136] last time.
Fixes #
=> Hotfix: display test set after adding it in first time

shell/webpack.config.js
duplicate compile loader which cause double compile time. So remove babel-loader for now
Fixes #
=> rm useless babel-loader

shell/app/org-home/stores/org.tsx, shell/app/user/stores/_perm-org.ts
update auth which from entryWorkbench to workBench
Fixes #
=> Hotfix: replace entryWorkbench to workBench

shell/app/App.tsx
Register module with router data will init routeInfo at first of all, otherwise routeInfo will be old data when get in subscription.
Fixes #
=> fix: register module which have router data first

shell/app/layout/common/invite-to-org.tsx, shell/app/org-home/stores/org.tsx
1. if the user joined the organization, it will redirect personal home page(current organization) when the user enter /orgName/inviteToOrg
2. if the user don't joined the organization, it will jump to personal home page(just joined organiztion) after joining successfully
Fixes #
=> Hotfix: jump to personal home page after joining it

shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
cluster overview display coloring percentage
Fixes #
=> feat: cluster overview display coloring percentage

cli/bin/erda.ts, cli/lib/build.ts, cli/lib/release.ts
1) the dependent projects like erda-ui-enterprise may not be the correct branch when executing release branch. As a result, the dists of admin and fdp will be wrong. Considering the injected modules may not be only from 'erda-ui-enterprise' in the future, we should check every branch of these modules.
2) add option of "-m --sourceMap" to skip the nonessential step;
3) add options of '-l' to command 'release' so that this command will not be limited by option "image"
Fixes #
=> feat: add erda-ui-enterprise branch check

shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
This bug has been fixed before，Reason for recurrence is the operation that in feat: pick code from old release (#36)。
before:
after misoperation:
Fixes #
=> Hotfix: keep query in manul test when refresh it

shell/app/modules/project/common/components/issue/issue-relation.tsx
separate related-issue buttons to prevent users from treating it as a tab
Fixes #
before:
current:
=> feat: separate related-issue buttons

shell/app/common/components/contractive-filter.tsx, shell/app/config-page/components/issue-kanban.tsx
feat: support issue kanban load more
Fixes #
=> feat: support issue kanban load more

shell/app/common/components/add-member-modal.tsx
hide application authorization when adding members in orgCenter
Fixes #
=> feat: hide application authorization when adding members in orgCenter

shell/app/modules/org/pages/projects/create-project.tsx, shell/app/modules/project/common/components/section-info-edit.tsx, shell/app/modules/project/pages/settings/components/project-info.tsx
When the user enters the project settings page，it shouldn't trigger the interface request about getClusterList and getLeftResources, when the user edit project(Modal), it can trigger it
Fixes #
=> fix: get clusterList and leftResources when edit project Modal

shell/app/modules/org/pages/projects/create-project.tsx, shell/app/modules/project/common/components/section-info-edit.tsx, shell/app/modules/project/pages/settings/components/project-info.tsx
When the user enters the project settings page，it shouldn't trigger the interface request about getClusterList and getLeftResources, when the user edit project(Modal), it can trigger it.
Fixes #
=> fix: get clusterList and leftResources when edit project Modal (#403)

shell/app/layout/pages/message/message.tsx, shell/app/layout/pages/page-container/components/sidebar.tsx
1. keep the bell icon (personal notification) in the sidebar
2. don't trigger interface of mbox without organization
Fixes #
=> fix: prevent getting stats without organization

shell/app/layout/pages/page-container/components/sidebar.tsx
hide icon that jump to personal home when the user is admin
Fixes #
=> fix: hide icon that jump to personal home when the user is admin

shell/app/layout/pages/message/message.tsx, shell/app/layout/pages/page-container/components/sidebar.tsx
it has been merged to release/1.0,  can't cherry-pick to master.
1. hide icon that jumps to personal home when the user is admin
2. prevent getting stats without organization
3. skip warning message when the user doesn't join any organization
Fixes #
=> fix: some issue about that  jump to personal home

shell/app/common/__tests__/components/lazy-render.test.tsx, shell/app/common/components/lazy-render.tsx
Even though it has entered the view, the value of 'intersectionRatio' is still 0，so update 'intersectionRatio' to 'isIntersecting'
Fixes #
=> fix: Api list render

shell/app/modules/cmp/common/custom-alarm/index.tsx
The interface data is returned incorrectly. The back-end suggests hiding the preview button temporarily
Fixes #
=> Hotfix: hide preview button  in custom alarm modal

shell/app/modules/application/pages/build-detail/index.tsx, shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx, shell/app/modules/application/stores/build.ts
1. jump out when clicking the link (to solve jump to another page with tooltip)
2. Re-request getBuildRuntimeDetail when entering pipeline-run-detail-page
Fixes #
=> fix: jump out when click link and getBuildRuntimeDetail when in the page

README.md, shell/app/layout/common/invite-to-org.tsx, shell/app/modules/application/pages/build-detail/index.tsx, shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
* Textarea ref state no longer exist on Antd 4.x， see https://github.com/ant-design/ant-design/pull/29095
* auto trim invitation code
release/1.1
Fixes #
=> Fix: refactor deprecated get inner state by ref

shell/app/modules/cmp/common/alarm-strategy/index.tsx
fix alarm-strategy table style bug.
release/1.1
Fixes # alarm-strategy table style bug
=> fix: alarm-strategy table style bug

shell/app/modules/cmp/common/alarm-record/index.tsx, shell/app/modules/dcos/pages/cluster-dashboard/alarm-record.tsx
remove redundant filters and fields in alarm record,  remove:
1. filters: 'handle status'  & 'assignee'
2.fields in table: 'handle status' & 'assignee' & 'handle time'
master && release/1.1
Fixes #
=> fix: remove redundant filters and fields in alarm record

shell/app/config-page/components/table/render-types.tsx
zero cannot display normally 
before:
now:
Fixes #
=> fix: display number zero in table of config-page

README.md, shell/app/modules/application/services/deploy.ts
pass `all=true` will list deprecated addon, so update the search query.
release/1.1
Fixes #
=> fix: get only public extension when edit erda.yml

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
fix cluster list type icon show incomplete.
Fixes # cluster list type icon show incomplete
=> fix: cluster list type icon show incomplete

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx, shell/app/modules/cmp/pages/cluster-manage/index.tsx
copywriting issue
command drawer shown when creating edas issue
release/1.1
Fixes #
=> copywriting issue & command drawer shown when creating edas issue

shell/app/modules/application/pages/release/components/release-detail-yml.tsx, shell/app/modules/application/pages/release/release-list.tsx, shell/app/modules/cmp/pages/alarm-report/report-records/index.tsx, shell/app/modules/msp/monitor/project-report/pages/project-report.tsx, shell/app/modules/project/pages/backlog/iteration-item.tsx
1. get yml when switching releaseId
2. fix init total is 0 results in current page is 0
Fixes #
=> Fix: get yml when switch releaseId

shell/app/modules/runtime/common/components/slide-panel-tabs.scss
**before:**
**current**
Fixes #
=> fix: display tab normally in container monitor

shell/app/modules/cmp/pages/middleware-dashboard/index.scss
fix cmp-addon query text too long bug.
| 🇺🇸 English | Fixed style problem when extended query column item name is too long. |
| 🇨🇳 中文    |  解决了扩展查询栏项目名过长时的样式问题。 |
Fixes # cmp-addon query text too long bug
=> fix: cmp-addon query text too long bug

shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx, shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx, shell/app/modules/cmp/pages/cluster-manage/index.tsx
edas cluster form add verification method field just like k8s
removed cluster address & Registry Address field
| 🇺🇸 English | edas cluster form add verification method field |
| 🇨🇳 中文    | edas 集群表单添加认证方式字段 |
Fixes #
=> feat(cmp): edas cluster form add introduce config & remove 2 fields

shell/app/common/__tests__/components/edit-field.test.tsx, shell/app/common/components/edit-field.tsx, shell/app/styles/antd-extension.scss, shell/tailwind.config.js
fix required items field is not marked.
->
| 🇺🇸 English | Fixed a bug where required items for project collaboration did not have required tags. |
| 🇨🇳 中文    |  修复了项目协同的必填项没有必填标记的bug。 |
Fixes # required items field is not marked
=> fix: required items field is not marked

shell/app/modules/project/pages/backlog/issue-item.tsx
fix backlog add item validate style bug.
| 🇺🇸 English | issue-backlog add item validate style bug.  |
| 🇨🇳 中文    | 项目协同-待处理中添加事项触发校验样式问题。 |
release/1.1
Fixes # backlog add item validate style bug.
=> fix: backlog add item validate style bug

shell/app/common/__tests__/components/edit-field.test.tsx, shell/app/common/components/edit-field.tsx
fix issue edit datepicker bug.
❎ No
| 🇺🇸 English | Fixed a bug where the month of the datepicker in edit-issue could not be changed.|
| 🇨🇳 中文    | 修复了事项编辑中日期选择框月份不能翻页的bug。 |
release/1.1
Fixes # issue edit datepicker bug
=> fix: issue edit datepicker bug

shell/app/common/components/edit-field.scss, shell/app/common/components/edit-field.tsx, shell/app/common/components/markdown-editor/index.scss, shell/app/common/components/markdown-editor/index.tsx, shell/app/config-page/components/action-form.tsx, shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx, shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx, shell/app/modules/project/common/components/issue/issue-drawer.tsx
fix(1.1): update markdown editor style
| 🇺🇸 English |     update markdown editor style         |
| 🇨🇳 中文    |     修改markdown编辑器样式         |
Fixes #
=> fix(1.1): update markdown editor style

shell/app/common/components/members-table.tsx
increase the width of member table.
| 🇺🇸 English | increase the width of member table. |
| 🇨🇳 中文    | 增加了成员表格的宽度。 |
release/1.1
Fixes # increase the width of member table.
=> fix: increase the width of member table

shell/app/modules/project/pages/plan-detail/columns/index.tsx
fix test-case table directory row bug.
| 🇺🇸 English | The rows representing directory in the test-case table show one more column of interface pass rate. |
| 🇨🇳 中文    | 测试用例表格中代表文件夹的行多显示了一列接口通过率。 |
Fixes # test-case table directory row bug.
=> fix: test-case table directory row bug

shell/app/common/components/file-editor.scss
modify the place of action buttons in FIleEditor to avoid overlapping with the close button
Fixes #
=> fix: modify the place of action buttons in FIleEditor

core/src/nusi/wrapped-table.tsx
table rowClick add cursor pointer.
❎ No
| 🇺🇸 English | Adds a mouse over table row style to a table with row click events. |
| 🇨🇳 中文    | 给有行点击事件的表格加上鼠标移入表格行的样式。 |
Fixes # table rowClick add cursor pointer.
=> fix: table rowClick add cursor pointer

shell/app/common/components/render-formItem.tsx, shell/app/modules/cmp/pages/networks/common/config.tsx, shell/app/styles/util.scss
fix: fix custom label require error
❎ No
| 🇺🇸 English |     fix: fix form custom label require validate error         |
| 🇨🇳 中文    |     修复form表单中自定义label必填校验错误         |
/cherry-pick release1.1
Fixes #
=> fix: fix form custom label require error

shell/app/common/components/markdown-editor/index.tsx
fix md editor button style
| 🇺🇸 English |     fix md editor button style         |
| 🇨🇳 中文    |   修复markdown编辑器按钮样式问题           |
Fixes #
=> fix(1.1): fix md editor button style

shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
fix test-case tree expand bug.
| 🇺🇸 English | Fixed bugs where the left arrow is not facing the right side when the left tree of the test-case is expanded, and when the child node is clicked, the parent node occasionally collapses..  |
| 🇨🇳 中文    | 解决了测试用例左侧树展开时左侧箭头朝向不对，以及点击子节点时，父节点偶尔会收起的bug。 |
release/1.1
Fixes # test-case tree expand bug.
=> fix: test-case tree expand bug

shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
fix case-table some rows beyond the right bug.
| 🇺🇸 English | case-table some rows beyond the right. |
| 🇨🇳 中文    | 测试用例表格中某些行超出右侧。 |
Fixes # case-table some rows beyond the right.
=> fix: case-table some rows beyond the right

core/src/nusi/index.tsx
replace Nusi Affix and InputNumber with Antd.
❎ No
| 🇺🇸 English | replace Nusi Affix and InputNumber with Antd. |
| 🇨🇳 中文    | 将Affix和InputNumber从Nusi迁移至Antd。 |
Fixes # replace Nusi Affix and InputNumber with Antd.
=> refactor: replace Nusi Affix and InputNumber with Antd

shell/app/org-home/router.js
Can't jump to organization list page normally, the bug due to the following changes
Fixes #
=> fix: jump to organization list page normally

shell/app/common/components/render-formItem.tsx
fix: skip checking rule if the type is hidden
❎ No
Fixes #
=> fix: skip checking rule if the type is hidden

shell/app/modules/cmp/common/alarm-state.tsx, shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
icon color should be white.
keep active machine list tab after click cluster in cluster overview.
| 🇺🇸 English | fix alarm state icon color is dark |
| 🇨🇳 中文    |修复告警列表图标颜色为黑色的问题 |
Fixes #
=> Fix: alarm state icon color

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.scss
fix trace debug body textarea style bug.
| 🇺🇸 English | The Textarea of the trace debug body is too long to see the Tab.  |
| 🇨🇳 中文    | 链路调试body的文本域过长时看不见上面的标签页。  |
release/1.1
Fixes # trace debug body textarea style bug
=> fix: trace debug body textarea style bug

shell/app/common/components/log/log-content.tsx, shell/app/common/components/runtime/simple-log-roller.tsx, shell/app/interface/global.d.ts, shell/app/modules/runtime/common/logs/components/container-log.jsx
ansi_up will escapes any unsafe HTML characters, which cause the mismatch bug.
❎ No
Fixes #
=> fix: restore escaped quotes in log content

shell/app/common/components/details-panel.tsx, shell/app/common/components/load-more-selector.tsx, shell/app/common/components/log/log-content.tsx, shell/app/common/components/runtime/simple-log-roller.tsx
fix deploy create releaseId select style bug.
->
| 🇺🇸 English | Fixed the width bug of the deploy center artifact ID select. |
| 🇨🇳 中文    | 修复了部署中心创建时制品id选择框下拉的宽度bug。 |
release/1.2
Fixes # deploy create releaseId select style bug.
=> fix: deploy create releaseId select style bug

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx, shell/app/styles/antd-extension.scss
add edas cluster operations & fix inline form wrap issue
| 🇺🇸 English |  add register command & retry init operations to edas cluster          |
| 🇨🇳 中文    |  edas集群添加注册命令与初始化重试操作菜单          |
release/1.2
Fixes #
=> add edas cluster operations & fix inline form wrap issue

shell/app/common/__tests__/components/log/download-log-modal.test.tsx, shell/app/common/__tests__/components/tree/tree.test.tsx, shell/app/common/components/log/download-log-modal.tsx
fix the bug that the log cannot be downloaded using the default duration
❎ No
| 🇺🇸 English | fix the bug that the log cannot be downloaded using the default duration |
| 🇨🇳 中文    | 修复使用默认时长无法下载日志的bug |
release/1.2
Fixes #
=> fix the bug that the log cannot be downloaded using the default duration

pnpm-lock.yaml, shell/app/common/components/markdown-editor/index.scss, shell/app/common/components/markdown-editor/index.tsx, shell/app/modules/project/common/components/issue/comment-box.tsx, shell/package.json
* disable show editor and preview at the same time
* hide toolbar buttons when preview content
* hide toggle toolbar arrow
* always show bottom button group
| 🇺🇸 English | update markdown editor interaction and style |
| 🇨🇳 中文    |  更新 markdown 编辑器交互和样式 |
❎ No
Fixes #
=> feat: update markdown editor interaction and style

shell/app/common/__tests__/components/img-holder.test.tsx, shell/app/common/components/img-holder.tsx
when encode some character such as emoji, will throw error and cause page crash.
✅ No
| 🇺🇸 English | Fix the crash problem that may occur when adding members with nicknames of special characters |
| 🇨🇳 中文    | 修复添加成员时昵称为特殊字符可能出现的崩溃问题 |
release/1.2
Fixes #
=> fix: encode some character error with encodeURI

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-history-list.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
add reset-button
| 🇺🇸 English |      [monitoring] link debugging, add reset button and clear all contents of the page        |
| 🇨🇳 中文    | 【监控】链路调试，添加重置按钮，清空页面所有内容         |
❎ No
Fixes #
=> feat(msp): add reset-button

shell/app/common/components/key-value-table.tsx, shell/app/styles/antd-extension.scss, shell/app/styles/app.scss
fix trace debug add params style bug.
-> 
| 🇺🇸 English | In the trace-debug, the text prompt that the form verification fails when adding parameters is not displayed completely. |
| 🇨🇳 中文    | 在链路调试中，添加参数时表单校验不通过的文字提示显示不完全。 |
release/1.2
Fixes # trace debug add params style bug
=> fix: trace debug add params style bug

shell/app/modules/cmp/common/alarm-strategy/index.tsx
Use alertIndex as option's key is repeated, use id as its key.
❎ No
release/1.1,  release/1.2
Fixes #
=> Hotfix: modify key of option to id in strategy

shell/app/modules/project/common/components/issue/issue-relation.tsx
fix(1.2): fix issue releations error
❎ No
| 🇺🇸 English |    fix issue relations error after change to backlog        |
| 🇨🇳 中文    |     修复事项详情中，一键转待办后，关联事项数据错误         |
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204825&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
=> fix(1.2): fix issue releations error

shell/app/modules/project/pages/backlog/backlog.scss
backlog table pagination style bug.
->
| 🇺🇸 English | Fixed a bug where two scrollbars appeared when the project was scrolled in the backlog table. |
| 🇨🇳 中文    | 修复了项目协同待处理列表滚动时出现两个滚动条的bug。 |
release/1.2
Fixes # backlog table pagination style bug
=> fix: backlog table pagination style bug

shell/app/modules/application/pages/repo/repo-branch.tsx
always show search input
❎ No
| 🇺🇸 English | fix the bug that the search box does not display when the data is empty |
| 🇨🇳 中文    | 修复空数据时搜索框不显示的bug |
release/1.2
Fixes #
=> always show search input

shell/app/common/utils/str-num-date.tsx, shell/app/modules/application/pages/repo/components/repo-file-container.tsx, shell/app/modules/application/stores/repo.ts
fix: fix repo file delete error
❎ No
| 🇺🇸 English |   fix api error after repo file been deleted           |
| 🇨🇳 中文    |      修复repo中删除文件后接口报错        |
Fixes #
=> fix(1.2): fix repo file delete error

shell/app/modules/runtime/common/components/slide-panel-tabs.tsx
modify the tab to IP address in container monitor
❎ No
Fixes #
=> Fix: modify the tab to IP address in container monitor

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
hide register command when cluster registered
❎ No
release/1.2
Fixes #
=> feat(cmp): hide register command when cluster registered

shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
remove the items-center of case-drawer
❎ No
release/1.2
Fixes #
=>  remove the items-center of case-drawer

pnpm-lock.yaml, shell/package.json
choose chart type before saving in dashboard
❎ No
release/1.2
Fixes #
=> fix: choose chart type before saving in dashboard

shell/app/modules/application/pages/repo/repo-tag.tsx
fix source type change bug after submit in add tag form.
❎ No
| 🇺🇸 English | Fixed a bug when changing the source type for the first time after resetting the form after a form submission error was reported while adding tags. |
| 🇨🇳 中文    | 修复了添加标签时，在表单提交报错重置表单之后，第一次切换源类型时的bug。 |
release/1.2
Fixes # in add tag form, source type change bug after submit
=> fix: in add tag form, source type change bug after submit

shell/app/common/components/members-table.tsx, shell/app/common/constants.ts
Some time the domain is not the current org, eg: erda-org.erda.cloud/playground, invite url will confuse users.
❎ No
❎ No
=> feat: use root domain in invite url

shell/app/styles/antd-extension.scss
fix Select in nusi Form width style bug.
->
| 🇺🇸 English |  Fixed a bug where the width of the drop-down box in some forms was not covered.  |
| 🇨🇳 中文    | 修复了一些表单中下拉框宽度不铺满的bug。   |
release/1.2
Fixes # Select in nusi Form width style bug
=> fix: Select in nusi Form width style bug

shell/app/layout/pages/page-container/page-container.tsx
fix page-container Card style bug.
->
| 🇺🇸 English | Fixed an API design bug that did not display empty page icon when the page had no branches. |
| 🇨🇳 中文    | 解决了api设计页面无分支时不显示空页面图标的bug。 |
release/1.2
Fixes # page-container Card style bug
=> fix: page-container Card style bug

shell/app/modules/org/pages/safety/index.tsx
Support render br for long audit content.
| 🇺🇸 English |  Audit log supports newline rendering  |
| 🇨🇳 中文    |  审计日志支持换行渲染  |
❎ No
=> feat: support render newline in audit template

core/package.json, core/src/utils/ws.ts, pnpm-lock.yaml, scheduler/src/main.ts, scheduler/src/proxy.ts, shell/package.json
fix websocket throw 403 error issue after migrate to node server
❎ No
❎ No
Fixes #
=> fix(scheduler): fix websocket 403 issue

core/src/history.ts, core/webpack.config.js, shell/app/App.tsx, shell/app/common/__tests__/components/error-boundary.test.tsx, shell/app/common/__tests__/utils/query-string.test.tsx, shell/app/common/utils/go-to.tsx, shell/tsconfig.json
fix: fix history listen execute twice
❎ No
| 🇺🇸 English |       fix: fix history listen execute twice       |
| 🇨🇳 中文    |      fix: 修复路由监听执行两次        |
release/1.2
Fixes #
=> fix: fix history listen execute twice

shell/app/config-page/components/file-tree/file-tree.spec.d.ts, shell/app/config-page/components/file-tree/file-tree.tsx
fix: fix file tree select none
❎ No
| 🇺🇸 English |    fix: fix file tree select none          |
| 🇨🇳 中文    |   fix: 修复file-tree组件选中为空           |
release/1.2
Fixes #
=> fix: fix file tree select none

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx, shell/app/modules/project/common/components/issue/issue-drawer.tsx
add confirmation when issue-drawer esc keydown.
❎ No
Fixes #
=> feat: add confirmation when issue-drawer esc keydown

shell/app/common/types/pipeline.d.ts, shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx, shell/app/modules/application/pages/pipeline/run-detail/build-log.tsx
action show multiple instances log.
| 🇺🇸 English | Multiple container instance logs can be displayed. |
| 🇨🇳 中文    | Aciton 支持展示多容器实例日志。 |
❎ No
Fixes #
=> feat: action show multiple instances log

shell/app/common/components/file-editor.tsx, shell/app/locales/en.json, shell/app/locales/zh.json
fix: fix file editor data exceed
| 🇺🇸 English |    fix: download check detail when the content of the file editor exceed the limit          |
| 🇨🇳 中文    |     feat: 文件编辑器内容超过限制时转为下载查看      |
❎ No
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=208387&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
=> fix: fix file editor data exceed

shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
Websocket is not stable, pipeline status is often not udpate until manual refresh page. Add a timer to get status.
❎ No
| 🇺🇸 English | auto fresh pipeline status every 10 seconds  |
| 🇨🇳 中文    | 每隔 10s 自动刷新流水线状态  |
❎ No
Fixes #
=> fix(dop): add timer to loop get pipeline status until websocket is stable

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
fix cluster list operate more btn style bug.
->
❎ No
Fixes #
=> fix: cluster list operate more btn style bug

shell/app/modules/publisher/pages/artifacts/version-list.tsx, shell/app/modules/publisher/types/publisher.d.ts
version-list of publisher add aab file download button.
| 🇺🇸 English | In my publisher version-list, added aab file download button.   |
| 🇨🇳 中文    |  在我的发布的版本内容中，增加aab文件的下载按钮。 |
❎ No
Fixes #
=> feat: version-list of publisher add aab file download button

shell/app/modules/cmp/common/utils.ts
Replace lookbehind in regular expression for Safari don't support it.
❎ No
❎ No
Fixes #
=> fix: replace lookbehind in regular expression

core/src/nusi/wrapped-table.tsx, shell/app/styles/antd-extension.scss
table style adjustment.
❎ No
| 🇺🇸 English | 1、Remove the fixed righ of the operation item; 2、Adjust all tables to the same size. |
| 🇨🇳 中文    | 1、去掉操作项的右侧固定； 2、调整所有表格大小一致。 |
❎ No
Fixes #
=> feat: table style adjustment

shell/app/modules/publisher/pages/artifacts/version-list.tsx
My-publisher version-list add aab Tab.
| 🇺🇸 English | In my-publisher version-list, add Android App Bundle Tab.  |
| 🇨🇳 中文    | 我的发布-版本内容中，新增Android App Bundle标签页 |
❎ No
Fixes #
=> feat: my-publisher version-list add aab Tab

shell/app/locales/zh.json, shell/app/menus/project.tsx, shell/app/modules/project/router.js, shell/app/modules/project/tabs.tsx
Adjust the dashboard position.
| 🇺🇸 English | move the dashboard under the project collaboration  |
| 🇨🇳 中文    | 把项目大盘移到了项目协同下 |
❎ No
Fixes #
=> feat(dop): move the dashboard under the project collaboration

shell/app/common/components/log/log-roller.scss, shell/app/modules/application/pages/pipeline/run-detail/build-log.tsx
fix pipeline log height is not 100% bug.
->
| 🇺🇸 English |  fix a bug where pipeline log height is not 100. |
| 🇨🇳 中文    | 修复了流水线日志的高度没有100%的bug。  |
❎ No
Fixes #
=> fix: pipeline log height is not 100%

shell/app/modules/application/pages/repo/components/repo-file-container.tsx
fix: back to valid parent path after delete repo file
❎ No
| 🇺🇸 English |   fix: back to valid parent path after delete repo file           |
| 🇨🇳 中文    | fix: 删除文件后返回有效的父级文件夹           |
❎ No
Fixes #
=> fix: back to valid parent path after delete repo file

pnpm-lock.yaml, shell/package.json
Safari can not input Chinese with IME in textarea. See https://github.com/ianstormtaylor/slate/issues/2457#issuecomment-490319129
❎ No
| 🇺🇸 English | fix markdown editor can not input Chinese in Safari |
| 🇨🇳 中文    | 修复 Safari 下 markdown 编辑器无法输入中文的问题 |
❎ No
=> fix: markdown editor can not input Chinese in Safari

shell/app/config-page/components/container/container.scss
Fix persional-home style bug in Safari.
->
| 🇺🇸 English | Fixed persional-home style bug in Safari 13. |
| 🇨🇳 中文    | 修复了Safari 13浏览器下个人仪表盘的样式问题。 |
❎ No
Fixes # https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/bug?id=217707&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG
=> fix: persional-home style bug in Safari

shell/app/common/components/load-more.tsx, shell/app/layout/stores/message.ts, shell/app/modules/application/pages/repo/repo-commit.tsx, shell/app/modules/application/pages/repo/repo-tree.tsx, shell/app/modules/application/stores/dataTask.ts, shell/app/modules/application/stores/repo.ts, shell/app/modules/publisher/stores/publisher.ts
fix: fix un exist branch page request error
❎ No
| 🇺🇸 English |       fix: fix un exist branch page loop request error      |
| 🇨🇳 中文    |   fix: 修复无效分支的页面循环报错       |
❎ No
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=219295&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
=> fix: fix un exist branch page loop request error

shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.scss, shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.scss, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
display detail when hovering over the time span.
before:
now:
❎ No
Fixes #
=> fix: modify style of waterfall flow in trace detail

shell/app/styles/antd-extension.scss
table header should not be wrapped
❎ No
release/1.2
Fixes #
=> style: table header should not be wrapped

shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx, shell/app/modules/application/pages/deploy/runtime-box.tsx, shell/app/modules/msp/monitor/status-insight/index.js
* show view config button in addon card only in project scope
* remove space between Chinese words
* remove wrapper in status page 
❎ No
❎ No
Fixes #
=> fix: show view config button in addon card only in project scope

shell/app/modules/project/pages/test-manage/case/case-drawer/index.scss, shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
fix test-plan-drawer-folder-name-too-long.
->
| 🇺🇸 English |  Fixed style bug caused by folder name too long in test-plan detail drawer.  |
| 🇨🇳 中文    | 修复了测试管理-执行计划中详情划窗里文件夹名字过长导致的样式问题。  |
❎ No
Fixes #
=> fix: test-plan-drawer-folder-name-too-long

pnpm-lock.yaml, shell/app/common/components/edit-field.tsx, shell/package.json
Fix markdown editor update state logic, which cause duplicate Chinese words in Safari.
❎ No
❎ No
Fixes #
=> fix(dop): duplicate Chinese words in Safari when edit issue

shell/app/App.tsx, shell/app/org-home/stores/org.tsx
fix none admin user enter admin route permission issue
❎ No
❎ No
Fixes #
https://erda-org.app.terminus.io/erda/dop/projects/387/issues/all?id=220510&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTA5MTgiLCIxMDAwNTYyIiwiMTAwMTA3NSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
=> fix(admin): fix none admin user in admin route permission issue

shell/app/common/__tests__/components/tree/tree.test.tsx, shell/app/common/components/tree/tree.tsx
Fix config sheet tree drag bug in data bank.
❎ No
release/1.3
Fixes #
=> fix: data-bank config-sheet tree drag bug

shell/app/modules/project/common/components/pipeline-manage/common/config-env-selector.tsx
support use last execute cluster in project pipeline, prevent choose the wrong cluster.
❎ No
| 🇺🇸 English | The project-level pipelining execution defaults to the last cluster |
| 🇨🇳 中文    | 项目级流水线执行是默认选择上次的集群 |
release/1.3
release/1.2
Fixes #
=> feat(dop): support use last execute cluster in project pipeline

shell/webpack.config.js
we got build error while building shell, maybe caused by recent package update. according to github issue https://github.com/webpack-contrib/thread-loader/issues/124 . I remove thread-loader for now
❎ No
❎ No
Fixes #
=> fix(common): remove thread-loader to fix build crash issue

scheduler/src/filters/error-catch.filter.ts, shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/org/common/audit-render.tsx, shell/app/modules/org/pages/projects/issue-field-setting-modal.scss, shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx, shell/app/modules/project/common/components/issue-workflow-setting-modal.scss, shell/app/modules/project/common/components/issue-workflow-setting-modal.tsx, shell/app/modules/project/common/components/issue-workflow.tsx, shell/app/modules/project/pages/backlog/backlog.tsx, shell/app/modules/project/pages/issue/component/table-view.tsx, shell/app/modules/project/pages/ticket/index.tsx, shell/app/modules/project/stores/issue-workflow.ts, shell/app/modules/project/stores/project.tsx
* fix issue workflow state not update after edit, caused by split state.
* fix workflow modal style, show move and delete at the same time when hover on button, expand the modal width.
* edit issue field logic and style.
* show scheduler full exception in case of empty stack.
->
| 🇺🇸 English | fix issue workflow not show icon after edit, update style |
| 🇨🇳 中文    | 修复工作流编辑后不展示图标的问题，更新了样式  |
release/1.3
Fixes #
=> fix(dop): issue workflow not update after edit, update style

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
Fixed cluster list operate more btn wrong limitNum bug.
->
| 🇺🇸 English | The number of buttons in the action column of the cluster management table has changed from three to one.  |
| 🇨🇳 中文    | 集群管理表格操作列显示按钮数量从三个变成一个。 |
release/1.3
Fixes #
=> fix: cluster list operate more btn wrong limitNum bug

shell/app/common/__tests__/components/tree/tree.test.tsx, shell/app/common/components/tree/tree.scss, shell/app/common/components/tree/tree.tsx
Fixed tree width too wide bug.
->
| 🇺🇸 English | Fixed the bug of overlapping operations when the tree structure text with operations is too long. |
| 🇨🇳 中文    |  解决了带操作的树形结构文字过长时跟操作重叠的问题。  |
release/1.3
Fixes #
=> fix: tree width too wide bug

shell/app/modules/publisher/pages/artifacts/artifacts-detail.tsx
Error analysis and statistics big market interface display problem
release/1.3
Fixes #
=> hotfix(dop): Error analysis and statistics big market interface display problem

shell/app/common/components/log/log-roller.tsx, shell/app/common/components/members-table.tsx, shell/app/common/constants.ts, shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/project/pages/third-service/components/instance-form.tsx
* Previous change it to constant value, to prevent confusion invitation link such as:
`orgA-org.erda.cloud/inviteToOrg/orgB`. But the invite url domain is wrong in other environments.
* fix i18n problem
❎ No
release/1.3
Fixes #
=> fix: invite url wrong in other environments

shell/app/common/components/log/log-roller.tsx, shell/app/common/containers/log-roller.tsx
Remove log download button when not support download or no log.
❎ No
| 🇺🇸 English | only show download log button when have log or support download  |
| 🇨🇳 中文    | 查看日志时只有存在日志或支持下载时才显示下载按钮 |
release/1.3
Fixes #
=> fix: only show download log button when have log

shell/app/common/components/contractive-filter.tsx
fix: add contractive filter label icon
release/1.3
Fixes #
=> fix: add contractive filter label icon

shell/app/org-home/stores/org.tsx
fix: fix support role in public org permissions
❎ No
| 🇺🇸 English |   fix: fix support role permission error  in public org           |
| 🇨🇳 中文    |  fix: 修复support账号在公开组织中访问权限错误           |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=227652&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
=> fix: fix support role permission error  in public org

shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
hide alert when edit k8s form
❎ No
release/1.3
Fixes #
https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=227852&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTA5MTgiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
=> fix(cmp): hide alert when edit k8s form

shell/app/modules/msp/env-setting/configuration/index.tsx, shell/app/modules/msp/types/configuration.d.ts
The access configuration page removes the request parameter subjectType and retains the subject
❎ No
release/1.3
Fixes #
=> feat(msp): The access configuration page removes the request parameter subjectType and retains the subject

shell/app/config-page/components/api-editor/api-editor.tsx
allow exist same assertion
❎ No
release/1.3
Fixes #
=> allow exist same assertion

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx, shell/app/user/stores/_perm-project.ts
Creator and assignee can change issue type.
❎ No
| 🇺🇸 English |  Projects collaborate with item creators and handlers to increase the ability to modify item types. |
| 🇨🇳 中文    | 项目协同事项创建者和处理人增加修改项目类型的权限。  |
release/1.3
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=223554&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
=> fix(dop): creator and assignee can change issue type

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx, shell/app/modules/project/common/components/issue/issue-relation.tsx, shell/app/modules/project/pages/backlog/issue-item.tsx
Create issue in normal mode, will fill default values in custom fields, but not in quick add mode.
This pr will fill enumerated custom fields default value when quick add issue.
❎ No
| 🇺🇸 English | add default value for enumerated custom fields when quick create issue  |
| 🇨🇳 中文    |  快速创建事项时枚举类型的自定义字段填充默认值 |
release/1.3
Fixes #
=> fix(dop): add default value for custom fields when quick create issue

shell/app/modules/msp/env-setting/configuration/type-select.tsx
Change the right margin of text
| 🇺🇸 English |      Change the right margin of text        |
| 🇨🇳 中文    |       修改文字的右边距       |
release/1.3
Fixes #
=> feat(msp): Change the right margin of text

core/src/service/index.ts, shell/app/common/components/authorize-member-modal.tsx, shell/app/common/services/index.ts
* Add application filter in authorize modal
* add common usePaging function in core/service
| 🇺🇸 English | Add application filter in authorize modal |
| 🇨🇳 中文    | 授权弹框中新增按应用搜索 |
release/1.3
Fixes #
=> feat: add application filter in authorize modal

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx, shell/app/modules/project/common/issue-config.ts, shell/app/modules/project/pages/backlog/issue-item.tsx
Add template for quick create issue.
❎ No
❎ No
Fixes #
=> fix: apply issue template when quick create

scheduler/src/app.module.ts
max-age was removed mistakenly yesterday.
I found max-age is still required, otherwise it will always go to revalidate cache
❎ No
release/1.3
Fixes #
=> scheduler add max-age

scheduler/src/app.module.ts
mf file is the root of each sub module, should revalidate all the time
otherwise, user is still possible to load staled files
❎ No
release/1.3
Fixes #
=> fix(scheduler): add no-cache to mf files

shell/app/org-home/stores/org.tsx
1. if resOrg is empty, it's value is '{}'
2. back home page with joined org from notFound and freshMan page
❎ No
release/1.3
Fixes #
=> fix: click home page with joined org from notFound and freshMan page

shell/app/modules/application/pages/test/test-detail.tsx, shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
Adjust line-height of test case table. 
->
| 🇺🇸 English |  Adjust line-height of test case table.   |
| 🇨🇳 中文    |   调整测试用例表格的行高。  |
release/1.3
Fixes #
=> fix: adjust test case table td line-height

shell/app/modules/msp/env-overview/service-list/pages/index.tsx, shell/app/modules/msp/env-overview/topology/pages/topology-dashboard/index.tsx
only the access service button is displayed under the MSP item
❎ No
release/1.3
Fixes #
=> fix(msp): only the access service button is displayed under the MSP item

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
Fix label selector search bug in edit issue drawer.
->
| 🇺🇸 English | Fix label selector fuzzy search bug in edit issue drawer. |
| 🇨🇳 中文    | 修复了事项编辑抽屉中标签选择器的模糊搜索bug。  |
release/1.3
Fixes #https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=231294&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwic3RhdGVzIjpbNDQwMiw0NDAzLDcxMDYsNDQwNCw3MTA1LDcxMDQsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
=> fix(dop): label selector search bug in edit issue drawer

shell/app/modules/msp/monitor/browser-insight/pages/summary/summary.tsx
Fix front-end monitor summary card style bug of buttons wrap lines in small screen page.
->
release/1.4
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=217186&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG
=> fix(msp): front-end monitor summary card style bug in small screen page

shell/app/common/components/card-container/index.tsx
fix: add chart container tip style
release/1.4
Fixes #
=> fix: add chart container tip style

pnpm-lock.yaml, shell/package.json
fix: upgrade dashboard to fix get chart data failed
release/1.4
Fixes #
[【微服务总览】热点服务TOP5图表获取数据失败](https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D)
=> fix: upgrade dashboard to fix get chart data failed

shell/app/modules/msp/env-overview/service-list/pages/service-name-select.tsx
fix that did not display corresponding service name from the service list page
❎ No
release/1.4
Fixes #
[【服务列表】点击列表中的服务，跳转到服务概览页面，服务定位有错](https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D)
=> fix: did not display correspond service name from service list page

pnpm-lock.yaml, shell/package.json
the same as [https://github.com/erda-project/erda-ui/pull/1772)](1772) upgrade dashboard to fix get chart data failed
for v1.0.43 didn't pull the newest code
❎ No
release/1.4
Fixes #
=> fix: upgrade dashboard to  v1.0.44

shell/app/config-page/index.tsx, shell/app/modules/cmp/pages/cluster-manage/cluster-pod-detail.tsx, shell/app/modules/cmp/pages/cluster-manage/cluster-workload-detail.tsx
fix: fix refresh list after k8s detail delete
❎ No
| 🇺🇸 English |   fix: fix refresh list after k8s detail delete           |
| 🇨🇳 中文    |    fix:修复集群详情页删除后刷新列表错误        |
release/1.4
Fixes #
=> fix: fix refresh list after k8s detail delete

shell/app/antd-overwrite/table/index.tsx
Fix table sorter style bug in config page.
->
release/1.4
Fixes #
=> fix(common): table sorter style bug in config page

shell/app/antd-overwrite/table/index.scss, shell/app/common/components/table/index.scss, shell/app/common/components/table/index.tsx, shell/app/modules/org/pages/projects/project-list.tsx, shell/app/styles/antd-extension.scss
Table sorting style change back except for orgCenter.
->
❎ No
Fixes #
=> fix(common): sorting style change back except for orgCenter

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx, shell/app/modules/msp/monitor/status-insight/pages/status/status.tsx
1. Remove the background color of the Add button for exception checking 
2. Edit active monitoring, and the last saved value is displayed in the header 
3. In advanced settings, the number of retransmissions cannot be limited to decimal    
4. Edit the Title Modification of the active monitoring page 
5. Repair the monitoring details page and click Edit. The exception check in advanced settings cannot be edited
❎ No
| 🇺🇸 English |    1. Remove the background color of the Add button for exception checking 2. Edit active monitoring, and the last saved value is displayed in the header 3. In advanced settings, the number of retransmissions cannot be limited to decimal    4.  Edit the Title Modification of the active monitoring page 5. …
=> Actively monitor related bugs

shell/app/styles/antd-extension.scss
Fix table style bug caused by antd version upgrade.
->
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=240455&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=541&type=BUG
=> fix(common): table style bug caused by antd version upgrade

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
Fix: there is displaying loading status  when request is completed
release/1.4, release/1.3-hotfix
Fixes #
[【链路调试】点击请求后，请求按钮一直置灰，无法再次点击](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XSwiYXNzaWduZWVJRHMiOlsiMTAwMDcyMyIsIjI0IiwiMTAzOTAiLCIxMDAwMzAwIiwiMTA5MTgiLCIxMDAxMjE0IiwiMTAwMDU2MiIsIjEwMDEwNzUiLCIxMDAxNTc5Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=ey …
=> fix: there is displaying loading status  when request is completed

shell/app/common/utils/go-to.tsx, shell/app/modules/msp/pages/transfer/si.tsx, shell/app/modules/msp/router.ts
compatible with old data, si redirects to transaction 
**[fix(msp): replace monitor alarm page](https://github.com/erda-project/erda-ui-enterprise/pull/151)**
❎ No
release/1.4
release/1.3-hotfix
Fixes #
=> fix(msp): compatible with old data, si redirects to transaction

shell/app/config-page/components/copy-button/copy-button.mock.ts, shell/app/config-page/components/copy-button/copy-button.spec.d.ts, shell/app/config-page/components/copy-button/copy-button.tsx, shell/app/config-page/components/index.tsx
Copy wrap another component and triggered by that component, this is confused for backend developer.
Change to standalone copyButton component.
❎ No
release/1.4
Fixes #
=> refactor: rename copy to copyButton component in config-page

shell/app/modules/project/common/components/section-info-edit.tsx, shell/app/modules/project/pages/settings/components/project-info.tsx
Project quota edit optimization.
❎ No
| 🇺🇸 English | Do not close popover when editing fails when edit project quota. |
| 🇨🇳 中文    | 当编辑项目quota时，编辑失败不关闭弹窗。 |
release/1.4
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/bug?id=242421&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=541&type=BUG
=> fix(common): project quota edit optimization

shell/app/layout/pages/page-container/page-container.tsx, shell/babel.config.js
Revert overwrite style config, overwrite antd component do not need import style.
❎ No
release/1.4
Fixes #
=> Fix: revert import overwrite antd component style

shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
When actively monitoring and modifying the format of the body, the window will pop up only when there is data
❎ No
release/1.4
Fixes #
=> fix(msp): When actively monitoring and modifying the format of the body, the window will pop up only when there is data

shell/app/common/components/setting-tabs/index.tsx, shell/app/modules/project/pages/settings/components/project-cluster.tsx
fix: fix setting tabs scroll / project setting number fixed
❎ No
| 🇺🇸 English |    fix: fix setting tabs scroll / project setting number fixed          |
| 🇨🇳 中文    |    fix: 修复设置菜单跳动问题 / 项目设置中显示的小数错误          |
release/1.4
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=245966&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG …
=> fix: fix setting tabs scroll / project setting number fixed

shell/app/modules/project/pages/test-plan/test-plan.tsx
fix: add manual test plan table filter
| 🇺🇸 English |     fix: add manual test plan table filter         |
| 🇨🇳 中文    | fix: add manual test plan table filter             |
release/1.4
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222663&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG
=> fix: add manual test plan table filter

shell/app/common/components/panel/index.tsx
project detail quota data repeat bug
release/1.4
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=246894&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG
=> fix(common): project-detail-quota-data-repeat-bug

shell/app/common/components/table/index.scss, shell/app/common/components/table/index.tsx, shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.scss, shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx, shell/app/styles/_color.scss
fix: fix resource rank icon style
❎ N
release/1.4
Fixes #
=> fix: fix resource rank icon style

shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
The active monitoring page assigns the URL attribute in the config returned by the interface to the URL
❎ No
release/1.4
Fixes #
=> fix(msp): The active monitoring page assigns the URL attribute in the config returned by the interface to the URL

core/src/service/index.ts
currently post & put api will carry body as query string which is incorrect.
❎ No
release/1.4
Fixes #
=> fix(common): fix post put api carry extra query string issue

shell/app/modules/org/pages/projects/settings/info/index.tsx
In different page, project quota are displayed in different order.
->
release/1.4
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=247656&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG
=> fix(common): project quota are displayed in different order

locales/en.json, locales/zh.json, shell/app/common/utils/go-to.tsx, shell/app/layout/common/error-page.scss, shell/app/layout/common/error-page.tsx, shell/app/user/stores/permission.ts, shell/app/user/types/user.d.ts
1. jump to project member management when the project owner view app doesn’t have permission to
2. According to design recommendations，align content to the left 
before:
current:
| 🇺🇸 English | Project owner can jump to project member management settings when don’t have the app permission |
| 🇨🇳 中文    | 项目管理员在无应用权限时可以跳转至项目成员管理进行设置 |
❎ No
Fixes #
[项目管理员无法给自己赋应用的权限，因为页面无法获取应用名](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsI …
=> fix: the project owner view app doesn't have permission

shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
1. The URL cannot be modified when repairing editing
2. When repairing the selection of status code and request body, the data of operate is not displayed normally
❎ No
| 🇺🇸 English |     1.  The URL cannot be modified when repairing editing 2.  When repairing the selection of status code and request body, the data of operate is not displayed normally        |
| 🇨🇳 中文    |     1.   修复编辑时无法修改URL 2.   切换状态码和请求体的时候operate没有正常显示     |
release/1.4
release/1.4.1
Fixes #
=> fix(msp): fix defects related to active monitoring

shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
Fix the value problem of the URL of the event of losing focus in the editing and monitoring params of the active monitoring page
❎ No
release/1.4
release/1.4.1
Fixes #
=> Fix the value problem of the URL of the event of losing focus in the editing and monitoring params of the active monitoring page

shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx, shell/app/modules/org/pages/setting/notice-channel.tsx
1. compatible with old data
2. should not auto fill the AccessKeyId and AccessKeySecret 
❎ No
release/1.4.1
Fixes #
[【告警】旧的数据升级后，告警规则、通知对象中的告警基级别显示有错](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D)
[【告警】进入告警列表页面，第一次打开告警规则的编辑页面，过滤规则的值字段不能编辑](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__ …
=> fix: alarm compatible with old data

shell/app/common/components/table/index.scss, shell/app/common/components/table/index.tsx
Table add hide header and adjust line height.
->
❎ No
Fixes #
=> refactor(common): table add hide header and adjust line height

shell/app/charts/components/monitor-chart-new.jsx
Fix  memory limit display bug in runtimes container monitor.
->
release/1.4
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=248120&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG
=> fix(dop): in runtimes container monitor, memory limit display bug

pnpm-lock.yaml, shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx, shell/package.json
1. display chart in overview of service
2. display chart in chart editor
the same as [fix: upgrade dashboard to v2.0.1 #2007](https://github.com/erda-project/erda-ui/pull/2007/files)
❎ No
❎ No
Fixes #
[【服务分析】使用ES存储trace/error和log数据后，服务概览中有图表显示有问题](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D) …
=> fix: upgrade dashboard to v2.0.1

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/cmp/common/alarm-strategy/index.tsx
display groups in notification object(msp & cmp)
before:
current:
| 🇺🇸 English |  In MSP and CMP,  change the display content of the notification object of the notification strategy to display all notification groups instead of person  |
| 🇨🇳 中文    | 在微服务平台和多云管理平台中，将通知策略的通知对象显示内容改为显示所有通知组别而不是个人 |
release/1.4.1
Fixes #
[【告警】告警策略列表，当添加多个通知组时，列表中通知对象字段只显示了第一个](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhY …
=> fix: display groups in notification object(msp & cmp)

cli/lib/build.ts, cli/lib/check-build-status.ts, cli/lib/util/i18n-config.ts, cli/package.json
remove cmp related code in cli since enterprise has removed `cmp` folder
=> remove cmp related code in cli

shell/app/common/components/table/table-footer.tsx
Fix table page size select display bug.
❎ No
❎ No
Fixes #
=> fix(common): table page size select display bug

pnpm-lock.yaml, shell/package.json
1. v2.0.2 is fixing that i18n impact erda-ui error, remove ConfigProvider from the dashboard when is production env
2. v2.0.3 is fixing that (1)display no mask which reminds user get data failed when didn't complete required fields
(2)line chart selected by default when adding chart
❎ No
Fixes #
=> fix: upgrade dashboard to v2.0.3

shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
display table x-scroll if content too much, the same as [fix: display table x-scroll if content too much #2043](https://github.com/erda-project/erda-ui/pull/2043)
❎ No
❎ No
Fixes #
=> fix: display table x-scroll if content too much

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/msp/monitor/error-insight/pages/errors/error-detail.tsx
fix the bug when the stack is empty in the error details page
❎ No
Fixes #
=> fix the bug when the stack is empty in the error details page

shell/app/common/components/edit-field/index.tsx
currently expand detail will trigger edit mode. fix it right now
❎ No
❎ No
=> remove settimeout && fix expand issue

shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Fix subscribers selector style bug.
->
Fixes #
=> fix(common): subscribers selector style bug

shell/app/config-page/components/list/list.tsx
remove the useless dependency of loadmore in the list to avoid multiple renders in useEffect
❎ No
❎ No
Fixes #
=> fix: remove useless dependency of loadmore in list

shell/app/common/components/edit-field/index.tsx
change label & set editor max height
❎ No
Fixes #
=> change label & set editor max height

shell/app/common/components/list/index.scss, shell/app/common/components/list/list-item.tsx
List prefixImg does not display, and style will be different without description.
->
❎ No
Fixes #
=> fix(common): list prefixImg does not display

shell/app/common/components/list/list-item.tsx
Fix cluster list status display bug.
->
❎ No
Fixes #
=> fix(cmp): cluster list status display bug

shell/app/common/utils/marked.ts
escape html to prevent html be rendered in MD
previous
now 
❎ No
=> add html escape

shell/app/common/components/edit-field/index.tsx
Due to img load is async, check content height is not accurate when onmount 
so trigger img load event and subscribe by MD component to check height on demand
❎ No
❎ No
=> add img loaded event listener

shell/app/common/components/list/index.scss, shell/app/common/components/list/list-item.tsx
Cluster list style optimization:
- extraInfos line height  is too small
- operations icon add hover background
- operations changed to click trigger
->
❎ No
Fixes #
=> fix(common): cluster list style optimization

shell/app/modules/org/pages/setting/notice-channel.tsx
update tab to the normal style
before:
current:
❎ No
Fixes #
=> style: update tab to normal style

shell/app/common/components/table/index.tsx
Fix bug of table unsorting will be in descending order.
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=252476&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG
=> fix(common): table unsorting will be in descending order

core/src/service/index.ts, shell/app/common/components/contractive-filter/index.tsx, shell/app/common/components/table/index.tsx
Fix  table reset bug:
- reset bug
- Front page does not display reset
- Give data.list a default value of an empty array
- operations icon does not display when operates is []
filter selector add load more.
❎ No
❎ No
Fixes #
=> fix(common): table reset bug

locales/en.json, locales/zh.json, shell/app/common/components/edit-field/index.tsx
add no desc holder in MD viewer, otherwise there would be blank
❎ No
=> add no desc holder

shell/app/common/utils/go-to.tsx, shell/app/menus/project.tsx, shell/app/modules/project/router.ts, shell/app/modules/project/tabs.tsx
fix that modify menu in the efficiency measure(wrong understanding of requirements), related with [feat: modify project management menu #2115](https://github.com/erda-project/erda-ui/pull/2115)
❎ No
❎ No
Fixes #
=> fix: modify menu in effeciency measure

shell/app/config-page/components/table/render-types.tsx
Fix style bug of config page table operations when operate is an empty array.
❎ No
❎ No
Fixes #
=> fix(common): config page table operations style bug

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
display total duration in the flame graph
❎ No
Fixes #
=> fix: display total duration in flame graph

shell/app/common/components/board-grid/index.tsx, shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-history-list.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx, shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts, shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
add startTime in params of trace detail api
❎ No
Fixes #
=> feat: add startTime in params of trace detail api

shell/app/App-vite.tsx, shell/app/App.tsx, shell/app/common/components/pagination/index.tsx, shell/app/common/components/table/index.tsx, shell/app/common/components/table/interface.ts, shell/app/common/components/table/table-config.tsx, shell/app/constants.ts, shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
Table reset always show and pageSizeOptions change
Fixes #
=> fix(common): table reset always show and pageSizeOptions change

shell/app/modules/cmp/common/alarm-strategy/index.tsx, shell/app/modules/cmp/stores/alarm-strategy.ts, shell/app/modules/msp/alarm-manage/alarm-strategy/stores/alarm-strategy.ts, shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx, shell/app/modules/msp/types/topology-service-analyze.d.ts
use the new table in MSP, reopen [refactor: use new table in msp
#2040](https://github.com/erda-project/erda-ui/pull/2040).
some bugfixes about table related with [fix(common): table unsorting will be in descending order #2107](https://github.com/erda-project/erda-ui/pull/2107)
**1. alarm-strategy** 
**before:**
**current:**
**2. events in trace-detail**
**before:**
**current:**
**3. link detail** 
**before:**
**current:**
Fixes #
=> refactor: use new table in msp

shell/app/common/components/table/index.scss, shell/app/common/components/table/index.tsx
Fix projects list style bug.
->
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249894&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0IiwiMjQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG
=> fix(common): projects list style bug

shell/app/common/components/edit-field/index.tsx, shell/app/modules/application/pages/repo/components/file-diff.tsx
1. fix md viewer expand button style issue
2. fix mr comment issue when click add comment twice then the MD editor is not closable.
to
❎ No
Fixes #
=> fix mr comment can not close issue

shell/app/config-page/components/list/list.tsx, shell/app/config-page/index.tsx
Fix config page container style bug of two scroll bars appear on the page or jump to the top of the page when updated.
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=258272&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0IiwiMjQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjQsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG
=> fix(common): config page container style bug

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/cmp/common/alarm-strategy/index.tsx
modify i18n about deleteing in alarm strategy list
❎ No
❎ No
Fixes #
=> fix: modify i18n about delete in alarm strategy list

shell/app/common/components/table/table-config.tsx
Table columns config cannot be hidden entirely
Fixes #
=> fix(common): table columns config cannot be hidden entirely

shell/app/config-page/components/table/render-types.tsx, shell/app/layout/pages/page-container/components/globalNavigation/userMenu.tsx, shell/app/layout/pages/page-container/page-container.tsx, shell/app/modules/project/common/components/issue/subscribers-selector.tsx, shell/app/modules/project/pages/issue/component/table-view.tsx, shell/app/modules/project/pages/issue/plan/index.tsx
show last two characters for Chinese user name
❎ No
| 🇺🇸 English |  show last two characters for Chinese user name when no avatar image  |
| 🇨🇳 中文    |  没有头像时展示中文名称的后两个字母  |
❎ No
Fixes #
=> Feature/show last two characters for Chinese user name

shell/app/common/__tests__/utils/str-num-date.test.tsx, shell/app/common/utils/index.ts, shell/app/common/utils/str-num-date.tsx, shell/app/config-page/components/bar-chart/bar-chart.mock.ts, shell/app/config-page/components/container/container.mock.ts, shell/app/config-page/components/contractive-filter/contractive-filter.mock.ts, shell/app/config-page/components/copy-button/copy-button.mock.ts, shell/app/config-page/components/dropdown-select/dropdown-select.mock.ts, shell/app/config-page/components/form-modal/form-modal.mock.ts, shell/app/config-page/components/info-preview/info-preview.mock.ts, shell/app/config-page/components/input-select/input-select.mock.ts, shell/app/config-page/components/sort-drag-group/sort-drag-group.mock.ts, shell/app/config-page/components/tree-select/tree-select.mock.ts, shell/app/config-page/mock/gallery.tsx
Export config page components mock data as default to show all exist component in gallery.
❎ No
❎ No
Fixes #
=> Feat: export config page components mock data as default

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
Don't show operation when action is empty
❎ No
❎ No
Fixes #
=> fix: not show operation when action is empty

shell/app/common/components/edit-field/index.tsx, shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx, shell/app/modules/project/common/components/issue/issue-relation.tsx, shell/app/modules/project/pages/backlog/issue-item.tsx
fix: issue include click to detail
❎ No
| 🇺🇸 English |   fix: issue include click to detail           |
| 🇨🇳 中文    |   fix: 包含事项点击进去详情         |
❎ No
Fixes #
=> fix: issue include click to detail

shell/app/config-page/components/issue-kanban.tsx
displaying avatar and not show loadMore when dragging in kanban
❎ No
❎ No
Fixes #
=> style: display avatar and not show loadMore when dragging in kanban

shell/app/config-page/components/gantt/components/calendar/calendar.scss, shell/app/config-page/components/gantt/components/calendar/calendar.tsx, shell/app/config-page/components/gantt/components/gantt/gantt.tsx
Use css transform instead of width to prevent performance issue
❎ No
❎ No
Fixes #
=> feat: gantt calendar use transform instead of width to prevent performance issue

shell/app/config-page/components/gantt/components/calendar/calendar.tsx, shell/app/config-page/components/gantt/components/gantt/gantt.tsx, shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx, shell/app/config-page/components/gantt/utils.ts, shell/app/modules/project/pages/issue/plan/index.tsx
1: fix time not enough one day
2: fix dates shows error
3: fix tree node render
❎ No
❎ No
Fixes #
=> fix: fix gant style

shell/app/modules/application/pages/repo/repo-branch.tsx
prevent to escape `/` in normal branch name.
❎ No
❎ No
Fixes #
=> fix: normal branch name display

shell/app/config-page/components/api-editor/api-editor.tsx, shell/app/modules/application/pages/settings/app-settings.tsx
fix: api editor button style
❎ No
| 🇺🇸 English |    fix: api editor button style          |
| 🇨🇳 中文    |   fix: 修复接口信息编辑表单按钮样式错误          |
cherry-pick hotfix/1.5-1208
Fixes #
=> fix: api editor button style

shell/app/config-page/components/table/render-types.tsx
Table text overflow bug.
->
| 🇺🇸 English | In a table, ellipses are displayed when the text in the content with icons exceeds the limit of length.  |
| 🇨🇳 中文    | 在表格中，带图标的内容中文字超出限制长度显示省略号。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=261678&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=772&type=BUG
=> fix(common): table text overflow bug

shell/app/config-page/components/issue-kanban.scss, shell/app/config-page/components/issue-kanban.tsx, shell/app/config-page/components/kanban-card/card.tsx
1. add highlight animation to card after dragging successful in kanban
2. modify card padding
3. remove issue id of card
| 🇺🇸 English | highlight card after dragging successful in kanban |
| 🇨🇳 中文    | 卡片拖拽成功后添加高亮动画至此卡片 |
❎ No
Fixes #
=> style: add highlight animation to card after dragging successful in kanban

shell/app/modules/msp/env-overview/service-list/pages/index.tsx
=> validate serviceIds before request

shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
msp project without applicationId to request in service overview
❎ No
❎ No
Fixes #
=> fix: msp project with applicationId in service overview

shell/app/common/components/contractive-filter/index.scss
Issue table filter close icon color bug
->
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263470&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG
=> fix(dop): issue table filter close icon color bug

shell/app/common/components/tags/index.scss, shell/app/config-page/components/issue-kanban.scss, shell/app/config-page/components/issue-kanban.tsx
1. modify color in kanban
2. remove labels and status in kanban
❎ No
| 🇺🇸 English | remove  labels and status in kanban |
| 🇨🇳 中文    | 将看板上的标签及状态信息去除  |
❎ No
Fixes #
=> fix: modify color in kanban

shell/app/common/components/menu/index.tsx, shell/app/layout/pages/page-container/components/header.scss, shell/app/layout/pages/page-container/components/header.tsx, shell/app/layout/pages/page-container/components/shell/index.scss, shell/app/layout/pages/page-container/components/sub-sidebar.scss, shell/app/layout/stores/layout.ts, shell/app/modules/application/pages/quality/index.tsx, shell/app/modules/project/tabs.tsx, shell/app/styles/_mixin.scss, shell/app/styles/app.scss
update page tabs position
->
| 🇺🇸 English | move header tabs align with page title  |
| 🇨🇳 中文    | 移动页面选项卡到上面与标题对齐 |
❎ No
Fixes #
=> feat: move header tabs align with page title

shell/app/config-page/components/table/render-types.tsx, shell/app/config-page/components/table/table.scss
Table td height adjustment
->
| 🇺🇸 English | Table height adjustment. |
| 🇨🇳 中文    | 表格高度调整。 |
❎ No
Fixes #
=> fix(common): table td height adjustment

shell/app/config-page/index.tsx
Fix timer still running after leave component-protocol page.
❎ No
❎ No
Fixes #
=> fix: clear page protocol interval timer when unmount

shell/app/org-home/stores/org.tsx
Fix bug of page does not get announcements list at initialization.
❎ No
❎ No
Fixes #
=> fix(common): get announcements list at initialization

shell/app/modules/msp/env-overview/service-list/pages/index.tsx
average throughput does not wrap
| 🇺🇸 English | Average throughput does not wrap             |
| 🇨🇳 中文    |  平均吞吐量不换行  |
❎ No
Fixes #
=> fix(msp): average throughput does not wrap

shell/app/styles/antd-extension.scss
fix radio solid button style
❎ No
Fixes #
=> fix radio solid button style

shell/app/common/components/card-list/index.tsx, shell/app/common/index.ts, shell/app/modules/msp/pages/micro-service/overview.tsx, shell/app/styles/_color.scss, shell/app/styles/util.scss
add card list and refactor msp overview
❎ No
❎ No
Fixes #
=> feat(common): add card list and refactor msp overview

shell/app/common/components/edit-field/index.tsx, shell/app/layout/stores/layout.ts
fix that enlarge the corresponding click image in issue drawer
❎ No
release/1.5-alpha.4
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=263094&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=-1&type=BUG
=> fix: enlarge the corresponding click image in issue drawer

pnpm-lock.yaml, shell/app/charts/components/monitor-chart-new.jsx, shell/app/charts/components/pie-chart.jsx, shell/package.json
1. fix: fetch 'https://geo.datav.aliyun.com/areas_v2/bound' without header to solve CORS problem
2. style:modify tooltip style in chart
| 🇺🇸 English | modify the style of tooltip in chart |
| 🇨🇳 中文    | 更改图表的 tooltip 样式 |
Fixes #
=> style: modify style of tooltip in chart

shell/app/common/components/configurable-filter/index.scss, shell/app/common/components/configurable-filter/index.tsx, shell/app/config-page/components/configurable-filter/configurable-filter.spec.d.ts
Configurable filter style optimization.
->
❎ No
Fixes #
=> fix(common): configurable filter style optimization

shell/app/common/components/table/index.tsx
table pagination bug:
In frontend paging table, pageNo does not change when dataSource change.
❎ No
❎ No
Fixes #
=> fix(common): table pagination bug

shell/app/common/components/configurable-filter/index.tsx
Fix configurable filter bug:
page error when values of filterSet doesn't exist.
❎ No
❎ No
Fixes #
=> fix(common): configurable filter bug

shell/app/common/components/configurable-filter/index.scss, shell/app/common/components/configurable-filter/index.tsx
Fix configurable filter tags select style bug.
->
❎ No
Fixes #
=> fix(common): configurable filter tags select style bug

shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
fix that valueOptions is  empty when operator is match or notMatch can not be saved
❎ No
❎ No
Fixes #
=> fix: valueOptions is  empty when operator is match or notMatch can not be saved

shell/app/common/components/members-table/index.tsx
hide email and phone columns of members table to avoid to scroll in horizontal 
❎ No
❎ No
Fixes #
=> fix: hide email and phone columns of members table

shell/app/common/components/edit-field/index.tsx
fix that not display cursor after selection, these selects have no search function
before:
current:
❎ No
❎ No
Fixes #
=> fix: not display cursor after selection

shell/app/common/components/members-table/index.tsx
fix that hide email and label columns of member table
❎ No
hotfix/12-21
Fixes #
=> fix: hide email and label columns of member table

shell/app/common/utils/go-to.tsx, shell/app/modules/msp/env-overview/service-list/pages/index.tsx, shell/app/modules/msp/env-overview/service-list/router.ts
modify route about service analysis
❎ No
hotfix/12-21
Fixes #
=> feat: modify route about service analysis

shell/app/common/utils/go-to.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx
fix that trace detail go back to transaction in service monitor
❎ No
hotfix/12-21
Fixes #
=> fix: trace detail go back to transaction in service monitor

shell/app/modules/org/pages/projects/settings/info/index.tsx
Fix msp project detail display bug in orgCenter.
❎ No
hotifx/12-21
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=267696&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=680&type=BUG
=> fix(common): msp project detail display bug in orgCenter

shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
remove usefullscreen
❎ No
❎ No
Fixes #
=> remove usefullscreen

shell/app/common/components/contractive-filter/index.scss
overwrite style affected by compress order
| 🇺🇸 English | fix member select style in milestone page  |
| 🇨🇳 中文    | 修复里程碑页面选人组件的样式问题  |
release/1.5
Fixes #
=> fix: member select style in milestone page 

shell/app/layout/pages/page-container/components/menu-head.tsx, shell/app/layout/pages/page-container/components/side-navigation.tsx, shell/app/layout/pages/page-container/components/sub-sidebar.tsx
fix fdp module can't be loaded when fold side navigator issue
❎ No
❎ No
=> fix fdp module can't be loaded when fold side navigator issue

shell/app/modules/msp/env-overview/service-list/router.ts
fix that remove extra breadcrumbName which is from service list jump to service monitor
❎ No
release/1.5
Fixes #
=> fix: remove extra breadcrumbName which is from service list jump to service monitor

shell/app/common/components/tags-row/index.scss, shell/app/common/components/tags-row/index.tsx, shell/app/views/index.ejs, shell/index.html
modify style about delete label in node list
**before:** 
**current:**
release/1.5
Fixes #
[【线上问题】节点列表标签删除样式显示不全](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=268054&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> style(common): modify style about delete label in node list

shell/app/config-page/components/gantt/components/gantt/gantt.tsx, shell/app/config-page/components/gantt/components/task-list/task-list.scss, shell/app/config-page/components/gantt/components/task-list/task-list.tsx
last task in gantt not show full.
| 🇺🇸 English |  fix last task in gantt not fully displayed |
| 🇨🇳 中文    |  修复甘特图上最后一个任务没有完整显示问题 |
release/1.5
Fixes #
=> fix: last task in gantt not fully displayed

shell/app/common/components/card-list/index.tsx, shell/app/common/use-hooks.tsx, shell/app/modules/msp/env-overview/service-list/pages/index.tsx
service list chart lazy load
❎ No
❎ No
Fixes #
=> service list chart lazy load

shell/app/config-page/components/gantt/components/gantt/gantt.tsx, shell/app/modules/project/common/components/issue/issue-drawer.tsx
prevent scroll today after clicking expander
✅ No
✅ No
Fixes #
[【甘特图】滑动任意事项超过屏幕距离会自动定位到今日](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=269371&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix: prevent scroll today after clicking expander

shell/app/modules/project/common/components/pipeline-manage/common/config-env-selector.tsx, shell/app/modules/project/types/auto-test.d.ts
fix: add autoStartCron params when create pipeline
❎ No
❎ No
Fixes #
=> fix: add autoStartCron params when create pipeline

shell/app/modules/org/pages/projects/settings/info/index.tsx
fix that public project changed to personal project after update project quota or rollback point
release/1.5
Fixes #
[更新项目配额会将公开项目设置成 私有项目](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=270929&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix: public project changed to personal project after update project quota or rollback point

shell/app/common/components/configurable-filter/index.tsx, shell/app/common/utils/go-to.tsx, shell/app/menus/project.tsx, shell/app/modules/project/pages/release/components/application-detail.tsx, shell/app/modules/project/pages/release/components/form.scss, shell/app/modules/project/pages/release/components/form.tsx, shell/app/modules/project/pages/release/components/project-detail.tsx, shell/app/modules/project/pages/release/components/update.tsx, shell/app/modules/project/router.tsx, shell/app/modules/project/services/release.ts, shell/app/modules/project/types/release.d.ts
- Project release management application release edit
- Project release management application release left menu close bug
- Filter style bug
- Add markdown width in create release page
- release list name display bug in create release
| 🇺🇸 English | Application release editing of project - level release.  |
| 🇨🇳 中文    |  项目级制品的应用制品编辑。  |
❎ No
Fixes #
=> feat(dop): project release management application release edit

shell/app/styles/util.scss
Fix page bottom button style bug
❎ No
Fixes #
=> fix(common): page bottom button style bug

shell/app/layout/pages/page-container/components/navigation/index.tsx
close site message when go to personal home
✅ No
❎ No
Fixes #
[在站内信页面点击个人工作台无效](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=271327&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix: close site message when go to personal home

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/project/pages/release/components/application-detail.tsx, shell/app/modules/project/pages/release/components/form.tsx
Project release management text adjustment.
->
| 🇺🇸 English | Version name replace with release name. |
| 🇨🇳 中文    |  版本名称改成制品名称  |
❎ No
Fixes #
=> fix(dop): project release management text adjustment

shell/app/common/components/table/index.scss, shell/app/common/components/table/index.tsx, shell/app/config-page/components/gantt/components/gantt/gantt.scss, shell/app/config-page/components/table/render-types.tsx, shell/app/config-page/components/table/table.tsx, shell/app/modules/cmp/router.ts, shell/app/modules/ecp/router.ts, shell/app/styles/antd-extension.scss
* update table operation dropdown theme
* remove odd space between calendar and content in gantt
❎ No
Fixes #
=> feat: update table operation dropdown theme

shell/app/common/components/user-profile/index.tsx, shell/app/org-home/pages/active-rank/index.tsx
1.  only show top 10 at most in the personal home(not display scroll bar)
2. click user info to go to personal setting of UC 
| 🇺🇸 English | only show top 10 at most in contribute rank, and click user info to go to personal setting|
| 🇨🇳 中文    | 贡献排行最多显示前 10 名，点击用户信息区域跳转至个人设置页面 |
Fixes #
=> feat: only show top 10 at most in personal home

shell/app/modules/project/pages/homepage/index.tsx, shell/app/modules/project/pages/iteration/table.tsx
1. update filter to tab in iteration
2. display nickname by default on project home page
**before:**
**current：**
| 🇺🇸 English | update filter to tab in iteration |
| 🇨🇳 中文    | 迭代管理从 filter 改为 tab |
Fixes #
=> feat: update filter to tab in iteration

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/span-title-info.tsx
modify style of tooltip in trace-detail
**before:**
**current:**
Fixes #
=> fix(msp): modify style of tooltip in trace-detail

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx, shell/app/modules/cmp/pages/cluster-manage/index.tsx
Clusters list reload after add or delete
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=270014&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(cmp): clusters list reload after add or delete

shell/app/common/components/table/index.scss, shell/app/layout/pages/page-container/components/navigation/index.scss, shell/app/layout/pages/page-container/components/navigation/index.tsx
revert table filter input style before update global input style.
min-h-8 not exist.
❎ No
Fixes #
=> Fix: logo wrap height style

shell/app/layout/pages/page-container/components/navigation/index.tsx
with the same route, close message site when clicking navigation item
❎ No
Fixes #
[【个人工作台】点击后会出现个人工作台和站内信的页面切换](https://erda.cloud/erda/dop/projects/387/issues/all?id=272273&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix: with the same route, close message site when click navigation item

shell/app/common/components/table/index.scss, shell/app/common/components/table/index.tsx
Fix table sorter dropdown menu display bug
->
Fixes #
=> fix(common): table sorter dropdown menu display bug

shell/app/modules/project/pages/homepage/index.scss, shell/app/modules/project/pages/homepage/readme-markdown.tsx
add edit button in markdown
| 🇺🇸 English | add edit button in markdown in project home page|
| 🇨🇳 中文    | 在项目首页中为 markdown 增加编辑按钮 |
❎ No
Fixes #
=> style: add edit button in markdown

shell/app/config-page/components/card/card.scss, shell/app/modules/application/common/app-selector.tsx, shell/app/modules/project/common/components/project-selector.tsx, shell/app/org-home/pages/personal-contribute/index.tsx
* update personal contribute item bg color
* remove project and app selector tooltip
| 🇺🇸 English | update personal contribute card background color |
| 🇨🇳 中文    |  调整个人贡献卡片背景色   |
Fixes #
=> feat: update personal contribute item background color

shell/app/common/components/table/index.tsx
Fix resources table sort bug.
❎ No
| 🇺🇸 English | Fix resources table invalid sorting bug.   |
| 🇨🇳 中文    |  修复了资源汇总列表的排序无效问题。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=272844&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(dop): resources table sort bug

shell/app/common/components/contractive-filter/index.scss
fix input border
❎ No
| 🇺🇸 English |  remove input border under contractive filter |
| 🇨🇳 中文    | 移除筛选器下的输入框边框 |
Fixes #
=> fix: remove input border under contractive filter

shell/app/common/utils/go-to.tsx, shell/app/config-page/components/bubble-graph/bubble-graph.spec.d.ts, shell/app/config-page/components/bubble-graph/index.tsx, shell/app/config-page/components/index.tsx, shell/app/config-page/components/table/v2/utils.tsx, shell/app/config-page/mock/data-rank.mock.ts, shell/app/config-page/mock/index.tsx, shell/app/config-page/mock/mock.tsx, shell/app/modules/msp/env-overview/service-list/pages/trace.tsx, shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx, shell/app/modules/msp/env-overview/service-list/router.ts, shell/app/modules/msp/monitor/trace-insight/components/duration.scss, shell/app/modules/msp/monitor/trace-insight/components/duration.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx, shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts, shell/app/modules/msp/types/service-analytics.d.ts
refactor tracing according to the new specification
❎ No
| 🇺🇸 English | refactor tracing according to the new specification |
| 🇨🇳 中文    |  根据新规范重构链路追踪  |
❎ No
Fixes #
=> feat: refactor tracing according to the new specification

shell/app/menus/appCenter.tsx, shell/app/org-home/pages/personal-home.tsx
Fdp display on menu according to environment
❎ No
| 🇺🇸 English |  ...  |
| 🇨🇳 中文    |   。。。   |
Fixes #
=> fix(common): fdp display on menu according to environment

shell/app/common/components/markdown-editor/editor.scss, shell/app/common/components/markdown-editor/index.scss, shell/app/common/components/markdown-editor/index.tsx, shell/app/modules/project/pages/homepage/index.scss, shell/app/modules/project/pages/homepage/index.tsx, shell/app/modules/project/pages/homepage/readme-markdown.tsx, shell/theme-color.js
1. fix full-screen markdown style in project home
2. update link style in markdown
| 🇺🇸 English | update style of markdown in project home page |
| 🇨🇳 中文    | 更改项目首页 markdown 样式  |
Fixes #
[项目主页编辑点击全屏异常](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=272953&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix: update full screen markdown style in project home

shell/app/modules/apiManagePlatform/pages/api-market/detail/components/api-body/index.tsx, shell/app/modules/apiManagePlatform/pages/api-market/detail/index.tsx
api version list uses a new table
❎ No
❎ No
Fixes #
=> feat: api version list use new table

shell/app/modules/project/pages/release/components/form.tsx
Project release upload file type change.
❎ No
| 🇺🇸 English | The type of files uploaded by project level artifacts has changed. |
| 🇨🇳 中文    | 项目级制品上传文件的类型改变。 |
❎ No
Fixes #
=> fix(dop): project release upload file type change

shell/app/modules/project/pages/release/components/form.tsx, shell/app/modules/project/router.tsx
project release create release by upload file remove changelog.
| 🇺🇸 English |  In file creation artifacts, the form item is removed from the description.   |
| 🇨🇳 中文    | 通过文件创建制品中，表单项去掉描述。 |
❎ No
Fixes #
=> fix(dop): project release create release by upload file remove changelog

shell/app/modules/project/stores/release.ts
Fix project release applications list pageSize bug.
❎ No
| 🇺🇸 English | Fixed a bug where the app list for artifact management would only display 20 entries by default. |
| 🇨🇳 中文    |  修复了制品管理的应用列表默认只显示20条数据的bug。  |
Fixes #
=> fix(dop): project release applications list pageSize bug

shell/app/config-page/components/grid/grid.spec.d.ts, shell/app/config-page/components/grid/grid.tsx, shell/app/config-page/components/line-graph/index.tsx, shell/app/modules/msp/monitor/browser-insight/pages/overview/overview.tsx, shell/app/views/index.ejs, shell/index.html
feat: add front monitor
❎ No
| 🇺🇸 English | add front monitor |
| 🇨🇳 中文    | 添加前端监控 |
❎ No
Fixes #
=> feat: add front monitor

shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx, shell/app/modules/project/pages/deploy/add-deploy/index.tsx, shell/app/modules/project/pages/deploy/deploy-config/index.tsx, shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx, shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx, shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
fix: fix project deploy table page no error
❎ No
| 🇺🇸 English | fix: fix project deploy table page no error             |
| 🇨🇳 中文    |   fix: 修复项目部署中心页码错误           |
❎ No
Fixes #
=> fix: fix project deploy table page no error

shell/app/common/components/pagination/index.scss, shell/app/common/components/pagination/index.tsx, shell/app/common/components/table/index.scss
Fix pagination btn hover style bug.
| 🇺🇸 English |  Fixed a bug where pager hover background would be disabled when used outside of a table.  |
| 🇨🇳 中文    |  修复了在表格之外使用分页器，分页器鼠标悬浮的背景效果会失效的bug。  |
❎ No
Fixes #
=> fix(common): pagination btn hover style bug

shell/app/layout/pages/page-container/components/header.scss, shell/app/layout/pages/page-container/components/header.tsx, shell/app/layout/pages/page-container/components/shell/index.tsx, shell/app/layout/pages/page-container/components/sidebar/index.scss, shell/app/locales/zh.json, shell/app/modules/project/pages/deploy/index.tsx, shell/app/modules/project/pages/homepage/index.scss, shell/app/modules/project/pages/homepage/index.tsx, shell/app/modules/project/pages/homepage/readme-markdown.tsx
* update project home style
* update breadcrumb position when sidebar not exist
* remove sidebar border
* add animate border to deploy record card
| 🇺🇸 English | update breadcrumb position when sidebar not exist  |
| 🇨🇳 中文    |  调整无权限页面的面包屑位置  |
❎ No
Fixes #
=> feat: update project home and breadcrumb style

shell/app/modules/org/pages/projects/operation-project-record.tsx, shell/app/styles/antd-extension.scss
modify style of drawer
**before：**
**current：**
| 🇺🇸 English | modify the style of Drawer |
| 🇨🇳 中文    | 修改 Drawer 组件样式 |
❎ No
Fixes #
=> style: modify the style of drawer

shell/app/modules/project/pages/pipelines/old-pipeline.tsx, shell/app/modules/project/router.tsx
revert old project pipeline
❎ No
| 🇺🇸 English |        -     |
❎ No
Fixes #
=> fix: revert old project pipeline

shell/app/common/components/base-list/index.tsx, shell/app/common/components/table/index.scss, shell/app/modules/msp/env-overview/service-list/pages/service-list.scss, shell/app/modules/org/common/card/index.scss, shell/app/org-home/pages/personal-home.scss, shell/app/styles/_color.scss
fix: revert table header bg color
❎ No
| 🇺🇸 English |     -        |
| 🇨🇳 中文    |       -      |
❎ No
Fixes #
=> fix: revert table header bg color

shell/app/modules/project/pages/pipelines/components/form.tsx, shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx, shell/app/modules/project/pages/pipelines/index.tsx
Fix project pipeline apps list status display bug
❎ No
| 🇺🇸 English |  The number of pipelines executing and failing in the list of applications to the left of the pipeline at the project level is not automatically refreshed. |
| 🇨🇳 中文    |  项目级流水线左侧应用列表中正在执行、失败的流水线数量不会自动刷新。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275706&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(dop): project pipeline apps list status display bug

shell/app/common/components/table/index.scss, shell/app/common/components/table/index.tsx, shell/app/common/components/table/table-config.tsx, shell/app/common/components/table/table-footer.tsx, shell/app/modules/project/router.tsx
Config table header background color optimization 
| 🇺🇸 English | Unified background color for componentized table headers. |
| 🇨🇳 中文    | 组件化表格头部背景色统一。  |
❎ No
Fixes #
=> fix(common): config table header background color optimization

shell/app/common/components/render-form-item/index.tsx
Fix configurable filter display bug when receiving null.
->
| 🇺🇸 English |  Fixed display issues when configurable filters receive NULL values.  |
| 🇨🇳 中文    | 修复了可配置筛选器接收null值时的显示问题。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275907&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(common): configurable filter display bug when receiving null

shell/app/common/components/dropdown-select-new/index.tsx
Org home display optimization when org name too long.
->
| 🇺🇸 English |  Optimize the display of personal workbench switch when the enterprise name is long.   |
| 🇨🇳 中文    | 企业名称比较长的情况下个人工作台切换显示优化。 |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275900&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(common): org home display optimization when org name too long

shell/app/modules/project/pages/release/components/application-detail.tsx
Fix project release detail yml file display bug.
❎ No
| 🇺🇸 English |  Fixed the display bug of YML files in project level artifact details. |
| 🇨🇳 中文    | 修复了项目级制品详情中yml文件的显示bug。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275920&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(dop): project release detail yml file display bug

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/project/pages/pipelines/components/form.tsx
Project pipeline name rules change
❎ No
| 🇺🇸 English | The name of the project level assembly line is allowed in Chinese. |
| 🇨🇳 中文    | 项目级流水线取名允许中文。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=276316&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(dop): project pipeline name rules change

shell/app/common/components/radio-tabs/index.tsx
In config page, radio tabs value change by state.
❎ No
| 🇺🇸 English | Makes the value of the tag radio button in the componentization change with the state of the componentized species. |
| 🇨🇳 中文    | 让组件化中的标签单选按钮的值随着组件化种的状态改变。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275905&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(common): in config page, radio tabs value change by state

shell/app/modules/cmp/common/custom-alarm/index.tsx, shell/app/modules/org/pages/projects/settings/info/index.scss, shell/app/modules/org/pages/projects/settings/info/index.tsx, shell/app/modules/project/pages/homepage/index.tsx
1. select display incomplete in table
2. modify the style of basic project info
**before:** 
**now:**
| 🇺🇸 English |      -     |
| 🇨🇳 中文    |      -    |
❎ No
Fixes #
[【告警】微服务告警规则，新增/编辑，添加过滤规则/字段规则，页面显示不全](https://erda.cloud/erda/dop/projects/387/issues/all?id=276193&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA3MjMiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
[项目标识比较长、项目描述比较长的情况下项目信息显示乱了](https://erda.cloud/erda/dop/projects/387/issues/all?id=275319&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&t …
=> fix: select display in table

shell/app/modules/org/pages/certificate/index.tsx, shell/app/modules/project/pages/issue/gantt/index.tsx
add check rule
❎ No
| 🇺🇸 English |  add no space check rule for certificate alias fields  |
| 🇨🇳 中文    | 证书表单中的别名字段添加禁止空格的校验 |
Fixes #
=> fix: add no space check rule for certificate alias fields

shell/app/modules/project/pages/release/release-protocol.tsx
Fix project release create disabled button style bug.
->
| 🇺🇸 English | Fixed a style issue where new buttons in project level artifacts had no power limit. |
| 🇨🇳 中文    | 修复了项目级制品新增按钮无权限时的样式问题。 |
Fixes #
=> fix(dop): project release create disabled button style bug

shell/app/common/utils/go-to.tsx, shell/app/modules/project/tabs.tsx
Project release put application in front of project.
->
| 🇺🇸 English |  In a project-level pipeline, applications come before projects. |
| 🇨🇳 中文    | 在项目级流水线中，应用放在项目前面。 |
Fixes #
=> fix(dop): project release put application in front of project

shell/app/modules/org/pages/projects/import-project-template.scss, shell/app/modules/org/pages/projects/import-project-template.tsx, shell/app/modules/org/pages/projects/settings/info/index.scss, shell/app/modules/org/pages/projects/settings/info/index.tsx
1. remove file style in importing project
❎ No
| 🇺🇸 English | project import file delete file optimize style |
| 🇨🇳 中文    | 项目导入文件删除文件优化样式 |
Fixes #
[项目导入文件删除优化](https://erda.cloud/erda/dop/projects/387/issues/all?id=275832&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix: remove file style in importing project

shell/app/modules/extra/entry.js, shell/app/modules/msp/stores/micro-service.tsx, shell/app/modules/msp/types/index.d.ts
fix msp menu [backend:feat: microservice menu api add isk8s field ](https://github.com/erda-project/erda/pull/3791)
❎ No
| 🇺🇸 English | fix whether isK8S logic |
| 🇨🇳 中文    |  修复 isK8S 的判断逻辑 |
release/1.5
Fixes #
=> fix: fix whether isK8S logic

shell/app/config-page/index.tsx
fix: revert config page partial update
| 🇺🇸 English |    fix: revert config page partial update          |
| 🇨🇳 中文    |   fix: 回退组件化协议部分更新          |
Fixes #
=> fix: revert config page partial update

shell/app/common/components/base-list/list-item.tsx
update list syle
| 🇺🇸 English |     feat: set list kv-info margin top to 8px         |
| 🇨🇳 中文    |  设置列表 kv 信息行上边距为 8 像素 |
Fixes #
=> feat: set list kv-info margin top to 8px

shell/app/common/components/list-select/index.scss, shell/app/common/components/list-select/index.tsx, shell/app/common/components/pagination/index.tsx
Create project release optimization.
->
| 🇺🇸 English | Fixed button style issues in new item-level pipeline forms, adding restriction to select only one artifact in the same application.  |
| 🇨🇳 中文    |  修复了新增项目级流水线表单中的按钮样式问题，增加同应用下只能选择一个制品的限制。  |
Fixes #
=> fix(dop): create project release optimization

shell/app/common/components/radio-tabs/index.tsx
Fix radio tabs default value bug.
->
| 🇺🇸 English | Fixed a bug where radio button TAB initial values were invalid. |
| 🇨🇳 中文    | 修复了单选按钮标签页初始值失效的bug。 |
Fixes #
=> fix(common): radio tabs default value bug

shell/app/modules/cmp/pages/cluster-container/cluster-pods.tsx, shell/app/modules/cmp/pages/cluster-container/cluster-workload.tsx
fix: fix cmp pods/workload top head button style
| 🇺🇸 English |   fix: fix cmp pods/workload top head button style        |
| 🇨🇳 中文    |    fix: 修复云管平台pods/workload页面顶部按钮样式问题        |
❎ No
Fixes #
=> fix: fix cmp pods/workload top head button style

shell/app/common/components/load-more-selector/index.scss, shell/app/common/components/load-more-selector/index.tsx
Fix load more selector style bug.
->
| 🇺🇸 English | Fixed style issues with selectors.  |
| 🇨🇳 中文    | 修复了选择器的样式问题。 |
Fixes #
=> fix(common): load more selector style bug

shell/app/charts/utils/formatter.js, shell/app/charts/utils/index.tsx, shell/app/config-page/components/bubble-graph/bubble-graph.spec.d.ts, shell/app/config-page/components/bubble-graph/index.tsx, shell/app/config-page/components/line-graph/index.tsx, shell/app/config-page/components/line-graph/line-graph.spec.d.ts
line-graph and bubble-graph auto unit 
Related PR [feat: linegraph and bubblegraph auto unit #3802](https://github.com/erda-project/erda/pull/3802)
❎ No
| 🇺🇸 English | line-graph and bubble-graph dynamic unit|
| 🇨🇳 中文    | 折线图气泡图坐标轴动态单位 |
❎ No
Fixes #
=> feat: line-graph and bubble-graph dynamic unit

pnpm-lock.yaml, shell/package.json
fix that i18n validating about required fields in the dashboard
❎ No
| 🇺🇸 English | fix that i18n validating about required fields in dashboard |
| 🇨🇳 中文    | 修复大盘中必填字段校验国际化问题 |
/cherry-pick release/1.6-alpha.2
Fixes #
[【集成环境】【国际化】自定义大盘，新增/编辑页面，字段为空时，提示语没有翻译](https://erda.cloud/erda/dop/projects/387/issues/all?id=277529&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA3MjMiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix(dashboard): i18n validating about required fields in dashboard

shell/app/common/components/markdown-editor/editor.tsx
fix: set markdown editor lang by current locale
❎ No
| 🇺🇸 English | fix: set markdown editor lang by current locale   |
| 🇨🇳 中文    |  根据国际化设置 markdown 编辑器的语言   |
❎ No
Fixes #
=> fix: set markdown editor lang by current locale

pnpm-lock.yaml, shell/package.json
fix that i18n validating about required fields in the dashboard
❎ No
| 🇺🇸 English | fix that i18n validating about required fields in dashboard |
| 🇨🇳 中文    | 修复大盘中必填字段校验国际化问题 |
✅ No
Fixes #
[【集成环境】【国际化】自定义大盘，新增/编辑页面，字段为空时，提示语没有翻译](https://erda.cloud/erda/dop/projects/387/issues/all?id=277529&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDA3MjMiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
=> fix: i18n about validating required in dashboard

shell/app/common/components/panel/index.tsx, shell/app/styles/antd-extension.scss
fix: fix drawer style
❎ No
| 🇺🇸 English |    fix: fix drawer background style          |
| 🇨🇳 中文    |   fix: 修复Drawer组件背景样式           |
Fixes #
=> fix: fix drawer background style

shell/app/config-page/components/table/table.scss
Fix config table batch operations disabled style bug.
->
| 🇺🇸 English | Color of the text when the batch button in the config table is disabled. |
| 🇨🇳 中文    |  组件化协议表格批量按钮不可点击时的文字颜色。   |
Fixes #
=> fix(common): config table batch operations disabled style bug

shell/app/common/components/table/index.tsx
Fix table sorter style bug.
->
| 🇺🇸 English | Right aligned table sorting style issues. |
| 🇨🇳 中文    | 右对齐时表格排序的样式问题。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=277846&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(common): table sorter style bug

shell/app/modules/project/pages/pipelines/index.tsx
Project pipeline apps list pipeline num.
->
| 🇺🇸 English | In the app list of project-level pipelines, it is also displayed when the total number of pipelines is 0. |
| 🇨🇳 中文    | 项目级流水线的app列表中，当流水线总数为0时也显示。 |
Fixes #
=> fix(dop): project pipeline apps list pipeline num

shell/app/common/components/render-form-item/index.tsx, shell/app/modules/project/pages/pipelines/components/form.tsx, shell/app/modules/project/services/pipeline.tsx
Project pipeline create form tree select optimization.
->
| 🇺🇸 English | Added a new folder to expand from unclickable in the tree selection box of the project pipeline form. |
| 🇨🇳 中文    | 新增项目级流水线表单的树形选择框中，文件夹从不可点击改为点击展开。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=278253&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=BUG
=> fix(dop): project pipeline create form tree select optimization

shell/app/common/components/markdown-editor/editor.tsx
markdown editor always use navigator.language as a prior flag, so always set locale every time in render.
❎ No
| 🇺🇸 English |  markdown editor locale change after rerender  |
| 🇨🇳 中文    |  修复 markdown 编辑器重新打开后国际化错误问题  |
release/1.5
Fixes #
=> fix: markdown editor locale change after rerender

shell/app/config-page/components/table/table.mock.ts
Config table column add tip in gallery.
->
| 🇺🇸 English | On the componentized protocol component library page, add a hint to the table column header.  |
| 🇨🇳 中文    |  在组件化协议的组件库页面中，给表格列头增加提示。  |
Fixes #
=> fix(dop): config table column add tip in gallery

shell/app/layout/pages/page-container/page-container.tsx, shell/app/modules/project/common/components/pipeline-manage/config-detail/index.tsx, shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/index.tsx, shell/app/modules/project/common/components/pipeline-manage/pipeline-detail.tsx
Obsoleted pipelines page scroll bug.
❎ No
| 🇺🇸 English | Fixed the old project pipeline page scintillation bug. |
| 🇨🇳 中文    | 修复了旧版项目流水线页面滚动闪烁的bug。 |
Fixes #
=> fix(dop): obsoleted pipelines page scroll bug

shell/app/menus/application.tsx
revert app deploy page for now
❎ No
| 🇺🇸 English |   revert app deploy page for now  |
| 🇨🇳 中文    | 临时恢复应用部署入口   |
❎ No
Fixes #
=> refactor: revert app deploy page for now

shell/app/common/components/list-select/index.tsx, shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/project/pages/release/components/form.tsx, shell/app/modules/project/services/release.ts
Project release create form releases list add latest filter.
| 🇺🇸 English |  Added filter by branch aggregation when selecting application artifacts in the new item-level artifacts form.  |
| 🇨🇳 中文    |  项目级制品新增表单中，选择应用制品时增加按分支聚合的筛选。  |
❎ No
Fixes #
=> feat(dop): project release create form releases list add latest filter

shell/app/config-page/page-render.tsx, shell/app/modules/cmp/pages/cluster-container/cluster-pods.tsx, shell/app/modules/cmp/pages/cluster-container/cluster-workload.tsx
fix: cmp top head button style in 1.5  
| 🇺🇸 English |     fix: cmp top head button style in 1.5         |
| 🇨🇳 中文    |  fix: 1.5版本修复cmp页头按钮样式问题            |
❎ No
Fixes #
=> fix: cmp top head button style in 1.5  

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx, shell/app/modules/cmp/pages/cluster-manage/index.tsx
Fix clusters list edit bug.
❎ No
| 🇺🇸 English | The cluster is modified successfully, but the cluster list is not automatically updated.  |
| 🇨🇳 中文    | 集群修改成功，集群列表没有自动更新。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=272874&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(cmp): clusters list edit bug

shell/app/App-vite.tsx, shell/app/App.tsx, shell/app/antd-default-props.tsx
add default delay for loading
❎ No
| 🇺🇸 English |add default delay for loading   |
| 🇨🇳 中文    |  给加载器添加默认的延迟显示时间   |
❎ No
Fixes #
=> feat: add default delay for loading

pnpm-lock.yaml, shell/app/common/components/markdown-render/index.tsx, shell/app/modules/dop/pages/projects/project-list-protocol.tsx, shell/package.json
* add break line plugin to auto add <br>
| 🇺🇸 English |  auto add line break for markdown render  |
| 🇨🇳 中文    | markdown 渲染器中自动添加换行符   |
❎ No
Fixes #
=> fix: add line break plugin for markdown render

shell/app/config-page/components/list-new/list-new.tsx, shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
Fix config page list operations bug.
❎ No
| 🇺🇸 English | Fixed an issue where the Record object in the list operation event of a componentized protocol was a read-only object. |
| 🇨🇳 中文    |  修复了组件化协议的列表操作事件中，接受参数中的record对象是只读对象的问题。 |
❎ No
Fixes #
=> fix(common): config page list operations bug

shell/app/common/components/render-pure-form/index.tsx, shell/app/modules/org/pages/projects/settings/info/index.tsx, shell/app/modules/project/common/components/section-info-edit.tsx
Project edit save button disabled by default.
❎ No
| 🇺🇸 English | The save button for project editing is disabled by default, only enabled when the form value changes. |
| 🇨🇳 中文    | 项目编辑的保存按钮默认禁用，表单值变化后才启用。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275782&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(common): project edit save button disabled by default

core/src/index.tsx, core/webpack.config.js, shell/app/App-vite.tsx, shell/app/App.tsx, shell/app/antd-default-props.tsx, shell/mf.config.js
fix locale and other config issue caused by different ConfigProvider instance;
merge with [this pr](https://github.com/erda-project/erda-ui-enterprise/pull/212)
❎ No
| 🇺🇸 English |   fix locale issue in admin page  |
| 🇨🇳 中文    |  修复 admin 后台国际化问题  |
❎ No
Fixes #
=> fix(core): make antd singleton in module feduration

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx, shell/app/modules/project/stores/issues.ts
Get options when opening issue detail.
❎ No
| 🇺🇸 English | Get options when opening issue detail. |
| 🇨🇳 中文    | 在打开协同详情时获取下拉选项。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=273037&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG
=> fix(dop): get options when opening issue detail

shell/app/layout/pages/page-container/components/sidebar/index.scss
Fix left menu background color bug
->
| 🇺🇸 English | Fix left menu background color bug. |
| 🇨🇳 中文    | 修复了左侧菜单背景色的bug。 |
❎ No
Fixes #
=> fix(common): left menu background color bug

shell/app/common/components/render-form-item/index.tsx, shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
Fix notify edit display bug.
->
| 🇺🇸 English |  Fixed display issues when notifying editors. |
| 🇨🇳 中文    |   修复了通知编辑时的显示问题。   |
❎ No
Fixes #
=> fix(dop): notify edit display bug

shell/app/common/components/card-container/index.scss, shell/app/common/components/card-list/index.tsx, shell/app/common/components/user-profile/index.tsx, shell/app/modules/msp/env-overview/service-list/pages/index.tsx, shell/app/modules/msp/env-overview/service-list/pages/overview.tsx, shell/app/modules/msp/pages/micro-service/overview.tsx, shell/app/modules/project/pages/issue/task-summary.tsx, shell/app/modules/project/pages/resource/components/service-list.scss, shell/app/org-home/pages/active-rank/index.tsx, shell/app/org-home/pages/personal-contribute/index.tsx
remove shadow style in some page
modify the style of CardList to make it the same as List
before:
current:
| 🇺🇸 English | according to UI to remove shadow style in some page|
| 🇨🇳 中文    | 根据 UI 建议移除一些页面的阴影样式 |
❎ No
Fixes #
=> style: remove shadow in some page

shell/app/common/components/configurable-filter/index.tsx, shell/app/common/components/render-form-item/index.tsx, shell/app/styles/antd-extension.scss
fix: fix filter style in select dropdown
before
after
| 🇺🇸 English |  fix: fix filter style in select dropdown            |
| 🇨🇳 中文    |   fix: 修复筛选器select下拉样式           |
❎ No
Fixes #
=> fix: fix filter style in select dropdown

shell/app/config-page/components/table/render-types.tsx, shell/app/locales/zh.json, shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Change Chinese translation of backlog.
->
| 🇺🇸 English | Text "待处理" changed to "待规划".  |
| 🇨🇳 中文    | 文案“待处理”改为“待规划”。 |
❎ No
Fixes #
=> fix(common): change Chinese translation of backlog

shell/app/modules/project/pages/release/components/form.tsx
Release version name checking rule change.
❎ No
| 🇺🇸 English |  Add "+" to verification rule of item - level product version name. |
| 🇨🇳 中文    | 项目级制品版本名称校验规则增加“+”。 |
❎ No
Fixes #
=> fix(dop): release version name checking rule change

shell/app/common/components/markdown-editor/editor.tsx, shell/app/styles/antd-extension.scss
disable markdown editor underline plugin for not support syntax
update image avatar background to transparent
| 🇺🇸 English |  disable markdown editor underline plugin for not support syntax   |
| 🇨🇳 中文    |  禁用 markdown 编辑器的下划线插件    |
❎ No
Fixes #
=> fix: disable markdown editor underline plugin

shell/app/common/components/table/index.scss, shell/app/config-page/components/table/table.tsx
- Table reload and config button add hover style.
- In config page, table add reload operations.
| 🇺🇸 English | The table header button adds a floating background color. |
| 🇨🇳 中文    |  表格头部按钮增加悬浮背景色。 |
❎ No
Fixes #
=> fix(common): table reload and config button add hover style

shell/app/config-page/components/gantt/components/gantt/gantt.tsx, shell/app/config-page/components/gantt/gantt.tsx, shell/app/config-page/components/gantt/types/public-types.ts, shell/app/config-page/index.tsx, shell/app/modules/project/pages/issue/gantt/index.tsx
fix: always position to today after filter
❎ No
| 🇺🇸 English |  fix: always position to today after filter in gantt  |
| 🇨🇳 中文    |   甘特图中搜索后总是定位到今天   |
❎ No
Fixes #
=> fix: always position to today after filter in gantt

scheduler/src/filters/not-found.filter.ts
org name may have "-", current proxy regexp is not match.
❎ No
| 🇺🇸 English | repo file is notfound when refresh page |
| 🇨🇳 中文    |   在代码仓库文件页面刷新后展示 notfound  |
❎ No
Fixes #
=> fix: repo file is notfound when refresh page

shell/app/modules/project/pages/issue/board.tsx
fix: export issue not pass filter params in kanban page
❎ No
| 🇺🇸 English | fix: export issue not pass filter params in kanban page  |
| 🇨🇳 中文    |  看板页面导出事项时没有带上过滤参数  |
❎ No
Fixes #
=> fix(dop): export issue not pass filter params in kanban page

shell/app/config-page/components/kanban/kanban.scss, shell/app/config-page/components/kanban/kanban.tsx, shell/app/modules/application/pages/build/build.scss, shell/app/modules/application/pages/build/build.tsx, shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx, shell/app/modules/project/common/components/issue/issue-drawer.scss
fix: rename list-item class to prevent misused with tailwind
❎ No
| 🇺🇸 English |   fix: rename list-item class to prevent misused with tailwind    |
| 🇨🇳 中文    |   重命名 list-item 样式类避免被 tailwind 加上错误样式   |
Fixes #
=> fix: rename list-item class to prevent misused with tailwind

shell/app/config-page/components/card/card.mock.ts, shell/app/config-page/components/card/card.tsx, shell/app/modules/project/router.tsx
fix: card component crashed in gallery page
❎ No
| 🇺🇸 English |  fix: card component crashed in gallery page   |
| 🇨🇳 中文    |   修复卡片组件在组件预览页崩溃的问题  |
Fixes #
=> fix: card component crashed in gallery page

shell/app/common/components/markdown-render/index.tsx
fix: line break in markdown render code block
| 🇺🇸 English |  fix: line break in markdown render code block  |
| 🇨🇳 中文    | 修复markdown 内容里的代码块没有换行的问题    |
Fixes #
=> fix: line break in markdown render code block

shell/app/common/components/configurable-filter/config-selector.tsx, shell/app/common/components/render-form-item/index.tsx
Fix configurable filter delete config bug
❎ No
| 🇺🇸 English | Fixed a bug where filters were triggered when a filter deleted a filter configuration.  |
| 🇨🇳 中文    | 修复了筛选器删除筛选配置时会触发筛选的bug。  |
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=282215&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(common): configurable filter delete config bug

shell/app/common/components/render-form-item/index.tsx
Fix configurable filter tags select scroll bar style bug.
->
| 🇺🇸 English | Fix style bug of filter tags select scroll bar. |
| 🇨🇳 中文    |  修复了筛选器中标签选择器滚动条的样式问题。  |
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=281968&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG
=> fix(common): configurable filter tags select scroll bar style bug

shell/app/common/components/render-form-item/index.tsx
TagsSelect supports radio selection.
❎ No
| 🇺🇸 English | Fixed bug of Label selector setup radio options would report errors. |
| 🇨🇳 中文    | 修复了标签选择器设置单选会报错的问题。 |
❎ No
Fixes #
=> fix(common): tagsSelect supports radio selection

shell/app/modules/project/pages/release/components/form.tsx, shell/app/modules/project/pages/release/components/release-select.scss, shell/app/modules/project/pages/release/components/release-select.tsx
Fix create project release style bug
->
| 🇺🇸 English |  Fixed an error in selecting application style display when creating project artifacts. |
| 🇨🇳 中文    | 修复了创建项目制品时选择应用制品样式显示错误。 |
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=283086&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG
=> fix(dop): create project release style bug

shell/app/modules/project/pages/release/components/form.tsx, shell/app/modules/project/pages/release/components/release-select.tsx
Fix project release group edit bug.
❎ No
| 🇺🇸 English |  Fixed issues where project artifacts and application artifacts were not mutually exclusive when editing and deletion failed. |
| 🇨🇳 中文    | 修复了项目制品编辑时同应用制品未互斥和删除失效的问题。 |
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=283327&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG
https://erda.cloud/erda/dop/projects/387/issues/all?id=283325&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDc …
=> fix(dop): project release group edit bug

shell/app/charts/utils/formatter.js, shell/app/modules/msp/alarm-manage/overview/base-overview.tsx
fixed tips not be fully displayed
❎ No
| 🇺🇸 English | fixed tips not be fully displayed  |
| 🇨🇳 中文    | 修复tips不能完全显示  |
Fixes #
=> fix(msp): fixed tips not be fully displayed

shell/app/modules/project/pages/release/components/form.tsx
Fix project release group style bug.
->
| 🇺🇸 English | Fixed a time display issue when selecting an app release.  |
| 🇨🇳 中文    |  修复了选择应用制品时时间显示的问题。  |
Fixes #
=> fix(dop): project release group style bug

shell/app/common/components/load-more-selector/index.tsx
fix: fix member selector dropdown width error
| 🇺🇸 English |     fix: fix member selector dropdown width error         |
| 🇨🇳 中文    |   fix: 修复成员选择下拉宽度错误         |
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=283363&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG
=> fix: fix member selector dropdown width error

shell/app/modules/project/pages/release/components/form.tsx
Project release filter empty groups.
❎ No
| 🇺🇸 English | Project release filter empty group. |
| 🇨🇳 中文    | 项目级制品分组过滤掉空的组。 |
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=283440&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG
=> fix(dop): project release filter empty groups

shell/app/common/components/load-more-selector/index.tsx
Load more selector icon change
->
| 🇺🇸 English |  Manually click load more button icon changed to static. |
| 🇨🇳 中文    | 手动点击的加载更多按钮图标改成静态的。 |
Fixes #
=> fix(common): load more selector icon change

shell/app/config-page/components/table/v2/table.tsx
fix sort key
❎ No
| 🇺🇸 English | fix a bug that sort is invalid |
| 🇨🇳 中文    | 修复排序无效的bug |
❎ No
Fixes #
=> fix(msp): fix sort key

shell/app/modules/msp/alarm-manage/alarm-strategy/index.js
remove noWrapper from the alarm strategy
❎ No
| 🇺🇸 English | remove noWrapper from the alarm strategy |
| 🇨🇳 中文    | 移除告警策略中的 noWrapper 配置项 |
❎ No
Fixes #
=> fix(msp): remove noWrapper from the alarm strategy

shell/app/modules/msp/pages/micro-service/overview.tsx
replace Tag with Badge in MSP project list and  consistent with the Personal Workbench
| 🇺🇸 English | replace Tag with Badge in MSP project list |
| 🇨🇳 中文    | 将 MSP 项目列表中的 Tag 替换为 Badge |
❎ No
Fixes #
=> feat(msp): replace Tag with Badge in MSP project list

shell/app/common/components/load-more-selector/index.tsx
Project selector style optimization.
->
| 🇺🇸 English | Style optimization for item selectors when item names are too long. |
| 🇨🇳 中文    |  项目选择器在项目名称超长时的样式优化。  |
❎ No
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=283567&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG
=> fix(dop): project selector style optimization

shell/app/configForm/nusi-form/form-items/date-picker.tsx
fix datapick validate
❎ No
| 🇺🇸 English | fix datePicker validate |
| 🇨🇳 中文    | 修复 datePicker 校验逻辑 |
❎ No
Fixes #
=> fix(msp): fix datePicker validate

locales/en.json, locales/zh.json, shell/app/modules/dop/pages/projects/project-list-protocol.tsx
fix: fix create project style
| 🇺🇸 English |    fix: fix create project style in project list          |
| 🇨🇳 中文    |     fix: 修复项目列表中创建项目按钮样式         |
❎ No
Fixes #
=> fix: fix create project style in project list

shell/app/modules/project/pages/issue/board.tsx
fix: fix kanban request twice when switch type
❎ No
| 🇺🇸 English |    fix: fix kanban request twice when switch type          |
| 🇨🇳 中文    |    fix: 修复看板切换类型后请求两次接口         |
❎ No
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=283874&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1090&type=BUG
=> fix: fix kanban request twice when switch type

shell/app/modules/application/pages/problem/problem-list.tsx
fix: return to first page after filter value change
❎ No
| 🇺🇸 English |fix: return to first page after filter value change |
| 🇨🇳 中文    |   问题列表筛选改变后返回第一页 |
❎ No
Fixes #
=> fix: return to first page after filter value change

shell/app/common/components/menu/index.tsx, shell/app/layout/pages/page-container/components/header.scss, shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/application/router.ts, shell/app/modules/application/tabs.tsx, shell/app/modules/project/tabs.tsx
fix(dop): tab info should disable click
❎ No
| 🇺🇸 English | Fixed an issue where clicking the TAB title of a page went to a page that did not exist     |
| 🇨🇳 中文    |   修复点击页面 tab 标题进入不存在页面的问题   |
❎ No
Fixes #
=> fix(dop): tab info should disable click

shell/app/modules/project/pages/release/components/application-detail.tsx, shell/app/modules/project/pages/release/components/form.scss
fix tabs not display when there is too much content
- [【线上问题】【制品】制品详情中 dice.yml内容比较多的时候滚动后菜单也跟着滚动不显示了](https://erda.cloud/erda/dop/projects/387/issues/all?id=285643&iterationID=1090&type=BUG)
✅ No
| 🇺🇸 English | fix tabs not display when there is too much content in dice.yml |
| 🇨🇳 中文    | 修复了 dice.yml  中内容过多时，tab不显示的问题 |
=> fix(dop): fix tabs not display when there is too much content

shell/app/common/components/configurable-filter/index.tsx
Fix configurable filter bug when form items depend on each other
Fixes #
- [Erda Cloud Issue Link]()
❎ No
| 🇺🇸 English | Fix configurable filter bug when form items depend on each other. |
| 🇨🇳 中文    |  修复了可配置筛选器在表单项相互依赖时的bug。  |
❎ No
=> fix(common): configurable filter bug when form items depend on each other

shell/app/modules/project/pages/release/components/form.tsx
Create release add latest filter.
Fixes #
| 🇺🇸 English | Added filter by branch aggregation when creating project artifacts to select application artifacts. |
| 🇨🇳 中文    | 创建项目制品选择应用制品时，增加按分支聚合的筛选。 |
❎ No
=> feat: create release add latest filter

shell/app/modules/project/pages/release/components/form.tsx
Fix create release style bug in firefox.
Fixes #
->
| 🇺🇸 English | Fixed styling issues when creating project artifacts in Firefox.  |
| 🇨🇳 中文    | 修复了在火狐浏览器下创建项目制品时的样式问题。 |
❎ No
=> fix: create release style bug in firefox

shell/app/common/components/configurable-filter/index.tsx
Configurable filter required form item remove the clear.
Fixes #
->
| 🇺🇸 English |  Remove the clear button from the mandatory field in configurable filters. |
| 🇨🇳 中文    |  可配置筛选器中，必填项去掉清除按钮。  |
release/2.0
=> fix(common): configurable filter required form item remove the clear button

shell/app/modules/msp/monitor/api-insight/common/components/apiDelayPanel.tsx, shell/app/modules/msp/monitor/api-insight/common/components/apiSizePanel.tsx, shell/app/modules/msp/monitor/api-insight/common/components/topPVPanel.tsx, shell/app/modules/msp/monitor/monitor-common/components/chartFactory.tsx, shell/app/modules/msp/query-analysis/custom-dashboard/index.ts, shell/app/modules/msp/router.ts, shell/app/modules/msp/types/gateway.d.ts
replace antd table with erdaTable [erda-project/erda-ui-enterprise#222](https://github.com/erda-project/erda-ui-enterprise/pull/222)
❎ No
| 🇺🇸 English | replace antd table with erdaTable |
| 🇨🇳 中文    | 使用 erdaTable 替换 antd table |
❎ No
Fixes #
=> feat(msp): replace antd table with erdaTable

shell/app/common/utils/__tests__/index.test.tsx, shell/app/common/utils/index.ts, shell/app/org-home/pages/land/index.tsx, shell/app/org-home/services/org.tsx, shell/app/org-home/stores/org.tsx
- [有平台管理员角色的账号着陆页可选择参与的企业列表数据错误](https://erda.cloud/erda/dop/projects/387/issues/all?id=281865&iterationID=1115&type=BUG)
| 🇺🇸 English | fix bug that landing page ORG list is incorrect under the platform administrator account |
| 🇨🇳 中文    | 修复平台管理员角色帐号下的着陆页 org 列表数据错误的问题 |
release/2.0
=> fix(dop): fix land page org list error

pnpm-lock.yaml, shell/app/modules/cmp/pages/alarm-report/report-records/index.tsx, shell/package.json
fix: i18n dashboard in O&M report
Fixes #
- [【集成环境】【国际化】运维报告，报告中的图例没有翻译](https://erda.cloud/erda/dop/projects/387/issues/all?id=279274&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=BUG)
❎ No
| 🇺🇸 English |  O&M report legend internationalization  |
| 🇨🇳 中文    | 运维报告图例国际化 |
❎ No
=> fix(cmp): i18n dashboard in O&M report

shell/app/modules/project/pages/release/components/release-select.tsx
Create release remove groups number limit.
Fixes #
❎ No
| 🇺🇸 English | Remove the limit on the number of groupings of artifacts when creating project-level artifacts.  |
| 🇨🇳 中文    |  创建项目级制品时，去掉制品分组的数量限制。  |
release/2.0
=> fix(dop): create release remove groups number limit

shell/app/common/components/configurable-filter/index.tsx
fix: fix configurable filter only external fields
Fixes #
| 🇺🇸 English |    fix: fix configurable filter only external fields          |
| 🇨🇳 中文    |   fix: 修复filter组件中只有外置fields的情况          |
❎ No
=> fix: fix configurable filter only external fields

shell/app/common/components/configurable-filter/index.tsx
Fix configurable filter input value display bug.
Fixes #
| 🇺🇸 English | In the project pipeline, the filter criteria are cleared when the pipeline classification is switched, but the input box in the filter still shows the previous filter value.  |
| 🇨🇳 中文    |  项目级流水线中，在切换流水线分类时会清空筛选的筛选条件，但是筛选器中的输入框还显示着之前的筛选值。  |
❎ No
=> fix(common): configurable filter input value display bug

shell/app/modules/msp/alarm-manage/alert-list/notification/base-notification-detail.tsx, shell/app/modules/msp/alarm-manage/index.ts
compatibility with old deployment center links
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=288812&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
❎ No
| 🇺🇸 English | compatibility with old deployment center links |
| 🇨🇳 中文    | 兼容旧部署中心链接 |
❎ No
=> fix(msp): compatibility with old deployment center links

shell/app/modules/project/pages/settings/components/project-cluster.tsx
Fix project setting quota table reload bug.
Fixes #
❎ No
| 🇺🇸 English | Fixed bug where project settings - project quota table refresh button would not work.  |
| 🇨🇳 中文    |  修复了项目设置-项目配额表格刷新按钮失效的bug。  |
❎ No
=> fix(common): project setting quota table reload bug

shell/app/modules/dop/router.ts
Dop application list router remove.
Fixes #
❎ No
| 🇺🇸 English |  The application list route in DevOps was deleted.  |
| 🇨🇳 中文    |  DevOps平台下的应用列表路由删除。  |
❎ No
=> fix(dop): dop application list router remove

shell/app/config-page/components/file-tree/file-tree.spec.d.ts, shell/app/config-page/components/file-tree/file-tree.tsx
fix: Tree component support node item draggable
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=257907&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=-1&type=BUG)
| 🇺🇸 English |  fix: Tree component support node item draggable            |
| 🇨🇳 中文    |    fix: Tree 组件支持节点的拖拽控制          |
❎ No
=> fix: Tree component support node item draggable

cli/lib/init.ts, cli/package.json
In local dev mode, the `BACKEND_URL` is actually the online UI url, so change the default value to `erda.io`
**api proxy flow:**
// online:
ui -> scheduler -> proxy: isProd ? **replaceOrg** : originPath -> BACKEND_URL(openAPI)
// local vite:
ui -> vite -> BACKEND_URL(online ui) -> online scheduler -> ...
// local webpack:
ui -> scheduler -> proxy: isProd ? replaceOrg : **originPath** -> BACKEND_URL(online ui) -> online scheduler -> ...
Fixes #
❎ No
| 🇺🇸 English |  update cli initial default value   |
| 🇨🇳 中文    |    更新 cli 初始化的初始默认值   |
❎ No
=> fix: update backend url tip and default value

shell/app/modules/project/pages/release/components/release-select.tsx
Fix deploy detail applications display bug.
Fixes #
->
| 🇺🇸 English |  Fixed display bug of application list in deployment sheet details.  |
| 🇨🇳 中文    |  修复了部署单详情中应用列表的显示bug。  |
❎ No
=> fix(dop): deploy detail applications display bug

shell/app/common/components/configurable-filter/index.scss
Fix configurable filter text color bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=292616&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
->
| 🇺🇸 English |  Fixed a text color bug in configurable filters.  |
| 🇨🇳 中文    |   修复了可配置筛选器的文字颜色bug。  |
❎ No
=> fix(dop): configurable filter text color bug

shell/app/common/components/members-table/index.tsx, shell/app/common/components/table/index.tsx, shell/app/common/components/table/interface.ts, shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx, shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx, shell/app/modules/project/common/components/branch-rule.tsx, shell/app/modules/project/common/components/scan-rule.tsx, shell/app/modules/project/pages/issue/issue-protocol.tsx, shell/app/modules/project/pages/iteration/table.tsx, shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx, shell/app/modules/project/pages/release/release-protocol.tsx, shell/app/modules/project/pages/settings/components/project-cluster.tsx, shell/app/modules/project/pages/settings/components/project-settings.tsx, shell/app/modules/project/pages/test-env/test-env.tsx, shell/app/modules/project/pages/test-plan/test-plan-protocol.tsx, shell/app/modules/project/pages/test-plan/test-plan.tsx, shell/app/modules/project/pages/test-report/index.tsx, shell/app/modules/project/pages/ticket/index.tsx
Save the display status of table columns.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=293043&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=REQUIREMENT)
❎ No
| 🇺🇸 English | Save the display state of each table column so that the table column remains explicitly and implicitly unchanged as its data changes.  |
| 🇨🇳 中文    |  保存每个表格列的展示状态，使其数据发生变化时表格列显隐保持不变。  |
❎ No
=> fix(common): save the display status of table columns

shell/app/common/components/table/index.tsx
Fix config page table batch selection bug.
Fixes #
->
| 🇺🇸 English |  Fixed display bug for batch selection of componentized tables.  |
| 🇨🇳 中文    |  修复了组件化表格批量选择的显示bug。  |
release/2.1-beta.1
=> fix(dop): config page table batch selection bug

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx, shell/app/modules/project/common/components/issue/subscribers-selector.tsx, shell/app/modules/project/common/components/workflow-state-form.tsx, shell/app/modules/project/pages/backlog/backlog.tsx, shell/app/modules/project/pages/backlog/iteration-item.tsx, shell/app/modules/project/pages/issue/issue-protocol.tsx, shell/app/modules/project/stores/issues.ts
query `type` is used for locate the target tab, but now, when copy issue share link in 'ALL' type tab, will put the issue type to query, so open the share link, the query filter not match.
Fixes #
❎ No
| 🇺🇸 English |   Fixed issue where some of the status entries in the event filter were displayed as numbers   |
| 🇨🇳 中文    |   修复事项筛选器的部分状态条目展示为数字的问题   |
❎ No
=> fix(dop): type in issue share link cause wrong filter item

shell/app/common/components/pagination/index.tsx, shell/app/modules/project/common/components/issue/issue-relation.tsx, shell/app/modules/project/pages/ticket/index.tsx
* fix open related ticket is not found
* limit relate table page size always to be 7
* fix ticket filter cause page crash when select only one time
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=295084&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTY0LDExNDZdLCJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJsYWJlbElEcyI6WzE0ODVdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6NTB9&iterationID=1146&type=BUG)
| 🇺🇸 English |   Fix the problem that the page cannot be found after opening the referenced ticket page    |
| 🇨🇳 中文    |  修复打开关联工单页面后找不到页面的问题     |
✅ …
=> fix(dop): referenced ticket page is not found

shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
domain names are deleted in the wrong order
Fixes #
- [【线上问题】runtime 详情中域名管理删除自定义域名异常](https://erda.cloud/erda/dop/projects/387/issues/all?id=296788&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English | fix that domain names are deleted in the wrong order |
| 🇨🇳 中文    | 修复域名删除顺序错误问题 |
=> fix(dop): domain names are deleted in the wrong order

pnpm-lock.yaml, shell/package.json
'textMap' is undefined in line chart option causing the console to report an error, the same as [fix(msp): textMap is undefined in line option #3188](https://github.com/erda-project/erda-ui/pull/3188)
Fixes #
❎ No
| 🇺🇸 English | 'textMap' is undefined in line chart option causing the console to report an error |
| 🇨🇳 中文    |  线状图的 option 文件中的 'textMap' 未定义，导致控制台报错  |
✅ No
=> fix(msp): textMap is undefined in line option

locales/en.json, locales/zh.json, shell/app/common/components/table/index.tsx, shell/app/common/components/table/interface.ts, shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx, shell/app/modules/apiManagePlatform/types/api-market.d.ts
add field valid  to check whether a file exists
**This PR should be merged after [fix: add field valid in downloads records response data #4462](https://github.com/erda-project/erda/pull/4462) merged**
Fixes #
❎ No
| 🇺🇸 English | add field `valid`  to check whether a file exists |
| 🇨🇳 中文    |  增加 `valid` 字段 判断文件是否存在 |
❎ No
=> feat(dop): add field `valid`  to check whether a file exists

shell/app/modules/project/pages/pipelines/index.tsx
Project pipeline types list optimization.
Fixes #
❎ No
| 🇺🇸 English |  Save the pipeline classification in the route parameter, the default is to return the first item in the list.  |
| 🇨🇳 中文    |   将流水线分类保存在路由参数中，默认选中返回列表第一项。  |
=> fix(dop): project pipeline types list optimization

.erda/pipelines/ci-build-ce.yml, cli/package.json, cspell.json, pipeline.yml, scheduler/src/proxy.ts
seem this issue happens at `OnError` function
maybe the res was ended before onError func, so that any further operation will cause unhandled error.
So that, this time add `try/catch` & `writableEnded ` check to avoid crash
Fixes #
❎ No
| 🇺🇸 English |    fix frontend server crash issue          |
| 🇨🇳 中文    |  修复前端服务器崩溃重启问题            |
=> fix(scheduler): fix server crash when handling proxy error issue

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/project/pages/release/components/form.tsx
Project release detail add modes.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298059&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=TASK)
| 🇺🇸 English | Added schema information to project artifact details. |
| 🇨🇳 中文    | 项目制品详情中增加模式信息。 |
❎ No
=> feat(dop): project release detail add modes

shell/app/modules/project/common/components/params-config/list-edit.tsx
fix: fix params config list edit add empty key error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix params config list edit add empty key error           |
| 🇨🇳 中文    |     fix: 修复参数配置中添加为空的key错误         |
❎ No
=> fix: fix params config list edit add empty key error

shell/app/common/components/radio-tabs/index.tsx, shell/app/modules/project/common/components/params-config/list-edit.tsx
feat: fix params-config tab switch error
Fixes #
❎ No
| 🇺🇸 English |    fix: fix params-config tab switch error          |
| 🇨🇳 中文    |    fix: 修复参数配置tab切换错误          |
❎ No
=> fix: fix params-config tab switch error

shell/app/modules/application/stores/repo.ts
fix: correct the count of committed MR, the count does not change with the results of the filter
Fixes #
- [修复：合并请求中已提交后面的数字和下面的列表信息不一致的问题](https://erda.cloud/erda/dop/projects/387/issues/all?id=300232&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIyNCIsIjEwOTE4IiwiMTAwMDMwMCIsIjEwMzkwIiwiMTAwMTIxNCIsIjEwMDA1NjIiLCIxMDAxMDc1IiwiMTAwMzA5MyIsIjEwMDA3MjMiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=TASK)
❎ No
| 🇺🇸 English | correct the count of committed MR |
| 🇨🇳 中文    | 修正已提交 MR 的数量 |
❎ No
=> fix(dop): correct the count of committed MR

shell/app/modules/project/common/components/params-config/list-edit.tsx
fix: fix params config list item to long style error
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=301047&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=BUG)
| 🇺🇸 English |     fix: fix params config list item to long style error         |
| 🇨🇳 中文    |    fix: 修复参数配置单元格过长样式问题         |
❎ No
=> fix: fix params config list item to long style error

shell/app/common/components/edit-field/index.tsx, shell/app/common/components/tags/index.tsx, shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Issue detail edit button style optimization.
Fixes #
| 🇺🇸 English |  Increased the edit icon in the event details; [Fixed] Increased the distance from the top of the edit icon when following the scroll Left-align label values with values of other items.  |
| 🇨🇳 中文    |  加大了事项详情中的编辑图标；增加了编辑图标跟随滚动时离顶部的距离；将标签值与其他项的值左对齐。  |
=> fix(dop): issue detail edit button style optimization

shell/app/config-page/components/table/render-types.tsx
Config table progress column optimization.
Fixes #
| 🇺🇸 English |   The circular progress bar column of the componentized table allows the percentage to be left undisplayed on the right side of the progress bar.  |
| 🇨🇳 中文    |  组件化表格的环状进度条列允许进度条右侧不显示百分比。  |
=> fix(common): config table progress column optimization

shell/app/modules/project/pages/issue/issue-dashboard.tsx, shell/app/modules/project/pages/issue/statistics.tsx, shell/app/modules/project/pages/issue/task-summary.tsx, shell/app/modules/project/router.tsx, shell/app/modules/project/tabs.tsx
Add statistics page to iteration.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298069&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=TASK)
| 🇺🇸 English | Add statistics pages within iterations. |
| 🇨🇳 中文    |  迭代内增加统计页。  |
❎ No
=> feat(dop): add statistics page to iteration

shell/app/modules/project/common/components/issue/issue-relation.tsx
fix: refresh issue detail after relation mr
Fixes #
❎ No
| 🇺🇸 English |   fix: refresh issue detail after relation mr           |
| 🇨🇳 中文    |     fix: 关联mr后，刷新事项详情         |
❎ No
=> fix: refresh issue detail after relation mr

shell/app/common/components/text-block-info/index.tsx, shell/app/config-page/components/simple-chart/simple-chart.spec.d.ts, shell/app/config-page/components/simple-chart/simple-chart.tsx
Text block info add jump link.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298072&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&type=TASK)
❎ No
| 🇺🇸 English |   Performance Metrics - Statistics page supports link jump.   |
| 🇨🇳 中文    |  效能度量-统计页支持链接跳转。   |
❎ No
=> feat(common): text block info add jump link

shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx, shell/app/modules/application/stores/build.ts
Fix pipeline build history page size change bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=304205&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&type=BUG)
❎ No
| 🇺🇸 English |  The pipeline execution record changes the number of items per page.   |
| 🇨🇳 中文    |  流水线执行记录变更每页条数失效。   |
release/2.1-beta.3-3
=> fix(dop): pipeline build history page size change bug

shell/app/modules/cmp/common/custom-dashboard/import-export.tsx, shell/app/modules/cmp/common/custom-dashboard/index.tsx
fix(msp): can not get the error when parsing file
❎ No
| 🇺🇸 English | can not get the error when parsing file |
| 🇨🇳 中文    | 未获取解析文件时的报错信息 |
❎ No
=> fix(msp): can not get error when parse file

shell/app/modules/cmp/common/custom-dashboard/import-export.tsx
feat: export tab is set as the default tab in the custom dashboard
❎ No
| 🇺🇸 English | export tab is set as the default tab in the custom dashboard |
| 🇨🇳 中文    | 在自定义大盘中将导出 tab 作默认 tab |
❎ No
=> feat(msp): export tab is set as default tab

shell/app/modules/project/common/components/params-config/list-edit.tsx
fix: fix params config empty tooltip
Fixes #
❎ No
| 🇺🇸 English |     fix: fix params config empty tooltip         |
| 🇨🇳 中文    |     fix: 修复参数配置中为空时展示tooltip         |
release/2.1-beta.3-3
=> fix: fix params config empty tooltip

pnpm-lock.yaml, shell/package.json
bump [@erda-ui/dashboard-configurator](https://github.com/Erda-FE/dashboard-configuration) from 2.0.12 to 2.0.13
Commits
- [6d0f429](https://github.com/Erda-FE/dashboard-configuration/pull/70/commits/6d0f429301f8636629013f9c2682ddb2666008ee) chore: replace node-sass with sass
Fixes #
❎ No
❎ No
=> feat(msp): bump @erda-ui/dashboard-configurator from 2.0.12 to 2.0.13

shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx, shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx, shell/app/modules/cmp/common/alarm-strategy/trigger-condition-select.tsx, shell/app/modules/cmp/services/alarm-strategy.ts, shell/app/modules/cmp/types/alarm-strategy.d.ts, shell/app/modules/msp/alarm-manage/alarm-strategy/services/alarm-strategy.ts
compatible with data and refactor code in MSP
❎ No
| 🇺🇸 English |  compatible with data and refactor code of alarm strategy in MSP   |
| 🇨🇳 中文    |  在微服务平台中的告警策略中兼容数据并重构代码 |
❎ No
=> fix(msp): compatible with data and refactor code in MSP

shell/app/modules/cmp/common/custom-dashboard/import-export.tsx, shell/app/modules/cmp/common/custom-dashboard/index.tsx
1. add a description filter to the custom dashboard
2. update the creator with the avatar in the table
3. go to record after exporting files
❎ No
| 🇺🇸 English | add a description filter to the custom dashboard  |
| 🇨🇳 中文    |  自定义大盘中增加按描述过滤的筛选项  |
❎ No
=> feat(msp): add description filter to the custom dashboard

shell/app/modules/project/common/components/pipeline-new/detail/editor.tsx
fix: switch to execute page when pipeline exist
Fixes #
❎ No
| 🇺🇸 English |      fix: switch to execute page when pipeline exist        |
| 🇨🇳 中文    |  fix: 切换流水线执行页面前判断是否存在            |
❎ No
=> fix: switch to execute page when pipeline exist

pnpm-lock.yaml, shell/package.json
display the nullDisplay when editing the dashboard
Fixes #
- [【集成环境】【自定义大盘】编辑时空值显示字段没没有显示](https://erda.cloud/erda/dop/projects/387/issues/all?id=305219&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&type=BUG)
❎ No
| 🇺🇸 English | display the nullDisplay when editing the dashboard |
| 🇨🇳 中文    | 编辑大盘的时候显示【空值显示字段】|
❎ No
=> fix(msp): display nullDisplay when editing dashboard

shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
fix: fix runtime domain setting style
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=305157&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1174&type=BUG)
❎ No
| 🇺🇸 English |    fix: fix runtime domain setting style          |
| 🇨🇳 中文    |     fix: 修复runtime域名设置样式问题     |
❎ No
=> fix: fix runtime domain setting style

shell/app/modules/project/pages/release/components/form.scss, shell/app/modules/project/pages/release/components/form.tsx
Fix create release style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=305448&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&type=BUG)
->
| 🇺🇸 English | Fixed style issues with add-on labels for artifacts.  |
| 🇨🇳 中文    |   修复了制品添加标签的样式问题。  |
❎ No
=> fix(dop): create release style bug

shell/app/common/components/markdown-render/__tests__/index.test.tsx, shell/app/common/components/markdown-render/index.tsx
display null when src of the image is empty in react-markdown
❎ No
| 🇺🇸 English | display null when zooming out the image and its src is empty in react-markdown |
| 🇨🇳 中文    | 在 react-markdown 中，当进行缩小图片操作且其 src 为空时不展示它 |
/cherry-pick release/2.1-beta.4
=> fix(common): display null when src of image is empty in react-markdown

shell/app/common/components/simple-log/__tests__/simple-log-search.test.tsx, shell/app/common/components/simple-log/__tests__/simple-log.test.tsx, shell/app/common/components/simple-log/simple-log-search.tsx, shell/app/config-page/components/table/v2/utils.tsx, shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx, shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
fix missing query params in SimpleLogSearch
Fixes #
- [【集成环境】错误分析-错误详情，查看日志页面，点击搜索报错](https://erda.cloud/erda/dop/projects/387/issues/all?id=306309&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English | fix missing query params in SimpleLogSearch |
| 🇨🇳 中文    | 修复日志搜索组件中查询参数缺失的问题 |
release/2.1-beta.4
=> fix(common): log search params missing

shell/app/modules/application/pages/repo/repo-mr.tsx, shell/app/modules/application/services/repo.ts, shell/app/modules/application/stores/repo.ts, shell/app/modules/application/types/repo.d.ts
display all MR types count in MR requests
Fixes #
before：
now: 
| 🇺🇸 English | display all MR types count in MR requests page |
| 🇨🇳 中文    |  合并请求页面中展示所有类型的数量  |
❎ No
=> feat(dop): display all MR types count in MR requests page

shell/app/common/components/tags-row/index.scss, shell/app/common/components/tags/index.scss
Tags tooltip background color optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=306279&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&type=TASK)
->
| 🇺🇸 English |   Change the background of the label float layer to white. |
| 🇨🇳 中文    |  标签浮层的背景改成白色。  |
❎ No
=> fix(common): tags tooltip background color optimization

shell/app/modules/project/stores/project.tsx
Fix click menu after switch project bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=305704&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&tab=ALL&type=BUG)
❎ No
| 🇺🇸 English |  Fixed an issue where switching items would not work if you clicked the menu quickly after switching items. |
| 🇨🇳 中文    |  修复了在切换项目后快速点击菜单，切换项目无效的问题。   |
❎ No
=> fix(dop): click menu after switch project bug

shell/app/modules/cmp/stores/cluster.ts
Get useable k8s clusters interface optimization.
Fixes #
❎ No
| 🇺🇸 English |   The available cluster interface, which was called on every page of the cloud platform, will be called once only when entering the cloud platform.  |
| 🇨🇳 中文    |  在云管平台每个页面都会调用的可用集群接口，改成只有进入云管平台时调用一次。   |
❎ No
=> fix(cmp): get useable k8s clusters interface optimization

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx, shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
fix: show iteration synchronously tip when update iteration success
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=307105&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=-1&type=BUG)
❎ No
| 🇺🇸 English |     fix: show iteration synchronously tip when update iteration success         |
| 🇨🇳 中文    |   fix: 在修改事项成功后显示同步迭代的提示           |
❎ No
=> fix: show iteration synchronously tip when update iteration success

shell/app/modules/cmp/common/custom-dashboard/index.tsx
correct update time with the edgeNow in dashboard list
Fixes #
❎ No
| 🇺🇸 English |  Fixed the update time displayed in the custom dashboard list   |
| 🇨🇳 中文    |  修正自定义大盘列表中显示的更新时间  |
❎ No
=> fix(msp): correct update time with edgeNow in dashboard list

shell/app/common/components/details-panel/index.tsx, shell/app/common/components/table/__tests__/index.test.tsx, shell/app/common/components/table/index.tsx
table sorter key is misUpdated by i18n fix;
Fixes #
❎ No
| 🇺🇸 English |  fix: table sort not work  |
| 🇨🇳 中文    |      修复表格排序失效的问题        |
release/2.1
=> fix: table sort not work

locales/zh.json, shell/app/modules/application/pages/settings/app-settings.tsx, shell/app/modules/org/pages/projects/settings/member/index.tsx, shell/app/modules/org/pages/setting/org-setting.tsx, shell/app/modules/project/pages/settings/components/project-settings.tsx
fix: links duplicate & links translation miss "[]"
Fixes #3434 
✅ Yes()
| 🇺🇸 English |      links duplicate & links translation miss "[]"        |
| 🇨🇳 中文    |       i18n 链接显示重复 & 链接中文翻译修改       |
❎ No
=> fix: links duplicate & links translation miss "[]"

Dockerfile, cli/lib/init-online.ts, cli/package.json
keep pnpm version to 6.x because 7.x has released and it requires node v14.19 but erda pipeline not support yet
Fixes #
❎ No
| 🇺🇸 English |     keep pnpm version to 6.x         |
| 🇨🇳 中文    |    固定pnpm版本为6.x          |
❎ No
=> fix:(cli): keep pnpm version to 6.x

shell/app/common/components/log-roller/index.tsx
Fixes #
- [【集成环境】容器日志，fluent-bit恢复后，补偿的日志顺序有错](https://erda.erda.cloud/erda/dop/projects/387/issues/all?id=305550&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEzMjkiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English | fix fetch log params |
| 🇨🇳 中文    | 修复获取日志参数 |
❎ No
=> fix(msp): fix fetch log params

shell/app/modules/dcos/pages/cluster-dashboard/instance-list.tsx
Fix overview services table pageSize change bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=309976&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=BUG)
❎ No
| 🇺🇸 English |  Fixed cloud management platform - Cluster Overview - Service catalog switching single page is invalid.   |
| 🇨🇳 中文    | 修复了云管平台-集群总览-服务目录切换单页条数无效的问题。 |
release/2.1
=> fix(cmp): overview services table pageSize change bug

shell/app/locales/utils.ts, shell/app/modules/application/router.ts, shell/app/modules/project/router.tsx
Fix runtime detail breadcrumb bug.
Fixes #
| 🇺🇸 English | Fixed an issue where there was no back button in the runtime details page when jumping from pipeline. |
| 🇨🇳 中文    |  修复了从流水线跳转去runtime详情页中没有返回按钮的问题。  |
❎ No
=> fix(dop): runtime detail breadcrumb bug

erda.yml, scheduler/src/proxy.ts
currently health check visit `/` and will get 302 error. Then it may restart server
Fixes #
| 🇺🇸 English |    fix health check wrong api          |
| 🇨🇳 中文    |    修复健康检查错误的api          |
release/2.2-beta.1
=> fix:(scheduler):fix health check api

shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
Runtime resource config scale add tip.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311054&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&tab=ALL&type=TASK)
| 🇺🇸 English |  The workbench service capacity expansion or reduction prompt is complete. |
| 🇨🇳 中文    |   工作台服务扩缩容提示信息完善。   |
❎ No
=> feat(dop): runtime resource config scale add tip

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
fix: do not open issue detail when issue not found
Fixes #
to 
| 🇺🇸 English |     fix: do not open issue detail when issue not found         |
| 🇨🇳 中文    |   fix: 事项查不到则不打开事项详情          |
❎ No
=> fix: do not open issue detail when issue not found

shell/app/modules/application/router.ts, shell/app/modules/application/tabs.tsx
Mr detail header add app name.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311442&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&tab=ALL&type=TASK)
| 🇺🇸 English |  Submit and display the application name on breadcrumbs on the Mr Details page  |
| 🇨🇳 中文    |  提交和 mr 详情页面包屑上展示应用名称。 |
❎ No
=> feat(dop): mr detail header add app name

shell/app/App.tsx, shell/app/org-home/stores/org.tsx
fix: fix land sysAdmin page whitout admin access
Fixes #
❎ No
| 🇺🇸 English |  fix: fix land sysAdmin page without admin access            |
| 🇨🇳 中文    |  fix: 修复无管理员权限但能访问管理员页面          |
release/2.1
=> fix: fix land sysAdmin page without admin access

shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
display notify method when edit strategy
Fixes #
❎ No
| 🇺🇸 English | display notify method when editing strategy |
| 🇨🇳 中文    | 编辑策略时显示通知方式|
/cherry-pick release/2.1
=> fix(msp): display notify method when edit strategy

shell/app/views/index.ejs, shell/index.html
Try the simplest way to solve mobile operate problem.
There are two ways:
have to write mobile responsive style for every page, and some is not easy such as top-button-group.
no code change, just show pc layout
zoom in:
Fixes #
as above
| 🇺🇸 English |  force show pc layout in mobile  |
| 🇨🇳 中文    |     强制移动端展示 pc 版页面布局   |
❎ No
=> feat: remove viewport meta to force show pc layout in mobile

package.json, pipeline.yml
add pnpm life cycle hook
it only works after pnpm v 6.21.x, so make sure your local pnpm is  v6.21.x or higher
Fixes # preinstall is not work after npm v7
❎ No
| 🇨🇳 中文    |      -      |
❎ No
=> [draft] Replace preinstall hook to pnpm devPreinstall

shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
Project pipeline actions operations icons tooltip optimization.
Fixes #
❎ No
| 🇺🇸 English |  Fixed an issue where bubble prompt does not disappear after project level pipeline node disable is enabled.
|
| 🇨🇳 中文    |  修复了项目级流水线节点禁用启用之后对应的气泡提示不消失的问题。 |
❎ No
=> fix(dop): project pipeline actions operations icons tooltip optimization

shell/app/common/components/edit-field/index.tsx, shell/app/common/components/markdown-editor/editor.tsx, shell/app/common/components/markdown-editor/index.tsx, shell/app/locales/en.json, shell/app/locales/zh.json, shell/app/modules/project/common/components/issue/comment-box.tsx
When nesting more than 2000 quotes, will throw Maximum call stack size exceeded error.
Set limit to 100.
Fixes #
❎ No
| 🇺🇸 English |   fix  markdown editor crash when nesting too many quotes  |
| 🇨🇳 中文    |        修复 markdown 编辑器里输入太多层引用时崩溃问题      |
❎ No
=> fix: markdown editor crash when nesting too many quotes

shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
don't query pipeline detail when pipelineId is 0
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=313691&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=BUG)
❎ No
| 🇺🇸 English | -  |
❎ No
=> fix(dop): don't query pipeline detail when pipelineId is 0

shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Fix  issue detail task type bug.
Fixes #
| 🇺🇸 English |  Fixed an issue where there was no option for task type in task details.  |
| 🇨🇳 中文    | 修复了任务详情中任务类型没有选项的问题。  |
release/2.2-beta.2
=> fix(dop): issue detail task type bug

shell/app/modules/runtime/pages/overview/components/index.tsx
Fix runtime detail icon style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=310928&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&type=BUG)
->
| 🇺🇸 English | Fixed issue with page icon layout when runtime exception occurs. |
| 🇨🇳 中文    | 修复了runtime异常时，页面icon的排版的问题。  |
release/2.2-beta.2
=> fix(dop): runtime detail icon style bug

locales/en.json
fix: i18n DingTalk work notice translation
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=315458&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XSwiYXNzaWduZWVJRHMiOlsiMTAwMzE0NiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1250&type=BUG)
✅ Yes(![image](https://user-images.githubusercontent.com/72543663/172083419-523b7447-9ec5-473a-a2b8-e2b0d94672c0.png))
| 🇺🇸 English |       fix i18n DingTalk work notice translation       |
| 🇨🇳 中文    |      修复国际化文案翻译“DingTalk work …
=> fix: i18n DingTalk work notice translation

shell/app/modules/application/router.ts
fix: fix dataTask menu in 2.1
Fixes #
❎ No
| 🇺🇸 English |     fix: fix dataTask menu in 2.1         |
| 🇨🇳 中文    |   fix: 修复数据任务菜单错误           |
❎ No
=> fix: fix dataTask menu in 2.1

shell/app/common/components/markdown-render/__tests__/index.test.tsx, shell/app/common/components/markdown-render/index.tsx
image in markdown render not fit container width no matter zoom out or not.
Fixes #
default:
scale:
->
default:
scale:
| 🇺🇸 English |  image width not fit container width in markdown render    |
| 🇨🇳 中文    |    修复markdown 编辑器里图片看不全的问题          |
❎ No
=> fix: image width not fit container width in markdown render

shell/app/common/utils/go-to.tsx, shell/app/styles/util.scss
fix: withdraw side menu item :before z-index=-1 & Collaboration go to ticket and open modal
Fixes #
❎ No
| 🇺🇸 English |       fix: withdraw side menu item :before z-index=-1 & collaboration go to ticket and open modal       |
| 🇨🇳 中文    |       解决侧边栏菜单的z-index导致点击失效 &     事项中关联的工单点击后跳转后打开 modal   |
❎ No
=> fix: withdraw side menu item :before z-index=-1 & collaboration go to ticket and open modal

shell/app/antd-overwrite/button/index.tsx, shell/app/i18n-easy-edit/config.ts
delete noEditSuffix in i18n-easy-edit & rewrite overwrite-antd-input
Fixes #
❎ No
| 🇺🇸 English |      delete noEditSuffix in i18n-easy-edit & rewrite overwrite-antd-input        |
| 🇨🇳 中文    |       删除 i18n-easy-edit 后缀修饰符 &  重写overwrite-antd-input 去除冗余逻辑 |
❎ No
=> fix: delete noEditSuffix in i18n-easy-edit & rewrite overwrite-antd-input

shell/app/modules/application/pages/settings/components/app-info.tsx, shell/app/modules/project/common/components/section-info-edit.tsx
fix: after formModal uploaded image, set ok-btn disabled to false
Fixes #
- [[Erda Cloud Issue Link](paste your link here](https://erda.cloud/erda/dop/projects/387/issues/all?id=318806&issueFilter__urlQuery=eyJhc3NpZ25lZUlEcyI6WyIxMDAzMTQ2Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1280&type=BUG))
❎ No
| 🇺🇸 English |     after formModal uploaded image, set ok-btn disabled to false        |
| 🇨🇳 中文    |       上传图片后，设置按钮为可点击状态       |
❎ No
=> fix: after formModal uploaded image, set ok-btn disabled to false

shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
fix: once dropdown labels, get latest labels
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=261637&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE2LDQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2XSwiYXNzaWduZWVJRHMiOlsiMTAwMzE0NiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=REQUIREMENT)
❎ No
| 🇺🇸 English |     fix: once dropdown labels, get latest labels         |
| 🇨🇳 中文    |        项目协同中每次下拉标签时，拉取最新的标签      |
❎ No
=> fix: once dropdown labels, get latest labels

Dockerfile
Tag `bullseye` is the future releases, unstable.
In some scenarios, `bullseye`  is less fault tolerant with the same version of NodeJS, causing the service to fail to start.
Error with bullseye image
Same machine with default slim tag image
@McDaddy 
Fixes #
❎ No
| 🇺🇸 English | change base image from bullseye to default slim tag(stretch)             |
| 🇨🇳 中文    |   替换基础构建镜像，从 bullseye 更换为默认 slim 的版本（stretch）           |
❎ No
=> fix(build): change base image from bullseye to default slim tag(stretch)

shell/app/interface/global.d.ts, shell/app/modules/cmp/pages/alarm-report/report-records/index.tsx, shell/app/modules/cmp/router.ts
fix: delete cmp report history pagination
Fixes #
❎ No
| 🇺🇸 English |     fix: delete cmp report history pagination         |
| 🇨🇳 中文    |   fix: 删除 运维报告历史翻页          |
❎ No
=> fix: delete cmp report history pagination

shell/app/common/components/pure-log-roller/__tests__/log-utils.test.tsx, shell/app/common/components/pure-log-roller/log-util.ts, shell/app/modules/runtime/common/logs/components/container-log.tsx
Fix bug of runtime log format conversion regex.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=368545&iterationID=1580&tab=BUG&type=BUG)
| 🇺🇸 English |   Fix bug of runtime log format conversion regex.  |
| 🇨🇳 中文    |  修复了runtime日志格式转换正则的问题、 |
release/2.3
=> fix: runtime log format conversion regex bug

shell/app/modules/project/pages/backlog/issue-item.scss, shell/app/modules/project/pages/backlog/issue-item.tsx
Issue detail backlog list add date select.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=371277&iterationID=1628&type=TASK)
| 🇺🇸 English |  Issue detail backlog list add date select.  |
| 🇨🇳 中文    |  事项详情待办列表增加日期选择。  |
release/2.3
=> feat: issue detail backlog list add date select

shell/app/modules/application/pages/repo/components/source-target-select.tsx
Fix create mr target branch reset bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=371277&iterationID=1580&type=TASK)
❎ No
| 🇺🇸 English |  Fix bug of target branch reset after target branch changed when creating mr.  |
| 🇨🇳 中文    |  修复了创建mr时，目标分支在目标分支改变之后重置的bug。  |
release/2.3
=> fix: create mr target branch reset bug

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx, shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
Fix issue estimated time bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix issue estimated time bug.  |
| 🇨🇳 中文    |  修复了协同中预估时间的问题。  |
❎ No
=> fix: issue estimated time bug

shell/app/common/components/configurable-filter/index.tsx, shell/app/menus/orgCenter.tsx, shell/app/modules/dop/pages/report/chart-column.tsx, shell/app/modules/dop/pages/report/index.tsx, shell/app/modules/dop/pages/report/rate-select.tsx, shell/app/modules/dop/services/index.ts
Add project report table filter.
Fixes #
| 🇺🇸 English |  Add project report table filter.  |
| 🇨🇳 中文    |  增加项目报表的列表筛选。  |
❎ No
=> feat: project report table filter

shell/app/modules/dop/pages/report/index.tsx
Fix project report detail display bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix project report detail display bug.  |
| 🇨🇳 中文    |  修复了项目报表详情展示数据的问题。  |
❎ No
=> fix: project report detail display bug

shell/app/modules/dop/pages/report/index.tsx
Fix project report detail page jump bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix project report detail page jump bug.  |
| 🇨🇳 中文    |   修复了项目报表详情页面跳转的bug。  |
❎ No
=> fix: project report detail page jump bug

shell/app/menus/dop.tsx, shell/app/menus/orgCenter.tsx, shell/app/modules/dop/pages/report/index.tsx, shell/app/modules/dop/services/index.ts
Project report table project name optimization.
Fixes #
| 🇺🇸 English |  Project report table project name optimization.  |
| 🇨🇳 中文    |   项目报表列表项目名称优化。   |
❎ No
=> fix: project report table project name optimization

shell/app/modules/dop/pages/report/index.tsx
Project report detail display optimization.
Fixes #
| 🇺🇸 English |  Project report detail display optimization.   |
| 🇨🇳 中文    |   项目报表详情页展示优化。   |
❎ No
=> fix: project report detail display optimization

shell/app/layout/stores/layout.ts
Fix bug of msp display bug when switch bug before refresh.
Fixes #
❎ No
| 🇺🇸 English |   Fix bug of msp display bug when switch bug before refresh.  |
| 🇨🇳 中文    |   修复了当切换组织后，刷新页面之前msp不展示的问题。  |
❎ No
=> fix: msp display bug when switch bug before refresh

shell/app/modules/cmp/common/custom-alarm/index.tsx
Msp alarm config add rule bug.
Fixes #
❎ No
| 🇺🇸 English |  Msp alarm config add rule bug.  |
| 🇨🇳 中文    |   微服务告警配置创建规则的bug。   |
❎ No
=> fix: msp alarm config add rule bug

shell/app/modules/dop/pages/report/index.tsx
Project report progress color optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12560/all?id=505154&iterationID=12560&type=BUG)
| 🇺🇸 English |   Project report progress color optimization.   |
| 🇨🇳 中文    |   项目报表进度条颜色优化。  |
❎ No
=> fix: project report progress color optimization

locales/en.json, locales/zh.json, shell/app/modules/application/pages/build-detail/config.tsx, shell/app/modules/application/pages/obsoleted-pipeline/run-detail/config.tsx, shell/app/modules/project/common/components/pipeline-manage/run-detail/config.ts, shell/app/modules/project/common/components/pipeline-new/config.tsx
Pipeline history internationalization bug.
Fixes #
| 🇺🇸 English |  Pipeline history internationalization bug.  |
| 🇨🇳 中文    |   流水线历史列表国际化bug。   |
❎ No
=> fix: pipeline history internationalization bug

shell/app/modules/org/pages/projects/settings/info/index.tsx, shell/app/modules/project/common/components/section-info-edit.tsx
Project info edit labels bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=533802&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |  Project info edit labels bug.  |
| 🇨🇳 中文    |   项目信息编辑标签报错。   |
❎ No
=> fix: project info edit labels bug

shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
add missing params let cmp container download logs from apiserver
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=438540&iterationID=-1&type=BUG)
❎ No
| 🇺🇸 English |  add missing params let cmp container download logs from apiserver            |
| 🇨🇳 中文    |    修补缺少的参数让多云管理容器从k8s apiserver下载日志          |
❎ No
=> fix: add missing params let cmp container download logs from apiserver

shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx, shell/app/modules/org/stores/issue-field.ts
Project level custom fields interface add params name.
Fixes #
❎ No
| 🇺🇸 English |   Project level custom fields interface add params name.  |
| 🇨🇳 中文    |   项目级自定义字段接口增加参数。 |
❎ No
=> fix: project level custom fields interface add params name

locales/en.json, locales/zh.json, shell/app/modules/runtime/pages/overview/components/service-card.tsx
Add finish time for stop pod
- [ x ] I18n is finished and updated by cli
- [ x ] Form fields validation is added and length is limited
- [ x ] Display normally on small screen
- [ x ] Display normally when some data is empty or null
- [ x ] Display normally in english mode
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=553572&iterationID=12783&tab=TASK&type=TASK
| 🇺🇸 English |      new feature, no break change        |
| 🇨🇳 中文    |      完全兼容        |
❎ No
=> fix(shell): add finish time for stop service pod

shell/app/App-vite.tsx, shell/app/App.tsx, shell/app/antd-default-props.tsx, shell/app/config-page/components/api-editor/api-editor.scss, shell/app/config-page/components/table/render-types.tsx, shell/app/layout/pages/page-container/components/chat-GPT/index.tsx, shell/app/layout/stores/layout.ts, shell/app/modules/application/common/components/create-add-on.tsx, shell/app/modules/application/services/repo.ts, shell/app/modules/dcos/services/service.ts, shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx, shell/app/modules/project/pages/test-plan/plan-modal.tsx, shell/app/modules/project/stores/test-plan.ts
Fixes #
❎ No
| 🇺🇸 English |       fix: fix bugs       |
| 🇨🇳 中文    |   fix: fix bugs           |
❎ No
=> fix: fix bugs

pipeline.yml
use `npm ci` when build enterprise-ui
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=620211&iterationID=12783&type=TASK)
❎ No
| 🇺🇸 English |    use `npm ci` when build enterprise-ui          |
| 🇨🇳 中文    |    构建 enterprise-ui 时使用 `npm ci`           |
❎ No
=> chore(build): use `npm ci` when build enterprise-ui

Dockerfile, pipeline.yml
1. Optimize Dockerfile multi-stage build.
2. All build behavior within container.
Local build command: 
```shell
docker build --build-context erda-ui-enterprise=../erda-ui-enterprise . -t <> 
```
@laojun @sfwn 
Fixes #
❎ No
| 🇺🇸 English |  optimize Dockerfile multi-stage build            |
| 🇨🇳 中文    |     优化 Dockerfile 多阶段构建         |
❎ No
=> ci: optimize Dockerfile multi-stage build
