shell/app/config-page/components/tree-select/tree-select.tsx
shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-tree-selector.tsx

Increase max-height of tree select.
->
| 🇺🇸 English | Increase max-height of tree select. |
| 🇨🇳 中文    | 增加了树形选择下拉框的高大高度。 |
release/1.3
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=221827&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG

fix: increase max-height of tree select

---

shell/app/modules/application/common/components/edit-global-variable.tsx

Fix dice.yml edit global variable style bug.
->
| 🇺🇸 English |  Fix dice.yml edit global variable style bug. |
| 🇨🇳 中文    |  修复了dice.yml中编辑全局变量里的样式错误。 |
release/1.3
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=226663&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG

fix: dice.yml edit global variable style bug

---

shell/app/config-page/components/index.tsx
shell/app/config-page/components/modal/modal.spec.d.ts
shell/app/config-page/components/modal/modal.tsx
shell/app/config-page/components/table/table.tsx
shell/app/config-page/config-page.d.ts
shell/app/config-page/index.tsx
shell/app/config-page/utils.tsx
shell/app/modules/cmp/common/cluster-terminal/xterm-binary.tsx
shell/app/modules/org/common/audit-render.tsx
shell/app/modules/org/pages/safety/index.tsx

fix: fix k8s aduit line break / log time format
❎ No
| 🇺🇸 English |     fix: fix k8s aduit line break / log time format         |
| 🇨🇳 中文    |   fix: 修复k8s设计日志换行、log时间格式化          |
release/1.3
Fixes #

fix: fix k8s aduit line break / log time format

---

shell/app/modules/project/pages/plan-detail/report/charts-result/index.tsx

update style of the chart in the test report 
before:
now:
release/1.2     release/1.3
Fixes #

fix: update pie chart in test report

---

core/src/common/components/ellipsis.scss
core/src/common/components/ellipsis.tsx
core/src/common/interface.d.ts
core/src/nusi/index.tsx

Replace Nusi Ellipsis and fixed tooltip position flashing bug.
❎ No
| 🇺🇸 English | Fixed tooltip position flashing bug.  |
| 🇨🇳 中文    |  修复了文字提示弹窗位置闪烁的bug。  |
release/1.3
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/bug?id=73872&issueFilter__urlQuery=eyJ0aXRsZSI6Ium8oOaghyIsInN0YXRlQmVsb25ncyI6WyJPUEVOIiwiV09SS0lORyIsIldPTlRGSVgiLCJSRU9QRU4iLCJSRVNPTFZFRCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=506&type=BUG

refactor: replace Nusi Ellipsis

---

shell/app/modules/msp/config.tsx

update msp menu key
❎ No
release/1.3
Fixes #

update msp menu key

---

pnpm-lock.yaml
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
shell/package.json

1. support api to cover option to config dashboard
2. fix displaying  chart when there is  dashboard Id
❎ No
release/1.3
Fixes #

fix: support api to cover option to config dashboard

---

erda.yml
shell/app/common/constants.ts
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/cmp/pages/cluster-manage/cluster-terminal.tsx
shell/app/user/services/user.ts
shell/app/user/stores/index.ts

fix: fix new uc user logout
❎ No
release/1.3
Fixes #

fix: fix new uc user logout

---

pnpm-lock.yaml
scheduler/package.json
scheduler/src/proxy.ts
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/menus/appCenter.tsx
shell/app/menus/orgCenter.tsx
shell/app/modules/application/stores/application.tsx
shell/app/modules/org/entry.js
shell/app/modules/org/stores/index.ts
shell/app/org-home/stores/org.tsx
shell/app/user/stores/_perm-org.ts

1. add org center menu permission
2.  fetch ws org from url
❎ No
release/1.3
Fixes #

feat(orgcenter): add org center menu permission

---

core/src/nusi/index.tsx

fix: fix Panel
❎ No
❎ No
Fixes #

fix: revert Panel to Nusi for now

---

shell/app/config-page/components/api-editor/api-editor.spec.d.ts
shell/app/config-page/components/api-editor/api-editor.tsx
shell/app/locales/en.json
shell/app/locales/zh.json

validate assert before submit
❎ No
| 🇺🇸 English | validate assert before submit |
| 🇨🇳 中文    | 提交断言前增加校验 |
release/1.3
Fixes #

validate assert before submit

---

Dockerfile
scheduler/src/proxy.ts

* use docker registry
* api/files not send org header
❎ No
release/1.3
Fixes #

feat: use image from erda registry to prevent dockerhub rate ilmit

---

pnpm-lock.yaml
shell/package.json

support muti y-axes
❎ No
release/1.3
Fixes #

fix: support muti y-axes

---

scheduler/src/proxy.ts
shell/app/modules/application/stores/application.tsx
shell/app/modules/org/stores/index.ts
shell/app/modules/project/stores/project.tsx
shell/app/org-home/stores/org.tsx

fix issue
❎ No
release/1.3
Fixes #

fix(dop): fix menu undefined issue

---

core/src/cube.ts

fix error when data is null
❎ No
release/1.3
Fixes #

fix error when data is null

---

shell/app/agent.js
shell/app/common/utils/axios-config.ts

fix: fix api uc in shell
❎ No
release/1.3
Fixes #

fix: fix api uc in shell

---

core/src/cube.ts
shell/app/modules/cmp/stores/alarm-strategy.ts
shell/app/modules/msp/alarm-manage/alarm-strategy/stores/alarm-strategy.ts

fix bug when data is null
❎ No
release/1.3
Fixes #

fix bug when response is null

---

shell/app/agent.js
shell/app/common/utils/axios-config.ts

fix: fix exclude org header api
❎ No
release/1.3
Fixes #

fix: fix exclude org header api

---

shell/app/modules/msp/env-setting/configuration/index.tsx
shell/app/modules/msp/types/configuration.d.ts

Remove the subjecttype parameter from the access configuration
❎ No
release/1.3
Fixes #

feat(msp): Remove the subjecttype parameter from the access configuration

---

shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/user/services/user.ts

fix: uc response data
❎ No
release/1.3
Fixes #

fix: uc response data

---

shell/app/config-page/components/container/container.spec.d.ts
shell/app/config-page/components/container/container.tsx
shell/app/config-page/components/table/render-types.tsx

fix: fix CP table multiple render click event
❎ No
release/1.3
Fixes #

fix: fix CP table multiple render click event

---

core/src/common/components/panel.tsx
core/src/nusi/index.tsx

Fix nodes detail bugs of clusters caused by replace Nusi Panel.
->
| 🇺🇸 English |  FIxed node information arrangement style bug of clusters management nodes detail.  |
| 🇨🇳 中文    |  修复了集群管理节点详情的节点信息排列样式bug。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=227822&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG

fix: nodes detail bugs of clusters caused by replace Nusi Panel

---

shell/app/common/utils/go-to.tsx
shell/app/modules/msp/env-overview/service-list/index.ts
shell/app/modules/msp/env-overview/service-list/pages/index.tsx

remove applicationId from service-list route
❎ No
release/1.3
Fixes #

remove applicationId from service-list route

---

shell/app/modules/project/router.js

Fix internationalization omission.
->
| 🇺🇸 English | Fixed a bug where scene sets would display Chinese in English mode. |
| 🇨🇳 中文    | 修复了场景集合在英文模式下显示中文的bug。 |
❎ No
Fixes #

fix: internationalization omission

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx

hiding check log button when project is MSP
❎ No
release/1.3
Fixes #

feat: hiding check log button when project is MSP

---

shell/app/common/utils/index.ts
shell/app/locales/en.json
shell/app/locales/zh.json

handle the translation problem
❎ No
release/1.3
Fixes #

Handle the translation problem

---

modules/uc/src/common/components/form-input.tsx
modules/uc/src/pages/login/index.tsx
modules/uc/src/pages/registration/index.tsx
modules/uc/src/pages/setting/index.tsx
shell/app/config-page/components/button/button.spec.d.ts
shell/app/config-page/components/button/button.tsx
shell/app/config-page/components/table/render-types.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/cmp/common/cluster-terminal/index.tsx
shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx
shell/app/modules/cmp/pages/cluster-manage/cluster-nodes-detail.tsx
shell/app/modules/cmp/pages/cluster-manage/cluster-pod-detail.tsx
shell/app/org-home/stores/org.tsx

fix: fix k8s ws ping / publisher menu emtpy
❎ No
| 🇺🇸 English |     fix: fix k8s ws ping / publisher menu emtpy         |
| 🇨🇳 中文    |    fix: 修复k8s ws心跳 / 移动平台菜单为空          |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=228016&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG

fix: fix k8s ws ping / publisher menu emtpy

---

shell/app/common/stores/common.ts

Loading too many logs can cause the page to stall
❎ No
| 🇺🇸 English | Limit log max lines to 5000 |
| 🇨🇳 中文    | 限制日志最大加载 5000 行  |
release/1.3
Fixes #

feat: limit log max lines to 5000

---

core/src/common/components/ellipsis.tsx

fix: fix ellipsis tooltip error
❎ No
| 🇺🇸 English |    fix: fix Ellipsis tooltip error          |
| 🇨🇳 中文    |     fix:修复Ellipsis组件展示tip的错误        |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=227926&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG

fix: fix ellipsis tooltip error

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

fix that request after choosing callType
❎ No
release/1.2    release/1.3
Fixes #

fix: request after choosing callType

---

core/src/nusi/index.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.tsx
shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
shell/app/styles/_color.scss
shell/app/styles/antd-extension.scss

Replace Nusi Search and List.
❎ No
❎ No
Fixes #

refactor(common): replace Nusi Search and List

---

shell/app/config-page/components/table/render-types.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/components/topology-ele.tsx

fix: fix topology drag
❎ No
release/1.3
Fixes #

fix: fix topology drag error

---

shell/app/modules/msp/monitor/trace-insight/components/duration.tsx

fix duration is decimal, related with [https://github.com/erda-project/erda-ui/pull/1119](url)
❎ No
❎ No
Fixes #

fix: time duration is decimal

---

shell/app/modules/msp/env-setting/configuration/index.tsx
shell/app/modules/msp/env-setting/configuration/type-select.tsx
shell/app/modules/msp/services/configuration.ts
shell/app/modules/msp/types/configuration.d.ts

access the configuration document and render with markdown
❎ No
release/1.3
Fixes #

feat(msp): access the configuration document and render with markdown

---

shell/app/modules/msp/monitor/error-insight/pages/errors/error-detail.tsx

Error details Click next for error details and you cannot return to step one content
❎ No
release/1.3
Fixes #

fix(msp): Error details Click next for error details and you cannot return to step one content

---

shell/app/modules/apiManagePlatform/api-ws.ts
shell/app/modules/apiManagePlatform/pages/api-market/design/api-doc-tree.tsx

Fix bug of api design miss url params when click left menu.
❎ No
| 🇺🇸 English |  Fix bug of api design miss url params when click left menu.   |
| 🇨🇳 中文    |  修复了api设计在点击左侧菜单时会丢失url参数的bug。  |
release/1.3
Fixes #

fix: api design miss url params when click left menu

---

shell/app/common/components/members-table.tsx

After exiting the microservice observation item, jump to the item list
❎ No
release/1.3
Fixes #

feat(msp): After exiting the microservice observation item, jump to the item list

---

shell/app/common/components/time-select/common.ts

correct end time of last month in relative time
❎ No
release/1.3 release/1.2
Fixes #

fix: fix end of last month in relative time

---

shell/app/common/components/contractive-filter.tsx
shell/app/config-page/components/table/table.tsx
shell/app/config-page/index.tsx
shell/app/modules/project/pages/backlog/backlog.tsx

fix: fix contractive filter quick add placeholder / readjust backlog filter item 
❎ No
| 🇺🇸 English |    fix: fix contractive filter quick add placeholder / readjust backlog filter item        |
| 🇨🇳 中文    |    fix: 修复ContractiveFilter 自定义添加 placeholder / 调整待办列表中filter项         |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=228877&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG …

fix: fix contractive filter quick add placeholder / readjust backlog filter item 

---

shell/app/common/utils/go-to.tsx
shell/app/modules/msp/env-overview/service-list/index.ts
shell/app/modules/msp/env-overview/service-list/pages/index.tsx

Slow transaction tracking Top50 click view log in tracking details to report error
❎ No
release/1.3
Fixes #

fix(msp): Slow transaction tracking Top50 click view log in tracking details to report error

---

shell/app/common/stores/_member.ts
shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/msp/alarm-manage/alarm-strategy/pages/alarm-index/index.tsx
shell/app/modules/msp/alarm-manage/notify-group/index.tsx

replace params in msp role list

---

shell/app/common/components/time-select/common.ts
shell/app/common/utils/go-to.tsx
shell/app/modules/msp/env-overview/topology/pages/topology-dashboard/index.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/node-item.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx

fix: jump to trace search  with status and time range from topology
❎ No
release/1.3
Fixes #

fix: jump to trace search  with status and time range from topology

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx

Change the place of attributes tab and associated services tab
❎ No
release/1.3
Fixes #

feat: change the place of attributes tab and associated services tab

---

modules/uc/package.json

fix: fix uc history version
❎ No
❎ No
Fixes #

fix: fix uc history version

---

shell/app/modules/apiManagePlatform/pages/api-market/components/api-resource/resource-summary.tsx
shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx
shell/app/modules/apiManagePlatform/pages/api-market/design/property-field.tsx

Fix Form validate bugs and response example show bug in api design.
❎ No
| 🇺🇸 English | Fixe Form validation bugs on the API design page and the display bug of the response params example. |
| 🇨🇳 中文    |  修复了API设计页面的表单校验bug以及返回参数示例显示的bug。  |
release/1.3
Fixes #

fix: form validate bugs and response example show bug in api design

---

shell/app/modules/org/pages/projects/project-list.tsx

project management center, add project type to the list
❎ No
release/1.3
Fixes #

fix: project management center, add project type to the list

---

shell/app/common/components/authorize-member-modal.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
shell/app/modules/project/common/components/issue/issue-drawer.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/services/issue.ts
shell/app/modules/project/stores/issues.ts
shell/app/modules/project/types/issue.d.ts

When quick create issue, custom field default value should come from this type.
❎ No
release/1.3
Fixes #

fix(dop): issue custom field default value should match its type

---

shell/app/modules/msp/env-overview/topology/pages/topology-dashboard/index.tsx

Network topology, click node, and then click Service Analysis to display that the page does not exist
❎ No
release/1.3
Fixes #

fix(msp): Network topology, click node, and then click Service Analysis to display that the page does not exist

---

shell/app/locales/en.json
shell/app/locales/zh.json

Fix api design internationalization bug.
->
| 🇺🇸 English | Fixed api degisn page inernationalization bug.  |
| 🇨🇳 中文    |  修复了api设计页面的国际化bug。  |
release/1.3
Fixes #

fix: api design internationalization bug

---

scheduler/src/app.module.ts
scheduler/src/filters/not-found.filter.ts
scheduler/src/middlewares/guard.middleware.ts

remove force https logic & set static file cache control
❎ No
release/1.3

fix(scheduler): remove force https logic & set static file cache control

---

shell/app/modules/msp/env-setting/configuration/index.tsx

Content for markdown  Add style
❎ No
release/1.3
Fixes #

fix(msp): Content for markdown  Add style

---

shell/app/common/components/tiled-filter.tsx
shell/app/configForm/nusi-form/form-items/array-obj.scss
shell/app/configForm/nusi-form/form-items/array-obj.tsx
shell/app/configForm/nusi-form/form-items/input-array.tsx
shell/app/configForm/nusi-form/form-items/radio.tsx

fix: fix config form error
❎ No
release/1.3
Fixes #

fix: fix config form error

---

shell/app/modules/project/pages/test-plan/plan-modal.tsx
shell/app/modules/project/pages/test-plan/test-plan.tsx
shell/app/modules/project/stores/test-plan.ts

fix: fix test plan onPageChange error with filter
❎ No
| 🇺🇸 English |  fix: fix test plan onPageChange error with filter            |
| 🇨🇳 中文    |   fix: 修复有搜索条件时，测试计划翻页错误         |
❎ No
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=230134&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG

fix: fix test plan onPageChange error with filter

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

backend require to modify the query with condition to get more precise value in MQ page.
❎ No
release/1.3
Fixes #

feat: modify query with condition to get more precise value

---

pnpm-lock.yaml
shell/package.json

One y-axis as default config unless option was covered to set multiple Y axes
❎ No
release/1.3
Fixes #

fix: default one y axis

---

shell/app/modules/project/common/issue-config.ts

remove desciption.
❎ No
release/1.3
master
Fixes #

fix: remove description in issue template

---

shell/app/modules/project/common/issue-config.ts

Task do not need template.
❎ No
release/1.3
master
Fixes #

fix: remove task template

---

shell/app/modules/project/common/issue-config.ts

❎ No
release/1.3
master
Fixes #

fix: issue template

---

shell/webpack.config.js

fix: icon park shake
❎ No
Fixes #

fix: icon park shake

---

shell/app/config-page/debug.scss
shell/app/config-page/debug.tsx
shell/app/config-page/index.tsx
shell/app/configForm/nusi-form/form-items/array-obj.tsx
shell/app/modules/dop/router.js

feature: debug assert 
❎ No
❎ No
Fixes #

feature: config page debug assert 

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

modify query of MQ in transaction
❎ No
❎ No
release/1.3
Fixes #

fix: modify query of MQ in transaction

---

shell/app/modules/cmp/pages/cluster-manage/cluster-nodes-detail.tsx

fix: fix k8s node detail style
❎ No
release/1.3
Fixes #

fix: fix k8s node detail style

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/org/pages/setting/block-network.tsx
shell/app/modules/org/pages/setting/org-setting.tsx

blocked copy adjustment
❎ No
release/1.3
Fixes #

fix: blocked copy adjustment

---

shell/app/common/components/members-table.tsx
shell/app/common/stores/_member.ts
shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/application/services/notify-group.ts
shell/app/modules/application/stores/notify-group.ts
shell/app/modules/application/types/common-notify-group.d.ts
shell/app/modules/cmp/common/alarm-strategy/index.tsx
shell/app/modules/msp/alarm-manage/alarm-strategy/pages/alarm-index/index.tsx
shell/app/modules/msp/alarm-manage/notify-group/index.tsx

update msp member manage & notify group api path and params
❎ No
release/1.3
Fixes #

 update msp member manage & notify group api path and params

---

shell/app/common/components/contractive-filter.tsx
shell/app/modules/project/pages/milestone/milestone-table.scss

fix: fix milestone style / contractive filter value error
❎ No
| 🇺🇸 English |       fix: fix milestone style / contractive filter value error       |
| 🇨🇳 中文    |  fix: 修复里程碑样式问题 / contractive filter 值显示错误            |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=230999&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=231001&issueF …

fix: fix milestone style / contractive filter value error

---

pnpm-lock.yaml
shell/package.json

add showAllTooltip param to display complete tooltip in line chart
❎ No
release/1.3
Fixes #

fix: add showAllTooltip to display complete tooltip in line chart

---

shell/app/modules/cmp/pages/cluster-manage/cluster-pod-detail.tsx

fix: fix pod detail style
❎ No
release/1.3
Fixes #

fix: fix pod detail style

---

shell/app/modules/msp/query-analysis/custom-dashboard/index.ts

change translation
❎ No
release/1.3
Fixes #

fix(msp): change translation

---

shell/app/yml-chart/common/pipeline-node-drawer.tsx

fix: fix pipeline edit error
❎ No
release/1.3
Fixes #

fix: fix pipeline edit error

---

scheduler/src/filters/not-found.filter.ts

fix: fix path refresh error
❎ No
release/1.3
Fixes #

fix: fix path refresh error

---

scheduler/src/proxy.ts

fix: fix wb path
❎ No
release/1.3
Fixes #

fix: fix wb path

---

scheduler/src/proxy.ts

Compatible with old `/wb/` repo clone path.
❎ No
release/1.3
Fixes #

fix: redirect /wb/ prefix pathname to gittar

---

core/src/common/interface.d.ts
core/src/nusi/index.tsx
pnpm-lock.yaml
shell/app/layout/pages/page-container/components/menu-head.tsx
shell/app/layout/pages/page-container/components/side-navigation.tsx
shell/app/layout/pages/page-container/components/sub-sidebar.scss
shell/app/layout/pages/page-container/components/sub-sidebar.tsx

fix a bug in FDP third level menu
❎ No
❎ No
Fixes #

remove nusi sideNavigation

---

shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx

Clear old timer in case add many timer.
❎ No
release/1.3
Fixes #

fix: clear old timer in pipeline loop data

---

shell/app/modules/project/pages/test-plan/test-plan.tsx

fix test plan paging issue
❎ No
release/1.3
Fixes #
https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=231516&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDkxOCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG

fix(dop): fix test plan paging issue

---

scheduler/src/proxy.ts

compatible with JGit clone
❎ No
release/1.3
Fixes #

fix: compatible with JGit clone

---

cli/lib/build-online.ts
cli/lib/build.ts
cli/lib/check-build-status.ts
cli/lib/util/env.ts
cli/lib/util/git-commands.ts
cli/package.json
cspell.json
pnpm-lock.yaml

add branch prompt & kill all process when throw error

---

shell/app/modules/application/stores/build.ts
shell/app/modules/application/types/build.d.ts
shell/app/modules/cmp/pages/cluster-manage/cluster-workload-detail.tsx
shell/app/modules/project/services/auto-test-case.ts
shell/app/modules/project/services/test-plan.ts

feat: pageNum to pageNo
❎ No
| 🇺🇸 English |  feat: pageNum to pageNo
|
| 🇨🇳 中文    |     feat: 接口中pageNum 改成 pageNo
|
release/1.4
Fixes #

feat: pageNum to pageNo

---

shell/app/modules/org/common/audit-render.tsx
shell/app/modules/org/pages/projects/project-list.tsx

fix cpu and memory quota sort
❎ No
release/1.4
Fixes #

fix: project list sort by memory and cpu quota

---

shell/app/config-page/components/button/button.tsx

fix: fix confiig-page button confirm placement
❎ No
| 🇺🇸 English |   fix: fix config-page button confirm placement           |
| 🇨🇳 中文    |fix: 修复组件化按钮确认操作的位置             |
release/1.4
Fixes #

fix: fix confiig-page button confirm placement

---

shell/app/antd-overwrite/table/index.scss
shell/app/antd-overwrite/table/index.tsx

Change sorting style and layout of Table.
->
| 🇺🇸 English | Change sorting style of Table, and layout adjust according to content.  |
| 🇨🇳 中文    | 改变了表格排序时的样式，以及布局根据内容自适应 |
❎ No
Fixes #

refactor(common): change sorting style and layout of Table

---

shell/app/modules/org/common/audit-templates.json

fix: update org update template
❎ No
| 🇺🇸 English |      update org update template        |
| 🇨🇳 中文    |        更新组织编辑审计日志      |
/cherry-pick release/1.4
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=241234&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sInN0YXRlcyI6WzQ0MDIsNzEwNCw3MTA1LDQ0MDMsNDQwNCw3MTA2LDQ0MDYsNDQwNyw0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG)
Fixes #

fix: update org update template

---

core/package.json
package.json
scheduler/package.json
shell/app/menus/cmp.tsx
shell/app/menus/dop.tsx
shell/app/modules/msp/stores/micro-service.tsx
shell/package.json

* update version to 1.4
* remove some menu for community version
❎ No
release/1.4
Fixes #

chore: bump version v1.4

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx

Fix bug of trace insight request method error.
release/1.4
release/1.3-hotfix
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=235327&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG

fix(msp): trace insight request method error

---

cli/lib/local-icon.ts
cli/package.json

download iconpark files to static directory
❎ No
release/1.4
Fixes #

fix: download iconpark files to local static directory

---

shell/app/config-page/components/file-tree/file-tree.tsx
shell/app/modules/application/pages/pipeline/pipeline-detail.tsx
shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
shell/app/modules/application/pages/pipeline/run-detail/index.tsx
shell/app/modules/project/pages/apps/app-form.tsx

fix: fix mobil init pipeline error
| 🇺🇸 English |   fix: fix mobil init pipeline error           |
| 🇨🇳 中文    |   fix: 修复初始化mobile应用流水线错误           |
release/1.4
Fixes #

fix: fix mobil init pipeline error

---

cli/lib/local-icon.ts
cli/package.json

match one url one time.
❎ No
release/1.4
Fixes #

fix: should not match more than one iconpark url

---

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx

Adding token management to EDAs cluster
❎ No
release/1.4
Fixes #

fix(cmp): adding token management to EDAs cluster

---

shell/app/config-page/index.tsx

fix: fix config-page srcoll error
❎ No
| 🇺🇸 English |  fix: fix config-page srcoll error            |
| 🇨🇳 中文    |      fix: 修复组件化协议窗口滚动错误        |
release/1.4
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=242014&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG

fix: fix config-page srcoll error

---

shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts

get real create time in trace-querier
❎ No
release/1.4
Fixes #
[【链路调试】点击右侧的记录，进行新请求，新生成的记录时间没有变](https://erda.cloud/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D)

fix: get real createdTime in trace-querier

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx

resolve conflict about msp-bugfix
❎ No
release/1.4
Fixes #

resolve conflict about msp-bugfix

---

shell/webpack.config.js

process env FOR_COMMUNITY not work
❎ No
release/1.4
Fixes #

fix: process env not work

---

shell/app/modules/msp/monitor/browser-insight/pages/domain/domain.tsx
shell/app/modules/msp/monitor/browser-insight/pages/page/page.tsx
shell/app/modules/msp/monitor/browser-insight/pages/position/position.tsx
shell/app/modules/msp/monitor/monitor-common/components/sort-list/sub-tab.tsx

unified front-end monitoring style
❎ No
release/1.4
Fixes #

feat(msp): unified front-end monitoring style

---

shell/app/common/utils/go-to.tsx
shell/app/modules/addonPlatform/pages/mysql/account.tsx
shell/app/modules/addonPlatform/pages/mysql/consumer.tsx

inParams name is wrong
goTo link is wrong
❎ No
release/1.4
Fixes #

fix(dop): fix mysql account inParams and goto link

---

shell/app/config-page/components/copy/copy.mock.ts
shell/app/config-page/components/copy/copy.spec.d.ts
shell/app/config-page/components/copy/copy.tsx
shell/app/config-page/components/index.tsx
shell/app/config-page/debug.tsx

Add copy as standalone component in config-page
❎ No
release/1.4
Fixes #

feat: add copy component in config-page

---

shell/app/modules/msp/env-overview/service-list/pages/overview.tsx

service overview topology hidden
❎ No
release/1.4
Fixes #

feat(msp): service overview topology hidden

---

shell/app/common/utils/go-to.tsx
shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
shell/app/modules/msp/monitor/topology/index.js
shell/app/modules/msp/monitor/topology/pages/transfer/si.tsx

replace monitor alarm page
❎ No
❎ No
Fixes #

fix(msp): replace monitor alarm page

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

set default dashboard type base on url
❎ No
release/1.4
release/1.3-hotfix
Fixes #

fix(msp): set default dashboard type base on url

---

shell/app/menus/dop.tsx
shell/app/modules/project/pages/third-service/components/third-addon-form.tsx

fix: fix addon form change field error
❎ No
| 🇺🇸 English |  fix: fix addon form cleared after change field   |
| 🇨🇳 中文    |  fix: 修复addon表单切换模式后被清空           |
release/1.4
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=243232&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG

fix: fix addon form change field error

---

shell/auto_test/fixtures.ts
shell/auto_test/tests/dop/merge-requests.spec.ts
shell/auto_test/tests/org/organization-settings.spec.ts

Automated testing of organizational settings
❎ No
❎ No
Fixes #

Automated testing of organizational settings

---

shell/app/config-page/components/copy-button/copy-button.tsx

fix: fix copy button error
❎ No
| 🇺🇸 English |  fix: fix copy button error            |
| 🇨🇳 中文    |    fix: 修复copy button拷贝失败         |
release/1.4
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=243828&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCIsIjI0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG

fix: fix copy button error

---

shell/app/config-page/components/modal/modal.tsx

fix: fix config-page modal visible
❎ No
| 🇺🇸 English |    fix: fix config-page modal visible          |
| 🇨🇳 中文    |     fix: 修复组件化协议modal组件visible状态错误        |
release/1.4
Fixes #

fix: fix config-page modal visible

---

shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx

The request body under the active monitoring exception check is changed to the response body
❎ No
release/1.4
Fixes #

The request body under the active monitoring exception check is changed to the response body

---

shell/app/config-page/components/grid/grid.tsx

fix: fix grid overflow error
❎ No
| 🇺🇸 English |    fix: fix grid overflow error          |
| 🇨🇳 中文    |   fix: 修复grid组件滑动问题           |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=244068&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG

fix: fix grid overflow error

---

pnpm-lock.yaml
shell/package.json

upgrade dashboard to v2.0.0
❎ No
❎ No
Fixes #

feat: upgrade dashboard to v2.0.0

---

pnpm-lock.yaml
shell/app/modules/msp/env-overview/service-list/pages/anomaly.tsx
shell/app/modules/msp/env-overview/service-list/pages/process.tsx
shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
shell/package.json

1. MQ page collapse that _serviceId should be serviceId
2. serviceName should be taken from serviceAnalyticsStore
3. fix zero will transform to undefined in dashboard
❎ No
release/1.4
Fixes #

fix: MQ page collapse

---

shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx

Process the data when actively monitoring the headers update
❎ No
release/1.4
Fixes #

fix(msp): Process the data when actively monitoring the headers update

---

shell/app/modules/org/common/audit-templates.json

add audit for mysql account
❎ No
| 🇺🇸 English |   add audit for mysql account           |
| 🇨🇳 中文    |     增加 mysql account 操作审计         |
❎ No
Fixes #

add audit for mysql account

---

shell/app/common/components/k-v-pair/index.tsx
shell/app/modules/project/pages/test-env/test-env-detail.tsx
shell/app/modules/project/pages/test-report/download.tsx
shell/app/modules/project/pages/third-service/components/third-addon-form.tsx

fix: fix mysql addon support tenant / test env params length
❎ No
| 🇺🇸 English |    fix: fix mysql addon support tenant / remove test env params length limit          |
| 🇨🇳 中文    |     fix: 修复mysql addon 引用已有实例的表单 / 去除测试环境变量修改参数长度限制        |
release/1.4
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=246022&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG …

fix: fix mysql addon support tenant / test env params length

---

locales/zh.json
shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
shell/app/modules/dcos/types/dashboard.d.ts

fix: fix resource rank table style
❎ No
❎ No
Fixes #

fix: fix resource rank table style(pick from 1.4)

---

shell/app/common/components/file-editor/index.tsx
shell/app/common/components/sort-drag-group-list/index.tsx
shell/app/config-page/debug.tsx

feat: add sort drag list tag
| 🇺🇸 English |    feat: add sort drag list tag         |
| 🇨🇳 中文    |    feat:    拖拽list组件添加tag       |
release/1.4
Fixes #

feat: add sort drag list tag

---

shell/app/common/components/form-modal/index.tsx
shell/app/modules/project/pages/settings/components/project-info.tsx

Fixed bug of project edit the second time failed.
❎ No
release/1.4
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=245900&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=541&type=BUG

fix(dop): project edit failed bug

---

shell/app/locales/zh.json
shell/app/modules/application/common/components/create-add-on.tsx

fix: fix dice yml addon form plan field
❎ No
| 🇺🇸 English | fix: fix dice yml addon form plan field             |
| 🇨🇳 中文    |   fix:  修复dice yml addon表单配置错误         |
release/1./4
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=72819&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=-1&type=BUG

fix: fix dice yml addon form plan field

---

shell/app/common/components/boot-prompt/index.tsx

BootPrompt optimization.
❎ No
release/1.4
Fixes #

refactor(common): bootPrompt optimization

---

shell/app/locales/zh.json
shell/app/menus/project.tsx
shell/app/modules/cmp/router.ts
shell/app/modules/dcos/router.ts
shell/app/modules/org/router.ts
shell/app/modules/project/router.ts
shell/app/modules/project/stores/project.tsx

fix: fix dop menus
❎ No
release/1.4
Fixes #

fix: fix dop menus and pageName

---

locales/en.json
locales/zh.json
shell/app/modules/org/common/cluster-quota.tsx
shell/app/modules/org/pages/projects/create-project.tsx
shell/app/modules/project/pages/settings/components/project-info.tsx

In project quota edit, front-end control tip display.
❎ No
release/1.4
Fixes #

fix(common): in project quota edit, front-end control tip display

---

shell/app/modules/org/common/audit-templates.json

Add auto test space update audit template
❎ No
❎ No
Fixes #

Add auto test space update audit template

---

shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.scss
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx
shell/app/modules/org/stores/index.ts
shell/app/styles/_color.scss

fix: fix project list / resource summary styles
❎ No
release/1.4
Fixes #

fix: fix project list / resource summary styles

---

shell/app/modules/org/pages/projects/settings/info/index.tsx

fix: fix project info edit style
❎ No
release/1.4
Fixes #

fix: fix project info edit style

---

shell/app/common/components/intro/index.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/msp/env-overview/service-list/pages/no-services-holder.tsx

show the guide page based on the project type
❎ No
release/1.4
Fixes #

fix(msp): show the guide page based on the project type

---

shell/app/modules/project/stores/project.tsx

Fix bug of org center project detail go to dop and back.
❎ No
release/1.4
Fixes #

fix(common): org center project detail go to dop and back bug

---

shell/app/common/components/members-table/index.tsx
shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/modules/org/common/card/index.scss
shell/app/modules/org/pages/projects/project-list.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx

project detail style optimization
release/1.4
Fixes #

fix(common): project detail style optimization

---

shell/app/menus/project.tsx
shell/app/modules/org/pages/projects/project-list.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx

pick fix from #1924 
❎ No
❎ No
Fixes #

fix: pick fix from master

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/trace-header.tsx

fix displaying tooltip of trace waterfalls flow
release/1.4
Fixes #

Fix: display tooltip of trace waterfalls flow

---

shell/app/common/components/table/index.tsx

Table td desc optimizaiton.
❎ No
Fixes #

fix(common): table td desc optimization

---

shell/app/modules/project/pages/auto-test/index.tsx

feat: add auto test case import in new protocol
❎ No
Fixes #

feat(1.4.1): add auto test case import in new protocol

---

pnpm-lock.yaml
shell/package.json

upgrade dashboard to v2.0..0
* replace nusi with antd, remove nusi totally. nusi style is not applied at all, so repalce Title with div directly.
* replace superagent with native fetch, move to dev dependency for tools still use it.
* update & remove useless packages
* run audit fix
* update readme
* check required fields before submit
❎ No
❎ No
Fixes #

chore: upgrade dashboard to v2.0..0

---

shell/app/modules/application/common/components/create-add-on.tsx

fix: fix dice yaml addon form plan field
❎ No
❎ No
Fixes #

fix: fix dice yaml addon form plan field

---

shell/app/common/components/filter/base-filter.tsx

Filter style unified
->
release/1.4
Fixes #

fix(common): filter style unified

---

shell/app/modules/org/pages/setting/notice-channel.tsx
shell/app/modules/org/pages/setting/org-setting.scss
shell/app/modules/org/pages/setting/org-setting.tsx

fix i18n about notice channel and update style
❎ No
❎ No
Fixes #

Fix: fix i18n about notice channel

---

shell/app/common/components/members-table/index.tsx
shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/layout/pages/page-container/components/side-navigation.tsx
shell/app/layout/pages/page-container/components/sub-sidebar.scss
shell/app/locales/zh.json
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
shell/app/modules/org/common/card/index.scss
shell/app/modules/org/common/card/index.tsx
shell/app/modules/org/pages/projects/project-list.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx

Org center style optimization.
release/1.4
Fixes #

fix(common): org center style optimization

---

shell/app/modules/msp/monitor/status-insight/pages/status/status-detail.tsx
shell/app/modules/msp/monitor/status-insight/types/index.d.ts

The URL of monitoring details also needs to be retrieved from config
❎ No
release/1.4
Fixes #

fix(msp): The URL of monitoring details also needs to be retrieved from config

---

shell/app/modules/project/stores/test-case.ts

fix: fix test case table select all
❎ No
| 🇺🇸 English |    fix: fix test case table select all          |
| 🇨🇳 中文    |      fix: 修复测试用例全选问题        |
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=234806&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix: fix test case table select all

---

shell/app/common/components/members-table/index.tsx
shell/app/common/components/table/index.tsx
shell/app/common/components/table/interface.ts
shell/app/common/components/table/table-config.tsx
shell/app/common/components/table/table-footer.tsx
shell/app/config-page/components/table/render-types.tsx
shell/app/config-page/components/table/table.tsx
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx
shell/app/modules/org/pages/projects/project-list.tsx
shell/app/modules/org/pages/setting/notice-channel.tsx

Table component code optimization
❎ No
❎ No
Fixes #

refactor(common): table component code optimization

---

shell/app/layout/pages/page-container/page-container.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/org/pages/approval/index.tsx

feat(org): add apply for column in approval table
| 🇺🇸 English | add apply for column in approval table  |
| 🇨🇳 中文    |  审批表格中添加申请原因列  |
release/1.3
release/1.4
Fixes #

feat(org): add apply for column in approval table

---

shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx
shell/app/modules/apiManagePlatform/pages/api-market/design/datatype-config.tsx
shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx

Api design edit bug.
❎ No
| 🇺🇸 English | Fixed a bug where editing data would be empty after switching data types. |
| 🇨🇳 中文    | 修复了切换数据类型后编辑数据会为空的缺陷。 |
release/1.4
Fixes #

fix(dop): api design edit bug

---

shell/app/modules/org/common/audit-templates.json

Update auto test space templates
❎ No
1.4.1
Fixes #

Update auto test space templates

---

pnpm-lock.yaml
shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
shell/package.json

1.  display chart in overview of service
2. display chart in chart editor
❎ No
release/1.4
Fixes #
[【服务分析】使用ES存储trace/error和log数据后，服务概览中有图表显示有问题](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D)
[【运维大盘】使用ES存储trace/error和log数据后，旧的大盘数显示不出来](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQ …

fix: upgrade dashboard to v2.0.1

---

shell/app/config-page/components/dropdown-select/dropdown-select.tsx
shell/app/org-home/pages/personal-home.tsx

Fix bug of announcement were not updated when organizations switched.
❎ No
release/1.4
Fixes #

fix(common): announcement were not updated when organizations switched

---

shell/app/config-page/index.tsx

fix: fix config page overflow style
❎ No
| 🇺🇸 English |     fix: fix config page overflow style         |
| 🇨🇳 中文    |   fix: 修复组件化协议滚动溢出问题        |
release/1.4.1
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249629&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix: fix config page overflow style

---

shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/cmp/common/alarm-strategy/index.tsx
shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
shell/app/modules/cmp/services/cluster.ts
shell/app/modules/cmp/stores/cluster.ts

remove VMS channel and SMS & VMS switch
❎ No
| 🇺🇸 English |  Remove VMS  from the notification channel，remove the SMS voice switch in the organization management |
| 🇨🇳 中文    |  将电话语音从通知渠道中去除，将管理后台的短信语音开关去除  |
release/1.4.1
Fixes #

fix: remove VMS channel and SMS & VMS switch

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/cmp/common/alarm-strategy/index.tsx
shell/app/modules/cmp/common/alarm-strategy/notify-strategy-select.tsx
shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx
shell/app/modules/cmp/services/cluster.ts
shell/app/modules/cmp/stores/cluster.ts

Pick 1.4.1 to 1.5-alpha1
❎ No
❎ No
Fixes #

Fix: Pick 1.4.1 to 1.5-alpha1

---

shell/app/charts/components/monitor-chart-new.jsx

fix: front-end monitor page collapse
❎ No
release/1.4  release/1.5-alpha1
Fixes #

fix: front-end monitor page collapse

---

shell/app/modules/msp/components/intro-page.tsx

add intro page for gateway
❎ No
Fixes #

add intro page for gateway

---

shell/app/common/components/table/index.tsx

Fix bug of table pagination bug in config page.
- Page turn request interface when front-end paging.
- There is no request interface when changing the sort.
❎ No
❎ No
Fixes #

fix(common): table pagination bug in config page

---

shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/common/components/table/interface.ts
shell/app/common/components/table/table-footer.tsx

table Component optimization.
❎ No
❎ No
Fixes #

refactor(common): table Component optimization

---

shell/app/config-page/components/edit-list/edit-list.tsx

fix: fix edit list useEffect error
❎ No
❎ No
Fixes #

fix: fix edit list useEffect error

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/cmp/pages/cluster-container/cluster-selector.tsx
shell/app/modules/cmp/pages/cluster-container/index.tsx
shell/app/modules/cmp/services/cluster.ts
shell/app/modules/cmp/stores/cluster.ts

❎ No
| 🇺🇸 English |    feat: update k8s cluster api          |
| 🇨🇳 中文    |   feat: 修改k8s接口           |
❎ No
Fixes #

feat（1.4.2）: update k8s cluster api

---

shell/app/modules/cmp/pages/cluster-container/cluster-nodes.tsx

fix: delete cluster node mock
❎ No
❎ No
Fixes #

fix: delete cluster node mock

---

shell/app/modules/application/pages/repo/components/branch-select.scss
shell/app/modules/application/pages/repo/components/branch-select.tsx

Code repository branch select style adjust.
->
Fixes #

fix(dop): repo branch select style adjust

---

shell/app/common/use-hooks.tsx
shell/app/layout/pages/page-container/page-container.tsx

keep react warning to fix some hidden incorrect logic.
Have checked all three files which use reset function.
❎ No
❎ No
Fixes #

Hotfix/remove updater reset logic in useUpdate unmount

---

shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx

display table x-scroll if content too much
❎ No
Fixes #
[【线上问题】【告警】告警策略，新增告警策略页面显示有问题](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D)

fix: display table x-scroll if content too much

---

pnpm-lock.yaml
shell/app/menus/appCenter.tsx
shell/app/menus/index.ts
shell/package.json

feat(msp): repalce msp name

---

shell/app/views/index.ejs
shell/index.html

fix response parse failure when status is not 200
❎ No
❎ No
Fixes #

fix response parse failure when status is not 200

---

shell/app/layout/pages/page-container/components/header.tsx
shell/app/layout/pages/page-container/page-container.tsx
shell/app/menus/cmp.tsx

* add key to breadcrumb item
* fix cmp menu style
->
❎ No
Fixes #

Fix: cmp menu item align style

---

shell/app/locales/zh.json

Fix perm table header text bug.
->
Fixes #

fix(common): perm table header text bug

---

shell/app/common/components/members-table/index.tsx
shell/app/common/components/table/index.tsx

Fix bug of members table pageSize change failure.
❎ No
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=250877&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): members table pageSize change bug

---

shell/app/config-page/debug.tsx
shell/app/layout/pages/page-container/page-container.tsx

support parse config-page debug page url
❎ No
❎ No
Fixes #

Feat:  support parse config-page debug page url

---

shell/app/config-page/debug.tsx
shell/app/layout/pages/page-container/page-container.tsx

use route query as default protocol config
❎ No
❎ No
Fixes #

Fix: use route query as default protocol config

---

shell/app/modules/msp/config.tsx
shell/app/modules/msp/stores/micro-service.tsx
shell/app/modules/msp/types/index.d.ts

delete useless menu key
❎ No
Fixes #

feat(msp): delete useless menu key

---

shell/app/modules/application/pages/pipeline/pipeline-detail.tsx

Fix pipeline switch branch bug when quickly switch to the execution details page after switching branches.
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=246603&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): pipeline switch branch bug

---

cli/bin/erda.ts
cli/package.json

add icon-localize command for integration build

(cli)  add icon-localize command

---

shell/app/common/components/pagination/index.scss
shell/app/common/components/pagination/index.tsx
shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/common/components/table/interface.ts
shell/app/common/components/table/table-footer.tsx

Separate table and pagination components
❎ No
❎ No
Fixes #

refactor(common): separate table and pagination components

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/menus/project.tsx

FIx side navigation text bug.
->
Fixes #

fix(dop): side navigation text bug

---

locales/en.json
locales/zh.json
shell/app/common/components/table/index.tsx
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx

Fix table bug:
- Fix table sort bug when paging at the front end
- Fix text bug of table empty status
- Fix table header align bug
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=252476&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): table sort and empty bug

---

shell/app/styles/antd-extension.scss

fix: fix tooltip max width
❎ No
❎ No
Fixes #

fix: fix tooltip max width

---

shell/app/config-page/config-page.d.ts
shell/app/config-page/index.tsx
shell/app/layout/pages/page-container/page-container.tsx

move to config page options
❎ No
❎ No
Fixes #

fix: update config page syncIntervalSeconds

---

shell/app/common/components/text-block-info/index.tsx
shell/app/config-page/components/grid/grid.tsx
shell/app/config-page/components/pie-chart/pie-chart.tsx
shell/app/config-page/index.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-pods.tsx

fix: fix k8s style
❎ No
❎ No
Fixes #

fix: fix k8s style

---

shell/app/modules/apiManagePlatform/pages/api-market/detail/components/api-preview-3.0.tsx

Fix bug of api market table desc and default does not display.
->
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=251601&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(dop): api market table desc and default does not display

---

shell/app/common/components/pagination/index.tsx
shell/app/config-page/components/table/render-types.tsx
shell/app/config-page/components/table/table.tsx

Fix table bug:
- page jump bug
- columns render bug in align of composite components
❎ No
❎ No
Fixes #

fix(common): table bug of page jump and align

---

shell/app/config-page/config-page.d.ts
shell/app/config-page/index.tsx
shell/app/layout/pages/page-container/page-container.tsx

support async component in config-page
❎ No
❎ No

Feature/support async component in config-page

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/span-time-info.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/span-title-info.tsx

modify tooltip style of flame graph
❎ No
❎ No
Fixes #

style: modify tooltip of flame graph

---

shell/app/config-page/components/pie-chart/pie-chart.tsx

Fix bug of pie chart does not display
❎ No
❎ No
Fixes #

fix(common): pie chart label

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx

fix that format flame data when root is only one
❎ No
❎ No
Fixes #

fix: format flame data when root is only one

---

shell/app/config-page/index.tsx
shell/app/layout/pages/page-container/page-container.tsx

fix: restore config-page op index check
❎ No
❎ No
Fixes #

fix: restore config-page op index check

---

shell/app/common/components/list/index.scss
shell/app/config-page/components/index.tsx
shell/app/config-page/components/list-new/list-new.scss
shell/app/config-page/components/list-new/list-new.spec.d.ts
shell/app/config-page/components/list-new/list-new.tsx
shell/app/config-page/components/list/list.scss
shell/app/config-page/components/list/list.tsx
shell/app/config-page/config-page.d.ts
shell/app/styles/_color.scss

Leave list style unchanged except for clusters list.
❎ No
❎ No
Fixes #

refactor(common): leave list style unchanged except for clusters list

---

shell/webpack.config.js

fix compile failed in development mode
❎ No
❎ No
Fixes #

fix compile failed in development mode

---

shell/app/modules/msp/env-overview/topology/pages/topology/topology.tsx

fix duplicated request
❎ No
❎ No
Fixes #

fix duplicated request

---

shell/app/config-page/components/pie-chart/pie-chart.tsx

wrap pie chart group
❎ No
Fixes #

fix(common): wrap pie chart group

---

shell/app/common/components/edit-field/index.tsx

Enable preview image as previous behavior
❎ No
❎ No
Fixes #

enable preview image

---

shell/app/config-page/components/list-new/list-new.tsx
shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx

Fix cluster list click bug.
❎ No
❎ No
Fixes #

fix: cluster list click bug

---

.github/PULL_REQUEST_TEMPLATE.md
shell/app/layout/pages/page-container/page-container.tsx

To avoid some common issues happened, add check points in pr template.
❎ No
❎ No
Fixes #

Chore: add check points in pr template

---

shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx

Fix cluster list token management bug.
❎ No
❎ No
Fixes # https://erda.cloud/erda/dop/projects/387/issues/bug?id=256437&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=680&type=BUG

fix(cmp): cluster list token management bug

---

shell/app/common/components/boot-prompt/index.scss
shell/app/common/components/boot-prompt/index.tsx
shell/app/common/components/filter/base-filter.tsx
shell/app/common/components/list/index.scss
shell/app/common/components/list/list-item.tsx
shell/app/common/components/table/index.tsx
shell/app/styles/_color.scss

list and table style optimization:
- filter input add clear icon
- list operations style optimization
- boot prompt style optimization
❎ No
Fixes #

fix(common): list and table style optimization

---

shell/app/modules/project/router.ts

Fix apps list style bug.
->
❎ No
Fixes #

fix(dop): apps list style bug

---

shell/app/modules/msp/pages/micro-service/overview.scss
shell/app/modules/msp/pages/micro-service/overview.tsx
shell/app/styles/_color.scss
shell/app/styles/_mixin.scss
shell/app/styles/util.scss

fix msp home page style
❎ No
❎ No
Fixes #

feat: fix msp home page style

---

core/package.json
package.json
scheduler/package.json
shell/app/common/components/tags-row/index.tsx
shell/package.json

fix: fix version / tags-row add error
❎ No
Fixes #

fix: fix version / tags-row add error

---

shell/app/layout/pages/page-container/components/sub-sidebar.scss

modify the menu style
**before:**
**current:**
Fixes #

style: modify menu style

---

pnpm-lock.yaml
shell/app/common/components/board-grid/index.tsx
shell/app/common/services/dashboard.ts
shell/app/interface/global.d.ts
shell/app/modules/cmp/pages/cluster-container/cluster-nodes-detail.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.tsx
shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx
shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
shell/app/modules/msp/env-overview/topology/pages/topology-dashboard/index.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
shell/package.json

upgrade dashboard to v2.0.4, there are:
1. register custom components
2. format code
3. fix declaration file
4. remove 'import DC'
❎ No
❎ No
Fixes #

feat: upgrade dashboard to v2.0.4

---

shell/app/modules/msp/pages/micro-service/overview.tsx
shell/app/modules/msp/router.ts

msp overview scroll full page
❎ No
Fixes #

feat(msp): msp overview scroll full page

---

shell/app/common/components/tags-row/index.tsx

Fix bug of tags row incomplete display in table.
->
Fixes #

fix(common): tags row incomplete display in table

---

shell/app/styles/antd-extension.scss

fix(common): radio style change

---

shell/app/config-page/components/list-new/list-new.tsx
shell/app/config-page/components/pie-chart/pie-chart.tsx
shell/app/config-page/components/table/render-types.tsx
shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx

Cluster list style optimization:
- Pie chart add label
- In table, progress displays the value returned by the back end
Fixes #

fix(cmp): cluster list style optimization

---

shell/app/modules/msp/pages/micro-service/overview.tsx
shell/app/styles/app.scss
shell/tailwind.config.js

add number font family [#2122]
❎ No
❎ No
Fixes #

feat: add number font family

---

shell/app/config-page/config-page.d.ts
shell/app/config-page/page-render.tsx

fix: fix cp visible in options
❎ No
| 🇺🇸 English |    fix: fix cp visible in options       |
| 🇨🇳 中文    | fix: 组件化协议中支持组件options.visible 配置      |
❎ No
Fixes #

fix: fix cp visible in options

---

shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx

Fix bug:
- resource summary table digital accuracy modification
- table line height change
- table bug o infinite loop when dataSource is undefined
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=257839&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(cmp): resource summary table style change

---

shell/app/modules/project/pages/settings/components/project-cluster.tsx

FIx project clusters list style bug.
->
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249887&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0IiwiMjQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(dop): project clusters list style bug

---

shell/app/common/use-hooks.tsx

fix that changing pageSize in useFilter is no effect
❎ No
❎ No
Fixes #

fix: changing pageSize in useFilter is no effect

---

shell/app/user/stores/_perm-org.ts

OrgCenter permission granted to support.
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=231292&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0IiwiMjQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): orgCenter permission granted to support

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.scss
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx

modify flame graph style, to avoid displaying unnecessary scroll bar
❎ No
Fixes #

fix: modify flame graph style

---

shell/app/modules/msp/env-overview/service-list/pages/index.scss
shell/app/modules/msp/env-overview/service-list/pages/overview.tsx

fix that wrapper style about dashboard in service overview
❎ No
❎ No
Fixes #

fix: wrapper style about dashboard in service overview

---

shell/app/common/components/contractive-filter/index.tsx
shell/app/common/components/custom-filter/index.tsx
shell/app/common/components/edit-list/index.tsx
shell/app/common/components/filter/index.tsx
shell/app/common/components/members-table/index.tsx
shell/app/common/components/search-table/index.tsx
shell/app/common/components/tiled-filter/index.tsx
shell/app/modules/msp/monitor/monitor-common/components/appsSelector.tsx
shell/app/modules/msp/pages/micro-service/overview.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-tree-selector.tsx
shell/app/modules/project/pages/plan-detail/index.tsx
shell/app/modules/project/pages/test-manage/case/header/plan-modal/index.tsx
shell/app/modules/project/pages/test-manage/case/manual-test.tsx

Input search filter debounce delay change.
❎ No
Fixes #

fix(common): input search filter debounce delay change

---

shell/app/common/components/board-grid/index.tsx
shell/app/modules/cmp/common/custom-dashboard/index.tsx
shell/app/modules/cmp/types/dashboard-model.d.ts
shell/app/modules/msp/env-setting/configuration/index.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
shell/app/modules/msp/stores/log-analyze.ts
shell/app/modules/msp/types/gateway.d.ts
shell/app/modules/msp/types/monitor.d.ts

upgrade table in msp [erda-ui-enterprise PR#187](https://github.com/erda-project/erda-ui-enterprise/pull/187)
❎ No
❎ No
Fixes #

upgrade table in msp

---

shell/app/modules/project/pages/settings/components/project-cluster.tsx

Project quota list display scroll.
->
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=249887&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjQsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(dop): project quota list display scroll

---

shell/app/config-page/components/gantt/gantt.scss
shell/app/config-page/components/gantt/gantt.spec.d.ts
shell/app/config-page/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/utils.ts
shell/app/config-page/mock/crud.mock.ts
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/issue/plan/index.scss
shell/app/modules/project/pages/issue/plan/index.tsx

Dop gantt left tree expand and create issue button
❎ No
Fixes #

feat(dop): dop gantt left tree expand and create issue button

---

shell/app/modules/msp/pages/micro-service/overview.scss

adjust animation speed and amplitude
❎ No
❎ No
Fixes #

adjust animation speed and amplitude

---

shell/app/modules/msp/pages/micro-service/overview.scss
shell/app/modules/msp/pages/micro-service/overview.tsx

adjust msp project list style
❎ No
❎ No
Fixes #

adjust msp project list style

---

shell/app/common/components/member-selector/index.tsx
shell/app/layout/pages/page-container/page-container.tsx

use getAvatarChars in member selector
❎ No
❎ No
Fixes #

Feat/use getAvatarChars in member selector

---

shell/app/modules/project/pages/issue/plan/index.tsx

fix: dop gantt tree user
❎ No
❎ No
Fixes #

fix: dop gantt tree user

---

shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx

Cancel include tasks drag in issue detail.
❎ No
❎ No
Fixes #

fix(dop): cancel include tasks drag in issue detail

---

shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
shell/app/config-page/components/gantt/components/grid/grid-body.tsx
shell/app/config-page/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/helpers/date-helper.ts
shell/app/config-page/components/gantt/utils.ts
shell/app/config-page/mock/index.tsx
shell/app/modules/project/pages/issue/plan/index.tsx

gantt node open detail
❎ No
❎ No
Fixes #

feature: gantt node open detail

---

shell/app/config-page/components/gantt/components/calendar/calendar.tsx
shell/app/config-page/components/gantt/components/grid/grid-body.tsx
shell/app/config-page/components/gantt/helpers/date-helper.ts

fix: fix gantt date error
❎ No
| 🇺🇸 English |   fix: fix gantt date error， page crush          |
| 🇨🇳 中文    |     fix: 修复甘特图日期计算错误导致页面崩溃     |
❎ No
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=260709&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix: fix gantt date error

---

shell/app/config-page/components/gantt/helpers/date-helper.ts
shell/app/modules/project/tabs.tsx

fix: fix gantt date count error
❎ No
| 🇺🇸 English |   fix: fix gantt date count error           |
| 🇨🇳 中文    |  fix: 修复甘特图日期计算错误          |
❎ No
Fixes #

fix: fix gantt date count error

---

shell/app/config-page/components/gantt/helpers/date-helper.ts

fix: fix date helper
❎ No
❎ No
Fixes #

fix: fix date helper

---

pnpm-lock.yaml
shell/app/modules/project/pages/backlog/backlog.tsx
shell/package.json

[fixed minor version #54](https://github.com/Erda-FE/dashboard-configuration/pull/54)
1. fix cascader unavailable
2. fix  no exported member 'ISSUE_ICON_MAP'
❎ No
❎ No
Fixes #

fix cascader unavailable

---

shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx

fix: k8s pod detail prev log error
❎ No
| 🇺🇸 English |    fix: k8s pod detail prev log error          |
| 🇨🇳 中文    |  fix: 修复k8d pod详情prev日志点击查看错误            |
❎ No
Fixes #

fix: k8s pod detail prev log error

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

fix can't comment on new line issue in MR compare page
❎ No
❎ No
Fixes #

fix(dop): fix can't comment on new line issue

---

shell/app/modules/project/pages/issue/plan/index.tsx

fix: fix avatar
❎ No
❎ No
Fixes #

fix: fix avatar

---

shell/app/config-page/components/list-new/list-new.tsx
shell/app/config-page/components/table/render-types.tsx
shell/app/modules/dcos/pages/cluster-dashboard/resources-summary.tsx

Fix style bug:
- progress display bug in table
- clusters list style bug
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=257839&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): progress display bug in table and clusters list style bug

---

shell/app/layout/pages/page-container/components/sub-sidebar.tsx
shell/app/menus/project.tsx

Center menuicon when folding
❎ No
❎ No
Fixes #

Center menuicon when folding

---

shell/app/common/components/edit-field/index.tsx

Issue detail enlarged image is not fully displayed
❎ No
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=259465&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=772&type=BUG

fix(dop): issue detail enlarged image is not fully displayed

---

shell/app/common/components/menu/index.tsx
shell/app/config-page/components/gantt/components/calendar/calendar.tsx
shell/app/config-page/components/gantt/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/components/grid/grid-body.tsx
shell/app/config-page/components/gantt/components/task-item/bar/bar.scss
shell/app/config-page/components/gantt/components/task-item/bar/bar.tsx
shell/app/config-page/components/gantt/components/task-item/task-item.tsx
shell/app/config-page/components/gantt/gantt.tsx
shell/app/config-page/mock/crud.mock.ts
shell/app/layout/pages/page-container/components/header.scss
shell/app/modules/project/pages/issue/plan/index.tsx
shell/app/modules/project/tabs.tsx

fix: gantt calendar error / add time range error
❎ No
| 🇺🇸 English |     fix: gantt calendar error / add time range error         |
| 🇨🇳 中文    |  fix: 修复甘特图日期显示错误、添加时间错误            |
❎ No
Fixes #

fix: gantt calendar error / add time range error

---

shell/app/config-page/components/gantt/gantt.tsx
shell/app/modules/project/pages/issue/plan/index.tsx

fix: fix gantt tree node style
❎ No
cherry-pick hotfix/1.5-1208
Fixes #

fix: fix gantt tree node style

---

locales/en.json
locales/zh.json
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/org/pages/setting/notice-channel.tsx

1. hidden channel type column
2. modify port from 0 ~ 65535 to 1 ~ 65535
3. use Badge(common) to display status 
4. place 'email' tab to first(default) tab
5. update Chinese translation on 'email' from '邮箱' to '邮件'
❎ No
❎ No
Fixes #

fix: modify table in notice channel

---

shell/app/modules/project/common/components/issue/issue-relation.tsx

Issue detail inclusion optimization:
- The issues list does not show included issues;
- Refreshed issues list after Including tasks or disconnecting; 
❎ No
❎ No
Fixes #

fix(dop): issue detail inclusion optimization

---

shell/app/org-home/pages/personal-home.tsx
shell/app/org-home/stores/org.tsx

Notice change bug when orgs were changed.
❎ No
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=262465&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): notice change bug when orgs were changed

---

shell/app/common/components/list/index.scss
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/types/issue.d.ts

issue detail inclusion add state.
| 🇺🇸 English | In issue detail inclusion tasks list, add state. |
| 🇨🇳 中文    | 事项详情的包含任务列表中，增加状态的显示。  |
❎ No
Fixes #

fix(dop): issue detail inclusion add state

---

shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/addon-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/external-service-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts

feat(msp): transform call time

---

locales/zh.json
shell/app/modules/project/tabs.tsx

feat: update tab text
No
Fixes #

feat: update project measure tab text

---

.github/workflows/git-sync.yml
pipeline.yml

add git-sync & pipeline.yml for CI
❎ No
❎ No
Fixes #

add git-sync & pipeline.yml for CI

---

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
shell/app/modules/project/common/components/issue/issue-icon.tsx

FIx bug o interface error when tickets turn to issue.
❎ No
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263119&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(dop): ticket turn to issue bug

---

shell/app/config-page/components/table/render-types.tsx

Fix issue table bug:
- two arrows
- state can not select
❎ No
Fixes #

fix(dop): issue table bug

---

shell/app/modules/org/stores/announcement.ts
shell/app/org-home/stores/org.tsx

prevent circular import
❎ No
❎ No
Fixes #

fix: move some logic to prevent circular import

---

shell/app/common/components/icon/index.tsx

Fix issue table complexity icon display bug.
->
❎ No
Fixes #

fix(dop): issue table complexity icon display bug

---

shell/app/config-page/components/table/render-types.tsx

Issue table state selector options bug
->
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263572&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(dop): issue table state selector options bug

---

shell/app/common/components/pagination/index.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.tsx

1. Increase the style when the mouse moves the page up arrow
2. Replace the icon when the language is unknown
3. The average delay is rounded to two decimal places
❎ No
| 🇺🇸 English |     1.  Increase the style when the mouse moves the page up arrow 2.  Replace the icon when the language is unknown    3. The average delay is rounded to two decimal places   |
| 🇨🇳 中文    |     1.增加鼠标移动上翻页箭头时候的样式  2.   替换语言为未知时候的图标   3. 平均延迟四舍五入保留两位小数    |
❎ No
Fixes #

feat:  service-list bugfix

---

shell/app/App-vite.tsx
shell/app/App.tsx

Import external and core modules first, prevent circular import error.
❎ No
❎ No
Fixes #

fix: adjust import order

---

shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/index.scss
shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx

feat(msp): disable scroll scaling
❎ No
❎ No
Fixes #

feat(msp): disable scroll scaling

---

shell/app/config-page/components/text-block-group/text-block-group.tsx
shell/app/layout/pages/page-container/page-container.scss

fix: top button group position when notice exist

---

shell/app/layout/pages/page-container/components/header.scss

overwrite global tab-item style
❎ No
Fixes #

fix: header tab menu style

---

pipeline.yml
shell/app/common/components/contractive-filter/index.tsx
shell/app/config-page/components/container/container.tsx
shell/app/config-page/components/issue-kanban.scss

speed up build.
fix style
❎ No
❎ No
Fixes #

chore: add more cache directories in pipeline

---

shell/app/config-page/components/gantt/components/calendar/calendar.tsx
shell/app/config-page/components/gantt/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/components/gantt/task-gantt-content.tsx
shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
shell/app/config-page/components/gantt/components/grid/grid-body.tsx
shell/app/config-page/components/gantt/components/grid/grid.scss
shell/app/config-page/components/gantt/components/task-item/task-item.tsx
shell/app/config-page/components/gantt/helpers/date-helper.ts
shell/app/modules/project/pages/issue/plan/index.tsx

fix: fix gantt hover left arrow, and some other styles
| 🇺🇸 English |   fix: fix gantt hover left arrow, and some other styles |
| 🇨🇳 中文    |   fix: 修复甘特图hover箭头不响应，以及部分样式问题 |
Fixes #

Hotfix: gantt hover arrow

---

shell/app/modules/msp/env-overview/service-list/pages/service-list-dashboard.tsx

fix that remove application id from service overview
❎ No
release/1.5-alpha.4
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=263866&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=680&type=TASK

fix: remove application id from service overview

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

❎ No
release/1.5-alpha.4
Fixes #

fix duplicate requsest

---

shell/app/charts/theme.js
shell/app/modules/msp/env-overview/service-list/pages/index.tsx

 fix service chart style

---

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
shell/app/modules/project/common/components/issue/issue-config.tsx

Issue detail complexity add icon.
| 🇺🇸 English |  In issue detail, complexity option add icon.  |
| 🇨🇳 中文    |  事项详情中，复杂度选项增加图标。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263575&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(dop): issue detail complexity add icon

---

shell/app/common/components/table/index.tsx
shell/app/config-page/index.tsx

Fix issue table reload button bug
❎ No
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=263766&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(dop): issue table reload button bug

---

locales/zh.json

modify the tip of creating app name
❎ No
❎ No
Fixes #

feat: modify tip of creating app name

---

scheduler/src/filters/not-found.filter.ts

fix: wrap environment variables with quotes

---

shell/app/config-page/components/table-group/table-group.tsx

fix that repeated splicing list in table group
❎ No
release/1.5-alpha.4
Fixes #

fix: duplicate concat list in table group

---

shell/app/modules/msp/stores/log-analyze.ts

fix analyzeRule scope id
❎ No
❎ No
Fixes #

 fix analyzeRule scope id

---

shell/app/common/components/radio-tabs/index.scss
shell/app/common/components/radio-tabs/index.tsx
shell/app/common/index.ts
shell/app/common/utils/query-string.tsx
shell/app/config-page/components/index.tsx
shell/app/config-page/components/radio-tabs/radio-tabs.mock.ts
shell/app/config-page/components/radio-tabs/radio-tabs.spec.d.ts
shell/app/config-page/components/radio-tabs/radio-tabs.tsx
shell/app/config-page/config-page.d.ts
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/issue/all.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx
shell/app/modules/project/tabs.tsx

feat: add issue tabs in all issues
| 🇺🇸 English |   feat: add issue tabs in all issues           |
| 🇨🇳 中文    |  feat: 全部事项中添加事项tabs           |
Fixes #

feat: add issue tabs in all issues

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/common/config.ts
shell/app/modules/project/pages/apps/app-form.tsx
shell/app/modules/project/pages/apps/app-type-select.scss
shell/app/modules/project/pages/apps/app-type-select.tsx

can not create a mobile app when there is no cluster in the project
❎ No
❎ No
Fixes #
[项目环境没有配置集群的情况下，新建移动应用使用模板、初始化失败的提示信息优化](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=252836&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIiwiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=772&type=BUG)

fix: can not create mobile app when there is no cluster in the project

---

shell/app/charts/components/echarts.jsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx

adjust legend style
before：
after：
❎ No
Fixes #

adjust legend style

---

shell/app/config-page/components/table/render-types.tsx

Fix table dropdown menu item bug.
❎ No
❎ No
Fixes #

fix(common): table dropdown menu item bug

---

shell/app/charts/components/echarts.jsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts

fix category criteria
❎ No
❎ No
Fixes #

 fix category criteria

---

shell/app/modules/project/pages/issue/all.tsx
shell/app/modules/project/tabs.tsx

fix: revert issue tabs
❎ No
❎ No
Fixes #

fix: revert issue tabs

---

shell/app/views/index.ejs

hotfix/remove-extra-character
❎ No
❎ No
Fixes #

fix: remove-extra-character

---

shell/app/common/components/render-form-item/index.tsx

Fix select options display bug.
->
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=266027&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): select options display bug

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/config-page/components/configurable-filter/configurable-filter.spec.d.ts
shell/app/config-page/components/configurable-filter/configurable-filter.tsx
shell/app/config-page/components/kanban/kanban.tsx
shell/app/config-page/page-render.tsx

Fix configurable filter bug.
❎ No
❎ No
Fixes #

fix(common): configurable filter bug

---

shell/app/common/components/configurable-filter/index.scss
shell/app/common/components/configurable-filter/index.tsx
shell/app/views/index.ejs
shell/index.html

Configurable filter optimization.
->
❎ No
Fixes #

fix(common): configurable filter optimization

---

shell/app/common/components/configurable-filter/index.scss
shell/app/common/components/configurable-filter/index.tsx

Fix configurable filter placeholder bug.
❎ No
Fixes #

fix(common): configurable filter placeholder bug

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/common/components/render-form-item/index.tsx

Fix select options display bug in form.
->
❎ No
Fixes #

fix(common): select options display bug in form

---

shell/app/common/components/render-form-item/index.tsx
shell/app/layout/pages/page-container/page-container.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx

fix: fix issue dnd provider error
❎ No
| 🇺🇸 English |   fix: fix issue dnd provider error           |
| 🇨🇳 中文    |  fix: 修复事项看板 dndProvider报错         |
❎ No
Fixes #

fix: fix issue dnd provider error

---

shell/app/modules/msp/env-overview/service-list/pages/index.tsx

clear search input when switch service type
❎ No
❎ No
Fixes #

clear search input when switch service type

---

shell/app/common/components/configurable-filter/config-selector.tsx
shell/app/config-page/components/configurable-filter/configurable-filter.tsx

fix: fix configurable filter save error
❎ No
❎ No
Fixes #

fix: fix configurable filter save error

---

shell/app/modules/msp/env-overview/service-list/pages/overview-new.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.scss
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx

fix service overview style
❎ No
❎ No
Fixes #

fix service overview style

---

shell/app/common/components/configurable-filter/index.tsx

Fix configurable filter display bug after filter:
Whether or not to update display bug after filter.
❎ No
❎ No
Fixes #

fix(common): configurable filter display bug after filter

---

shell/app/common/components/table/index.scss

Fix table header style bug in multi-line.
->
❎ No
Fixes #

fix(common): table header style bug in multi-line

---

shell/app/modules/project/pages/issue/board.tsx

fix: fix kanban style

---

shell/app/common/components/configurable-filter/index.scss

Fix configurable filter clear text position bug
->
❎ No
Fixes #

fix(common): configurable filter clear text position bug

---

shell/app/common/components/configurable-filter/index.scss

Fix configurable filter cursor style bug.
->
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=266461&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): configurable filter cursor style bug

---

shell/app/common/components/render-form-item/index.tsx

Date range optimization:
The end time is set to the last second of the day.
❎ No
❎ No
Fixes #

fix(common): date range optimization

---

shell/app/common/components/render-form-item/index.tsx

Fix configurable filter tags select dropdown bug.
->
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=266463&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=680&type=BUG

fix(common): configurable filter tags select dropdown bug

---

shell/app/common/components/table/index.tsx

Fix table select row bug.
❎ No
❎ No
Fixes #

fix(common): table select row bug

---

shell/app/common/components/render-form-item/index.tsx

Date range select start time optimization.
❎ No
❎ No
Fixes #

fix(common): date range select start time optimization

---

shell/app/modules/apiManagePlatform/pages/api-market/detail/index.tsx

Fix page error after jump from api-market detail.
❎ No
❎ No
Fixes #

fix(common): page error after jump from api-market detail

---

shell/app/config-page/components/kanban/kanban.tsx
shell/app/config-page/index.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
shell/app/modules/project/pages/issue/board.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx

fix: issue download error
❎ No
| 🇺🇸 English |    fix: issue download error          |
| 🇨🇳 中文    |  fix: 修复事项导出错误            |
❎ No
Fixes #

fix: issue download error

---

shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx

topology is scaled to 0.6 by default
❎ No
❎ No
Fixes #

topology is scaled to 0.6 by default

---

shell/app/config-page/components/index.tsx
shell/app/config-page/components/scale-card/scale-card.mock.ts
shell/app/config-page/components/scale-card/scale-card.scss
shell/app/config-page/components/scale-card/scale-card.spec.d.ts
shell/app/config-page/components/scale-card/scale-card.tsx
shell/app/views/index.ejs
shell/index.html

Add scale card component
❎ No
Fixes #

feat: add scale card component

---

shell/app/common/components/filter/base-filter.tsx
shell/app/common/components/table-actions/index.tsx
shell/app/common/components/table/index.scss
shell/app/common/components/table/index.tsx
shell/app/modules/apiManagePlatform/pages/access-manage/list/index.tsx
shell/app/modules/apiManagePlatform/pages/api-market/list/index.tsx
shell/app/modules/apiManagePlatform/pages/client/list/index.tsx
shell/app/modules/apiManagePlatform/router.ts
shell/app/modules/apiManagePlatform/stores/api-market.ts
shell/app/modules/application/pages/deploy-list/deploy-list.tsx
shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
shell/app/modules/dop/router.ts
shell/app/modules/project/common/components/branch-rule.tsx
shell/app/modules/project/common/components/scan-rule.tsx
shell/app/modules/project/pages/iteration/table.tsx
shell/app/modules/project/pages/resource/components/service-list.jsx
shell/app/modules/project/pages/settings/components/project-cluster.tsx
shell/app/modules/project/pages/test-env/test-env.tsx
shell/app/modules/project/pages/test-manage/case/columns/more-operation/index.tsx
shell/app/modules/project/pages/test-manage/case/manual-test.tsx
shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
shell/app/modules/project/pages/test-plan/test-plan.tsx
shell/app/modules/project/pages/ticket/index.tsx
shell/app/modules/project/router.ts
shell/app/modules/publisher/pages/publisher-manage/publisher-list-v2.tsx

Replace dop table.
❎ No
| 🇺🇸 English | Replace tables in dop with new table. |
| 🇨🇳 中文    |  将DevOps平台的表格都替换成新的表格。  |
❎ No
Fixes #

refactor(dop): replace dop table

---

.erda/pipelines/ci-build-ce.yml

update ci pipeline
❎ No
❎ No
Fixes #

update ci pipeline

---

shell/app/common/components/table/table-config.tsx
shell/app/modules/project/pages/test-manage/case/columns/index.tsx

Table columns filter optimization.
->
hotfix/12-21
Fixes #

fix(common): table columns filter optimization

---

scheduler/src/filters/not-found.filter.ts
shell/app/common/constants.ts
shell/app/common/utils/go-to.tsx
shell/app/layout/pages/page-container/components/sidebar.tsx

admin user call api under org domain will cause some 401.
❎ No
No
Fixes #

feat: jump to admin use wildcard domain

---

shell/app/common/components/configurable-filter/index.scss
shell/app/common/components/members-table/index.tsx
shell/app/common/components/render-form-item/index.tsx
shell/app/common/utils/go-to.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.tsx
shell/app/modules/msp/env-overview/service-list/router.ts
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx

fix: merge hotfixs to 1.5

---

shell/app/common/components/table/index.tsx
shell/app/modules/apiManagePlatform/pages/access-manage/list/index.tsx
shell/app/modules/apiManagePlatform/stores/api-access.ts
shell/app/modules/application/pages/deploy-list/deploy-list.tsx

Fix table pagination bug in dop:
- my approve table call the interface twice when pageSize change.
- table operations columns width fixed.
- access manage table reload button bug.
❎ No
hotfix/12-21
Fixes #

fix(dop): table pagination bug in dop

---

pipeline.yml

add ce build script
❎ No
❎ No
Fixes #

add ce build script

---

shell/app/modules/msp/components/analyzer-chart.tsx
shell/app/modules/msp/config.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.scss
shell/app/modules/msp/env-overview/service-list/pages/index.tsx
shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
shell/app/styles/util.scss

each chart is requested independently
❎ No
❎ No
Fixes #

feat(msp): each chart is requested independently

---

shell/app/modules/application/pages/deploy-list/deploy-list.tsx
shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
shell/app/modules/project/common/components/branch-rule.tsx
shell/app/modules/project/common/components/scan-rule.tsx
shell/app/modules/project/pages/settings/components/project-cluster.tsx
shell/app/modules/project/pages/test-env/test-env.tsx

Fix table reload button bug in dop.
❎ No
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=268646&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): table reload button bug in dop

---

.gitignore
shell/app/config-page/index.tsx
shell/app/modules/extra/entry.js

** revert config page async request**
❎ No
❎ No
Fixes #

 revert config page async request

---

shell/app/modules/msp/env-overview/service-list/pages/index.tsx

validate tenantId
❎ No
❎ No
Fixes #

validate tenantId

---

shell/app/common/use-hooks.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.scss
shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/floating-edge/index.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/addon-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/api-gateway-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.scss
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/progress/hexagon.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/progress/index.scss
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts
shell/app/modules/msp/env-overview/topology/types/topology.d.ts
shell/app/styles/util.scss
shell/app/views/index.ejs
shell/index.html

* feat(msp): custom scroll bar
* feat(msp): add breathing lighting for error node
* feat(msp): heightlight node and edge when click node
* feat(msp): service topology add full screen controller
* feat(msp): add useFullScreen hooks
* feat(msp): hack for safari
❎ No
❎ No
Fixes #

topology optimization (#2348)

---

locales/en.json
locales/zh.json
shell/app/common/use-hooks.tsx
shell/app/config-page/components/gantt/components/calendar/calendar.tsx
shell/app/config-page/components/gantt/components/gantt/gantt.scss
shell/app/config-page/components/gantt/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
shell/app/config-page/components/gantt/gantt.spec.d.ts
shell/app/config-page/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/types/public-types.ts
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/issue/gantt/index.scss
shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/views/index.ejs
shell/index.html

[feat: position today in gantt #2373](https://github.com/erda-project/erda-ui/pull/2373) 
[fix: prevent scroll today after clicking expander #2394](https://github.com/erda-project/erda-ui/pull/2394)
✅ No
❎ No
Fixes #

feat: position today in gantt (pick to release/1.5 by manual)

---

shell/app/config-page/components/gantt/components/gantt/gantt.scss
shell/app/config-page/components/gantt/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/components/gantt/task-gantt.tsx
shell/app/config-page/components/gantt/types/public-types.ts
shell/app/modules/project/pages/issue/gantt/index.scss
shell/app/views/index.ejs
shell/index.html

update gantt operate button style
release/1.5
Fixes #

feat: update gantt operate button style

---

shell/app/common/components/card-list/index.tsx
shell/app/config-page/components/gantt/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/helpers/date-helper.ts
shell/app/styles/_color.scss
shell/app/styles/util.scss
shell/tailwind.config.js

fix: position to today not work in gantt
❎ No
release/1.5
Fixes #

fix: position to today not work in gantt at init

---

shell/app/common/components/card-list/index.tsx
shell/app/config-page/components/gantt/components/gantt/gantt.tsx
shell/app/config-page/components/gantt/helpers/date-helper.ts
shell/app/styles/_color.scss
shell/app/styles/util.scss
shell/tailwind.config.js

pick pr to 1.5
❎ No
❎ No
Fixes #

pick: position to today not work in gantt at init

---

shell/app/layout/pages/page-container/components/sidebar.tsx

add protocol prefix
❎ No
❎ No
Fixes #

fix: add protocol to admin entry href link

---

shell/app/config-page/components/kanban/kanban.tsx

fix: fix kanban operation data
❎ No
| 🇺🇸 English |     fix: fix kanban operation data         |
| 🇨🇳 中文    |   fix: 修复看板组件化操作数据          |
❎ No
Fixes #

fix: fix kanban operation data

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx

rename dubboMethod to rpcMethod [Dubbo Method replace to Rpc Method](https://github.com/erda-project/erda/pull/3490)
❎ No
❎ No
Fixes #

rename dubboMethod to rpcMethod

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/utils/index.ts
shell/app/modules/msp/env-overview/topology/types/topology.d.ts

add external interface statistics & prevent node overlap
❎ No
❎ No
Fixes #

add external interface statistics & prevent node overlap

---

shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx

Fix page jitter when api design edit.
❎ No
release/1.5
Fixes #

fix(dop): page jitter when api design edit

---

shell/app/config-page/components/gantt/helpers/date-helper.ts

fix: fix gantt bar postion error
❎ No
| 🇺🇸 English |   fix: fix gantt bar postion error           |
| 🇨🇳 中文    |    fix: 修复甘特图任务位置错误          |
Fixes #

fix: fix gantt bar postion error

---

shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx

fix: fix issue plan time clear
❎ No
| 🇺🇸 English |   fix: fix issue plan time clear           |
| 🇨🇳 中文    |     fix: 修复事项计划时间清空错误         |
release/1.5
Fixes #

fix: fix issue plan time clear

---

shell/app/config-page/components/gantt/helpers/date-helper.ts

fix: fix gantt bar position error
❎ No
❎ No
Fixes #

fix: fix gantt bar position error

---

shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx

fix(msp): afresh layout when switch page
❎ No
❎ No
Fixes #

rearrange after switching page

---

shell/app/modules/msp/env-overview/service-list/pages/index.tsx

fix refresh invalid
❎ No
release/1.5
Fixes #

fix refresh invalid

---

shell/app/modules/msp/pages/micro-service/overview.tsx
shell/app/modules/msp/services/index.ts
shell/app/modules/msp/types/index.d.ts

async request msp project list statistics 
❎ No
❎ No
Fixes #

async request msp project list statistics

---

locales/en.json
locales/zh.json
shell/app/modules/runtime/common/logs/components/log-filter.tsx

rename log advanced search
❎ No
❎ No
Fixes #

rename log advanced search

---

cli/bin/erda.ts
cli/lib/build-online.ts
cli/lib/check-build-status.ts
cli/lib/fetch-image-content.ts
cli/lib/init-online.ts
cli/lib/util/env.ts
cli/lib/util/git-commands.ts

To speed up build image, not fetch enterprise code in pipeline, but will cause cli build failed.
❎ No
❎ No
Fixes #

feat: cli support build ce version

---

cli/package.json

chore: update cli to 1.4.5

---

pipeline.yml

pipeline yml add `--ce` option for ce version

feat(common): pipeline update

---

shell/app/modules/project/pages/issue/gantt/index.tsx

fix: fix gantt bar text color
❎ No
❎ No
Fixes #

fix: fix gantt bar text color

---

shell/app/common/components/dropdown-select-new/index.scss
shell/app/org-home/pages/personal-home.tsx

fix: fix workbench style
❎ No
❎ No
Fixes #

fix: fix workbench style

---

shell/app/modules/msp/stores/micro-service.tsx

fix menu issue in open source env
❎ No
release/1.5
Fixes #

fix(msp): fix menu issue in open source env

---

shell/app/common/components/dropdown-select-new/index.scss
shell/app/common/components/dropdown-select-new/index.tsx
shell/app/common/components/load-more-selector/index.scss
shell/app/common/components/load-more-selector/index.tsx
shell/app/layout/pages/page-container/components/navigation/index.tsx
shell/app/layout/pages/page-container/components/sidebar/menu-head.scss
shell/app/layout/pages/page-container/components/sidebar/menu-head.tsx
shell/app/modules/application/common/app-selector.scss
shell/app/modules/application/common/app-selector.tsx
shell/app/modules/project/common/components/project-selector.scss
shell/app/modules/project/common/components/project-selector.tsx
shell/app/org-home/pages/org-selector.tsx
shell/app/org-home/pages/personal-home.tsx

fix: fix new theme load-more-selector style
❎ No
Fixes #

fix: fix new theme load-more-selector style

---

shell/app/config-page/components/scale-card/scale-card.tsx
shell/app/org-home/pages/personal-home.tsx

fix: fix workbench org selector
❎ No
| 🇺🇸 English |      fix: fix workbench org selector        |
| 🇨🇳 中文    | fix: 修复工作台企业选择错误             |
❎ No
Fixes #

fix: fix workbench org selector

---

shell/app/common/constants.ts

update the URL to the official doc
✅ No
release/1.5
Fixes #

fix: update the URL to official doc

---

shell/app/common/components/base-list/list-item.tsx
shell/app/common/components/user-profile/index.tsx
shell/app/config-page/components/base-list/base-list.tsx
shell/app/config-page/components/card/card.tsx
shell/app/config-page/mock/crud.mock.ts
shell/app/config-page/page-render.tsx
shell/app/config-page/utils.tsx
shell/app/org-home/pages/personal-home.tsx

fix: fix operations disabled in new components
❎ No
| 🇺🇸 English |     fix: fix operations disabled in new components         |
| 🇨🇳 中文    |   fix: 修复组件化协议中新组件disabled操作          |
❎ No
Fixes #

fix: fix operations disabled in new components

---

shell/app/modules/project/pages/release/components/application-detail.tsx
shell/app/modules/project/pages/release/components/form.tsx
shell/app/modules/project/pages/release/components/update.tsx
shell/app/modules/project/router.tsx
shell/app/modules/project/types/release.d.ts

project release management bug
❎ No
❎ No
Fixes #

fix(dop): project release management bug

---

.github/semantic.yml

add semantic.yml for pr title linting
❎ No
❎ No
Fixes #

chore: add semantic.yml for pr title linting

---

shell/app/modules/project/pages/homepage/index.scss
shell/app/modules/project/pages/homepage/index.tsx
shell/app/modules/project/pages/homepage/readme-markdown.tsx

update style in project home: 
1. modify the background color to white
2. modify tooltip to the left of the link
❎ No
Fixes #

style: update style in project home

---

shell/app/config-page/components/table/render-types.tsx

Fix table operate disabledTip failure bug
❎ No
❎ No
Fixes #

fix(common): table operate disabledTip failure bug

---

shell/app/common/components/base-list/list-item.tsx
shell/app/config-page/components/card/card.tsx
shell/app/org-home/pages/personal-contribute/index.tsx

fix: fix personal workbench radar chart style
❎ No
Fixes #

fix: fix personal workbench radar chart style

---

shell/app/modules/project/pages/homepage/index.tsx

fix: page home fetch cause crash
❎ No
❎ No
Fixes #

fix: page home fetch cause crash

---

shell/webpack.config.js

fix: support load webp file

---

shell/app/layout/pages/page-container/page-container.tsx
shell/app/modules/project/pages/homepage/index.tsx
shell/app/modules/project/pages/homepage/readme-markdown.tsx

fix: hide scroll tip when hide header

---

shell/app/common/components/table/index.scss
shell/app/layout/pages/page-container/components/sidebar/menu-head.scss
shell/app/modules/project/pages/ticket/index.tsx

fix: sidebar menu image radius

---

shell/app/common/components/table/index.scss
shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/modules/project/router.tsx
shell/app/org-home/pages/personal-home.tsx

fix: personal workbench entries link

---

shell/app/common/components/form-modal/index.scss
shell/app/modules/project/pages/homepage/index.tsx

optimize modal style  in project home page
❎ No
❎ No
Fixes #

style: optimize modal style  in project home

---

shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-overview.tsx

adjust the range of nodes that trigger the event
❎ No
❎ No
Fixes #

fix: adjust the range of nodes that trigger the event

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/org-home/pages/personal-home.tsx

fix: fix greeting word
❎ No
❎ No
Fixes #

fix: fix greeting word

---

.github/prlint.json

check chinese & english changelog
❎ No
| 🇺🇸 English |       check chinese & english changelog before pr merged as required       |
| 🇨🇳 中文    |     增加 prlint.json 强制要求 pr 必须提供 changelog     |
❎ No
Fixes #

chore: check chinese & english changelog

---

shell/app/modules/org/common/audit-templates.json

add release-manage audit template
❎ No
| 🇺🇸 English | add release-manage audit template |
| 🇨🇳 中文    | 添加制品管理审计模板 |
❎ No

feat: add release-manage audit template

---

shell/app/config-page/components/table/table.scss
shell/app/config-page/components/table/table.tsx
shell/app/styles/_color.scss

Config page table batch operations button style adjustment.
❎ No
Fixes #

fix(common): config page table batch operations button style adjustment

---

shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/pages/milestone/milestone-table.scss

Issue management font weight adjustment
->
| 🇺🇸 English | backlog and milestone list font is not bold.  |
| 🇨🇳 中文    |   待处理和里程碑列表字体取消加粗。 |
❎ No
Fixes #

fix(dop): issue management font weight adjustment

---

shell/app/common/components/markdown-editor/editor.scss
shell/app/layout/pages/page-container/components/sidebar/index.tsx
shell/app/layout/pages/page-container/components/sidebar/sidebar-menu.tsx
shell/app/locales/zh.json
shell/app/menus/project.tsx
shell/app/modules/project/pages/homepage/index.scss
shell/app/modules/project/pages/homepage/index.tsx

1. open the window to go to the link that starts with 'www'
2. expand project management menu when entering project home page by default
3. optimize markdown background-color
4. update <a> color  from default color to highlight color
❎ No
| 🇺🇸 English | expand project management menu when entering project home page by default |
| 🇨🇳 中文    | 进入项目首页时默认展开项目管理菜单 |
❎ No
Fixes #

fix(dop): open window to go to link that starts with 'www'

---

shell/app/common/components/table/index.scss
shell/app/config-page/utils.tsx

fix: function is undefined

---

shell/app/common/components/table/index.scss
shell/app/layout/pages/page-container/components/navigation/index.tsx

fix: add min height to global logo wrap

---

shell/app/modules/project/router.tsx

Fix project release breadcrumb bug
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=271594&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project release breadcrumb bug

---

shell/app/modules/apiManagePlatform/api-ws.ts

Fix websocket bug in http protocol
❎ No
❎ No
Fixes #

fix(common): websocket bug in http protocol

---

shell/app/common/components/filter/index.tsx
shell/app/configForm/form/form.tsx
shell/app/configForm/form/utils.ts
shell/app/modules/dcos/pages/cluster-dashboard/resources-usage-trend.tsx
shell/app/modules/org/pages/certificate/index.tsx
shell/app/modules/org/pages/safety/index.tsx
shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/styles/antd-extension.scss

feat: add lang param to export api
fix(dop): not load ticket list when open share link
fix(dop): open target issue when url have issue id
fix: trim certificate fields
fix: revert input border for some condition
❎ No
| 🇺🇸 English |  open target issue when url have issue id |
| 🇨🇳 中文    | 修复甘特图页面没有打开分享链接的问题 |
Fixes #

fix: open target issue in gantt page

---

shell/app/config-page/components/line-graph/index.tsx
shell/app/modules/msp/components/time-select.tsx
shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

line chart supports data drill-down
❎ No
❎ No
Fixes #

feat: line chart supports data drill-down

---

.eslintrc.js
package.json
pnpm-lock.yaml
shell/app/common/components/custom-filter/index.tsx

prevent use deprecated function.
❎ No
❎ No
Fixes #

feat: add eslint error for deprecated function

---

shell/app/App-vite.tsx
shell/app/App.tsx

modify modal to center position vertically
❎ No
| 🇺🇸 English | Center Modal vertically |
| 🇨🇳 中文    | 使弹窗垂直居中 |
Fixes #

style(common): modify modal to center position

---

shell/app/modules/msp/env-overview/service-list/pages/overview.tsx
shell/app/modules/project/pages/issue/task-summary.tsx

feat: adjust card style

---

shell/app/modules/application/pages/repo/components/compare-detail.tsx
shell/app/modules/application/pages/repo/components/file-diff.tsx

1. hidden markdown when clicking discard button
2. remove the function that comment can be stored temporarily
| 🇺🇸 English | remove the function that comment can be stored temporarily in MR request|
| 🇨🇳 中文    | 在合并请求中去除暂存评论功能 |
Fixes #
[合并请求 回复 评论点击无效](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=272179&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)
[代码合并请求评审框不能关闭](https://dice.app.terminus.io/erda/dop/projects/387/issues/all?id=272078&issu …

fix: hidden markdown when click cancel button

---

shell/app/modules/project/pages/apps/app-list.tsx
shell/app/modules/project/router.tsx

Applications list optimization
| 🇺🇸 English | Applications list style optimization |
| 🇨🇳 中文    | 应用列表样式优化。 |
❎ No
Fixes #

feat(dop): applications list optimization

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

❎ No
| 🇺🇸 English | fix bug when switch tabs without using the latest time |
| 🇨🇳 中文    | 修复切换tabs时，未使用最新时间参数的问题 |
Fixes #

fix: fix bug when switch tabs without using the latest time

---

pipeline.yml

refactor: remove the version in pipeline.yaml
❎ No
| 🇺🇸 English |       remove the version in pipeline.yaml      |
| 🇨🇳 中文    |      去掉 pipeline.yml 中指定制品版本        |
✅ Yes(release/1.5 release/1.6-alpha.1)

refactor: remove the version in pipeline.yaml

---

shell/app/config-page/components/card/card.scss

fix animation speed
❎ No
| 🇺🇸 English |   card border animation speed  |
| 🇨🇳 中文    | 调整卡片动画速度  |
Fixes #

fix: card border animation speed

---

shell/app/config-page/utils.tsx

Fix list tooltip display bug
| 🇺🇸 English |   fix(common): list tooltip display bug            |
| 🇨🇳 中文    |   修复: 列表tooltip未显示问题        |
Fixes #

fix(common): list tooltip display bug

---

shell/app/common/components/base-list/index.scss
shell/app/config-page/components/card/card.scss
shell/app/modules/project/pages/apps/app-list.scss
shell/app/modules/project/pages/apps/app-list.tsx

fix style
| 🇺🇸 English |  fix app list style under project level |
| 🇨🇳 中文    |  修复应用列表样式  |
Fixes #

fix: app list style under project level

---

shell/app/modules/msp/env-overview/service-list/pages/overview.tsx

adjust margin
❎ No
| 🇺🇸 English | adjust service detail page margin |
| 🇨🇳 中文    | 调整服务详情页边距  |
Fixes #

feat: adjust margin

---

shell/app/modules/project/common/components/issue/issue-relation.tsx

Fix bug of issue backlog list page error after row click.
❎ No
| 🇺🇸 English |  Fixed a bug where items clicked together with the pending list.  |
| 🇨🇳 中文    |  解决了事项协同待处理列表行点击报错的bug。           |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=272695&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): issue backlog list page error after row click

---

cli/lib/check-build-status.ts
cli/package.json

fix mistake skip build when cache is empty in integration env pipeline issue
❎ No
| 🇺🇸 English |   -           |
| 🇨🇳 中文    |     -         |
❎ No
Fixes #

fix: mistake skip build when cache is empty in integration env pipeline issue

---

shell/app/modules/org/common/audit-templates.json

Project release detail herf bug in safety log.
❎ No
| 🇺🇸 English |   Fixed item level artifact link errors in audit logs. |
| 🇨🇳 中文    |  修复了审计日志中项目级制品链接错误。  |
❎ No
Fixes #

fix(common): project release detail herf bug in safety log

---

shell/app/modules/project/pages/release/components/project-detail.tsx

Fix project release detail formal btn display bug.
| 🇺🇸 English |  Fixed a switch to official button in official products. |
| 🇨🇳 中文    |  修复了正式制品也存在转正式按钮的bug。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=274181&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project release detail formal btn display bug

---

shell/app/org-home/pages/land/index.tsx

can not click org because blur trigger before click
❎ No
❎ No
Fixes #

fix: land page org can not click

---

shell/app/layout/common/error-page.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/org-home/pages/land/index.tsx

update land page text
remove duplicate and useless NotJoinOrg component.
❎ No
❎ No
Fixes #

fix: update land page text

---

core/src/service/index.ts

when xxx.useData be using at multiple components at same time, only one component will get re-render
❎ No
| 🇺🇸 English |    -          |
| 🇨🇳 中文    |   -           |
❎ No

fix(common): fix useState/useData doesnt render all components issue

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/release/components/form.tsx

project release upload file text change.
->
| 🇺🇸 English | Product management - Add product text changes by uploading files.  |
| 🇨🇳 中文    |   制品管理-通过上传文件新增制品的文字改变。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=274460&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project release upload file text change

---

shell/app/common/utils/go-to.tsx
shell/app/layout/router.tsx
shell/app/org-home/stores/org.tsx

remove useless freshman route
❎ No
| 🇺🇸 English |        -     |
❎ No
Fixes #

feat: remove freshman page

---

core/src/service/index.ts

replace with native implementation
❎ No
❎ No
Fixes #

fix: react-use is not a core dependencies

---

shell/app/org-home/pages/land/index.tsx

fix text too long
❎ No
❎ No
Fixes #

fix: truncate if text too long

---

scheduler/src/filters/not-found.filter.ts

not send env to client
❎ No
| 🇨🇳 中文    |       -      |
❎ No
Fixes #

fix: not send env to client

---

shell/app/config-page/components/bubble-graph/index.tsx
shell/app/config-page/components/grid/grid.spec.d.ts
shell/app/config-page/components/grid/grid.tsx
shell/app/config-page/components/line-graph/index.tsx
shell/app/modules/msp/env-overview/service-list/pages/process.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx

fix: fix self-test problems

---

shell/app/modules/cmp/common/alarm-strategy/index.tsx
shell/app/modules/cmp/common/custom-alarm/index.tsx
shell/app/modules/cmp/common/custom-dashboard/index.tsx
shell/app/modules/msp/env-setting/configuration/index.tsx

add creator column [erda-project/erda-ui-enterprise#203 ](https://github.com/erda-project/erda-ui-enterprise/pull/203)
❎ No
❎ No
Fixes #

feat: add creator column

---

shell/app/config-page/components/bubble-graph/index.tsx

hidden node when value is 0
❎ No
❎ No
Fixes #

feat: hidden node when value is 0

---

shell/app/modules/org/common/audit-templates.json

update release audit template
❎ No
| 🇺🇸 English | update release audit template |
| 🇨🇳 中文    | 修改制品管理审计模板 |
❎ No

fix: update release audit template

---

shell/app/config-page/components/base-list/base-list.tsx

fix: fix base list reload
❎ No
| 🇺🇸 English |    fix: fix base list reload       |
| 🇨🇳 中文    |    fix: 修复base-list组件reload逻辑      |
❎ No
Fixes #

fix: fix base list reload

---

shell/app/modules/msp/env-overview/service-list/pages/process.tsx
shell/app/modules/msp/types/topology-service-analyze.d.ts

add empty holder
❎ No
| 🇨🇳 中文    |- |
❎ No
Fixes #

feat: add empty holder

---

shell/app/layout/pages/page-container/components/navigation/user-menu.scss
shell/app/layout/pages/page-container/components/navigation/user-menu.tsx
shell/app/org-home/pages/land/index.tsx

update user menu style
❎ No
| 🇺🇸 English |         -    |
| 🇨🇳 中文    |          -   |
❎ No
Fixes #

fix: user menu style

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/menus/project.tsx

Dop menu text change.
| 🇺🇸 English | DevOps left menu text change. |
| 🇨🇳 中文    |  DevOps平台左侧菜单文案修改。  |
❎ No
Fixes #

fix(dop): menu text change

---

shell/app/config-page/components/bubble-graph/index.tsx

adjust bubble size
❎ No
❎ No
Fixes #

feat: adjust bubble size

---

shell/app/config-page/components/card/card.scss
shell/app/config-page/components/card/card.spec.d.ts
shell/app/config-page/components/card/card.tsx
shell/app/layout/pages/page-container/components/navigation/user-menu.tsx
shell/app/modules/project/pages/issue/board.tsx
shell/app/org-home/pages/personal-home.tsx

* fix logout
* remove card default border animation
* remove kanban filter bottom border
❎ No
| 🇺🇸 English |  fix user logout is unavailable  |
| 🇨🇳 中文    | 修复用户登出无效的问题  |
❎ No
Fixes #

fix: user logout is unavailable

---

shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
shell/app/modules/application/stores/build.ts

Fix pipeline execute detail display bug.
❎ No
| 🇺🇸 English | Fixed a bug where pipeline execution details kept showing no data.  |
| 🇨🇳 中文    |  修复了流水线执行明细一直显示无数据的bug。  |
❎ No
Fixes #

fix(dop): pipeline execute detail display bug

---

shell/app/modules/msp/env-overview/service-list/pages/index.tsx
shell/app/modules/msp/env-overview/service-list/pages/overview.tsx

optimize the refresh button style
❎ No
Fixes #

feat: optimize the refresh button style

---

shell/app/common/components/contractive-filter/index.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx

add trace duration tips
❎ No
❎ No
Fixes #

feat: add trace duration tips

---

shell/app/modules/project/common/components/issue/subscribers-selector.tsx

Fix issue attention btn dropdown style bug.
->
| 🇺🇸 English | Fixed style issues with project Co-focus button dropdown boxes. |
| 🇨🇳 中文    |  修复了项目协同关注按钮下拉框的样式问题。  |
❎ No
Fixes #

fix(dop): issue attention btn dropdown style bug

---

shell/app/common/components/pagination/index.scss
shell/app/config-page/components/table/render-types.tsx
shell/app/config-page/components/table/v2/utils.tsx
shell/app/modules/application/pages/pipeline/config-detail/index.tsx
shell/app/modules/project/pages/apps/app-list.tsx
shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/pages/pipelines/components/logs.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.scss
shell/app/modules/project/pages/pipelines/index.tsx
shell/app/modules/project/router.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline management detail
| 🇺🇸 English | Details of the project level pipeline. |
| 🇨🇳 中文    | 项目级流水线的详情。 |
❎ No
Fixes #

feat(dop): project pipeline management detail

---

shell/app/config-page/components/bubble-graph/index.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx

fix trace params
❎ No
❎ No
Fixes #

feat: fix trace params

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.tsx

Project pipeline style optimization.
❎ No
| 🇺🇸 English |  Project level pipelining style optimization.   |
| 🇨🇳 中文    |  项目级流水线样式优化。  |
❎ No
Fixes #

feat(dop): project pipeline style optimization

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx

Project pipeline interface change
❎ No
| 🇺🇸 English | Modify fields based on interface changes. |
| 🇨🇳 中文    |  根据接口变动修改字段。  |
❎ No
Fixes #

fix(dop): project pipeline interface change

---

core/src/index.tsx
core/src/stores/route.ts
shell/app/common/components/contractive-filter/index.tsx
shell/app/common/components/table/index.scss
shell/app/modules/msp/env-overview/service-list/pages/service-list.scss
shell/app/modules/org/common/card/index.scss
shell/app/modules/project/pages/apps/app-list.scss
shell/app/modules/project/pages/apps/app-list.tsx
shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/styles/_color.scss

feat: support i18n for date range pick in filter
fix: update query type to string
fix: gantt inParams parentId must be number
feat: update app default logo to icon
fix: project app list style
feat: replace $color-table-head-bg with $color-default-02
❎ No
Fixes #

fix: date range picker translation in filter

---

shell/app/config-page/components/bubble-graph/index.tsx
shell/app/config-page/components/line-graph/index.tsx
shell/app/modules/msp/env-overview/service-list/pages/transaction.scss
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-detail.tsx
shell/app/modules/msp/monitor/browser-insight/router.ts
shell/app/styles/antd-extension.scss

hidden summary、location analysis、geography
❎ No
❎ No
Fixes #

feat: hidden summary、location analysis、geography

---

shell/app/common/components/markdown-editor/editor.scss
shell/app/layout/pages/page-container/components/header.scss
shell/app/modules/project/pages/apps/app-list.tsx

* update markdown render style
* fix scrollbar in content in app list
| 🇺🇸 English |  update markdown render style  |
| 🇨🇳 中文    | 更新 markdown 渲染样式  |
❎ No
Fixes #

feat: update markdown render style

---

shell/app/modules/org/common/audit-templates.json

update audit template about msp and cmp modules
❎ No
| 🇺🇸 English | update audit template about msp and cmp modules |
| 🇨🇳 中文    | 更新 msp 与 cmp 模块的部分审计模板 |
❎ No
Fixes #

feat: update audit template(msp and cmp modules)

---

shell/app/modules/project/pages/deploy/deploy-config/index.tsx
shell/app/modules/project/pages/deploy/index.tsx

fix: fix deploy tab change error
❎ No
| 🇺🇸 English | fix: fix deploy tab change error             |
| 🇨🇳 中文    |   fix: 修复部署中心tab切换错误           |
❎ No
Fixes #

fix: fix deploy tab change error

---

shell/app/modules/project/router.tsx

update project pipeline route
❎ No
| 🇺🇸 English |     -        |
❎ No
Fixes #

feat: update project pipeline route

---

shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx

fix: fix deploy config add in line
❎ No
❎ No
Fixes #

fix: fix deploy config add in line

---

shell/app/modules/project/pages/release/components/application-detail.tsx
shell/app/modules/project/pages/release/components/form.tsx

Fix project release edit style bug;
->
| 🇺🇸 English | Fixed issue with project level artifacts editing page style |
| 🇨🇳 中文    | 修复了项目级制品编辑页面样式问题。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=274639&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project release edit style bug。。

---

shell/app/modules/project/pages/deploy/deploy-detail/index.tsx

fix: add deploy detail table search
| 🇺🇸 English |    fix: add deploy detail table search          |
| 🇨🇳 中文    |      fix: 添加部署详情表格搜索        |
❎ No
Fixes #

fix: add deploy detail table search

---

shell/app/common/components/radio-tabs/index.scss
shell/app/menus/dop.tsx
shell/app/menus/project.tsx
shell/app/modules/project/pages/deploy/deploy-config/index.tsx

* fix some styles
* hide my app menu
| 🇺🇸 English |  remove my application list menu   |
| 🇨🇳 中文    |           移除我的应用列表菜单入口   |
❎ No
Fixes #

fix: remove my application list menu

---

shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/pages/deploy/deploy-config/index.tsx
shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
shell/app/modules/project/pages/deploy/deploy-detail/index.tsx

fix: fix placeholder
❎ No
| 🇺🇸 English |    -          |
❎ No
Fixes #

fix: fix placeholder

---

shell/app/common/utils/go-to.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/menus/project.tsx
shell/app/modules/project/pages/pipelines/index.tsx
shell/app/modules/project/router.tsx
shell/app/modules/project/tabs.tsx

Fix project pipeline style bug
| 🇺🇸 English | Fixed project level pipeline style issues. |
| 🇨🇳 中文    |  项目级流水线样式问题修复。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275521&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline style optimization

---

shell/app/modules/project/pages/deploy/add-deploy/add-release.scss

| 🇺🇸 English |    -          |
| 🇨🇳 中文    |     -         |
❎ No
Fixes #

fix: fix app selector height

---

shell/app/modules/project/router.tsx

Dop page name optimization
| 🇺🇸 English | DevOps platform artifacts and application page names changed. |
| 🇨🇳 中文    | DevOps平台制品和应用页面名修改。  |
❎ No
Fixes #

fix(dop): dop page name optimization

---

shell/app/modules/project/pages/deploy/deploy-config/index.tsx
shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
shell/app/modules/runtime/stores/runtime.ts

fix: project runtime auth
❎ No
| 🇺🇸 English |     fix: project runtime auth         |
| 🇨🇳 中文    |    fix: 修复项目runtime权限问题          |
❎ No
Fixes #

fix: project runtime auth

---

shell/app/layout/pages/page-container/components/navigation/user-menu.tsx

fix: fix admin entry auth error
❎ No
| 🇺🇸 English |    fix: fix admin entry auth error          |
| 🇨🇳 中文    |    fix: 修复admin入口权限错误       |
❎ No
Fixes #

fix: fix admin entry auth error

---

shell/app/modules/msp/env-setting/configuration/index.tsx
shell/app/modules/org/common/audit-templates.json

update data structure about token
❎ No
| 🇺🇸 English |     -    |
| 🇨🇳 中文    |       -     |
❎ No
Fixes #

feat: update data structure about token

---

shell/app/org-home/pages/active-rank/index.tsx
shell/app/org-home/pages/personal-contribute/index.tsx

Fix invite to org page throw error.
❎ No
| 🇺🇸 English |  An error occurred on the page linked to join the organization. |
| 🇨🇳 中文    |  通过链接加入组织页面报错。  |
❎ No
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=276029&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(common): invite to org page throw error

---

shell/app/config-page/components/table/v2/utils.tsx

Config table text td add tooltip.
| 🇺🇸 English | Added hints to the text grid of the componentized table.  |
| 🇨🇳 中文    |  组件化表格的文字格增加提示。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275521&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

feat(common): config table text td add tooltip

---

shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx

Fix project pipeline detail link bug.
❎ No
| 🇺🇸 English |  Fixed the project level pipeline details link jump bug. |
| 🇨🇳 中文    | 修复了项目级流水线详情执行明细链接跳转错误bug。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275835&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline detail link bug

---

shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline branch list interface change.
❎ No
| 🇺🇸 English | Project level pipeline branch list interface changes. |
| 🇨🇳 中文    |  项目级流水线分支列表接口变更。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275836&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline branch list interface change

---

shell/app/modules/project/pages/pipelines/components/logs.tsx

Add project pipeline logs detail close button
->
| 🇺🇸 English | Add close button to project level pipeline execution record detail drawer. |
| 🇨🇳 中文    |  项目级流水线执行记录详情抽屉增加关闭按钮。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275904&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline logs detail close button

---

shell/app/config-page/index.tsx

feat: partial render config page
❎ No
| 🇺🇸 English |     feat: partial render config page         |
| 🇨🇳 中文    |    feat: 组件化协议部分渲染         |
❎ No
Fixes #

feat: partial render config page

---

shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/extra/entry.js
shell/app/modules/msp/env-overview/service-list/pages/process.tsx
shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx

feat: notify group add params 

---

shell/app/modules/cmp/pages/cluster-container/cluster-nodes-detail.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-nodes.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-pods.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-workload-detail.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-workload.tsx

fix: fix cmp container drawer style
| 🇺🇸 English |     fix: fix cmp container drawer style         |
| 🇨🇳 中文    |  fix: 修复cmp容器资源详情滑窗的样式      |
❎ No
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=276152&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=772&type=TASK

fix: fix cmp container drawer style

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/config-page/components/configurable-filter/configurable-filter.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.tsx

Fix project pipeline table filter bug.
❎ No
| 🇺🇸 English | Fixed a bug where the left app list was not updated after the project level pipeline table was filtered to all apps. |
| 🇨🇳 中文    | 修复了项目级流水线表格筛选为全部应用后，左侧应用列表不更新的bug。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=275813&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline table filter bug

---

shell/app/modules/msp/env-overview/service-list/pages/overview.tsx

remove filter by front
❎ No
❎ No
Fixes #

feat: remove filter by front

---

shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/org-home/pages/land/index.tsx

fix style
| 🇺🇸 English |  align logo and user avatar in land page  |
| 🇨🇳 中文    |  对齐着陆页的 logo 和头像  |
Fixes #

fix: align logo and user avatar in land page

---

shell/app/modules/project/pages/issue/gantt/index.tsx

fix param type not match
❎ No
| 🇺🇸 English |     -        |
| 🇨🇳 中文    |       -      |
Fixes #

fix: choose issue id should convert type for api

---

shell/app/config-page/components/card/card.tsx

fix: fix personal star app cancel error
❎ No
| 🇺🇸 English |  fix: fix personal star app cancel error            |
| 🇨🇳 中文    |  fix: 修复个人工作台星标应用点击自动取消错误            |
❎ No
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=276534&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix: fix personal star app cancel error

---

shell/app/modules/project/pages/pipelines/components/form.scss
shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline create pipeline optimization.
->
| 🇺🇸 English | New form interaction changes in the project pipeline. |
| 🇨🇳 中文    |  项目级流水线新增表单交互变更。  |
Fixes #

fix(dop): project pipeline create pipeline optimization

---

cli/bin/erda.ts
cli/lib/build-enterprise-online.ts
cli/lib/build-enterprise.ts
cli/lib/init-online.ts
cli/lib/init.ts
cli/lib/util/env.ts
cli/package.json
core/package.json
core/src/index.tsx
core/src/utils/mf-helper.ts
core/webpack.config.js
cspell.json
erda.yml
pnpm-lock.yaml
scheduler/src/proxy.ts
scheduler/src/util.ts
shell/app/App.tsx
shell/mf.config.js

support solo enterprise build
1. introduce dynamic module federation remotes
2. add server for enterprise ui
3. update cli to support enterprise build
❎ No
| 🇺🇸 English |    support enterprise ui solo build          |
| 🇨🇳 中文    |   支持企业版UI独立打包           |
❎ No

fix: try to merge PR for solo enterprise build

---

erda.yml

add enterprise-ui service
❎ No
| 🇺🇸 English |    add enterprise-ui service          |
| 🇨🇳 中文    |     添加enterprise-ui的service         |
❎ No
Fixes #

feat(common): add enterprise-ui service

---

shell/app/config-page/index.tsx

Fix  config page inParams update bug.
❎ No
| 🇺🇸 English |  Fixed a bug where componentized protocol page parameters were not updated. |
| 🇨🇳 中文    |   修复了组件化协议页面传参不更新的bug。  |
Fixes #

fix(common): config page inParams update bug

---

shell/app/config-page/components/base-list/base-list.tsx

fix: fix personal page error
❎ No
| 🇺🇸 English |     fix: fix personal page error         |
| 🇨🇳 中文    |     fix: 修复个人工作台报错         |
❎ No
Fixes #

fix: fix personal page error

---

scheduler/src/proxy.ts

proxy static file issue
❎ No
| 🇺🇸 English |   fix proxy static file issue           |
| 🇨🇳 中文    |   修复无法转发静态文件的问题           |
❎ No
Fixes #

feat(common): fix proxy static file issue

---

shell/app/config-page/index.tsx

feat: add config page partial
❎ No
| 🇺🇸 English |      feat: add config page partial update        |
| 🇨🇳 中文    |   feat: 组件化协议增量修改          |
❎ No
Fixes #

feat: add config page partial update

---

shell/app/common/components/base-list/list-item.tsx
shell/app/config-page/page-render.tsx

fix: fix deploy runtime selectable
❎ No
| 🇺🇸 English |    fix: fix deploy runtime selectable error          |
| 🇨🇳 中文    |     fix: 修复部署中心runtime不可选的展示错误         |
❎ No
Fixes #

fix: fix deploy runtime selectable error

---

shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/views/index.ejs
shell/index.html

Create project pipeline add icon
| 🇺🇸 English | Create a project level pipeline form to add icons. |
| 🇨🇳 中文    | 创建项目级流水线表单增加图标。 |
Fixes #

fix(dop): create project pipeline add icon

---

shell/app/modules/application/stores/pipeline-config.ts

fix: fix cicds config api error
❎ No
| 🇺🇸 English |    fix: fix cicds config api error      |
| 🇨🇳 中文    | fix: 修复流水线参数配置接口错误  |
Fixes #

fix: fix cicds config api error

---

shell/app/modules/org/common/audit-templates.json

motify alert audit template
❎ No
| 🇺🇸 English |       motify alert audit template       |
| 🇨🇳 中文    |      改变审计日志模版        |
❎ Yes release/1.6-alpha.2

feat: modify audit template

---

shell/app/common/components/markdown-editor/editor.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/cmp/common/custom-alarm/index.tsx

fix MdEditor locales
❎ No
| 🇺🇸 English | fix MdEditor locales |
| 🇨🇳 中文    | 修复 MdEditor 国际化问题 |
Fixes #

fix: MdEditor locales

---

shell/app/common/components/badge/index.scss
shell/app/common/components/badge/index.tsx
shell/app/common/components/configurable-filter/index.scss
shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
shell/app/modules/project/types/deploy.d.ts

fix: fix deploy release api params
❎ No
| 🇺🇸 English |    fix: fix deploy release api params          |
| 🇨🇳 中文    |      fix: 修复制品搜索参数          |
❎ No
Fixes #

fix: fix deploy release api params

---

shell/app/common/components/markdown-editor/editor.tsx
shell/app/config-page/components/simple-chart/simple-chart.scss
shell/app/layout/pages/page-container/components/navigation/user-menu.tsx

fix style in english mode
->
---
->
---
->
| 🇺🇸 English | fix style in english mode  |
| 🇨🇳 中文    |  修复英文模式下的样式问题  |
Fixes #
[issue1](https://erda.cloud/erda/dop/projects/387/issues/all?id=277082&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG)

fix: fix style in english mode

---

shell/app/common/components/list-select/index.tsx
shell/app/modules/project/pages/release/components/application-detail.tsx
shell/app/modules/project/pages/release/components/form.tsx

Project release text change.
| 🇺🇸 English |  Text change:  Change the article name in the project level article to version.   |
| 🇨🇳 中文    |  文案修改：将项目级制品中的制品名称改成版本。  |
Fixes #

fix(dop): project release text change

---

shell/app/modules/msp/env-overview/service-list/pages/service-name-select.tsx
shell/app/modules/msp/env-overview/service-list/pages/transaction-detail.tsx
shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx

feat: copy transaction link
❎ No
| 🇺🇸 English | transaction details link can be copied and shared |
| 🇨🇳 中文    | 事务详情链接可复制分享 |
❎ Yes
Fixes #

feat: copy transaction link

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/pipelines/index.scss
shell/app/modules/project/pages/pipelines/index.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline apps list add pipelines total num.
| 🇺🇸 English |  Project pipeline apps list add pipelines total num.  |
| 🇨🇳 中文    |  项目级流水线应用列表增加流水线总数显示。  |
Fixes #

feat(dop): project pipeline apps list add pipelines total num

---

shell/app/common/components/erda-alert/index.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/release/application.tsx
shell/app/modules/project/pages/release/release-protocol.tsx

Project release remove application list.
->
| 🇺🇸 English | Project level releases Application release List Deletes the application list.  |
| 🇨🇳 中文    |  项目级制品应用制品列表删除应用列表。  |
Fixes #

fix(dop): project release remove application list

---

shell/app/common/utils/index.ts
shell/app/modules/project/tabs.tsx
shell/app/modules/publisher/pages/artifacts/artifacts-detail.scss
shell/app/modules/publisher/pages/artifacts/artifacts-detail.tsx
shell/app/modules/publisher/pages/artifacts/index.tsx
shell/app/org-home/stores/org.tsx

* fix: artifact menu style
* deploy page tag first letter upper
* update breadcrumb org name after update org info
->
---
| 🇺🇸 English |  fix menu style in artifact detail page |
| 🇨🇳 中文    |  修复制品详情页菜单样式  |
Fixes #

fix: fix artifact detail menu style

---

shell/app/common/components/edit-list/index.tsx

fix: fix i18n
❎ No
| 🇨🇳 中文    |        -      |
Fixes #

fix: fix i18n

---

shell/app/locales/en.json
shell/app/locales/utils.ts
shell/app/locales/zh.json
shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
shell/app/modules/runtime/pages/overview/components/index.tsx

❎ No
| 🇺🇸 English | fix logServer locale |
| 🇨🇳 中文    | 修复日志服务国际化  |
Fixes #

fix: log server locale

---

shell/app/App-vite.tsx
shell/app/App.tsx

Remove space between Chinese button characters.
->
| 🇺🇸 English |  Remove space between Chinese button characters.   |
| 🇨🇳 中文    |  去掉了中文按钮中的空格。  |
Fixes #

fix(common): remove space between Chinese button characters

---

shell/app/modules/org/common/audit-templates.json

modify dashboard template
- [ X] I18n is finished and updated by cli
- [ X] Form fields validation is added and length is limited
- [ X] Display normally on small screen
- [ X] Display normally when some data is empty or null
- [ X] Display normally in english mode
❎ No
| 🇺🇸 English |       modify dashboard template       |
| 🇨🇳 中文    |        修改微服务大盘审计日志模版      |
Fixes #

fix: modify dashboard template

---

shell/app/charts/theme.js
shell/app/modules/msp/env-overview/service-list/pages/index.tsx

fix: pick alpha.5
❎ No
| 🇺🇸 English |    -          |
| 🇨🇳 中文    |     -         |
❎ No
Fixes #

fix: pick alpha.5

---

scheduler/src/proxy.ts

add optional call
❎ No
| 🇺🇸 English |     add optional call         |
| 🇨🇳 中文    |     添加optional call         |
Fixes #

feat(common): add optional call

---

shell/app/common/components/base-list/index.spec.d.ts
shell/app/common/components/base-list/index.tsx
shell/app/common/components/head-operation-bar/index.tsx
shell/app/config-page/components/base-list/base-list.spec.d.ts
shell/app/config-page/components/base-list/base-list.tsx
shell/app/modules/project/pages/deploy/index.scss
shell/app/modules/project/pages/deploy/index.tsx

fix: fix deploy style
| 🇺🇸 English |      fix: fix deploy style        |
| 🇨🇳 中文    |     fix: 部署中心样式修改       |
Fixes #

fix: fix deploy style

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/pipelines/index.tsx
shell/app/modules/project/pages/release/components/application-detail.tsx

Project release detail optimization.
| 🇺🇸 English |  Add the cluster name and GitRepo address for project level artifacts details. |
| 🇨🇳 中文    |  项目级制品详情增加集群名称和GitRepo地址。  |
Fixes #

fix(dop): project release detail optimization

---

shell/app/common/components/table/index.tsx

Fix front end pagination total bug
❎ No
| 🇺🇸 English | Fixed a bug in the total number of pager displays in front page cases.  |
| 🇨🇳 中文    |  修复了前端分页情况下分页器的总数显示bug。 |
Fixes #

fix(common): front end pagination total bug

---

shell/app/modules/org/common/audit-templates.json

modify dashboard english template
❎ No
| 🇺🇸 English |       modify dashboard english template       |
| 🇨🇳 中文    |       修改大盘英文模版       |
Fixes #

feat: modify dashboard english template

---

shell/app/common/components/erda-icon/index.tsx
shell/app/config-page/components/table/v2/table.spec.d.ts
shell/app/config-page/components/table/v2/utils.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/pipelines/components/logs.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.scss
shell/app/modules/project/pages/pipelines/index.tsx

Project pipeline table optimization.
->
| 🇺🇸 English | Project pipeline table optimization. |
| 🇨🇳 中文    |  项目级流水线表格优化。  |
Fixes #

fix(dop): project pipeline table optimization

---

shell/app/common/components/erda-alert/index.tsx
shell/app/modules/msp/monitor/status-insight/pages/status/status.scss
shell/app/modules/msp/monitor/status-insight/pages/status/status.tsx

optimize active monitor style
| 🇺🇸 English | optimize active monitor style |
| 🇨🇳 中文    | 优化主动监控样式 |
✅ Yes
Fixes #

feat: optimize active monitor style

---

shell/app/common/components/input-select/index.tsx

fix: fix input select load data loop
❎ No
| 🇺🇸 English |   fix: fix input select load data loop           |
| 🇨🇳 中文    |    fix: 修复input select组件循环加载数据        |
Fixes #

fix: fix input select load data loop

---

shell/app/config-page/components/table/v2/utils.tsx

Fix config page table row click bug.
❎ No
| 🇺🇸 English |  Item - level pipeline table row click error.  |
| 🇨🇳 中文    |  项目级流水线表格行点击报错。  |
Fixes #

fix(common): config page table row click bug

---

shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/common-node.tsx

❎ No
| 🇺🇸 English | fixed occasional missing connections between nodes |
| 🇨🇳 中文    |  修复偶发个别节点之间连线缺失 |
release/1.6=alpha.2
Fixes #

feat: always show node Handle

---

shell/app/config-page/index.tsx

feat: pick config page partial update
❎ No
| 🇺🇸 English |   -             |
❎ No
Fixes #

feat: pick config page partial update

---

shell/app/common/components/table/index.tsx
shell/app/common/components/table/interface.ts
shell/app/common/components/table/table-config.tsx
shell/app/common/components/table/table-footer.tsx
shell/app/config-page/components/table/v2/table.spec.d.ts
shell/app/config-page/components/table/v2/table.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx

Project pipeline table style optimization.
->
| 🇺🇸 English | Project pipeline table style optimization.  |
| 🇨🇳 中文    |  项目级流水线表格样式优化。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=278276&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline table style optimization

---

shell/app/modules/project/router.tsx

Fix project releaes url query bug.
❎ No
| 🇺🇸 English | Fixed a bug in project level artifacts where the filter criteria were not cleared when switching between applications and projects.  |
| 🇨🇳 中文    | 修复了项目级制品中，切换应用和项目时筛选条件没有清空的bug。 |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=278088&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project releaes url query bug

---

shell/app/i18n.ts
shell/app/views/index.ejs
shell/index.html

update document description.
❎ No
| 🇺🇸 English | update page title in share link  |
| 🇨🇳 中文    |  更新分享链接里的页面标题 |
❎ No
Fixes #

feat: update page title in share link

---

shell/app/config-page/components/card/card.scss

fix: fix kanban card style
| 🇺🇸 English |    fix: fix kanban card style          |
| 🇨🇳 中文    |    fix: 修复看板卡片样式      |
Fixes #

fix: fix kanban card style

---

shell/app/config-page/components/base-list/base-list.tsx

fix: fix list title status click style
| 🇺🇸 English |      fix: fix list title status clickable style        |
| 🇨🇳 中文    |  fix: 修复list组件titleStatus的可点击样式           |
Fixes #

fix: fix list title status clickable style

---

shell/app/common/components/erda-alert/index.scss
shell/app/modules/project/pages/pipelines/components/form.scss
shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline create check name and pipeline.
| 🇺🇸 English | Check whether the name of the pipeline is duplicated and whether the pipeline file has been used. |
| 🇨🇳 中文    |  项目级流水线新增时校验名称是否重复，流水线文件是否已被使用。  |
❎ No
Fixes #

feat(dop): project pipeline create check name and pipeline

---

shell/app/modules/apiManagePlatform/pages/api-market/components/api-resource/resource.scss
shell/app/modules/apiManagePlatform/pages/api-market/components/api-resource/resource.tsx

fix: api method select style
❎ No
Fixes #

fix: api method select style

---

shell/app/modules/application/pages/pipeline/index.tsx
shell/app/modules/application/router.ts

Pipeline scroll bar optimization.
| 🇺🇸 English | Pipeline scroll bar optimization. |
| 🇨🇳 中文    | 流水线的滚动条优化。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=277639&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): pipeline scroll bar optimization

---

shell/app/common/components/contractive-filter/index.tsx
shell/app/modules/project/pages/backlog/backlog.tsx

Fix issues backlog filter selector style bug.
->
| 🇺🇸 English | Fixed the style of the dropdown box in the filter in project Collaboration - pending. |
| 🇨🇳 中文    | 修复了项目协同-待处理中，筛选器里下拉框的样式问题。  |
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=278889&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): issues backlog filter selector style bug

---

shell/app/common/components/base-list/index.tsx
shell/app/common/components/edit-field/index.tsx
shell/app/common/components/table/index.tsx
shell/app/config-page/components/base-list/base-list.tsx
shell/app/config-page/components/gantt/components/task-item/bar/bar.tsx
shell/app/config-page/components/gantt/components/task-item/project/project.tsx
shell/app/modules/project/pages/homepage/readme-markdown.tsx

fix: fix safari style issues
| 🇺🇸 English |     fix: fix safari style issues         |
| 🇨🇳 中文    |   fix: 修复safari兼容性样式问题        |
Fixes #

fix: fix safari style issues

---

shell/app/modules/project/pages/issue/board.tsx

feat: add issue kanban refresh
❎ No
| 🇺🇸 English |    feat: add issue kanban refresh          |
| 🇨🇳 中文    |      feat: 看板添加刷新图标        |
❎ No
Fixes #

feat: add issue kanban refresh

---

shell/app/common/components/erda-icon/index.tsx
shell/app/views/index.ejs
shell/index.html

Update icons for applications list.
❎ No
| 🇺🇸 English |  Fixed app list public and private icons not displayed.  |
| 🇨🇳 中文    |  修复应用列表公有私有图标不显示的问题。  |
❎ No
Fixes #

fix(dop): update icons for applications list

---

shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline detail display optimization without branch.
❎ No
| 🇺🇸 English |  In the project-level pipeline, if the branch to which the pipeline belongs is deleted, clicking details does not display basic information, but only display execution records.  |
| 🇨🇳 中文    |  在项目级流水线中，如果流水线所属的分支被删除，点开详情不展示基础信息，只展示执行记录。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=279350&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline detail display optimization without branch

---

shell/app/modules/project/pages/pipelines/components/basic.tsx

Fix project pipeline detail action bug.
❎ No
| 🇺🇸 English |  For details about the pipeline, incorrect parameter transfer occurs on the configuration information page. |
| 🇨🇳 中文    | 流水线详情，配置信息页面传参错误。 |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=279851&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=772&type=BUG

fix(dop): project pipeline detail action bug

---

shell/app/modules/msp/pages/micro-service/overview.tsx

refactor the msp project list using base-list
❎ No
| 🇺🇸 English |  refactor the msp project list using ErdaList |
| 🇨🇳 中文    | 使用 ErdaList 重构 msp 项目列表 |
❎ No
Fixes #

feat: refactor the msp project list using ErdaList

---

shell/app/config-page/components/gantt/components/gantt/task-gantt-content.tsx
shell/app/config-page/components/gantt/components/task-item/bar/bar.tsx
shell/app/config-page/components/gantt/components/task-item/project/project.tsx

fix: fix gantt hover bug
❎ No
| 🇺🇸 English |   fix: fix gantt hover bug           |
| 🇨🇳 中文    |   fix: 修复甘特图hover错误问题           |
❎ No
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=269754&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=772&type=BUG

fix: fix gantt hover bug

---

shell/app/config-page/components/action-form.tsx
shell/app/modules/application/common/components/edit-stage.tsx
shell/app/yml-chart/common/pipeline-node-drawer.tsx

fix: fix pipeline custom script action image error
❎ No
| 🇺🇸 English |    fix: fix pipeline custom script action image error          |
| 🇨🇳 中文    |    fix: 修复自定义任务action中镜像字段未传递错误          |
❎ No
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=229831&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=772&type=BUG

fix: fix pipeline custom script action image error

---

shell/app/common/components/contractive-filter/index.tsx
shell/app/modules/cmp/common/addon-detail/detail.tsx
shell/app/modules/cmp/common/addon-detail/resource.tsx
shell/app/modules/cmp/pages/alarm-report/index.tsx
shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/aliCloud-preview.tsx
shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-forms/edit-table.tsx
shell/app/modules/cmp/pages/cluster-manage/operation-history.tsx
shell/app/modules/cmp/pages/domain-manage/index.tsx
shell/app/modules/cmp/pages/middleware-dashboard/index.tsx
shell/app/modules/cmp/pages/middleware-detail/detail.tsx
shell/app/modules/cmp/pages/middleware-detail/resource.tsx
shell/app/modules/cmp/pages/middleware-detail/upgrade-info.tsx
shell/app/modules/cmp/pages/pod-detail/index.tsx
shell/app/modules/cmp/pages/tasks/task-list.tsx

feat: migrate cmp table
❎ No
| 🇺🇸 English |    feat: migrate cmp table          |
| 🇨🇳 中文    |   feat: cmp Table组件迁移           |
❎ No
Fixes #

feat: migrate cmp table

---

shell/app/modules/org/pages/projects/settings/info/index.tsx

Fix project edit bug
❎ No
| 🇺🇸 English |  Fixed a bug where projects could not be edited in admin. |
| 🇨🇳 中文    |  修复了在管理中心中，项目无法编辑的bug。  |
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=280606&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG

fix(common): project edit bug

---

shell/app/modules/project/tabs.tsx

Hide milestone
❎ No
| 🇺🇸 English |  Hide milestone.  |
| 🇨🇳 中文    | 隐藏里程碑 |
❎ No
Fixes #

fix(dop): hide milestone

---

shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx

Notify table operation optimization
| 🇺🇸 English |  Notification list open and close actions changed to text. |
| 🇨🇳 中文    | 通知列表的开启关闭操作改成文字形式。 |
❎ No
Fixes #

fix(dop): notify table operation optimization

---

README.md
cli/lib/init-online.ts
cli/lib/init.ts
cli/package.json

update project initialization process and readme.
❎ No 
| 🇺🇸 English |  update project initialization process and readme   |
| 🇨🇳 中文    |   更新初始化过程和 readme 文档  |
❎ No
Fixes #

feat: update project initialization process and readme

---

shell/app/common/components/table/index.tsx
shell/app/common/index.ts
shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
shell/app/modules/application/pages/problem/problem-list.tsx
shell/app/modules/application/pages/test/test-list.tsx
shell/app/modules/application/router.ts

Replace application table
| 🇺🇸 English | Replace the problem list, execution list, and pipeline execution record list with new tables. |
| 🇨🇳 中文    | 替换问题列表、执行列表、流水线执行记录列表为新表格。 |
❎ No
Fixes #

refactor(dop): replace application table

---

shell/app/common/components/configurable-filter/config-selector.tsx
shell/app/common/components/configurable-filter/index.scss
shell/app/common/components/configurable-filter/index.tsx
shell/app/locales/en.json
shell/app/locales/zh.json

fix: fix filter style
| 🇺🇸 English |     fix: fix filter style         |
| 🇨🇳 中文    |    fix:  修复filter样式          |
no
Fixes #

fix: fix filter style

---

shell/app/common/components/configurable-filter/index.tsx

fix: fix configurable filter value sort error
❎ No
| 🇺🇸 English |     fix: fix configurable filter value sort error         |
| 🇨🇳 中文    |    fix: 修复filter值排序导致页面错误        |
❎ No
Fixes #

fix: fix configurable filter value sort error

---

shell/app/common/components/configurable-filter/external-item.scss

fix: fix filter input focus transition
❎ No
| 🇺🇸 English |     fix: fix filter input focus transition         |
| 🇨🇳 中文    |  fix: 修复filter中input的获焦动画样式问题            |
❎ No
Fixes #

fix: fix filter input focus transition

---

.npmrc
cli/.npmrc
core/.npmrc
pnpm-lock.yaml
shell/.npmrc

update registry mirror
merge npmrc to one root file.
❎ No
| 🇺🇸 English | chore: change npm mirror domain from npm.taobao.org to npmmirror.com  |
| 🇨🇳 中文    |  更新 npm 淘宝镜像源的域名   |
❎ No
Fixes #

chore: change npm mirror domain from npm.taobao.org to npmmirror.com

---

shell/app/common/components/cards-layout/index.tsx
shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx

Fix bug of addon switch environment page error.
❎ No
| 🇺🇸 English | Fixed an occasional error with environment deployment Addon switching environment page. |
| 🇨🇳 中文    |  修复了环境部署Addon切换环境页面偶现报错的问题。  |
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=282511&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMTQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG

fix(dop): addon switch environment page error

---

shell/app/modules/application/pages/settings/components/app-variable-config.tsx
shell/app/modules/application/pages/settings/components/variable-config-form.tsx

fix: fix config file upload params
| 🇺🇸 English |     fix: fix config file upload params         |
| 🇨🇳 中文    |     fix: 修复参数配置上传文件传参错误   |
❎ No
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=283015&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG

fix: fix config file upload params

---

shell/app/modules/org/services/project-list.ts
shell/app/modules/project/pages/issue/import-export.tsx

fix: fix import export record params error
❎ No
| 🇺🇸 English |    fix: fix import export record params error          |
| 🇨🇳 中文    |    fix: 修复事项导入导出参数错误         |
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=283328&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG

fix: fix import export record params error

---

shell/app/modules/msp/alarm-manage/alarm-record/index.ts
shell/app/modules/msp/alarm-manage/alarm-strategy/index.js
shell/app/modules/msp/alarm-manage/index.ts
shell/app/modules/msp/alarm-manage/overview/index.tsx

modify params & remove page wrapper
❎ No
| 🇺🇸 English | modify alarm overview params & remove page wrapper |
| 🇨🇳 中文    | 修改告警总览参数&移除页面白色背景 |
Fixes #

fix(msp): modify params & remove page wrapper

---

pipeline.yml

update pipeline branch
❎ No
❎ yes
Fixes #

feat: update pipeline

---

shell/app/modules/project/pages/release/components/application-detail.tsx

Project release add resource.
| 🇺🇸 English |  project release detail add resource. |
| 🇨🇳 中文    |  项目级制品详情增加resource。  |
❎ No
Fixes #

feat(dop): project release add resource

---

locales/en.json
locales/zh.json
shell/app/modules/dop/pages/projects/project-list-protocol.tsx

feat: add create project in project -list
| 🇺🇸 English |    feat: add create project in project list          |
| 🇨🇳 中文    |   feat: 项目列表中添加创建项目链接           |
❎ No
Fixes #

feat: add create project in project list

---

shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/modules/project/pages/issue/import-export.tsx

feat: add gantt import export
| 🇺🇸 English |   feat: add gantt import export           |
| 🇨🇳 中文    |   feat: 甘特图添加导入导出功能           |
❎ No
Fixes #

feat: add gantt import export

---

shell/app/modules/application/pages/repo/repo-tree.tsx

Repo tree table columns width optimization.
->
| 🇺🇸 English | Code warehouse table column width adjustment. |
| 🇨🇳 中文    |  代码仓库表格列宽调整。  |
❎ No
Fixes #

fix(dop): repo tree table columns width optimization

---

shell/app/modules/msp/alarm-manage/alert-list/events/base-event-detail.tsx

force update inParams
❎ No
| 🇺🇸 English | add forceUpdate for eventDetail |
| 🇨🇳 中文    | 事件详情增加 forceUpdate |
❎ No
Fixes #

fix(msp): add inParams into forceUpdate

---

shell/app/modules/dop/pages/projects/project-list-protocol.tsx

fix const 
❎ No
| 🇨🇳 中文    |         -     |
❎ No
Fixes #

fix: remove duplicate const variable

---

shell/app/common/components/empty-holder/index.tsx

Fix empty holder scroll bar bug.
->
| 🇺🇸 English | Fixed an issue with scroll bars appearing on blank pages. |
| 🇨🇳 中文    | 修复了空白页出现滚动条的问题。 |
❎ No
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=281969&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG

fix(common): empty holder scroll bar bug

---

shell/app/config-page/components/base-list/base-list.tsx
shell/app/config-page/components/common.spec.d.ts

feat: update list batch operation icon data
❎ No
| 🇺🇸 English |  feat: update list batch operation icon data            |
| 🇨🇳 中文    |   feat: 修改list组件批量操作中icon数据结构           |
❎ No
Fixes #

feat: update list batch operation icon data

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/pages/problem/problem-detail.tsx

Fix problem detail style bug.
->
| 🇺🇸 English |  Fixed style issues in the problem details drawer. |
| 🇨🇳 中文    | 修复问题详情抽屉中的样式问题。 |
❎ No
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=284424&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG

fix(dop): problem detail style bug

---

shell/app/common/components/menu/index.tsx
shell/app/interface/global.d.ts
shell/app/modules/application/router.ts
shell/app/modules/application/tabs.tsx
shell/app/modules/project/router.tsx
shell/app/modules/project/tabs.tsx

feat: update back style in tab
->
| 🇺🇸 English |  feat: update back style in tab  |
| 🇨🇳 中文    |   更新 tab 返回样式 |
❎ No
Fixes #

feat: update back style in tab

---

shell/app/common/utils/go-to.tsx
shell/app/config-page/mock/crud.mock.ts
shell/app/modules/addonPlatform/pages/common/components/addon-detail-drawer.tsx
shell/app/modules/application/common/app-list-protocol.tsx
shell/app/modules/application/pages/build-detail/index.tsx
shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
shell/app/modules/application/pages/problem/problem-list.tsx
shell/app/modules/application/pages/quality/entry.tsx
shell/app/modules/application/pages/quality/index.tsx
shell/app/modules/application/pages/repo/repo-tree.tsx
shell/app/modules/application/tabs.tsx
shell/app/modules/cmp/common/addon-detail/detail.tsx
shell/app/modules/cmp/pages/domain-manage/index.tsx
shell/app/modules/cmp/pages/tasks/task-list.tsx
shell/app/modules/org/common/audit-templates.json
shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/pages/deploy/deploy-config/index.tsx
shell/app/modules/project/pages/deploy/index.tsx
shell/app/modules/project/router.tsx

fix: update application jump link to project level page
❎ No
| 🇺🇸 English |    fix: update application jump link to project level page          |
| 🇨🇳 中文    |     更新应用级页面的链接到项目级        |
❎ No
Fixes #

fix: update application jump link to project level page

---

shell/app/modules/application/pages/repo/components/repo-mr-form.scss
shell/app/modules/application/pages/repo/components/repo-mr-form.tsx
shell/app/modules/application/pages/repo/components/source-target-select.tsx
shell/app/modules/application/pages/repo/repo-mr-creation.tsx
shell/app/modules/application/router.ts
shell/app/modules/application/stores/repo.ts
shell/app/modules/application/types/repo.d.ts
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/services/issue.ts
shell/app/modules/project/types/issue.d.ts
shell/app/styles/util.scss

feat: add issue relation on create mr
| 🇺🇸 English |    feat: add issue relation on create mr          |
| 🇨🇳 中文    |  feat: 创建mr时添加事项关联        |
❎ No
Fixes #

feat: add issue relation on create mr

---

shell/app/modules/application/tabs.tsx

fix: change to check and redirect tab key
❎ No
| 🇺🇸 English |        Fix check logic for applying home jump    |
| 🇨🇳 中文    |    修复应用首页跳转的检查逻辑          |
❎ No
Fixes #

fix: change to check and redirect tab key

---

shell/app/modules/project/pages/deploy/deploy-config/index.tsx
shell/app/modules/project/router.tsx
shell/app/modules/runtime/pages/overview/components/index.tsx
shell/app/modules/runtime/pages/overview/components/info.tsx

fix: deploy env config can not switch
❎ No
| 🇺🇸 English |   fix: deploy env config can not switch    |
| 🇨🇳 中文    |      修复部署配置环境无法切换的问题        |
❎ No
Fixes #

fix: deploy env config can not switch

---

shell/app/modules/project/pages/release/components/application-detail.tsx

Application release edit optimization.
❎ No
| 🇺🇸 English | Add a plus sign to the version name verification rule of item artifacts. |
| 🇨🇳 中文    |  项目制品的版本名称校验规则增加加号。  |
❎ No
Fixes #

fix(dop): application release edit optimization

---

shell/app/modules/project/pages/release/components/application-detail.tsx

Fix application release detail resource bug.
| 🇺🇸 English |  Fixed a bug when viewing resource content in app details. |
| 🇨🇳 中文    |  修复了应用制品详情中查看resource内容时页面报错的bug。  |
❎ No
Fixes # https://erda.cloud/erda/dop/projects/387/issues/all?id=285181&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG

fix(dop): application release detail resource bug

---

shell/app/modules/project/tabs.tsx

fix: fix deploy runtime tab click error
❎ No
| 🇺🇸 English |     fix: fix deploy runtime tab click error         |
| 🇨🇳 中文    |      fix: 修复部署中心跳runtime页面后tab点击出错        |
yes
Fixes #

fix: fix deploy runtime tab click error

---

.erda/pipelines/ci-build-ce.yml
pipeline.yml

chore: update build community image pipeline yml
❎ No
❎ No
Fixes #

chore: update build community image pipeline yml

---

shell/app/modules/dop/pages/projects/project-list-protocol.tsx

fix: fix apply unblock params type
❎ No
| 🇺🇸 English |   fix: fix apply unblock params type           |
| 🇨🇳 中文    |      fix: 修复申请部署参数错误        |
cherry-pick release/1.6-alpha.4
Fixes #

fix: fix apply unblock params type

---

shell/auto_test/README.md
shell/auto_test/login.spec.ts
shell/auto_test/tests/admin/audit.spec.ts
shell/auto_test/tests/admin/cluster-manage.spec.ts
shell/auto_test/tests/admin/global-config.spec.ts
shell/auto_test/tests/admin/org-manage.spec.ts
shell/auto_test/tests/admin/user-manage.spec.ts
shell/auto_test/tests/dop/add-ticket.spec.ts
shell/auto_test/tests/dop/deploy.spec.ts
shell/auto_test/tests/dop/history.spec.ts
shell/auto_test/tests/dop/layout.spec.ts
shell/auto_test/tests/dop/pipeline.spec.ts
shell/auto_test/tests/dop/repo.spec.ts
shell/auto_test/tests/org/audit-log.spec.ts
shell/auto_test/tests/org/mobile-development-management.spec.ts
shell/auto_test/tests/org/organization-information.spec.ts
shell/package.json

update staging domain in auto test
❎ No
| 🇺🇸 English |     -        |
| 🇨🇳 中文    |      -       |
❎ No
Fixes #

chore: update staging domain in auto test 

---

.erda/pipelines/ci-build-ce.yml
.github/PULL_REQUEST_TEMPLATE.md

fix: missing build_cmd in pipeline yml
update pr template
❎ No
❎ No
Fixes #

fix: missing build_cmd in pipeline yml

---

.github/workflows/git-sync.yml
pipeline.yml

add tag version & remove useless push hack
Fixes #
- [Erda Cloud Issue Link]()
❎ No
| 🇺🇸 English |      add tag version & remove useless push hack        |
| 🇨🇳 中文    |       主动指定 version & 移除无用的 hack       |
❎ No

ci: add tag version & remove useless push hack

---

shell/app/modules/project/tabs.tsx

fix: fix deploy runtime tab title
Fixes #
- [Erda Cloud Issue Link]()
❎ No
| 🇺🇸 English |    fix: fix deploy runtime tab title          |
| 🇨🇳 中文    |    fix:修改部署中心runtime页面tab的title显示          |

fix: fix deploy runtime tab title

---

.github/PULL_REQUEST_TEMPLATE.md
shell/app/modules/project/pages/deploy/deploy-detail/index.tsx
shell/app/modules/project/types/deploy.d.ts
shell/auto_test/README.md
shell/auto_test/login.spec.ts
shell/auto_test/tests/admin/audit.spec.ts
shell/auto_test/tests/admin/cluster-manage.spec.ts
shell/auto_test/tests/admin/global-config.spec.ts
shell/auto_test/tests/admin/org-manage.spec.ts
shell/auto_test/tests/admin/user-manage.spec.ts
shell/auto_test/tests/dop/add-ticket.spec.ts
shell/auto_test/tests/dop/deploy.spec.ts
shell/auto_test/tests/dop/history.spec.ts
shell/auto_test/tests/dop/layout.spec.ts
shell/auto_test/tests/dop/pipeline.spec.ts
shell/auto_test/tests/dop/repo.spec.ts
shell/auto_test/tests/org/audit-log.spec.ts
shell/auto_test/tests/org/mobile-development-management.spec.ts
shell/auto_test/tests/org/organization-information.spec.ts
shell/package.json

chore: update staging domain to daily
Fixes #
❎ No
| 🇺🇸 English |   chore: update staging domain to daily    |
| 🇨🇳 中文    |   更新环境域名   |
❎ No

chore: update staging domain to daily

---

shell/app/common/components/load-more-selector/index.scss

fix placeholder style
Fixes #
- [【应用布局】样式统一修复](https://erda.cloud/erda/dop/projects/387/issues/all?id=284402&issueFilter__urlQuery=eyJhc3NpZ25lZUlEcyI6WyIxMDAwMzAwIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG)
❎ No
| 🇺🇸 English | fix placeholder style |
| 🇨🇳 中文    | 修复 placeholder 样式 |

fix(dop): fix placeholder style

---

shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/types/deploy.d.ts

fix preCheckResult validation.
PrePR: [feat(dop): update project deploy app list #2984](https://github.com/erda-project/erda-ui/pull/2984)
Fixes #
❎ No
| 🇺🇸 English | Fix button disable judgment logic |
| 🇨🇳 中文    | 修复按钮 disable 的判断逻辑 |

fix(dop): fix button disable judgment logic

---

shell/app/common/components/user-info/index.tsx
shell/app/config-page/components/table/v2/utils.tsx
shell/app/modules/application/pages/repo/common.tsx
shell/app/modules/application/pages/repo/components/repo-mr-table.tsx
shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/project/common/components/issue/issue-activities.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/pages/plan-detail/common-comp.tsx
shell/app/modules/project/pages/test-manage/case/case-drawer/case-meta.tsx
shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
shell/app/modules/runtime/pages/overview/components/activity.tsx

fix user avatar
Fixes #
- [【集成环境】人员头像替换问题汇总#前端部分](https://erda.cloud/erda/dop/projects/387/issues/all?id=283400&iterationID=1090&type=BUG)
❎ No
| 🇺🇸 English | fix user avatar |
| 🇨🇳 中文    | 修复用户头像 |

fix(dop): fix user avatar

---

shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx

Project pipeline table add yml file.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMDkwLDExMTUsMTA2OV0sImFzc2lnbmVlIjpbIjU1IiwiMTAwMTIwNSIsIjkyIiwiMTAwMDU2MCIsIjEwMDEyNjEiLCIxMDAxMDczIl19&id=285636&iterationID=1090&pId=0&type=REQUIREMENT)
| 🇺🇸 English |  Project pipeline table add yml file.  |
| 🇨🇳 中文    |  项目流水线表格增加yml文件信息。 |
❎ No

feat(dop): project pipeline table add yml file

---

shell/app/common/components/user-info/index.tsx
shell/app/config-page/components/table/v2/utils.tsx
shell/app/modules/application/pages/repo/common.tsx
shell/app/modules/application/pages/repo/components/repo-mr-table.tsx
shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/project/common/components/issue/issue-activities.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/pages/plan-detail/common-comp.tsx
shell/app/modules/project/pages/test-manage/case/case-drawer/case-meta.tsx
shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
shell/app/modules/runtime/pages/overview/components/activity.tsx

* fix(dop): fix user avatar
* feat(dop): remove console
(cherry picked from commit 8a9cbca62bd3db977f8b648c4b9841e12bc4f55a)
Fixes #
❎ No
| 🇺🇸 English | fix user avatar |
| 🇨🇳 中文    | 修复用户头像 |
❎ No

fix(dop): fix user avatar (#2995)

---

shell/app/config-page/components/date-picker/date-picker.tsx

fix: fix date picker value update error
Fixes #
❎ No
| 🇺🇸 English |    fix: fix date picker value update error          |
| 🇨🇳 中文    |    fix: 修复datepicker组件值更新错误          |

fix: fix date picker value update error

---

shell/app/charts/utils/formatter.js

fix time format
Fixes #
❎ No
| 🇺🇸 English |  fix time format  |
| 🇨🇳 中文    | 修复时间格式化问题  |

fix(msp): fix time format

---

shell/app/modules/project/pages/release/components/release-select.tsx

Fix create release style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=287595&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG)
->
| 🇺🇸 English | Fixed style issues when selecting application artifacts for new project artifacts.|
| 🇨🇳 中文    |  修复了新增项目制品选择应用制品时的样式问题。  |
❎ No

fix(dop): create release style bug

---

shell/app/modules/project/pages/release/components/form.tsx

Fix create release application filter bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=287596&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
❎ No
| 🇺🇸 English |  Fixed a bug that filtered by application when creating project artifacts.  |
| 🇨🇳 中文    |  修复了创建项目制品时根据应用筛选时的bug。 |
release/2.0

fix(dop): create release application filter bug

---

shell/app/modules/application/pages/build-detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/project/common/components/pipeline-manage/run-detail/pipeline-chart/run-case-node.tsx
shell/app/yml-chart/chart/yml-chart.tsx

fixed  bug that pipeline horizontal scroll when there are popover
- [【线上问题】【流水线】流水线有弹框的时候左右滚动](https://erda.cloud/erda/dop/projects/387/issues/all?id=287039&iterationID=1115&type=BUG)
❎ No
| 🇺🇸 English | fixed  bug that pipeline horizontal scroll when there are popover |
| 🇨🇳 中文    | 修复了有弹框时，流水线左右滚动的问题 |
release/2.0

fix(dop): fix pipeline popover

---

shell/app/modules/project/common/components/issue/subscribers-selector.tsx

FIx subscribers selector endless loop bug.
Fixes #
❎ No
| 🇺🇸 English |  Fixed an issue with the human selector loop.  |
| 🇨🇳 中文    | 修复了关注人选择器死循环的问题。 |
release/2.0

fix(dop): subscribers selector endless loop bug

---

shell/app/modules/cmp/common/cluster-terminal/xterm-binary.tsx
shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx

fix: fix k8s terminal line error
Fixes #
❎ No
| 🇺🇸 English |     fix: fix k8s terminal line  error         |
| 🇨🇳 中文    |     fix: 修复k8s控制台行显示错误       |
release/2.0

fix: fix k8s terminal line error

---

shell/app/modules/org/common/audit-templates.json

feat: add audit template for releaseRule
Fixes #
❎ No
| 🇺🇸 English | feat: add audit for releaseRule |
| 🇨🇳 中文    | 添加制品规则审计模板 |
❎ No

feat: add audit tamplate for releaseRule

---

shell/app/common/utils/go-to.tsx
shell/app/interface/global.d.ts
shell/app/modules/application/router.ts
shell/app/modules/application/tabs.tsx
shell/app/modules/project/pages/deploy/index.tsx
shell/app/modules/project/services/deploy.ts
shell/app/modules/project/tabs.tsx
shell/app/modules/runtime/stores/runtime.ts

feat: add app deploy
Fixes #
| 🇺🇸 English |   feat: add app deploy           |
| 🇨🇳 中文    |    feat: 新增应用部署          |
❎ No

feat: add app deploy

---

shell/app/modules/project/pages/deploy/index.tsx

fix: fix app deploy scenario key
- [x ] Display normally when some data is empty or null
Fixes #
❎ No
| 🇺🇸 English |     fix: fix app deploy scenario key         |
| 🇨🇳 中文    |      fix: 修复应用部署的场景key       |
❎ No

fix: fix app deploy scenario key

---

shell/app/modules/project/pages/deploy/index.tsx

fix: fix app deploy filter style
Fixes #
❎ No
| 🇺🇸 English |      fix: fix app deploy filter style        |
| 🇨🇳 中文    |     fix: 修复应用部署filter样式         |
release/2.0

fix: fix app deploy filter style

---

shell/app/modules/project/pages/deploy/index.tsx

fix: fix duplicate appId in deploy
Fixes #
❎ No
| 🇺🇸 English |    fix: fix duplicate appId in deploy          |
| 🇨🇳 中文    |    fix: 修复部署页面上appId命名重复          |
release/2.0

fix: fix duplicate appId in deploy

---

shell/app/config-page/components/base-list/base-list.tsx

fix: fix base list state update
Fixes #
❎ No
| 🇺🇸 English | fix: fix base list state update             |
| 🇨🇳 中文    |  fix: base list组件state变化修改           |
release/2.0

fix: fix base list state update

---

shell/app/common/components/erda-icon/index.tsx
shell/app/views/index.ejs
shell/index.html

Application list mr icon optimization.
Fixes #
->
| 🇺🇸 English |  Application list Mr Request number icon replaced.   |
| 🇨🇳 中文    | 应用列表mr请求数图标更换。 |
release/2.0

fix(dop): application list mr icon optimization

---

shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx

Fix project pipeline running number display bug after batch run
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=289460&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1090&type=BUG)
❎ No
| 🇺🇸 English |  Fixed a bug where the number of pipeline applications in operation was not updated during batch execution.  |
| 🇨🇳 中文    |   修复了项目流水线，批量执行时，应用的运行中的流水线个数没有更新的bug。    |
release/2.0

fix(dop): project pipeline running number display bug after batch run

---

shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx

fix: fix app pipeline refresh error.
Fixes #
❎ No
| 🇺🇸 English |   fix: fix app pipeline refresh error           |
| 🇨🇳 中文    |    fix: 修复应用流水线刷新错误          |
release/2.0

fix: fix app pipeline refresh error

---

shell/app/common/components/load-more-selector/index.scss
shell/app/common/components/load-more-selector/index.tsx

update load-more-selector style
Fixes #
- [【升级测试】【告警中心】【通知组管理】新建通知组，添加人员时，滚动条不明显](https://erda.cloud/erda/dop/projects/387/issues/all?id=289463&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MjB9&iterationID=1090&type=BUG)
❎ No
| 🇺🇸 English | update load-more-selector style |
| 🇨🇳 中文    | 调整 LoadMoreSelector 样式 |
❎ No

fix(dop): update load-more-selector style

---

shell/app/org-home/pages/land/index.tsx

fix: fix community add org type
Fixes #
❎ No
| 🇺🇸 English |   fix: fix community add org type           |
| 🇨🇳 中文    |      fix: 社区办添加组织参数修复        |
release/2.0

fix: fix community add org type

---

shell/app/common/components/edit-field/index.tsx
shell/app/common/components/table/interface.ts
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
shell/app/modules/project/common/components/issue/issue-testCase-relation.tsx

update style.
Fixes #
->
| 🇺🇸 English |     fix issue detail style  |
| 🇨🇳 中文    |  修复事项详情样式问题  |
❎ No

fix(dop): update issue detail style

---

shell/app/common/components/load-more-selector/index.scss
shell/app/modules/extra/entry.js

revert load more selector style
Fixes #
❎ No
release/2.0

fix(dop): revert load more selector style

---

shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx

Project pipeline id decoding mode change.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=289875&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
❎ No
| 🇺🇸 English |  Fixed some bug where project level pipelines could not view details.  |
| 🇨🇳 中文    |  修复了一些项目级流水线无法查看详情的bug。 |
❎ No

fix(dop): project pipeline id decoding mode change
