erda-project/erda-ui

- .github/workflows/license-check.yml
- .licenserc.json
- LICENSE
- README.md
Add LICENSE file and LicenseChecker action
> Add LICENSE file and LicenseChecker action

- shell/mf.config.js
> add user store expose

- .gitignore
- cli/bin/erda.js
- cli/lib/build.js
- cli/lib/i18n.js
- cli/lib/setup.js
- cli/lib/util/google-translate.js
- core/webpack.development.js
- setup.js
- shell/bash/login-ssh.sh
- shell/tsconfig.json
- shell/webpack.production.js
- [ x] Feature
1) add items to .gitnore
2) add params of execPath to build cmd in order to execute the js both on local and pipeline
3) use relative path in setup.js
4) remove the useless local-release.js
5) format the code of tsconfig.js
6) add sourceMap to shell/webpack.prodcution.js
Fixes #
- [ x] Yes(screenshot is required)
> feat: modify the build and setup

- core/package-lock.json
- core/package.json
- shell/package-lock.json
- shell/package.json
- update cube-state version to v1.3.0
Fixes #
> chore: update cube-state

- shell/app/config-page/components/api-editor/api-editor.tsx
- shell/app/modules/microService/monitor/browser-insight/pages/script/script-detail.tsx
- shell/app/modules/microService/monitor/mobile-insight/pages/script/script-detail.tsx
- shell/market/pages/download.tsx
> chore: resolve code scaning alerts

- shell/app/config-page/components/api-editor/api-editor.tsx
> fix: fix header is null

- core/src/index.tsx
- shell/app/layout/stores/layout.ts
Fixes # i18n doesn't work in Admin's menu
> feat: admin menu init

- shell/README.md
```text
Fix some minor nits for readme
```
> Fix some minor nits for readme

- cli/bin/erda.js
- cli/lib/launcher.js
- cli/package-lock.json
- cli/package.json
- core/webpack.config.js
- setup.js
- shell/package.json
- core module add file cache config
-  add launch script to manage module processes [PM2及erda launch简介](https://yuque.antfin-inc.com/dice/zs3zid/adgu0p)
Fixes #
> create launch script

- shell/app/org-home/stores/org.tsx
fix request header key org
Fixes #
> fix: fix org header key

- shell/app/modules/project/pages/settings/components/project-info.tsx
> fix: project-info.tsx

- shell/app/App.tsx
- shell/app/common/utils/go-to.tsx
- shell/app/org-home/stores/org.tsx
fix go-to path error
get org before render App to ensure all the api can get the right header
Fixes #
> fix go-to path error

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/dcos/common/custom-label.tsx
- shell/app/modules/dcos/pages/machine-manager/tag-form.tsx
> fix: label regexp change

- shell/app/config-page/components/list/list.tsx
- shell/app/config-page/components/table-group/table-group.tsx
- shell/app/config-page/components/text/text.scss
- shell/app/config-page/config-page.d.ts
- shell/app/config-page/index.tsx
- shell/app/config-page/page-render.tsx
- shell/app/org-home/pages/personal-home.tsx
1. update styles
Fixes #
1. fix loadmore in List and TableGroup
> refactor: :hammer: modify loadmore in List and TableGroup and update style

- shell/app/layout/common/error-page.tsx
- shell/app/layout/locales/en.json
- shell/app/layout/locales/zh.json
- shell/app/layout/pages/page-container/components/menu-head.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/layout/stores/layout.ts
- shell/app/org-home/stores/org.tsx
- shell/tsconfig.json
get deault org when first router is -
fix back to index router path
Fixes #
> get deault org when first router is -

- shell/app/common/constants.ts
official docs changes domain name, it need to update
Fixes #
> feat: update official docs link

- shell/app/config-page/components/list/list.tsx
- shell/app/config-page/components/table-group/table-group.tsx
fix error with concat of null or undefined
Fixes #
> fix: fix concat of null of undefined

- shell/app/App.tsx
- shell/app/org-home/pages/personal-home.tsx
- shell/app/org-home/stores/org.tsx
> fix：fix personal home page route

- cli/lib/i18n.js
- cli/lib/util/i18n-extract.js
- fix i18n script get undefined locale path error, because of missing ns parameter for writeLocale function
Fixes #
> fix i18n script get undefined locale path error

- shell/app/modules/application/pages/settings/components/variable-config-form.tsx
Fixes # fix parameter settings input bug
> fix: parameter settings input bug

- shell/app/modules/apiManagePlatform/services/api-market.ts
fix omission api with org
Fixes #
> fix omission api with org

- shell/app/modules/dataCenter/common/custom-dashboard/custom-dashboard.tsx
- yarn.lock
> fix: custom-dashboard add api auth

- nginx.conf.template
change nginx fdp address to variable
Fixes #
> change nginx fdp address to variable

- shell/app/menus/appCenter.tsx
- shell/app/org-home/stores/org.tsx
fix breadcrumb path error
fix orgName not match route path
Fixes #
> fix breadcrumb path error

- nginx.conf.template
> add missing dollar

- shell/app/modules/dcos/common/custom-label.tsx
Fixes # label regexp second change
> fix: label regexp second change

- shell/app/modules/dcos/common/custom-label.tsx
Fixes # label regexp third change
> fix: label regexp third change

- core/src/index.tsx
- shell/app/common/components/board-grid.tsx
> fix the org problem of board-grid url

- shell/app/modules/application/common/yml-editor/chart/yml-chart-utils.tsx
- shell/app/yml-chart/chart/yml-chart-utils.tsx
Pipeline crash after create in some condition, do some strict check.
Fixes #
> fix: pipeline crash in some condition

- core/src/index.tsx
- shell/app/config-page/components/api-resource/resource.scss
- shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
- shell/webpack.development.js
1) the style problem occurred because of the nusi, so fix it;
2) fix the save problem
Fixes #
> fix the style and save problems of api design

- shell/app/charts/components/svg-icon.js
- shell/app/modules/microService/monitor/error-insight/pages/errors/error-overview.tsx
- shell/app/modules/microService/monitor/monitor-common/components/chartFactory.tsx
- shell/app/modules/microService/monitor/topology/pages/topology-dashboard/index.tsx
- shell/app/modules/microService/monitor/topology/pages/topology/node-item.scss
> fix monitor bugs

- shell/app/modules/dataCenter/pages/cluster-manage/cloud-machine-form-modal.tsx
fix cloud machine form cloud vendor value
Fixes #
> fix cloud machine form cloud vendor value

- shell/app/modules/project/common/components/issue/iteration-select.tsx
before fix, like this :
Fixes #
Because paging was not used, it was removed, resulting in a destructed array with no one-to-one correspondence
> fix: :bug: fix close issue drawer with api error

- shell/app/common/components/key-value-table.tsx
fix that can't add config params in config management
Fixes #
> hotfix: :bug: fix can't add config params in config management

- cli/lib/launcher.js
- core/src/framework/regist-router.tsx
- nginx.conf.template
- shell/mf.config.js
1. add fdp websocket nginx config
2. add pm2 log date display
3. export org store for fdp
4. fix route config frozen issue
Fixes #
> export org store for fdp

- shell/app/config-page/components/api-resource/resource-summary.tsx
the problem occurs because of the modify of markdown yesterday
Fixes #
> fix the setFileds problem of markdown

- shell/app/modules/application/pages/repo/repo-tree.tsx
Fixes # warehouse address change, from server
> warehouse address from server

- shell/package-lock.json
- shell/package.json
Update dashboard configurator version to support the conversion of invalid chart value ​​to 0.
Fixes #
> chore: update dashboard configurator version

- shell/app/common/utils/go-to.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/menus/workBench.tsx
- shell/app/modules/project/types/project.d.ts
- shell/app/modules/workBench/pages/projects/project-list-protocol.tsx
- shell/app/modules/workBench/router.js
> feat: separate public project list as a menu item

- cli/lib/add-license.js
- cli/lib/build.js
- cli/lib/check-license.js
- cli/lib/copy.js
- cli/lib/gen-version.js
- cli/lib/release.js
- cli/lib/setup.js
- cli/lib/util/env.js
> feat: check code up to date when build or release

- core/src/cube.ts
- shell/app/common/__tests__/upload-props.test.tsx
- shell/app/common/components/markdown-editor/index.tsx
> fix notify params missing

- cli/bin/erda.js
- cli/lib/build.js
- cli/lib/i18n.js
- cli/lib/local-icon.js
- cli/lib/release.js
- cli/lib/util/env.js
- shell/package-lock.json
enable build package based on docker image.
Fixes #
> refactor build script to enable build based on docker image

- shell/app/modules/application/pages/pipeline/config-detail/pipeline-editor/case-node-form.tsx
- shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-node-form.tsx
fix pipeline inputstring data dump yaml error
Fixes #
> fix pipeline inputstring data dump yaml error

- shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
- shell/app/modules/project/services/test-case.ts
- shell/app/modules/project/stores/test-case.ts
delete api section in manaual test case
Fixes #
turn into
> delete api section in manaual test case

- shell/app/modules/dcos/common/custom-label.tsx
Fixes # label regex fourth change, delete '/'
> label regex change, delete '/'

- nginx.conf.template
delete useless nginx config
Fixes #
> delete useless nginx config

- shell/app/modules/org/common/config.ts
the propertyType of import source is Select, not Person
Fixes #
> fix: modify the propertyType of import source to Select

- cli/.eslintrc.js
- cli/README.md
- cli/bin/erda.ts
- cli/lib/add-license.ts
- cli/lib/build.ts
- cli/lib/check-license.ts
- cli/lib/copy.ts
- cli/lib/gen-version.ts
- cli/lib/i18n.ts
- cli/lib/launcher.ts
- cli/lib/local-icon.ts
- cli/lib/release.ts
- cli/lib/setup.ts
- cli/lib/util/env.ts
- cli/lib/util/file-walker.ts
- cli/lib/util/google-translate.ts
- cli/lib/util/i18n-extract.ts
- cli/lib/util/log.ts
- cli/package-lock.json
- cli/package.json
- cli/templates/license.ts
- cli/tsconfig.json
convert all cli js to ts
Fixes #
> convert all cli js to ts

- shell/app/org-home/stores/org.tsx
…didn't joined it
go to workbench when the user view the public organization but didn't joined it
Fixes #
> Feature: go to workbench when the user view the public organization but didn't joined it

- shell/app/agent.js
- shell/app/user/stores/_perm-org.ts
* error handler called twice
* all roles except guest can see my publisher menu
Fixes #
> fix: error handler called twice & my publisher menu permission

- shell/app/modules/addonPlatform/pages/common/components/addon-detail-drawer.tsx
fix deployment detail page is not found
Fixes #
modify the params of runtimeDetailRoot from applicationId to appId
> fix: fix deployment detail page is not found

- shell/app/modules/project/services/test-case.ts
fix test case export error
Fixes #
> fix test case export error

- core/src/nusi/fixed-select.tsx
- shell/app/common/components/edit-field.tsx
- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
- shell/app/modules/project/common/components/issue/text-field-input.tsx
- shell/app/modules/project/common/components/issue/time-input.tsx
- shell/app/modules/project/common/components/issue/time-trace.tsx
1：optimized automatic positioning of form check in issue detail 
2：fix ref in fixed select
Fixes #
- [] No
> optimized automatic positioning of form check in issue detail 

- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
> fix: code shorthand

- shell/app/modules/application/pages/repo/components/start-tip.tsx
Fixes # change git address, get address from server
> fix: get git address from server

- shell/app/agent.js
- shell/app/styles/antd-extension.scss
extended pk-table style somehow is overwritted by original style.
other style have to be checked later to add prefix.
Fixes #
> add prefix to pk-table overwrite style

- shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
- shell/app/modules/project/services/test-case.ts
- shell/app/modules/project/stores/test-case.ts
revert api section in test case
Fixes #
> revert api section in test case

- shell/app/modules/dataCenter/pages/log-query/index.tsx
> fix: adjust log query table style

- shell/app/common/utils/go-to.tsx
- shell/app/common/utils/query-string.tsx
- shell/app/modules/application/pages/repo/components/repo-file-container.tsx
- shell/app/modules/application/pages/repo/components/repo-nav.tsx
- shell/app/modules/application/pages/repo/repo-tree.tsx
set pipeline edit mode when click edit pipeline button
Fixes #
> set pipeline edit mode when click edit pipeline button

- shell/app/modules/project/pages/plan-detail/batch-processing/index.tsx
fix all export to batch export test case when not all selected
Fixes #
fix all export to batch export test case when not all selected
This change due to api changes
> Hotfix: add relationID to queryParam, in order to batch export test case when not all selected

- shell/app/modules/application/pages/build-detail/pipeline-log.scss
- shell/app/modules/application/pages/build-detail/pipeline-log.tsx
- shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.scss
- shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
- [] Bugfix
add check detail in pipeline log;
Fixes #
turns to
> add check detail in pipeline log

- shell/app/common/components/markdown-editor/editor.tsx
- shell/app/modules/project/pages/test-manage/case/header/import-file.tsx
> fix some upload problems

- core/src/nusi/index.tsx
- shell/package.json
> fix: update dc

- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
fix [bug](https://erda-org.erda.cloud/workBench/projects/387/issues/all?id=58647&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDMwMCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=436&type=BUG)
Fixes #
> feat: fix error when estimateTime empty

- shell/app/modules/dataCenter/pages/cloud-source/index.tsx
- shell/app/modules/dataCenter/pages/cluster-manage/index.tsx
delete oss storage count
Fixes #
> delete oss storage count

- README.md
Add Dingtalk group QR code.
Fixes #
> Add Dingtalk QR code image to README

- shell/app/modules/microService/monitor/monitor-common/components/chartFactory.tsx
> fix: some chart page loop error

- shell/app/org-home/stores/org.tsx
redirect to orgRoot when auth check failed
Fixes #
> redirect to orgRoot when auth check failed

- shell/app/modules/microService/pages/gateway/containers/api-limits.tsx
- shell/app/modules/org/pages/announcement/index.tsx
1. fix limit type doesn't popup when editing api gateway
2. update published announcement list immediately after pub/stop
Fixes #
> Hotfix/release 1.0

- shell/app/App.tsx
get the organization info first, or will get org is undefined when need org info (like issueStore)
Fixes #
> Hotfix: get import source options when entering issues page

- shell/app/modules/publisher/pages/artifacts/artifacts-form-modal.tsx
- shell/app/modules/publisher/pages/artifacts/artifacts-info.tsx
Closing background image field for not used.
Fixes #
> feat: comment unused mobile artifact bgImage and preview image

- shell/app/modules/project/pages/auto-test/scenes.tsx
add copy in auto test result drawer
Fixes #
> add copy in auto test result drawer

- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
convert '' to 0 when remainingTime is ''
Fixes #
> fix bug that the issue editor can not delete estimateTime

- shell/app/modules/project/pages/test-manage/case/manual-test.tsx
synchronize url query to test case search, because of refresh page and search query shows error;
Fixes #
> synchronize url query to test case search

- shell/app/config-page/components/list/list.spec.d.ts
- shell/app/config-page/components/list/list.tsx
- shell/app/config-page/components/table-group/table-group.scss
- shell/app/config-page/components/table-group/table-group.tsx
- shell/app/config-page/index.tsx
- shell/app/config-page/page-render.tsx
- shell/app/org-home/pages/personal-home.mock.ts
1. fix loadMore in list component
2. update style of tableGroup 
Fixes #
> Hotfix: fix loadmore in list component

- cli/bin/erda.ts
- cli/lib/check-license.ts
filter check-license output
Fixes #
> filter check-license output

- shell/app/App.tsx
> fix: add i18n for moment globally

- shell/app/common/components/members-table.tsx
jump to specific page when user exits application, project or organization
Fixes #
jump to specific page when user exits application, project or organization
> fix: jump to specific page when user exits application, project or organization

- shell/app/modules/project/pages/backlog/iteration-item.tsx
fix iteration duration in backlog
Fixes #
> fix iteration duration in backlog

- shell/app/modules/dataCenter/common/custom-dashboard/custom-dashboard.tsx
- shell/package-lock.json
- shell/package.json
> fix dashboard data url with org

- shell/app/common/components/board-grid.tsx
fix: fix board grid api url
Fixes #
> fix: fix board grid api url

- shell/app/common/components/edit-field.scss
- shell/app/common/components/edit-field.tsx
- shell/app/common/components/markdown-editor/index.tsx
- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
optimize issue detail content
Fixes #
> optimize issue detail content

- shell/app/common/utils/str-num-date.tsx
- shell/app/modules/application/pages/repo/components/repo-mr-table.tsx
- shell/app/modules/project/common/components/issue/issue-activities.tsx
1、fix time fromNow display few seconds after
2、fix comment content center aligned
Fixes #
> fix time fromNow display few seconds after

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/microService/monitor/service-list/pages/anomaly.tsx
- shell/app/modules/microService/monitor/service-list/pages/overview.tsx
- shell/app/modules/microService/monitor/service-list/pages/process.tsx
- shell/app/modules/microService/monitor/service-list/pages/transaction.tsx
- shell/app/modules/microService/monitor/trace-insight/pages/trace-querier/trace-detail.scss
- shell/app/modules/microService/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
> monitor optimization 

- core/package.json
- core/src/nusi/index.tsx
- shell/app/styles/antd-extension.scss
Fixes # upgrade Button\BackTop\Badge\Collapse\Carousel to antd4.x
> refactor: Button\BackTop\Badge\Collapse\Carousel upgrade to antd4.x

- shell/app/common/utils/index.ts
- shell/app/modules/apiManagePlatform/pages/api-market/components/relation.tsx
- shell/app/modules/dataCenter/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
- shell/app/modules/microService/pages/gateway/containers/api.tsx
- shell/app/modules/org/pages/projects/create-project.tsx
- shell/app/modules/project/pages/apps/app-form.tsx
fix catastrophic backtracking regexp.
Fixes #
> fix catastrophic backtracking regexp

- shell/app/modules/microService/monitor/service-list/pages/transaction.tsx
add trace time range into effect
Fixes #
> trace time range

- shell/app/modules/application/pages/repo/components/compare-detail.tsx
fix: file diff render list error
Fixes #
> fix: file diff render list error

- shell/app/common/components/member-selector.tsx
- shell/app/common/services/index.ts
- shell/app/locales/en.json
- shell/app/locales/zh.json
feat: update uc user api to new api: api/user/aciton/search
Fixes #
- [] Yes(screenshot is required)
> feat: update uc user api

- shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
show tips when title is too long
Fixes #
> show tips when title is too long

- core/package-lock.json
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/views/index.ejs
- shell/app/views/skeleton.html
> feat: replace the icon of switching language

- shell/app/common/components/json-checker.tsx
- shell/app/common/components/runtime/simple-log-search.jsx
- shell/app/config-page/components/api-editor/api-editor.tsx
- shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
- shell/app/modules/project/pages/test-manage/case/manual-test.tsx
- shell/app/modules/runtime/pages/overview/components/index.tsx
Fixes # Button icon bug result from upgrade to antd4.x
> fix: Button icon bug result from upgrade to antd4.x

- shell/app/common/components/input-select/input-select.tsx
- shell/app/modules/application/pages/pipeline/config.tsx
- shell/app/modules/application/pages/pipeline/pipeline-detail.tsx
- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
- shell/app/modules/application/pages/pipeline/run-detail/index.tsx
feat: update pipeline auth
feat: add input select tooltip in option item
Fixes #
> feat: update pipeline auth

- README.md
complete the content of quick start of README
Fixes #
> feat: complete the content of quick start in README

- .github/workflows/codecov.yml
- core/package-lock.json
- shell/app/common/__tests__/components/board-grid.test.tsx
- shell/app/common/__tests__/components/confirm-delete.test.tsx
- shell/app/common/__tests__/components/crud-table.test.tsx
- shell/app/common/__tests__/components/delete-confirm.test.tsx
- shell/app/common/__tests__/components/lazy-render.test.tsx
- shell/app/common/__tests__/components/load-more.test.tsx
- shell/app/common/__tests__/components/paging-table.test.tsx
- shell/app/common/index.ts
- shell/jest.config.js
add case for common comp
upgrade jest config
Fixes #
> add case for common comp

- shell/app/common/__tests__/components/board-grid.test.tsx
upgrade board-grid case
Fixes #
> upgrade board-grid case

- shell/app/config-page/components/list/list.tsx
fix that turn the page of application list
Fixes #
it's 'list' instead of  'combineList' to map when it is pagination mode.
> Hotfix: Fixed app list paging issues

- shell/app/modules/project/pages/settings/components/project-cluster.tsx
- shell/app/modules/project/pages/settings/components/project-rollback.tsx
fix project unset cluster error
Fixes #
> fix: fix project unset cluster error

- shell/app/views/index.ejs
> fix: reset link rel of iconfont to stylesheet

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
show tip when service inner address not exist
Fixes #
> feat: show tip when service inner address not exist

- core/src/i18n.ts
- core/src/nusi/index.tsx
- core/webpack.config.js
- core/webpack_ts.loader.js
- shell/app/App.tsx
- shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
- shell/app/styles/antd-extension.scss
- shell/package-lock.json
- shell/package.json
Fixes # upgrade message \ Menu \ Modal \ notification \ Popconfirm \ Popover \ Rate to antd4.x antd upgrade dashboard-configurator to 1.2.4
> refactor: upgrade components to antd4.x and upgrade dc

- shell/app/layout/pages/page-container/components/sub-sidebar.tsx
FDP will adjust the menu to multiple levels
Fixes #
> Adjust the menu component to support multi-level menus

- shell/app/common/utils/marked.ts
fix: set link jumpout in markdown
Fixes #
> fix: set link jumpout in markdown

- Dockerfile
upgrade erda-nginx version to 1.0, make it work for mac m1.
Fixes #
> upgrade erda-nginx version to 1.0

- .npmrc
> fix pnpm problem

- shell/app/modules/project/pages/auto-test/scenes.tsx
fix: scenes execute result error
Fixes #
> fix: scenes execute result error

- shell/app/modules/microService/monitor/service-list/pages/process.tsx
process analysis set default instance
Fixes #
> process analysis set default instance

- shell/package.json
- shell/tsconfig.json
> fix: remove market-build in shell

- dice.yml
to deploy ui on erda pipeline, these are necessary envs
Fixes #
@daskyrk
> feature: add envs to dice.yml

- setup.js
> fix: use npm to install global package instead of pnpm

- shell/app/modules/dataCenter/common/custom-alarm/index.tsx
clear the grouping rules when modifying indicators
Fixes #
> clear the grouping rules when modifying indicators

- README.md
- shell/app/modules/microService/monitor/service-list/pages/process.tsx
- shell/app/modules/microService/monitor/service-list/pages/service-list-dashboard.tsx
- shell/app/modules/microService/monitor/trace-insight/pages/trace-querier/trace-search.tsx
- shell/app/modules/microService/types/monitor.d.ts
- shell/app/modules/project/pages/dashboard/index.tsx
- shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
fix service analysis  duplicate requests
Fixes #
> monitor bug fix

- core/package.json
- pnpm-lock.yaml
- shell/package.json
Fix BeforeEffect hook not called when effect defined as no argument.
Fixes #
> chore: update cube-state version

- shell/app/modules/microService/monitor/topology/pages/topology-dashboard/index.tsx
goto detail page with query time
Fixes #
> Hotfix: goto detail page with query time

- shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
> reset case tree fix

- dice.yml
- erda.yml
- replace dice.yml with erda.yml
- erda.yml is the deployment file for ui on ci/cd
Fixes #
> replace dice.yml with erda.yml

- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
put responsible person behind the assignee in bug issue
Fixes #
> feat: [optimize interaction] put responsible person behind the assignee in bug issue

- shell/app/common/components/monitor/components/timeRangeSelector.tsx
rendering charts with initial time in monitor
Fixes #
> Hotfix: rendering chart with initial time in monitor

- core/src/nusi/fixed-select.tsx
Fixes # Select upgrade to Antd4.x
> refactor: Select upgrade to Antd4.x

- shell/app/modules/project/router.js
fix: fix backlog to issue query error
Fixes #
> fix: fix backlog to issue query error

- erda.yml
> feature: fix typo

- shell/app/modules/microService/monitor/error-insight/pages/errors/error-overview.tsx
- shell/app/modules/microService/monitor/trace-insight/pages/trace-querier/trace-search.tsx
- shell/app/modules/microService/types/monitor.d.ts
remove tag.error & pagination by fe
Fixes #
> remove tag.error & pagination by fe

- shell/app/common/components/edit-field.scss
- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
- shell/app/modules/project/common/components/issue/issue-drawer.tsx
modify style of issue drawer
1. remove description label 
2. keep the width of issue drawer to 70%
3. ensure that this part can be displayed in the  a certain proportion
Fixes #
> style: modify style of issue drawer

- shell/mf.config.js
> export error page

- shell/app/layout/pages/page-container/components/menu-head.scss
> fix: fix icon size in sidebar of fdp pages

- shell/package.json
add build market command
Fixes #
> add build market command

- shell/app/modules/project/pages/iteration/iteration-modal.tsx
adjust default size to 8 rows  of  iteration-goal textarea
Fixes #
> style: adjust default size to 8 rows  of  iteration-goal textarea

- shell/app/common/components/input-select/input-select.tsx
- shell/app/config-page/components/action-form.tsx
- shell/app/configForm/nusi-form/form-items/index.tsx
- shell/app/configForm/nusi-form/form-items/input-select.scss
- shell/app/configForm/nusi-form/form-items/input-select.tsx
- shell/app/configForm/nusi-form/form.tsx
- shell/app/yml-chart/common/action-config-form.tsx
feat: add input-select in configForm, prepare for new action
Fixes #
> feat: add input-select in configForm, prepare for new action

- Dockerfile
pipeline deploy step failed due to COPY path is incorrect
Fixes #
> fix(common): docker file wrong path change

- pnpm-lock.yaml
- shell/app/charts/utils/line-option.ts
- shell/app/charts/utils/regist.tsx
- shell/app/common/components/board-grid.tsx
- shell/app/common/services/dashboard.ts
- shell/app/modules/dataCenter/common/custom-dashboard/custom-dashboard.tsx
- shell/app/modules/dataCenter/pages/cloud-source/index.tsx
- shell/app/modules/dataCenter/pages/cluster-manage/cluster-state.tsx
- shell/app/modules/microService/monitor/service-list/pages/index.tsx
- shell/app/modules/microService/monitor/service-list/pages/service-list-dashboard.tsx
- shell/app/modules/microService/monitor/service-list/pages/transaction.tsx
- shell/app/modules/microService/monitor/topology/pages/topology-dashboard/index.tsx
- shell/jest.config.js
- shell/jest.config.local.js
- shell/package.json
- shell/webpack.config.js
> replace @terminus/dashboard-configurator with @erda-ui/dashboard-configurator

- shell/app/modules/microService/monitor/service-list/pages/process.tsx
- shell/app/modules/microService/monitor/topology/pages/topology/node-item.scss
- shell/app/modules/microService/types/topology-service-analyze.d.ts
> show ip in process filter

- shell/app/modules/dataCenter/pages/log-query/index.scss
- shell/app/modules/dataCenter/pages/log-query/index.tsx
- shell/app/modules/project/pages/test-manage/case/columns/index.tsx
- shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
* enlarge case title width
* show log content directly
Fixes #
> feat: update log analysis and use case table content column style

- core/webpack.production.js
- cspell.json
- scheduler/src/index.js
- scheduler/src/util.js
1. scheduler add fdp-app proxy
2. prettier format scheduler
Fixes #
> scheduler add fdp-app proxy

- shell/app/modules/dataCenter/pages/log-query/index.scss
- shell/app/modules/dataCenter/pages/log-query/index.tsx
fix log analysis content column style.
Fixes #
> fix: log analysis content column style in master

- shell/app/modules/dataCenter/pages/log-query/index.scss
- shell/app/modules/dataCenter/pages/log-query/index.tsx
log analysis content column should show as multiple line.
expand operation column width.
Fixes #
> fix: log analysis content column style

- shell/app/config-page/components/form-modal/form-modal.tsx
- shell/app/config-page/components/text/text.spec.d.ts
- shell/app/config-page/components/text/text.tsx
- shell/app/configForm/nusi-form/form-items/upload.tsx
- shell/app/org-home/pages/personal-home.mock.ts
feat: add create org Modal
feat: add create org Modal
Fixes #
> add create org Modal

- cli/lib/i18n.ts
- cli/lib/init.ts
- cli/lib/util/env.ts
- cli/package.json
- scheduler/package.json
1. cli init add root path check alert
2. remove .erda/config dependency in i18n script
Fixes #
> cli update

- shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
- fix bug that the testSet cannot be expanded in Firefox
- fix endless loop when menu child empty
Fixes #
> testCase bug fix

- shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
fix: test case table scroll width
Fixes #
> fix: test case table scroll width

- shell/app/modules/application/stores/application.tsx
- shell/app/modules/project/stores/project.tsx
fix: fix no auth app header name error
Fixes #
> fix: fix no auth app header name error

- shell/app/configForm/nusi-form/form-items/upload.tsx
use 'supportFormat' to control 'accept' of Upload component
Fixes #
> fix: use 'supportFormat' to control 'accept' of Upload component

- shell/app/modules/project/stores/project.tsx
fix: fix breadcrumb info error
Fixes #
> fix: fix breadcrumb info error

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/application/pages/deploy/deploy.tsx
- shell/app/modules/application/pages/deploy/runtime-box.tsx
feat: add fake runtime display
Fixes #
> feat: add fake runtime display

- shell/app/common/components/edit-field.scss
- shell/app/modules/project/common/components/issue/edit-issue-drawer.scss
- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
- shell/app/styles/antd-extension.scss
Fixes # fix Tabs and Select style bug
> Hotfix/Tabs and Select style bug

- erda.yml
Move service scope variable to environment variable to let it can be overwrite by app setting config.
Fixes #
> chore: update erda.yml

- shell/app/modules/project/stores/resource.ts
restore CPU chart in resource summary
Fixes #
> feat: restore cpu chart in resource summary

- shell/app/config-page/components/form-modal/form-modal.tsx
- shell/app/config-page/components/text/text.spec.d.ts
- shell/app/config-page/components/text/text.tsx
- shell/app/configForm/nusi-form/form-items/upload.tsx
- shell/app/org-home/pages/personal-home.mock.ts
cherry-pick [pr#328](https://github.com/erda-project/erda-ui/pull/328) & [pr#343](https://github.com/erda-project/erda-ui/pull/343)
Fixes #
> cherry-pick pr

- pnpm-lock.yaml
- shell/app/App.tsx
- shell/app/interface/global.d.ts
- shell/app/modules/dataCenter/pages/cloud-source/index.tsx
- shell/package.json
- shell/webpack.config.js
dashboard-configurator is packaged and imported after compilation
Fixes #
> Chore: upgrade dashboard

- shell/app/layout/common/error-page.tsx
- shell/app/layout/pages/page-container/page-container.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/org-home/types/org.d.ts
> hide dataCenter for free users

- pnpm-lock.yaml
- shell/app/common/__tests__/components/edit-list/edit-list.test.tsx
- shell/app/common/__tests__/components/key-value-textarea.test.tsx
- shell/app/common/__tests__/utils/str-num-date.test.tsx
- shell/app/common/components/board-grid.tsx
- shell/app/common/services/dashboard.ts
- shell/app/modules/dataCenter/pages/cluster-manage/cluster-state.tsx
- shell/app/modules/microService/monitor/service-list/pages/index.tsx
- shell/app/modules/microService/monitor/service-list/pages/service-list-dashboard.tsx
- shell/app/modules/microService/monitor/service-list/pages/transaction.tsx
- shell/app/modules/microService/monitor/topology/pages/topology-dashboard/index.tsx
- shell/package.json
dashboard-configurator export .ts file  and erda-ui update the way of import DC, like import CubeState 
Fixes #
> chore: update the way of import DC

- shell/app/layout/pages/page-container/components/header.tsx
- shell/app/modules/application/common/app-selector.tsx
- shell/app/modules/project/common/components/project-selector.tsx
display complete name when hovering it
Fixes #
> fix: display complete name when hover it

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/application/common/app-list-protocol.tsx
- shell/app/modules/project/stores/project.tsx
- shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
- shell/app/modules/runtime/pages/overview/components/service-card.tsx
- shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
- shell/app/modules/runtime/pages/overview/containers/index.tsx
- shell/app/modules/runtime/stores/runtime.ts
- shell/app/modules/runtime/stores/service.ts
feat: update runtime service config directly
Fixes #
> feat: update runtime service config directly

- shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
- shell/app/modules/runtime/types/service.d.ts
fix: fix service config update data
Fixes #
> fix: fix service config update data

- shell/app/layout/common/error-page.tsx
- shell/app/layout/pages/page-container/page-container.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/org-home/types/org.d.ts
> pick free user tips (#362)

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/application/common/app-list-protocol.tsx
- shell/app/modules/application/stores/application.tsx
- shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
- shell/app/modules/project/stores/project.tsx
- shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
- shell/app/modules/runtime/pages/overview/components/service-card.tsx
- shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
- shell/app/modules/runtime/pages/overview/containers/index.tsx
- shell/app/modules/runtime/stores/runtime.ts
- shell/app/modules/runtime/stores/service.ts
- shell/app/modules/runtime/types/service.d.ts
feat: pick runtime config from 1.0
Fixes #
> feat: pick runtime config from 1.0

- pnpm-lock.yaml
- shell/package.json
1. modify 'justify-content: **start**'/'align-items: **start**'  to 'flex-start'
2. add tip to DcIcon
Fixes #
> feat: upgrade dashboard-configuration

- core/src/nusi/fixed-select.tsx
Fixes # bugs caused by Select upgrade to antd4.x
> fix: bugs caused by Select upgrade to antd4.x

- shell/app/modules/apiManagePlatform/pages/api-market/design/index.scss
- shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
**Before:**
**Current:**
Fixes #
> style: adjust the position of dataType panel in API design

- shell/app/common/utils/str-num-date.tsx
Fixes # orgs list international bug
> fix: orgs list international bug

- shell/app/layout/pages/page-container/components/sub-sidebar.tsx
> fix(common): fix menu active key bug

- shell/app/locales/en.json
- shell/app/locales/zh.json
fix: fix runtime config tip
Fixes #
> fix: fix runtime config tip

- shell/app/common/components/edit-list/edit-list.tsx
> fix(release1.0): add edit-list select options title

- pnpm-lock.yaml
- shell/app/modules/application/pages/repo/components/file-diff.tsx
- shell/package.json
add requestIdleCallback polyfill to support safari
Fixes #
> fix(dop): add requestIdleCallback polyfill to support safari

- shell/app/modules/application/pages/repo/components/file-diff.tsx
- shell/app/modules/application/stores/repo.ts
pick fix repo PR diff file cannot expand issue
Fixes #
> pick:fix repo PR diff file cannot expand issue

- shell/app/modules/application/pages/repo/components/file-diff.tsx
- shell/app/modules/application/stores/repo.ts
- shell/app/modules/application/types/repo.d.ts
fix repo PR diff file cannot expand issue
Fixes #
> fix(dop): fix repo PR diff file cannot expand issue

- shell/app/modules/project/pages/test-manage/case/case-drawer/related-bugs.tsx
> add placeholder in MemberSelector of related bugs From

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
update cpu min value / update form tip
Fixes #
> fix(release1.0): update cpu min value / update form tip

- shell/app/modules/application/pages/repo/repo-tree.tsx
> hidden token and userName when token is empty

- shell/app/common/components/add-member-modal.tsx
- shell/app/common/components/members-table.tsx
- shell/app/modules/project/pages/settings/components/project-settings.tsx
add hasConfigAppAuth to MembersTable in project scope
Fixes #
> refactor: add hasConfigAppAuth to MembersTable in project scope

- shell/app/common/components/edit-list/edit-list.tsx
- shell/app/config-page/components/issue-kanban.tsx
- shell/app/configForm/nusi-form/form-items/select.tsx
fix: compatibal select with antd 4
Fixes #
> fix: compatibal select with antd 4

- shell/app/modules/project/pages/backlog/backlog.scss
- shell/app/modules/project/pages/backlog/backlog.tsx
- shell/app/modules/project/pages/backlog/issue-item.scss
- shell/app/modules/project/pages/backlog/issue-item.tsx
- shell/app/modules/project/stores/iteration.ts
change LoadMore to Pagination in backlog
Fixes #
> feat: change LoadMore to Pagination in backlog

- shell/app/modules/application/pages/repo/repo-tree.tsx
> pick  hidden token and userName when token is empty (#396)

- erda.yml
- shell/app/layout/pages/page-container/components/sidebar.tsx
to avoid UC_PUBLIC_URL is null or ''
Fixes #
> fix: add UC_PUBLIC_URL in erda.yml

- shell/app/common/__tests__/components/image-upload.test.tsx
- shell/app/common/__tests__/components/tree/tree.test.tsx
- shell/app/common/__tests__/components/user-info.test.tsx
- shell/app/common/__tests__/utils/api-creator.test.tsx
- shell/app/common/__tests__/utils/axios-config.test.tsx
- shell/app/common/__tests__/utils/go-to.test.tsx
- shell/app/common/__tests__/utils/index.test.tsx
- shell/app/common/__tests__/utils/query-string.test.tsx
- shell/app/common/components/image-upload.tsx
- shell/app/common/utils/index.ts
- shell/test/setupJest.ts
test(common): add test case for common comp
Fixes #
> add test case for common comp

- shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
fix: fix vip addr incomplete
Fixes #
> fix(release1.0): fix vip addr incomplete

- .cz-config.js
- .eslintrc.js
- cli/bin/erda.ts
- cli/lib/build.ts
- cli/lib/init.ts
- cli/lib/util/env.ts
- cli/package.json
- cspell.json
- erda.yml
- nginx.conf.template
- pnpm-lock.yaml
- scheduler/src/index.js
- shell/app/common/utils/go-to.tsx
- shell/app/common/utils/index.ts
- shell/app/interface/global.d.ts
- shell/app/layout/common/error-page.tsx
- shell/app/layout/pages/page-container/components/menu-head.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/layout/stores/layout.ts
- shell/app/menus/appCenter.tsx
- shell/app/menus/util.ts
- shell/app/modules/edge/pages/application/index.tsx
- shell/app/modules/project/pages/settings/components/project-info.tsx
- shell/app/org-home/stores/org.tsx
- shell/app/views/index.ejs
- shell/webpack.config.js
> feat(common): remove fdp

- nginx.conf.template
- shell/app/config-page/components/issue-kanban.tsx
1、fix nginx redirect from https to http; dop redirect get 404;
2、fix kanban loadMore logic;
Fixes #
> hotfix: nginx config / kanban loadMore

- shell/app/modules/application/pages/pipeline/run-detail/config.tsx
- shell/app/modules/application/stores/build.ts
fix: fix pipeline task info error
Fixes #
> fix: update pipeline when single task is final status

- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/modules/org/pages/setting/org-info.tsx
- shell/app/user/stores/_perm-project.ts
> cherry-pick upgrade free user‘s permission  form (#411)

- shell/app/modules/application/stores/repo.ts
there is not a file path' in API in the code repository
Fixes #
> fix: there is not a file path' in api in code repo

- core/src/service/api-creator.ts
Export some interface for external module to use it.
Fixes #
> feat: export some interface for outer use

- pnpm-lock.yaml
- shell/package.json
1. Display multi-dimensions multi values in the chart
2. Update field name
3. Make the string of tooltip in the chart  longer 
Fixes #
> feat: display multi-dimensions multi-values

- core/src/nusi/index.tsx
- shell/app/common/components/form-modal.tsx
- shell/app/common/components/load-more-selector.tsx
- shell/app/modules/application/pages/repo/repo-tree.tsx
- shell/app/modules/cmp/common/custom-alarm/index.tsx
- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
- shell/app/modules/cmp/pages/cluster-manage/cloud-machine-form-modal.tsx
- shell/app/modules/cmp/pages/middleware-dashboard/scale-modal.tsx
- shell/app/modules/cmp/pages/tasks/task-list.tsx
- shell/app/styles/antd-extension.scss
Fixes # bugs caused by Form upgrade and some other style bugs
> fix: bugs caused by Form upgrade and some other style bugs

- shell/app/config-page/components/table-group/table-group.tsx
- shell/app/config-page/components/table/table.tsx
- shell/app/config-page/components/text/text.spec.d.ts
- shell/app/config-page/debug.tsx
- shell/app/config-page/index.tsx
- shell/app/config-page/mock/index.tsx
- shell/app/modules/dop/router.js
- shell/webpack.config.js
feat: add proxy api in config page debug page
Fixes #
> feat: add proxy api in config page debug page

- shell/app/common/components/load-more-selector.scss
- shell/app/common/components/load-more-selector.tsx
- shell/app/locales/zh.json
- shell/app/modules/application/pages/release/release-list.tsx
fix: clear branch info when app clear
Fixes #
> fix: clear branch info when app clear

- shell/webpack.config.js
> fix: add log

- shell/webpack.config.js
Feature/zxj fix UI env key
Fixes #
> fix:  fix UI env key

- core/package.json
- pnpm-lock.yaml
- shell/package.json
1. display normal content when xAxis is not time in the bar chart 
before:
now:
2.add round_float to latest value
3.cascader supporting both upper and lower case
before:
now:
Fixes #
> feat: upgrade dashboard to v.1.0.22

- shell/app/config-page/components/table/table.scss
- shell/app/config-page/components/table/table.tsx
- shell/app/locales/zh.json
- shell/app/modules/application/common/components/deployments-field.tsx
- shell/app/modules/application/common/components/edit-service.tsx
- shell/app/modules/application/common/components/resource-field.tsx
- shell/app/modules/publisher/pages/artifacts/artifacts-form-modals.tsx
- shell/app/styles/antd-extension.scss
Fixes # bugs caused by Form and Collapse upgrade
> fix: bugs caused by Form and Collapse upgrade

- README.md
- package.json
> docs: update README

- shell/app/common/types/route.d.ts
- shell/app/layout/pages/page-container/components/header.tsx
refactor header & fix warning below https://stackoverflow.com/questions/62336340/cannot-update-a-component-while-rendering-a-different-component-warning
Fixes #
> feat(common): refact header to avoid react warning

- shell/app/modules/org/pages/projects/create-project.tsx
- shell/app/modules/project/pages/apps/app-form.tsx
- shell/app/modules/project/pages/settings/components/project-rollback.tsx
- shell/app/yml-chart/common/pipeline-node-drawer.tsx
> fix: fix form key

- shell/app/layout/common/error-page.tsx
- shell/app/layout/locales/en.json
- shell/app/layout/locales/zh.json
- shell/app/user/stores/permission.ts
jump to app list instead of DevOps page when the user has the project Auth but doesn't have the app auth
Fixes #
> fix: jump to app list instead of DevOps page

- README.md
- shell/app/modules/application/pages/repo/components/branch-select.tsx
- shell/app/modules/application/pages/repo/components/repo-editor.tsx
- shell/app/modules/application/pages/repo/components/source-target-select.scss
- shell/app/modules/application/pages/repo/mr-detail.scss
- shell/app/modules/application/pages/repo/repo-tree.tsx
Form value not update by old style.
Fixes #
> fix: form item value not update

- core/package.json
- pnpm-lock.yaml
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/modules/application/pages/release/release-list.tsx
- shell/app/modules/cmp/pages/networks/common/components/cidr-input.tsx
1、fix Form.Item children wrap by Tooltip
2、fix appCenter key error
3、update cube state version
4、fix normal application release branch filter
Fixes #
> fix: fix Form.Item children wrap

- shell/app/modules/cmp/pages/alarm-analyze/index.tsx
> fix(cmp): fix alarm chart layout

- shell/app/charts/components/monitor-chart-new.jsx
- shell/app/modules/msp/monitor/monitor-common/components/resource-usage/config.ts
> Hotfix: display percentage normally

- README.md
- shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
- shell/app/modules/cmp/pages/alarm-report/index.tsx
- shell/app/modules/msp/pages/gateway/containers/api-package-create.tsx
* Notify group create form
* Gateway api creato form
Fixes #
> Fix: some form not switch when field change

- shell/app/modules/project/pages/settings/components/project-cluster.tsx
- shell/app/modules/project/pages/settings/components/project-rollback.tsx
fix: fix form key error
Fixes #
> fix: fix form key error

- shell/app/modules/cmp/common/alarm-strategy/index.tsx
- shell/app/modules/project/pages/third-service/components/third-addon-form.tsx
1、fix alaram strtegy table column data not found
2、fix addon form error
Fixes #
> fix: fix alaram strategy table

- pnpm-lock.yaml
- shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
> fix the copy icon error in runtime page

- shell/app/config-page/components/dropdown-select/dropdown-select.tsx
1. fix that dropdown will close when clicking the input box
2. fix that search problem like this：
Fixes #
> Hotfix: search org in dropdown

- shell/app/modules/ecp/pages/resource/machine-manage.tsx
> fix: breadcrumb jump error

- shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
Fixes #
[Erda Cloud issue link](https://terminus-org.erda.cloud/erda/workBench/projects/387/issues/bug?id=71154&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&type=bug)
> show case whole dirName

- shell/app/modules/application/pages/repo/repo-commit.tsx
- shell/app/modules/application/pages/repo/repo-tag.tsx
> fix: repo commits bugs

- shell/app/common/components/log/log-roller.scss
- shell/app/modules/runtime/pages/overview/components/domain-modal.scss
- shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
> fix: runtime style bugs

- shell/app/common/components/members-table.tsx
- shell/app/common/utils/index.ts
- shell/app/modules/application/common/yml-editor/pipeline-editor.tsx
- shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx
- shell/app/modules/application/pages/repo/components/repo-editor.tsx
- shell/app/modules/application/pages/settings/app-settings.tsx
- shell/app/yml-chart/pipeline-editor.tsx
fix: fix yaml error tip
Fixes #
> fix: fix yaml error tip

- shell/app/modules/application/pages/repo/repo-commit.tsx
don't get commit list when no branch
Fixes #
> Hotfix: don't get commit list when no branch

- shell/app/modules/org/pages/safety/index.tsx
Fixes #  audit log DateRangePicker width
> fix: audit log DateRangePicker width

- shell/app/common/components/log/log-roller.scss
- shell/app/modules/project/pages/test-manage/components/case-table/index.tsx
> fix table render when unsort

- shell/app/modules/runtime/common/components/pod-table.tsx
- shell/app/styles/antd-extension.scss
> fix: pod table add tooltip

- shell/app/modules/project/pages/test-manage/components/case-tree/index.tsx
fix that If there are already expanded nodes, click on other nodes to not expand
Fixes #
> fix: expand case set

- shell/app/modules/project/pages/test-plan/plan-modal.tsx
> fix: test plan edit bug

- .github/workflows/codecov.yml
> trigger codecov workflow only ts/tsx file changed

- shell/app/layout/stores/message.ts
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/msp/pages/gateway/containers/api-package.tsx
- shell/app/modules/project/common/components/issue/issue-drawer.scss
- shell/app/modules/project/common/components/issue/subscribers-selector.tsx
Fixes # personal news improvement bugs
> fix: personal news improvement bugs

- shell/app/modules/org/pages/setting/org-info.tsx
> fix publisher switcher error

- shell/app/modules/msp/pages/gateway/containers/api-package-detail.tsx
Fixes # msp api-package-detail filter bug
> fix: msp api-package-detail filter bug

- shell/app/configForm/form/form.tsx
Fixes # bugs caused by Form upgrade
> fix: bugs caused by Form upgrade

- shell/app/modules/application/pages/repo/repo-tag.tsx
> fix: repo add tag bug

- shell/app/common/components/authorize-member-modal.tsx
- shell/app/common/components/edit-field.tsx
- shell/app/modules/application/common/components/edit-stage.scss
- shell/app/modules/project/common/components/issue/issue-drawer.tsx
- shell/app/yml-chart/common/pipeline-node-drawer.tsx
> fix: fix pipeline action form

- shell/app/modules/org/pages/certificate/index.tsx
Fixes # failed to add certificate
> fix: failed to add certificate

- shell/app/common/components/edit-field.tsx
- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
fix custom text field can't edit issue
Fixes #
> fix(dop): fix custom text field can't edit issue

- README.md
- erda.yml
- shell/app/modules/msp/pages/gateway/containers/api.scss
reduce resource request
fix select input style
Fixes #
> chore: reduce ui resource request

- shell/app/modules/cmp/common/components/table-col.tsx
- shell/app/modules/cmp/pages/networks/vpc/vpc-form-modal.tsx
> fix: fix vpc form

- README.md
- shell/app/styles/antd-extension.scss
- shell/app/styles/util.scss
This style is no longer suitable.
Fixes #
> Feat: remove ant tab overwrite style

- shell/app/modules/cmp/pages/domain-manage/index.tsx
- shell/app/modules/project/common/components/issue/issue-drawer.scss
- shell/app/modules/project/common/components/issue/subscribers-selector.tsx
> fix: follower-style-bugs

- shell/app/common/components/contractive-filter.scss
- shell/app/common/components/filter-group/filter-group.scss
- shell/app/config-page/components/table/table.scss
Fixes # calendar picker style bug
->
> fix: calendar picker style bug

- modules/market/craco.config.js
>  upgrade market publicPath

- shell/app/configForm/editor/form-preview.tsx
- shell/app/locales/zh.json
- shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-yml-graphic-editor.scss
fix: fix config sheet pipeline drawer
Fixes #
> fix: fix config sheet pipeline drawer

- shell/app/common/components/paging-table.jsx
- shell/app/modules/msp/pages/gateway/containers/api-package.tsx
Fixes # api-package table operates column fixed
> fix: api-package table operates column fixed

- shell/app/modules/org/pages/projects/project-list.tsx
Fixes # orgCenter project-list table columns overlap
> fix: orgCenter project-list table columns overlap

- modules/market/src/pages/download.tsx
> fix app logo failed to load

- shell/app/modules/cmp/common/custom-alarm/index.tsx
fix that setValue in form of custom alarm strategy
Fixes #
> Hotfix: setValue in form of custom alarm strategy

- shell/app/common/components/edit-field.tsx
- shell/app/common/components/img-holder.tsx
- shell/app/config-page/components/button/button.tsx
- shell/app/modules/project/common/components/issue/subscribers-selector.tsx
1、fix: fix edit field
2、fix ImageHolder special user nick
Fixes #
> fix: fix edit field

- shell/app/common/utils/go-to.tsx
fix that click 'my-approval' in the menu will fold.
Fixes #
> fix: click 'my approval' in menu of dop

- shell/app/modules/cmp/common/alarm-strategy/index.tsx
> fix select cannot be fully displayed

- shell/app/locales/zh.json
Fixes # followers internationalization bugs
> fix: followers internationalization bugs

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
- shell/tailwind.config.js
> import cluster feature

- shell/app/config-page/components/table/table.scss
> fix: gantt date style bug

- shell/app/modules/application/pages/deploy/deploy.tsx
fix: fix rumtime deploy workspace error
Fixes #
> fix: fix rumtime deploy workspace error

- shell/app/modules/application/pages/repo/components/repo-file.tsx
fix: fix repo file path
Fixes #
> fix: fix repo file path

- shell/app/common/components/edit-field.scss
- shell/app/common/components/load-more-selector.scss
- shell/app/modules/project/pages/backlog/issue-item.scss
- shell/app/styles/antd-extension.scss
Fixes # backlog add item style bug
- [] No
->
> fix: backlog add item style bug

- shell/app/styles/antd-extension.scss
Fixes # issue table icon style bug
->
> fix: issue table icon style bug

- shell/app/layout/pages/message/message.scss
- shell/app/layout/pages/message/message.tsx
Fixes # personal news improvement style bugs
->
> fix: personal news improvement style bugs

- shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
>  adjust data to params

- shell/app/common/components/edit-field.scss
- shell/app/styles/antd-extension.scss
Fixes # issues drawer style bugs
->
> fix: issues drawer style bugs

- erda.yml
modify ENABLE_BIGDATA to false
Fixes #
> Chore: modify ENABLE_BIGDATA to false

- shell/app/config-page/components/button/button.tsx
- shell/app/menus/application.tsx
- shell/app/modules/application/stores/build.ts
1、fix: fix project-level app menu, delete api menu
2、fix: runtime detail empty error
Fixes #
> fix: fix project-level app menu / runtime detail empty error

- shell/app/layout/pages/page-container/components/sidebar.scss
- shell/app/layout/pages/page-container/components/sidebar.tsx
Fixes # message button double-click unselected text
> fix: message button double-click unselected text

- shell/app/modules/cmp/pages/cluster-manage/operation-history.tsx
- shell/app/modules/cmp/services/cluster.ts
- shell/app/modules/cmp/stores/cluster.ts
Fixes # operate-history interface fail
> fix: operate-history-interface-fail

- shell/app/layout/pages/message/message.tsx
Fixes # message unread count interface remove delay
> fix: message unread count interface remove delay

- shell/app/user/common/perm-editor/perm-editor.scss
fix: fix perm editor style
Fixes #
> fix: fix perm editor style

- shell/app/modules/project/common/components/issue/issue-relation.tsx
Fixes # milestone drawer table memberSelect width bug
->
> fix: milestone drawer table memberSelect width bug

- shell/app/common/components/members-table.tsx
Fixes # member-table operate column fixed right
->
> fix: member-table operate column fixed right

- shell/app/modules/msp/monitor/external-insight/pages/affairs/affairs.tsx
- shell/app/modules/msp/monitor/service-insight/pages/database/database.tsx
- shell/app/modules/msp/monitor/service-insight/pages/web/web.tsx
- shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
- shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.tsx
- shell/app/modules/msp/monitor/trace-insight/services/trace-detail.ts
- shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
- shell/app/modules/msp/monitor/trace-insight/stores/trace-detail.ts
- shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
- shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
- shell/app/modules/msp/services/trace.ts
- shell/app/modules/msp/stores/trace.ts
fix(msp): upgrade trace detail api
Fixes #
> upgrade trace detail api

- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
- shell/tailwind.config.js
cluster import minor change
Fixes #
> cluster import minor change

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
> feat(cmp): add fixed submit value

- shell/app/modules/application/pages/repo/repo-tree.scss
Fixes # pipeline edit style bug
->
> fix: pipeline edit style bug

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
- shell/app/modules/project/pages/test-manage/case/manual-test.tsx
- shell/app/modules/project/types/test.d.ts
add refresh icon when detect newly import case
Fixes #
> feat(dop): add refresh icon when detect newly import case

- shell/app/layout/pages/message/message.scss
fix message-list style bug
release/1.1
Fixes # message-list style bug
> fix: message-list style bug

- shell/app/modules/project/pages/backlog/issue-item.tsx
- shell/app/styles/antd-extension.scss
fix backlog style bugs.
release/1.1
Fixes # backlog style bugs
> fix: backlog style bugs

- shell/app/modules/cmp/types/alarm-record.d.ts
- shell/app/modules/msp/monitor/alarm-record/stores/alarm-record.ts
update param of request in alarm records(msp)
release 1.1 & master
Fixes #
> fix: update param of request in alarm records of msp

- README.md
- shell/app/layout/common/invite-to-org.tsx
- shell/app/modules/application/pages/release/components/release-detail-edit.tsx
- shell/app/modules/project/common/components/section-info-edit.tsx
trim Invitation code
add default text for release version
release/1.1
Fixes #
> Fix: trim Invitation code, add default text for release version

- shell/app/common/components/edit-field.scss
- shell/app/modules/project/pages/backlog/issue-item.scss
- shell/app/styles/antd-extension.scss
fix select global style bug
release/1.1
Fixes # select global style bug
> fix: select global style bug

- pnpm-lock.yaml
- shell/app/modules/msp/monitor/trace-insight/pages/trace-detail/components/trace-detail.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-detail.tsx
- shell/package.json
fix jump error
release/1.1
Fixes #
> fix jump error

- shell/app/config-page/components/button/button.tsx
- shell/app/config-page/index.tsx
- shell/app/modules/publisher/pages/statistics/detail.tsx
1、fix: fix statistics detail request 
2、clear autoRefresh timeout 
release/1.1
Fixes #
> fix: fix statistics detail request / autoRefresh timeout

- shell/app/modules/project/pages/test-manage/case/header/export-file.tsx
- shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
- shell/app/modules/project/pages/test-manage/case/header/import-file.tsx
- shell/app/modules/project/pages/test-manage/case/manual-test.tsx
release/1.1
Fixes #  recent import and export records remove interval
> fix: recent import and export records remove interval

- shell/app/modules/msp/monitor/monitor-alarm/services/alarm-strategy.ts
Because of interface name conflict,  update interface of getAlertTypes
Fixes #
> fix: update interface of getAlertTypes

- shell/app/modules/publisher/pages/error-report/index.tsx
- shell/app/styles/antd-extension.scss
fix error list style bug
release/1.1
Fixes # error list style bug
> fix: error list style bug

- shell/app/config-page/components/table/table.scss
- shell/app/styles/antd-extension.scss
fix table icon style bug
release/1.1
Fixes # table icon style bug
> fix: table icon style bug

- shell/app/modules/application/pages/repo/components/file-diff.tsx
fix: fix repo file path error
release/1.1
Fixes #
> fix: fix repo file path error

- shell/app/common/components/render-formItem.tsx
fix custom-alarm bug caused by Form upgrade
release/1.1
Fixes # custom-alarm bug caused by Form upgrade
> fix: custom-alarm bug caused by Form upgrade

- shell/app/modules/msp/monitor/service-list/pages/index.tsx
fix table-chart click event
release/1.1
Fixes #
> fix table-chart click event

- shell/app/layout/pages/page-container/components/header.tsx
- shell/app/modules/project/stores/project.tsx
fix: fix breadcrumb;
fix: forbidden space detail request
release/1.1
Fixes #
> fix: fix breadcrumb / forbidden space request

- shell/app/modules/msp/monitor/external-insight/pages/affairs/affairs.tsx
- shell/app/modules/msp/monitor/service-insight/pages/database/database.tsx
- shell/app/modules/msp/monitor/service-insight/pages/web/web.tsx
- shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
- shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
getTraceDetailContent return content in trance querier
release/1.1
Fixes #
> getTraceDetailContent return content in trance querier

- README.md
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/runtime/common/components/deployment-table.tsx
missing this deployment text.
release/1.1
Fixes #
> Fix: add release deployment type 

- shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
- shell/app/styles/antd-extension.scss
- shell/app/styles/app.scss
fix: fix table style
release/1.1
Fixes #
> fix: fix table style

- nginx.conf.template
- shell/app/modules/cmp/types/cluster.d.ts
- shell/app/modules/dcos/common/containers/terminal.jsx
- shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
- shell/app/modules/runtime/services/log.ts
- shell/app/modules/runtime/stores/log.ts
feat: delete terminal colonySoldier url
Fixes #
> feat: delete terminal colonySoldier url

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
> fix(common): merge code

- shell/app/common/components/render-formItem.tsx
- shell/app/layout/pages/page-container/components/sidebar.scss
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/locales/zh.json
- shell/app/modules/msp/monitor/status-insight/pages/status/status.tsx
- shell/app/modules/msp/pages/gateway/containers/api-package-detail.tsx
fix international, table style and message style bugs.
release/1.1
Fixes # international, table style and message style bugs
> fix: international, table style and message style bugs

- shell/app/modules/apiManagePlatform/pages/api-market/design/index.scss
- shell/app/styles/antd-extension.scss
> fix: input style in API design

- shell/app/modules/project/pages/settings/components/project-label.tsx
fix that can't choose the color in label setting
Fixes #
> fix: choose color in label setting

- shell/app/modules/application/pages/deploy-list/deploy-list.tsx
fix my-approve table style bug
release/1.1
Fixes # my-approve table style bug
> fix: my-approve table style bug

- shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-history-list.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
- shell/app/modules/msp/monitor/trace-insight/services/trace-detail.ts
- shell/app/modules/msp/monitor/trace-insight/services/trace-querier.ts
- shell/app/modules/msp/monitor/trace-insight/stores/trace-detail.ts
- shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts
- shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
- shell/app/modules/msp/services/trace.ts
- shell/app/modules/msp/stores/trace.ts
upgrade trace detail api reponse
release/1.1
Fixes #
> upgrade trace detail api reponse

- shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
- shell/app/modules/project/pages/test-manage/case/manual-test.tsx
feat(dop): format code
remove import operator check
someone who raise the import action should also see the refresh button
release/1.1
Fixes #
> feat(dop): remove import operator check

- shell/app/modules/dcos/common/containers/terminal.jsx
> fix: fix terminal api (not patch to 1.1)

- shell/app/modules/cmp/pages/middleware-dashboard/index.tsx
fix addon table style bug
release/1.1
Fixes # addon table style bug
> fix: addon table style bug

- shell/app/modules/project/common/components/issue/subscribers-selector.tsx
fix followers component show bug.
release/1.1
Fixes # followers component show bug
> fix: followers component show bug

- shell/app/modules/msp/pages/gateway/containers/api-limits.tsx
- shell/app/modules/msp/pages/gateway/containers/api-package-create.tsx
fix api-package edit form bug.
release/1.1
Fixes # api-package edit form bug
> fix: api-package edit form bug

- shell/app/modules/application/pages/repo/components/compare-detail.tsx
- shell/app/modules/application/pages/repo/mr-detail.tsx
fix issue https://erda-org.app.terminus.io/erda/workBench/projects/387/issues/all?id=73569&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTA5MTgiLCIxMDAwNTYyIiwiMTAwMTA3NSJdfQ%3D%3D&issueGantt__urlQuery=eyJ0b3RhbCI6OCwicGFnZU5vIjoxLCJwYWdlU2l6ZSI6MjAwLCJpc3N1ZVZpZXdHcm91cFZhbHVlIjoiZ2FudHQiLCJJc3N1ZVR5cGUiOiJBTEwifQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG
release/1.1
Fixes #
> fix(dop): fix repo compare detail missing issue

- shell/app/modules/org/pages/certificate/index.tsx
fix upload certificate cannot show filename
release/1.1
Fixes #
> fix upload certificate cannot show filename

- shell/app/common/components/contractive-filter.scss
- shell/app/common/components/contractive-filter.tsx
Change issues dropdown font color.
->
release/1.1
Fixes # issues dropdown font color.
> fix: issues dropdown font color

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
- shell/app/modules/cmp/pages/cluster-manage/index.tsx
- shell/app/views/index.ejs
add cluster type icon & don't open command drawer when edit cluster config
release/1.1
Fixes #
> fix(cmp): add cluster type icon & don't open command drawer when edit cluster config

- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
fix cluster list style bug
release/1.1
Fixes # cluster list style bug
> fix: cluster list style bug

- shell/app/common/components/filter-group/filter-group.scss
fix calendar style bug
release/1.1
Fixes # calendar style bug
> fix: calendar style bug

- shell/app/layout/pages/message/message.scss
fix message center style bug
release/1.1
Fixes # message center style bug
> fix: message center style bug

- shell/app/modules/cmp/common/alarm-strategy/index.scss
- shell/app/modules/cmp/common/custom-alarm/index.scss
- shell/app/modules/cmp/common/custom-alarm/index.tsx
- shell/app/modules/msp/pages/gateway/containers/api-package-create.scss
select cannot be fully displayed
release/1.1
Fixes #
> select cannot be fully displayed

- shell/app/modules/org/pages/projects/create-project.tsx
- shell/app/styles/antd-extension.scss
> Hotfix: modify font color of label in the form

- shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
fix: fix case api form
release/1.1
Fixes #
> fix: fix case api form

- shell/app/modules/application/common/components/health-check-field.tsx
- shell/app/modules/msp/monitor/application-insight/index.js
- shell/app/modules/msp/monitor/browser-insight/index.js
- shell/app/modules/msp/monitor/mobile-insight/index.js
fix: fix dice yaml editor form error
fix: fix monitor breadcrumb
- [] No
release/1.1
Fixes #
> fix: fix dice yaml editor form error

- shell/app/modules/dcos/pages/service-manager/rds-manager/database.tsx
- shell/app/modules/dcos/pages/service-manager/rds-manager/rds-account.tsx
fix: fix tooltip undefined
Fixes #
> fix: fix tooltip undefined

- shell/app/modules/cmp/common/custom-alarm/index.tsx
hide button of viewing dashboard in msp & cmp temporarily
Fixes #
> fix: hide button of viewing dashboard in msp & cmp temporarily

- pnpm-lock.yaml
- shell/app/common/components/json-checker.tsx
fix copy json invalid
release/1.1
Fixes #
>  fix copy json invalid

- shell/app/modules/msp/monitor/topology/pages/topology/node-item.tsx
jump to transactions page with status
Fixes #
> Hotfix: jump to transactions page with status

- shell/app/modules/msp/monitor/topology/pages/topology-dashboard/index.tsx
goto detail page with time in topology(fixed before, but the code was killed again)
Fixes #
> Hotfix: goto detail page with time in topology

- shell/app/modules/msp/pages/gateway/containers/api-package-create.tsx
fix api-package-create validate bug.
Fixes # api-package-create validate bug
> fix: api-package-create validate bug

- shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
fix: custom domain edit failed
Fixes #
> fix: fix domain modal form

- shell/app/layout/pages/message/message.scss
- shell/app/layout/pages/message/message.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
message center style change.
release/1.1
Fixes # message center style change
> fix: message center style change

- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
fix cluster list operate column style bug.
release/1.1
Fixes # cluster list operate column style bug
> fix: cluster list operate column style bug

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
remove kubeconfig link in k8s import form
release/1.1
Fixes #
> feat(cmp): remove kubeconfig link

- shell/app/modules/cmp/common/custom-alarm/index.tsx
set select dropdownMatchSelectWidth to false
release/1.1
Fixes #
> set select dropdownMatchSelectWidth to false

- cspell.json
- shell/app/common/components/erda-icon/erda-icon.tsx
- shell/app/common/index.ts
- shell/app/layout/pages/message/message.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/org-home/types/org.d.ts
- shell/app/views/index.ejs
- shell/app/views/skeleton.html
1) modify the icon size and margin in skeleton.html to avoid the shaking behavior when rendering;
2) to remove the dice-layout link of iconfont and use iconpark link;
3) create ErdaCustomIcon component to use custom icon of iconpark
Fixes #
> feat: remove dice-layout link of iconfont

- shell/app/layout/pages/message/message.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
message center text change.
release/1.1
Fixes # message center text change
> fix: message center text change

- shell/app/App.tsx
- shell/app/org-home/stores/org.tsx
fix: fix url starts with /r/ redirect error
Fixes #
> fix: fix url starts with /r/ redirect error

- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
fix cluster list operate column  bug.
release/1.1
Fixes # cluster list operate column  bug
> fix: cluster list operate column  bug

- shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
- shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
fix: cmp-overview interactive defects.
Fixes # cmp-overview interactive defects
> fix: cmp-overview interactive defects

- shell/app/config-page/components/api-editor/api-editor.spec.d.ts
- shell/app/config-page/components/api-editor/api-editor.tsx
- shell/app/config-page/page-render.tsx
feat: add api editor loop form
- [] No
Fixes #
> feat(1.2): add api editor loop form

- shell/app/common/components/render-formItem.tsx
fix required mark not showing issue
release/1.1
Fixes #
> fix(common): fix required mark not showing issue

- pnpm-lock.yaml
- shell/package.json
fix when switching types, the data is not up to date
release/1.2
Fixes #
> fix: upgrade dashboard-configuration to v1.0.24

- shell/app/config-page/components/api-editor/api-editor.tsx
fix: fix api editor loop error
Fixes #
> fix(1.2): fix api editor loop error

- shell/app/modules/application/stores/repo.ts
Automatically update the commit information after the code repo has been committed
Fixes #
> Feat: Automatically update the commit information after the code repo has been committed

- shell/app/modules/apiManagePlatform/pages/access-manage/edit/index.tsx
fix
release/1.1
Fixes # access-manage edit data backfill bug
> fix: access-manage edit data backfill bug

- shell/app/config-page/components/issue-kanban.tsx
fix: fix issue kanban data error
Fixes #
> fix(1.1): fix issue kanban data error

- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
- shell/app/modules/cmp/pages/cluster-manage/index.tsx
> fix(cmp): merge code

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
* Add changeLog section to auto generate changeLog from pull requests.
* replace the checkbox style choose
Fixes #
> Chore: update pull request template

- shell/app/modules/project/common/components/pipeline-manage/common/config-env-selector.tsx
fix: fix project pipeline cluster error
❎ No
| 🇺🇸 English |     fix project pipeline cluster error         |
| 🇨🇳 中文    |     修复项目流水线集群参数错误         |
Fixes #
> fix(1.0): fix project pipeline cluster error

- shell/app/common/__tests__/components/member-selector.test.tsx
- shell/app/common/components/load-more-selector.tsx
- shell/app/common/components/member-selector.tsx
- shell/app/common/services/file-tree.tsx
- shell/app/modules/project/pages/test-manage/case/filter-drawer.tsx
feat: add select none in member selector
feat: encodeURI in pipeline node id request
| 🇺🇸 English |  add select none in member selector / encode nodeId in pipeline filetree API |
| 🇨🇳 中文    |     在memberSelector中支持未指定选项 / pipeline filetree相关接口添加nodeId的encode转换         |
Fixes #
> feat(1.2): add select none in member selector

- shell/package.json
add online extra logic script
in pipeline add one step `npm run online-extra-logic`
❎ No
Fixes #
> fix(common): add online extra logic script

- shell/app/yml-chart/common/pipeline-node-drawer.tsx
feat: add action use protocol in action detail
❎ No
| 🇺🇸 English |    add action use protocol in action detail，if useProtocol=true，then use config-page to render         |
| 🇨🇳 中文    |      在action详情接口中添加useProtocol标示，标示为true则走组件化协议        |
Fixes #
> feat(1.2): add action use protocol in action detail

- shell/app/modules/application/pages/repo/components/file-diff.tsx
fix: fix repo file diff data duplicate error
❎ No
| 🇺🇸 English |    fix: fix repo file diff data duplicate error       |
| 🇨🇳 中文    |    修复repo文件比对数据重复错误          |
Fixes #
> fix: fix repo file diff data duplicate error

- shell/app/modules/cmp/common/alarm-record/detail.tsx
alarm detail remove view button
❎ No
| 🇺🇸 English | remove the alarm list view button |
| 🇨🇳 中文    | 移除告警列表查看按钮 |
Fixes #
> remove the alarm list view button

- shell/app/modules/org/pages/projects/project-list.tsx
orgCenter project-list columns increase width.
| 🇺🇸 English | orgCenter project-list columns increase width. |
| 🇨🇳 中文    | 给管理中心-项目管理的表格增加宽度。 |
Fixes # orgCenter project-list columns increase width
> fix: orgCenter project-list columns increase width

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
fix data not loaded when update edas cluster form
❎ No
Fixes #
> fix(cmp): fix data not load when update form

- shell/app/layout/pages/page-container/page-container.tsx
show dataCenter to free users
❎ No
| 🇺🇸 English |  The function restrictions of the CMP for free users are lifted  |
| 🇨🇳 中文    |   对免费用户的多云管理平台功能限制解除  |
Fixes #
> feat: show dataCenter to free users

- shell/app/common/components/edit-field.scss
- shell/app/common/components/edit-field.tsx
- shell/app/common/components/markdown-editor/index.scss
- shell/app/common/components/markdown-editor/index.tsx
- shell/app/config-page/components/action-form.tsx
- shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
- shell/app/modules/project/common/components/issue/issue-drawer.tsx
fix: md editor update
fix: copy issue popover visible error
| 🇺🇸 English |    md editor update / copy issue popover visible error        |
| 🇨🇳 中文    |     markdown编辑器样式修改 / 复制事件弹窗取消无效         |
Fixes #
> fix(1.1): md editor update

- shell/app/modules/project/common/components/pipeline-manage/common/config-env-selector.tsx
fix: fix project pipeline env error
❎ No
| 🇺🇸 English |     fix: fix project pipeline env error         |
| 🇨🇳 中文    |    修复项目流水线env参数错误          |
Fixes #
> fix: fix project pipeline env error

- shell/app/config-page/components/file-tree/file-tree.scss
fix: fix nusi tree drag style
| 🇺🇸 English |        fix nusi tree drag style      |
| 🇨🇳 中文    |         修复nusi组件tree拖拽样式问题     |
Fixes #
> fix: fix nusi tree drag style

- shell/app/config-page/components/action-form.tsx
fix: fix action form get operations key error
❎ No
| 🇺🇸 English |     fix: fix action form get operations key error |
| 🇨🇳 中文    |    修复action form中operation取key值错误          |
Fixes #
> fix: fix action form get operations key error

- shell/app/modules/project/common/components/issue/issue-relation.tsx
adjust width of related issues table.
| 🇺🇸 English | adjust width of related issues table. |
| 🇨🇳 中文    | 调整关联事项表格列的宽度。  |
Fixes # adjust width of related issues table
> fix: issue-relation-columns-width-adjustment

- shell/app/config-page/components/action-form.tsx
- shell/app/yml-chart/chart/yml-chart-utils.tsx
- shell/app/yml-chart/chart/yml-chart.scss
fix: fix ymal chart addNode disappear / action form data error
❎ No
| 🇺🇸 English |      fix: fix ymal chart addNode disappear / action form data error        |
| 🇨🇳 中文    |     修复yml编辑器添加节点消失 / actionForm组件化数据错误         |
Fixes #
> fix: fix ymal chart addNode disappear / action form data error

- shell/app/modules/apiManagePlatform/pages/api-market/version/index.scss
- shell/app/modules/apiManagePlatform/pages/api-market/version/version-info.tsx
fix version-info style bug.
Fixes # version-info style bug
> fix: version-info style bug

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/project/pages/test-manage/case/header/import-export-record.tsx
- shell/app/modules/project/types/test.d.ts
the data structure of ImportExportResult  has changed
Fixes #
> fix: update data structure of import & export case list

- core/src/nusi/wrapped-table.tsx
add the other components of Table to WrappedTable.
❎ No
Fixes #
> refactor: add the other components of Table to WrappedTable

- shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-form.scss
- shell/app/modules/msp/monitor/monitor-common/components/sort-list/sort-list.scss
- shell/app/modules/runtime/pages/overview/components/service-card.scss
fix service panel can not show issue
❎ No
Fixes #
> fix(common): fix service panel can not show issue

- shell/app/styles/antd-extension.scss
fix ant form inline style issue
Fixes #
> fix(common): fix ant form inline style issue

- shell/app/modules/cmp/common/custom-alarm/index.tsx
feat(cmp): group rule change to required
❎ No
| 🇺🇸 English |    When creating a custom alarm rule, change the grouping rule to a required option          |
| 🇨🇳 中文    |    创建自定义告警规则的时候把分组规则改成必选项        |
Fixes #
> feat(cmp): group rule change to required

- shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
fix trace span offset
❎ No
release/1.1
Fixes #
> fix trace span offset

- cli/lib/build.ts
- cli/package.json
fix pipeline failed issue when only build community version
❎ No
Fixes #
> fix pipeline failed issue when only build community version

- shell/app/modules/msp/pages/micro-service/overview.tsx
feat(msp): add timeselect in msp overview
add timeselect on msp overview
❎ No
Fixes #
> add timeselect on msp overview

- shell/app/modules/project/pages/third-service/components/instance-form.tsx
- shell/app/modules/project/pages/third-service/components/third-addon-form.tsx
fix custom-addon edit bug.
❎ No
| 🇺🇸 English | Fixed an issue where the extension service custom addon edit was incorrectly reported. |
| 🇨🇳 中文    | 修复了扩展服务自定义插件编辑时报错的问题。 |
release/1.1
Fixes # custom-addon edit bug
> fix: custom-addon edit bug

- shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
fix cluster overview interaction error
❎ No
Fixes #
> fix cluster overview interaction error

- shell/app/common/__tests__/components/menu-popover.test.tsx
- shell/app/common/components/erda-icon/erda-icon.tsx
- shell/app/layout/stores/breadcrumb.ts
- shell/app/modules/msp/pages/micro-service/project-list.tsx
- shell/app/modules/msp/pages/micro-service/switch-env.tsx
- shell/app/modules/msp/router.js
- shell/app/modules/msp/services/index.ts
- shell/app/modules/msp/stores/micro-service.tsx
- shell/app/modules/org/pages/projects/create-project.tsx
- shell/app/modules/org/pages/projects/project-list.tsx
- shell/app/modules/org/pages/projects/settings.tsx
- shell/app/modules/project/pages/settings/components/project-info.tsx
- shell/app/modules/project/types/project.d.ts
- shell/app/views/index.ejs
add breadcrumb and refactor switch env
❎ No
Fixes #
> add breadcrumb and refactor switch env

- shell/app/common/components/dropdown-select.tsx
- shell/app/common/components/erda-icon/erda-icon.tsx
- shell/app/common/components/image-upload.tsx
- shell/app/common/components/tree/edit-category.tsx
- shell/app/modules/application/pages/build-detail/pipeline-log.tsx
- shell/app/modules/application/pages/deploy/deploy.tsx
- shell/app/modules/application/pages/deploy/runtime-box.tsx
- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
- shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
- shell/app/modules/application/pages/repo/components/repo-file-container.tsx
- shell/app/modules/application/pages/repo/repo-branch.scss
- shell/app/modules/application/pages/repo/repo-branch.tsx
- shell/app/modules/application/pages/repo/repo-commit.tsx
- shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
- shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
- shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
- shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
- shell/app/modules/project/pages/test-manage/case/manual-test.tsx
- shell/app/yml-chart/pipeline-editor.tsx
Delete extra code and modify color name
❎ No
Fixes #
> Delete extra code and modify color name

- shell/app/modules/application/common/components/pipeline-node.tsx
- shell/app/modules/application/pages/build-detail/pipeline-chart/pipeline-node.tsx
- shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
feat: update pipeline log style
| 🇺🇸 English |      feat: update pipeline log style  |
| 🇨🇳 中文    |        优化pipleine日志样式      |
Fixes #
> feat: update pipeline log style

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/msp/monitor/topology/pages/topology-dashboard/index.tsx
- shell/app/modules/msp/monitor/topology/pages/topology/topology.tsx
- shell/app/modules/msp/pages/micro-service/project-list.tsx
- shell/app/modules/msp/pages/micro-service/switch-env.tsx
fix request errors when page back
❎ No
release/1.2
Fixes #
> fix request errors when page back

- shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx
- shell/app/modules/msp/monitor/monitor-overview/services/monitor-overview.ts
- shell/app/modules/msp/monitor/monitor-overview/stores/monitor-overview.ts
- shell/app/modules/msp/monitor/monitor-overview/types/index.d.ts
- shell/app/modules/msp/monitor/status-insight/pages/status/add-modal.tsx
remove the api that query monitor instance
❎ No
release/1.2
Fixes #
> remove the api that query monitor instance

- shell/app/modules/project/pages/ticket/index.tsx
The size of ticket Table change.
release/1.2
Fixes # Ticket Table row too high.
> fix: the size of ticket Table change

- shell/app/common/components/back-to-top.tsx
- shell/app/common/components/contractive-filter.tsx
- shell/app/common/components/erda-icon/erda-icon.tsx
- shell/app/common/components/sort-drag-list.tsx
- shell/app/common/components/tree/edit-category.tsx
- shell/app/modules/application/common/components/goto-commit.tsx
- shell/app/modules/application/pages/build-detail/pipeline-log.tsx
- shell/app/modules/application/pages/deploy/deploy.tsx
- shell/app/modules/application/pages/deploy/runtime-box.scss
- shell/app/modules/application/pages/deploy/runtime-box.tsx
- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
- shell/app/modules/application/pages/pipeline/run-detail/pipeline-log.tsx
- shell/app/modules/application/pages/repo/components/repo-file-container.tsx
- shell/app/modules/application/pages/repo/repo-branch.tsx
- shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
- shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
- shell/app/modules/project/pages/test-manage/case/case-drawer/case-api.tsx
- shell/app/modules/project/pages/test-manage/case/case-drawer/index.tsx
- shell/app/modules/project/pages/test-manage/case/manual-test.tsx
- shell/app/modules/publisher/pages/artifacts/version-list.tsx
- shell/app/yml-chart/pipeline-editor.tsx
Replace class with classname and adjust the icon position
❎ No
release/1.2
Fixes #
> Replace class with classname and adjust the icon position

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/application/pages/repo/components/repo-editor.tsx
when create file, submit message is required.
❎ No
release/1.2
Fixes # when create file, submit message is required.
> fix: when create file, submit message is required

- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
- shell/app/modules/project/common/components/issue/issue-relation.tsx
- shell/app/modules/project/stores/issues.ts
issue type maybe undefined and cause the page crash.
refactor issue relation component, use issue detail from props directly.
Nope
Fixes #
> fix: issue type maybe undefined some time

- shell/app/modules/msp/services/index.ts
- shell/app/modules/project/pages/settings/components/project-info.tsx
replace the request method for updating tenant
❎ No
release/1.2
Fixes #
> replace the request method for updating tenant

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/msp/config.ts
- shell/app/modules/msp/pages/micro-service/switch-env.tsx
- shell/app/modules/msp/stores/micro-service.tsx
fix page redirect error when click projectName
❎ No
release/1.2
Fixes #
> fix page redirect error when click projectName

- shell/app/modules/runtime/common/components/pod-table.tsx
> fix(dop): fix invalid date issue

- core/src/nusi/index.tsx
- core/src/nusi/wrapped-tag.tsx
- shell/app/styles/antd-extension.scss
replace Nusi Avatar and Tag with Antd.
❎ No
release/1.2
Fixes # replace Nusi Avatar and Tag with Antd
> refactor: replace Nusi Avatar and Tag with Antd

- shell/app/modules/org/pages/projects/create-project.tsx
fix project card style
release/1.2
Fixes #
> fix project card style

- shell/app/modules/project/pages/third-service/components/addon-modal.tsx
- shell/app/modules/project/pages/third-service/components/instance-form.tsx
fix: fix project service form error
❎ No
| 🇺🇸 English |     fix: fix project service form error         |
| 🇨🇳 中文    |     修复项目-扩展服务表单错误         |
Fixes #
> fix: fix project service form error

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
add form field trim
❎ No
release/1.2
Fixes #
> fix(cmp): add content trim

- shell/app/modules/application/pages/repo/components/source-target-select.tsx
fix create pr error
❎ No
release/1.2
Fixes #
> fix create pr error

- shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
- shell/app/modules/application/pages/settings/components/app-notify/index.scss
- shell/app/modules/application/pages/settings/components/app-notify/notify-config.tsx
- shell/app/modules/cmp/common/alarm-strategy/index.scss
- shell/app/modules/cmp/common/alarm-strategy/index.tsx
- shell/app/modules/cmp/common/custom-alarm/index.tsx
- shell/app/modules/msp/stores/micro-service.tsx
fix msp menu request error
fix style error
override scroll
❎ No
release/1.2
Fixes #
> fix request occasional error

- shell/app/modules/application/common/yml-editor/pipeline-editor.tsx
- shell/app/modules/application/pages/pipeline/index.tsx
- shell/app/modules/application/pages/pipeline/scope-config.tsx
- shell/app/yml-chart/common/pipeline-node-drawer.tsx
feat: add project level pipeline action request params
❎ No
| 🇺🇸 English |     feat: add project level pipeline action request params         |
| 🇨🇳 中文    |     项目级应用中，流水线action请求带上特殊参数区分         |
❎ No
Fixes #
> feat: add project level pipeline action request params

- core/src/nusi/index.tsx
- shell/app/config-page/components/breadcrumb/breadcrumb.tsx
replace Nusi Breadcrumb with Antd.
❎ No
❎ No
Fixes # replace Nusi Breadcrumb with Antd
> refactor: replace Nusi Breadcrumb with Antd

- shell/app/modules/dcos/pages/machine-manager/machine-table.tsx
fix table rowkey
❎ No
release/1.2
Fixes #
>  fix table rowkey

- shell/app/modules/cmp/common/components/log-tag-selector.tsx
❎ No
| 🇺🇸 English | fix the bug that  projectId is missing when query  app |
| 🇨🇳 中文    | 修复了请求应用列表projectId缺失的bug |
release/1.2
Fixes #
> fix the bug that  projectId is missing when query  app

- nginx.conf.template
nginx.conf change.
❎ No
| 🇺🇸 English | Fixed bug where Git repository can be cloned without password. |
| 🇨🇳 中文    | 修复了git仓库不用账号密码也能clone的bug。 |
release/1.1
Fixes # nginx.conf change
> fix: nginx.conf change

- shell/app/yml-chart/common/pipeline-node-drawer.tsx
pipeline node label change.
❎ No
❎ No
Fixes # pipeline node label change
> fix: pipeline node label change

- shell/app/modules/dcos/pages/cluster-dashboard/groupTabs.tsx
fix tab interaction
❎ No
release/1.2
Fixes #
> fix tab interaction

- core/src/nusi/index.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-common-panel.tsx
- shell/app/styles/antd-extension.scss
replace Nusi Card with Antd.
❎ No
❎ No
Fixes # replace Nusi Card with Antd.
> refactor: replace Nusi Card with Antd

- erda.yml
change the replicas in production
❎ No
❎ No
Fixes #
> change the replicas in production

- shell/app/modules/msp/stores/micro-service.tsx
> clear project info when leave mspDetail

- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-detail.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
add cluster detail content text conversion
❎ No
release/1.2
Fixes #
> feat(cmp): add cluster detail content text conversion

- shell/app/config-page/components/image/image.scss
- shell/app/modules/project/pages/data-source/index.tsx
1. add emptyHolder to dataSource page
2. update the style of Image which type is small
Fixes #
> style: add emptyHolder to dataSource page

- shell/app/common/__tests__/components/img-holder.test.tsx
- shell/app/common/components/json-checker.tsx
fix copy doesn't work in trace page
❎ No
release/1.2
Fixes #
> fix copy doesn't work in trace page

- shell/app/modules/project/common/components/issue/issue-relation.tsx
fix: fix issue relation error
❎ No
| 🇺🇸 English |  fix issue relations error after change to backlog      |
| 🇨🇳 中文    |   修复事项详情中，一键转待办后，关联事项数据错误       |
❎ No
Fixes #
> fix: fix issue relation error

- shell/app/yml-chart/common/pipeline-node-drawer.tsx
fix: fix pipeline action form init error
❎ No
| 🇺🇸 English |   fix: fix pipeline action form init error           |
| 🇨🇳 中文    |   修复流水线action表单初始化错误           |
Fixes #
> fix: fix pipeline action form init error

- shell/app/layout/pages/page-container/components/sidebar.scss
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
fix: add version tag
| 🇺🇸 English |    fix: add version tag in app center          |
| 🇨🇳 中文    |      应用中心里添加版本信息        |
Fixes #
> fix: add version tag

- shell/app/modules/project/pages/apps/app-type-select.scss
- shell/app/modules/project/pages/apps/app-type-select.tsx
fix: fix app select style
❎ No
| 🇺🇸 English |        fix: fix app select style in En mode     |
| 🇨🇳 中文    |     fix: 修复应用选择英文模式下样式问题         |
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=206305&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
> fix: fix app select style

- core/src/history.ts
- core/src/index.tsx
- core/webpack.config.js
- shell/app/App.tsx
- shell/app/common/__tests__/components/addon-settings.test.tsx
- shell/app/common/__tests__/components/custom-filter.test.tsx
- shell/app/common/__tests__/components/error-boundary.test.tsx
- shell/app/common/__tests__/components/filter-group/filter-group.test.tsx
- shell/app/common/__tests__/components/setting-tabs.test.tsx
- shell/app/common/__tests__/utils/go-to.test.tsx
- shell/app/common/__tests__/utils/query-string.test.tsx
- shell/app/common/utils/axios-config.ts
- shell/app/common/utils/go-to.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/org-home/stores/org.tsx
- shell/app/user/stores/index.ts
- shell/app/views/init.js
- shell/tsconfig.json
fix: init optimize
❎ No
| 🇺🇸 English |     fix: init optimize         |
| 🇨🇳 中文    |   初始化逻辑优化           |
❎ No
Fixes #
> fix: init optimize

- shell/app/modules/application/pages/repo/components/source-target-select.tsx
fix: fix branch compare source target position
| 🇺🇸 English |    fix: switch source branch with target branch position when create pull request         |
| 🇨🇳 中文    |    创建合并请求时调换源分支和目标分支的位置          |
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=205969&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
> fix: fix branch compare source target position

- shell/app/modules/application/pages/repo/repo-branch.tsx
remove extra semicolon
❎ No
release/1.2
Fixes #
> remove extra semicolon

- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.scss
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
fix trace querier body
❎ No
release/1.2
Fixes #
> fix trace querier body

- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.scss
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-querier.tsx
(cherry picked from commit f4df1a5af1ebf4b3ac4fd5a1ed485ada9b6fba55)
❎ No
❎ No
Fixes #
> fix trace querier body (#924)

- shell/app/common/components/markdown-editor/index.scss
- shell/app/common/components/markdown-editor/index.tsx
fix: fix md button show error
❎ No
| 🇺🇸 English | fix: fix md button show error             |
| 🇨🇳 中文    |    fix: 修复md 编辑器按钮显示错误       |
❎ No
Fixes #
> fix: fix md button show error

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/menus/appCenter.tsx
- shell/app/menus/index.ts
- shell/app/menus/util.ts
- shell/app/modules/cmp/pages/cluster-manage/add-cluster-forms/cluster-form.tsx
fix: fix menu i18n
❎ No
| 🇺🇸 English |  fix: fix menu i18n   uppercase error         |
| 🇨🇳 中文    |   fix: 修复菜单国际化大小写问题           |
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=206480&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
> fix: fix menu i18n

- core/package.json
- package.json
- scheduler/package.json
- shell/package.json
Now we are still v1.2.0, version will be shown in app center.
❎ No
❎ No
> chore: unified package version

- shell/app/modules/cmp/pages/account-guidance/index.scss
fix style in en mode
| 🇺🇸 English | fixed the bug that the page style is abnormal in en mode |
| 🇨🇳 中文    | 修复了英文模式下页面样式异常的bug |
release/1.2
Fixes #
>  fix style in en mode

- pnpm-lock.yaml
- shell/package.json
the same as [https://github.com/erda-project/erda-ui/pull/929]
choose chart type before saving in dashboard
❎ No
Fixes #
> fix: upgrade dashboard to v1.0.25

- shell/app/modules/application/pages/problem/problem-detail.tsx
page crash in problem detail page
❎ No
release/1.1 , release/1.2
Fixes #
> fix: page crash in problem detail page

- core/src/index.tsx
set history missing caused fdp index loading crash
❎ No
release/1.2
Fixes #
> fix(common): rollback set history config

- core/src/history.ts
- core/src/index.tsx
- core/webpack.config.js
- shell/app/App.tsx
- shell/app/common/__tests__/components/error-boundary.test.tsx
- shell/app/common/__tests__/utils/query-string.test.tsx
- shell/app/common/utils/axios-config.ts
- shell/app/common/utils/go-to.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/org-home/stores/org.tsx
- shell/app/user/stores/index.ts
- shell/app/views/init.js
- shell/tsconfig.json
Feature: init optimize 1.2
❎ No
| 🇺🇸 English |     feat: init optimize 1.2         |
| 🇨🇳 中文    |    feat: 优化初始化应用          |
❎ No
Fixes #
> Feature: init optimize 1.2

- shell/app/modules/org/pages/projects/create-project.tsx
disable ability to create msp projects
❎ No
| 🇺🇸 English |  |
| 🇨🇳 中文    |  |
❎ No
Fixes #
> disable ability to create msp projects

- shell/app/common/types/pipeline.d.ts
- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
- shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/index.tsx
- shell/app/modules/application/types/build.d.ts
add tooltip in case of incomplete display in english mode.
❎ No
release/1.2
> fix: add tooltip to pipeline record status

- pnpm-lock.yaml
- shell/package.json
add css dc namespace to FormBuilder
❎ No
❎ No
Fixes #
> fix: add css dc namespace to FormBuilder

- shell/app/modules/project/pages/apps/app-form.tsx
Current repository address regular expression is incorrect.
❎ No
| 🇺🇸 English | Fixed the incorrect regular expression about the repository address field |
| 🇨🇳 中文    |   修复代码仓库地址字段正则错误的问题  |
release/1.2
> fix: update repository address regexp

- shell/app/modules/org/common/audit-templates.json
Add cmp dashboard auit template
❎ No
❎ No
> feat: add dashboard auit template

- cspell.json
- shell/auto_test/fixtures.ts
- shell/auto_test/tests/dop/deploy.spec.ts
add case for deploy
❎ No
❎ No
Fixes #
> test(dop): add case for deploy

- shell/tailwind.config.js
fix bg-purple class missing in prod issue 
❎ No
| 🇺🇸 English |  fix purple color tag  no background color issue       |
| 🇨🇳 中文    |    修复紫色标签无背景色的问题          |
release/1.2
Fixes #
> fix(common): add purple to safelist

- shell/package.json
❎ No
| 🇺🇸 English |    fix: fix version          |
| 🇨🇳 中文    |      fix: 修复版本号        |
❎ No
Fixes #
> fix: fix version

- shell/app/modules/apiManagePlatform/pages/api-market/design/basic-params-config.tsx
fix the same property name error in api design page
❎ No
release/1.2
Fixes #
> fix: same propertyName error tip

- shell/app/org-home/stores/org.tsx
Fix that viewing public organization list is not found
❎ No
release/1.2
Fixes #
> fix: view public organization is not found

- shell/app/modules/msp/monitor/trace-insight/common/utils/traceConvert.ts
- shell/app/modules/msp/monitor/trace-insight/types/index.d.ts
fix trace detail error style
❎ No
| 🇺🇸 English | fix tracking details errorType |
| 🇨🇳 中文    | 修复追踪详情错误类型 |
release/1.2
Fixes #
> fix trace detail error style

- core/src/history.ts
- core/webpack.config.js
- shell/app/App.tsx
- shell/app/common/__tests__/components/error-boundary.test.tsx
- shell/app/common/__tests__/utils/query-string.test.tsx
- shell/app/common/utils/go-to.tsx
- shell/tsconfig.json
❎ No
| 🇺🇸 English |    fix: fix history listen execute twice          |
| 🇨🇳 中文    |  fix: 修复路由监听执行两次          |
❎ No
Fixes #
> fix: fix history listen execute twice

- core/src/history.ts
fix: fix history compare
❎ No
❎ No
Fixes #
> fix: fix history compare

- pnpm-lock.yaml
- shell/auto_test/fixtures.ts
- shell/auto_test/tests/admin/user-manage.spec.ts
- shell/auto_test/tests/dop/app/app-config.spec.ts
- shell/auto_test/tests/dop/app/app-manage.spec.ts
- shell/auto_test/tests/dop/app/branch-rule.spec.ts
- shell/auto_test/tests/dop/app/notify.spec.ts
- shell/auto_test/tests/dop/app/private-config.spec.ts
- shell/auto_test/tests/dop/deploy.spec.ts
- shell/auto_test/tests/dop/layout.spec.ts
- shell/auto_test/tests/dop/pipeline.spec.ts
- shell/auto_test/tests/dop/project-manage.spec.ts
- shell/auto_test/tests/pages/app-manage.ts
- shell/auto_test/tests/pages/base.ts
- shell/auto_test/tests/pages/notify.ts
- shell/auto_test/tests/pages/project-manage.ts
- shell/auto_test/tests/pages/user-manage.ts
- shell/auto_test/tests/pages/variable-config.ts
add case for app
❎ No
❎ No
Fixes #
> add case for app

- shell/auto_test/fixtures.ts
- shell/auto_test/tests/dop/branches.spec.ts
- shell/auto_test/tests/dop/merge-requests.spec.ts
> add UI test

- shell/app/App.tsx
- shell/app/common/utils/axios-config.ts
- shell/app/modules/project/pages/apps/app-form.tsx
- shell/app/user/stores/index.ts
fix: fix admin login api error
❎ No
| 🇺🇸 English |     fix: fix admin login api error         |
| 🇨🇳 中文    |    fix: 修复admin用户登录后错误         |
✅ Yes(version is required)  release/1.2
Fixes #
> fix: fix admin login api error

- shell/app/App.tsx
- shell/app/common/utils/axios-config.ts
- shell/app/modules/project/pages/apps/app-form.tsx
- shell/app/user/stores/index.ts
fix: fix admin login api error
❎ No
| 🇺🇸 English |   fix: fix admin login api error           |
| 🇨🇳 中文    |   fix: 修复admin用户登录后报错         |
❎ No
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=208743&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
> fix(1.2): fix admin login api error

- shell/auto_test/fixtures.ts
- shell/auto_test/tests/dop/history.spec.ts
- shell/auto_test/tests/dop/repo.spec.ts
auto test of commi history and souce pages
❎ No
❎ No
Fixes #
> feat: auto test of commit history and souce

- shell/app/modules/runtime/pages/overview/components/service-card.tsx
Open terminal which is crashed in deploy center for terminal lack of instance
❎ No
❎ No
Fixes #
> fix: open terminal which is crashed in deploy center

- pnpm-lock.yaml
- shell/package.json
convert unit which is week or day to hour in dashboard
❎ No
release/1.2
Fixes #
> fix: convert unit which is week or day to hour in dashboard

- shell/app/modules/project/common/components/issue/issue-relation.tsx
Increase the width of issue-relation table.
->
| 🇺🇸 English | Increased the width of issue title in the table of issue-relation in project collaboration. |
| 🇨🇳 中文    | 增加了项目协同中关联事项表格里事项标题的宽度。 |
release/1.2
Fixes #
> fix: Increase the width of issue-relation-table

- shell/app/org-home/stores/org.tsx
fix: fix freshMan url redirect
❎ No
| 🇺🇸 English |      fix: fix freshMan url redirect        |
| 🇨🇳 中文    |     fix: 修复freshMan路由刷新后重定向         |
✅ Yes(version is required) release/1.2
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=210283&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
> fix: fix freshMan url redirect

- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
- shell/app/modules/application/services/build.ts
- shell/app/modules/application/stores/build.ts
- shell/app/modules/application/types/build.d.ts
feat: update pipeline task api
❎ No
❎ No
Fixes #
> feat: update pipeline task api

- shell/app/config-page/components/file-tree/file-tree.scss
- shell/app/modules/project/common/components/pipeline-manage/index.scss
fix file-tree style bug caused by Tree upgrade.
->
❎ No
Fixes #
> fix: file-tree style bug caused by Tree upgrade

- shell/app/common/__tests__/constants.test.tsx
- shell/app/common/constants.ts
- shell/app/common/utils/go-to.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
- shell/app/modules/msp/stores/micro-service.tsx
- shell/app/modules/project/pages/settings/components/project-cluster.tsx
feat: collect all doc url
❎ No
❎ No
Fixes #
> feat: collect all doc url

- scheduler/src/proxy.ts
parse org from req url in scheduler
❎ No
❎ No
Fixes #
> feat(scheduler): parse org from req url

- scheduler/src/proxy.ts
change url to origin url in order to get the url which contains org
❎ No
❎ No
Fixes #
> fix(scheduler): get orgin url from request.originUrl

- modules/market/package.json
- pnpm-lock.yaml
mistaken remove babel-plugin-import from market which caused build crash.
❎ No
❎ No
Fixes #
> fix(market): rollback package dependency change

- shell/app/views/index.ejs
Re add about layout script
❎ No
❎ No
Fixes #
> fix: Re add about layout script

- pnpm-lock.yaml
- shell/package.json
1. i18n footer button about Modal;
2. fix that can't click sort method;
the same as pr [https://github.com/erda-project/erda-ui/pull/1018]
❎ No
❎ No
Fixes #
> fix: upgrade dashboard to version 1.0.28

- pnpm-lock.yaml
- shell/package.json
1. i18n footer button about Modal
2. fix that can't click sort method
❎ No
release/1.2
Fixes #
> fix: fix i18n about Modal footer 

- shell/app/modules/msp/components/time-select.tsx
- shell/app/modules/msp/monitor/topology/pages/topology-dashboard/index.tsx
fix relative time calculation method
❎ No
❎ No
Fixes #
> fix relative time calculation method

- shell/app/common/services/index.ts
feat: update erda config protocol api
❎ No
| 🇺🇸 English |         |
| 🇨🇳 中文    |          |
❎ No
Fixes #
> feat: update erda config protocol api

- pnpm-lock.yaml
- shell/package.json
i18n dashboard that are built-in
❎ No
❎ No
Fixes #
> fix: i18n built-in dashboard

- shell/app/common/components/use-hooks.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
- shell/app/modules/msp/services/topology-service-analyze.ts
- shell/app/modules/msp/stores/topology-service-analyze.ts
- shell/app/modules/msp/types/topology-service-analyze.d.ts
add sorting method for trace detail
❎ No
| 🇺🇸 English | trace list support sort by duration |
| 🇨🇳 中文    | 追踪详情列表支持按耗时排序 |
release/1.2
Fixes #
> add sorting method for trace detail

- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
- shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
feat: add pipeline link in project-level-app pipeline detail
❎ No
| 🇺🇸 English |    feat: add pipeline link in project-level-app pipeline detail          |
| 🇨🇳 中文    |   feat: 项目级应用流水线执行详情中，新增流水线跳转链接        |
❎ No
Fixes #
> feat: add pipeline link in project-level-app pipeline detail

- shell/app/common/components/use-hooks.tsx
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
- shell/app/modules/msp/services/topology-service-analyze.ts
- shell/app/modules/msp/stores/topology-service-analyze.ts
- shell/app/modules/msp/types/topology-service-analyze.d.ts
* feat(msp): add sorting method for trace detail
* feat(msp): add pagination for trace detail
(cherry picked from commit 129551040c8986e6155b57132c4c54ca590eaa97)
add sorting method for trace detail
❎ No
| 🇺🇸 English | trace list support sort by duration |
| 🇨🇳 中文    | 追踪详情列表支持按耗时排序 |
❎ No
Fixes #
> add sorting method for trace detail (#1030)

- scheduler/src/proxy.ts
add dev referer header in case open api upgrade
❎ No
❎ No
Fixes #
> feat(scheduler): add dev referer in case open api upgrade

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
rename columns name & modify dataIndex
❎ No
❎ No
Fixes #
> rename columns name & modify dataIndex

- shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
fix docs show bug when api-design change branch after search.
❎ No
❎ No
Fixes #
> fix: api-design change branch after search bug

- shell/app/common/components/contractive-filter.tsx
- shell/app/modules/project/pages/backlog/backlog.tsx
- shell/app/modules/project/types/issue-workflow.d.ts
- shell/app/styles/antd-extension.scss
enhance filter condition in backlog
| 🇺🇸 English |    enhance filter condition in backlog          |
| 🇨🇳 中文    |     优化待处理的过滤筛选         |
> feat(dop): enhance filter condition in backlog

- shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
- shell/app/modules/msp/services/topology-service-analyze.ts
- shell/app/modules/msp/stores/topology-service-analyze.ts
❎ No
| 🇺🇸 English | add limit for trace detail list |
| 🇨🇳 中文    | 追踪详情列表增加条数限制 |
release/1.2
Fixes #
> add limit for trace detail

- shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
- shell/app/modules/msp/services/topology-service-analyze.ts
- shell/app/modules/msp/stores/topology-service-analyze.ts
(cherry picked from commit 83a5a65612b83efd5c8537607a58a9dc0c9c4bce)
add limit for trace detail list
❎ No
| 🇺🇸 English | add limit for trace detail list |
| 🇨🇳 中文    | 追踪详情列表增加条数限制 |
❎ No
Fixes #
> add limit for trace detail & remove pagination (#1042)

- shell/app/config-page/components/table/table.tsx
- shell/app/modules/msp/stores/micro-service.tsx
fix: fix typo
❎ No
❎ No
Fixes #
> fix: fix typo

- shell/app/modules/apiManagePlatform/configs.ts
api-design content-type text change.
❎ No
❎ No
Fixes #
> fix: api-design content-type text change

- cspell.json
- pnpm-lock.yaml
- scheduler/.gitignore
- scheduler/package.json
- scheduler/src/filters/error-catch.filter.ts
- scheduler/src/main.ts
- scheduler/src/middlewares/guard.middleware.ts
- scheduler/src/proxy.ts
- scheduler/src/util.ts
introduce winston(like log4j for Java) to handle log process. Logs of scheduler will looks like below
❎ No
❎ No
Fixes #
> feat(scheduler): introduce winston to handle log process

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/apiManagePlatform/pages/api-market/design/api-doc-tree.tsx
- shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
Change api-design empty page text.
| 🇺🇸 English |. api-design empty page text.  |
| 🇨🇳 中文    | 改变api设计空页面的文字。 |
❎ No
Fixes #
> feat: api-design empty page text change

- shell/app/common/components/contractive-filter.tsx
- shell/app/modules/msp/monitor/trace-insight/components/duration.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
replace contractive filter
❎ No
❎ No
Fixes #
> replace contractive filter

- shell/app/yml-chart/chart/config.ts
fix pipeline style bug in Safari.
->
| 🇺🇸 English |  Fixed pipeline line style bug in Safari. |
| 🇨🇳 中文    | 修复了流水线页面在Safari浏览器上线条的样式问题。 |
❎ No
Fixes #
> fix: pipeline style bug in Safari

- shell/app/config-page/index.tsx
- shell/app/modules/application/pages/pipeline/index.tsx
- shell/app/modules/project/pages/issue/issue-protocol.tsx
fix pipeline and issue page update bug when page go back.
❎ No
❎ No
Fixes #
> fix: pipeline and issue page update bug when page go back

- scheduler/package.json
- shell/app/common/components/members-table.tsx
- shell/app/user/stores/_perm-org.ts
admin member table missing delete operation
❎ No
❎ No
Fixes #
> fix: admin member table missing delete operation

- shell/app/modules/org/common/audit-render.tsx
Render scope key 'system' not match backend key 'sys';
❎ No
❎ No
Fixes #
> fix: audit renderer scope not match backend key

- shell/app/modules/apiManagePlatform/pages/api-market/design/index.tsx
Api-design allow external repo.
❎ No
| 🇺🇸 English | Api-design allow external repo. |
| 🇨🇳 中文    | Api设计允许外部仓库。 |
❎ No
Fixes #
> feat: api-design allow external repo

- shell/app/common/components/contractive-filter.scss
- shell/app/common/components/contractive-filter.tsx
feat: add contractive filter quick delete
| 🇺🇸 English |    feat: add contractiveFilter quickDelete           |
| 🇨🇳 中文    |    feat: contractiveFilter 添加删除功能          |
❎ No
Fixes #
> feat: add contractive filter quick delete 

- shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
Search by topic field in the MQ page
❎ No
❎ No
Fixes #
> fix: search by topic field in mq page

- shell/app/views/index.ejs
update iconpark url
❎ No
❎ No
Fixes #
> update iconpark url

- shell/app/modules/application/pages/pipeline/run-detail/build-detail.scss
- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
> style: optimize style of build detail page

- shell/app/modules/org/common/audit-templates.json
fix: add runtime audit template
❎ No
| 🇺🇸 English |      add runtime audit template        |
| 🇨🇳 中文    |       增加部署审计模板       |
❎ No
Fixes #
> fix: add runtime audit template

- shell/app/modules/cmp/common/alarm-strategy/index.tsx
- shell/app/modules/msp/alarm-manage/alarm-strategy/pages/alarm-index/index.tsx
hide application in msp project
❎ No
❎ No
Fixes #
> hide application in msp project

- shell/app/modules/msp/env-setting/configuration/index.tsx
change the border style
❎ No
Fixes #
> feat(msp): change the border style

- shell/app/modules/project/common/components/issue/edit-issue-drawer.tsx
add complexity to bug issue
release/1.2
Fixes #
> fix: add complexity to bug issue

- shell/app/modules/org/common/audit-templates.json
Add audit template for test plan archive and issue state
❎ No
❎ No
Fixes #
> Add audit template for test plan archive and issue state

- README.md
- docs/introduction_en.md
- docs/introduction_zh.md
> docs: add technology stack and architecture introduction

- shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
Fix that request slow trace without the lastest time
❎ No
❎ No
Fixes #
> fix: request slow trace without lastest time

- cli/README.md
- cli/package.json
❎ No
| 🇺🇸 English |     update the repository and homepage of readme content of cli, and remove the useless command description         |
| 🇨🇳 中文    |      跟新了erda-ui/cli中readme的仓库地址，主页地址，同时更新了readme中command指令的内容        |
❎ No
Fixes #
update the readme content of erda-ui/cli
> fix: update the readme content of erda-ui/cli

- scheduler/src/proxy.ts
Fix scheduler type check error.
❎ No
❎ No
Fixes #
> fix: scheduler type check error

- shell/tools/comparison.js
Compare the specified branch on Github with zh.json locally.
❎ No
| 🇺🇸 English ||
| 🇨🇳 中文    |    |
❎ No
Fixes #
> feat: international text comparision

- shell/app/common/utils/go-to.tsx
- shell/app/modules/cmp/common/alarm-record/index.tsx
- shell/app/modules/cmp/common/custom-dashboard/custom-dashboard.tsx
- shell/app/modules/cmp/common/custom-dashboard/index.tsx
fix msp dashboard url
❎ No
❎ No
Fixes #
> fix msp dashboard url

- shell/app/common/components/contractive-filter.tsx
- shell/app/common/components/tags-row.scss
- shell/app/config-page/components/contractive-filter/contractive-filter.tsx
- shell/app/config-page/components/table/render-types.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-detail.tsx
- shell/app/modules/cmp/router.js
fix: fix k8s bugs
❎ No
❎ No
Fixes #
> fix: fix k8s bugs

- shell/app/modules/msp/env-setting/configuration/index.tsx
- shell/app/modules/msp/services/configuration.ts
- shell/app/modules/msp/types/configuration.d.ts
add loading status and change the button position
❎ No
❎ No
Fixes #
> feat(msp): add loading status and change the button position

- scheduler/src/filters/not-found.filter.ts
- shell/app/modules/runtime/pages/overview/components/service-card.tsx
* error list maybe empty.
* add tip for start scheduler.
❎ No
❎ No
Fixes #
> fix(dop): runtime service errors maybe empty

- shell/app/modules/msp/env-overview/topology/pages/topology/topology.tsx
fix topology params name
❎ No
❎ No
Fixes #
> fix topology params name

- pnpm-lock.yaml
- shell/app/modules/msp/monitor/service-list/pages/transaction.tsx
- shell/app/styles/antd-extension.scss
- shell/package.json
1. fix that content overflow
2. button in the dashboard is modified to text type
3. callType has no value, should not be in query
❎ No
❎ No
Fixes #
> fix: modify  the content displaying in transaction

- shell/app/modules/msp/monitor/trace-insight/components/duration.tsx
fix: fix duration is decimal
❎ No
❎ No
Fixes #
> fix: fix duration is decimal

- cli/bin/erda.ts
- cli/lib/comparison-build.ts
- cli/package.json
in order to speed up build process in pipeline, we need a script to compare commit sha between previous build and current HEAD. if changes detected then, start building otherwise, skip build and reuse last built
❎ No
❎ No
Fixes #
> add comparison build script

- pnpm-lock.yaml
- shell/package.json
Fix that input width of modal in dashboard
❎ No
❎ No
Fixes #
> fix: input width of modal in dashboard

- scheduler/src/controllers/uc.controller.ts
- shell/app/common/components/contractive-filter.tsx
- shell/app/common/components/tags-row.scss
- shell/app/common/components/tags-row.tsx
- shell/app/common/utils/index.ts
- shell/app/config-page/components/index.tsx
- shell/app/config-page/components/table/render-types.tsx
- shell/app/config-page/components/tags/tags.spec.d.ts
- shell/app/config-page/components/tags/tags.tsx
- shell/app/config-page/config-page.d.ts
- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/cmp/common/cluster-terminal/xterm-binary.tsx
- shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-terminal.tsx
- shell/app/styles/antd-extension.scss
> fix:  fix k8s bugs

- pnpm-lock.yaml
- pnpm-workspace.yaml
fix: add uc in pnpm workspace
❎ No
❎ No
Fixes #
> fix: add uc in pnpm workspace

- shell/app/config-page/components/file-tree/file-tree.scss
- shell/app/config-page/components/file-tree/file-tree.tsx
- shell/app/styles/antd-extension.scss
Fix file-tree node could not be moved and tree style bug.
->
❎ No
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=221806&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=221826&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRU …
> fix: file-tree node could not be moved and tree style bug

- shell/app/common/utils/go-to.tsx
msp swich-environment problem
❎ No
❎ No
Fixes #
> fix(msp): msp swich-environment problem

- core/package.json
- modules/uc/package.json
- pnpm-lock.yaml
- shell/package.json
Fix security alerts.
❎ No
❎ No
Fixes #
> chore: fix package security alerts

- shell/app/yml-chart/common/pipeline-node-drawer.tsx
- shell/app/yml-chart/pipeline-editor.tsx
fix: fix old action form error
❎ No
| 🇺🇸 English |  fix: fix action form edit struct-array error            |
| 🇨🇳 中文    |  fix: 修复action表单中编辑数组对象结构错误            |
release/1.2
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=221774&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG
> fix: fix old action form error

- shell/app/config-page/components/contractive-filter/contractive-filter.tsx
pick contractive-filter from v1.3
❎ No
❎ No
Fixes #
> pick contractive-filter from v1.3

- erda.yml
- shell/app/common/utils/go-to.tsx
- shell/app/config-page/components/table/table.scss
- shell/app/modules/cmp/router.js
- shell/app/styles/antd-extension.scss
fix: add uc test addr / fix router in cmp
❎ No
❎ No
Fixes #
> fix: add uc test addr / fix router in cmp

- modules/uc/package.json
- pnpm-lock.yaml
fix compile error
❎ No
release/1.3
Fixes #
> fix: compile error caused by latest postcss version

- erda.yml
fix: delete test uc addr
❎ No
release/1.3
Fixes #
> fix: delete test uc addr

- shell/app/modules/apiManagePlatform/router.ts
- shell/app/modules/application/router.js
temporarily hide API design
❎ No
❎ No
Fixes #
> temporarily hide API design

- shell/app/common/utils/go-to.tsx
- shell/app/modules/msp/stores/micro-service.tsx
msp swich-environment problem
❎ No
release/1.3
Fixes #
> Hotfix/msp swich-environment problem

- shell/app/modules/msp/env-setting/configuration/index.tsx
add translation
❎ No
release/1.3
Fixes #
> feat(msp): add translation

- modules/uc/package.json
- modules/uc/src/router.tsx
- pnpm-lock.yaml
fix: fix uc dep
❎ No
release/1.3
Fixes #
> fix: fix uc dep

- shell/app/common/utils/go-to.tsx
msp switch-environment problem
❎ No
release/1.3
Fixes #
> fix(msp): msp switch-environment problem

- shell/app/modules/runtime/common/logs/components/log-filter.tsx
default 10 minutes
❎ No
❎ No
Fixes #
> default 10 minutes for v1.2

- shell/app/modules/runtime/common/logs/components/log-filter.tsx
default 10 minutes
❎ No
release/1.3
Fixes #
> default 10 minutes

- cli/lib/build.ts
- scheduler/src/proxy.ts
- scheduler/src/util.ts
remove mask of fdp
❎ No
release/1.3
Fixes #
> fix(scheduler): remove fdp mask

- erda.yml
- scheduler/src/filters/not-found.filter.ts
- shell/app/App.tsx
- shell/app/interface/global.d.ts
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/org-home/router.js
Add env variable to control ecp exist.
❎ No
release/1.3
Fixes #
> feat: add env variable to enable edge computing platform or not

- shell/app/common/components/tiled-filter.scss
- shell/app/common/components/tiled-filter.tsx
- shell/app/config-page/components/table/render-types.tsx
- shell/app/configForm/editor/form-preview.tsx
- shell/app/modules/cmp/common/cluster-terminal/xterm-channel.tsx
fix: fix k8s terminal set size
❎ No
✅ Yes(version is required) 
release/1.3
Fixes #
> fix: fix k8s terminal set size

- shell/app/menus/application.tsx
show api design
❎ No
release/1.3
Fixes #
> show api design

- shell/app/common/components/edit-field.tsx
resolve conflict and pick
❎ No
❎ No
Fixes #
> fix(dop): pick markdown edit field not save content to 1.3

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/application/pages/deploy-list/deploy-list.tsx
Id filter add number validator in my approve.
❎ No
| 🇺🇸 English | In my approve, id filter add number validator. |
| 🇨🇳 中文    |  我审批的页面中，id过滤框新增数字校验。  |
release/1.2
release/1.3
Fixes # https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=218631&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMTIxNCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
> fix: id filter add number validator in my approve

- shell/app/locales/en.json
- shell/app/locales/zh.json
- shell/app/modules/msp/env-setting/configuration/index.tsx
modify msp modal style
release/1.3
Fixes #
> modify msp modal style

- shell/app/modules/msp/env-setting/configuration/index.tsx
add see detail permission
release/1.3
Fixes #
> add see detail permission

- erda.yml
- modules/uc/src/common/utils.ts
- modules/uc/src/locales/en.json
- modules/uc/src/locales/zh.json
- modules/uc/src/pages/registration/index.tsx
- scheduler/src/proxy.ts
fix: uc proxy 
❎ No
release/1.3
Fixes #
> fix: uc proxy 

- shell/app/common/components/tiled-filter.tsx
add tiled filter dropdown select
| 🇺🇸 English |            |
| 🇨🇳 中文    |             |
release/1.3
Fixes #
> fix: add tiled filter dropdown select

- shell/app/config-page/components/chart-dashboard/chart-dashboard.spec.d.ts
- shell/app/config-page/components/chart-dashboard/chart-dashboard.tsx
- shell/app/config-page/components/index.tsx
- shell/app/config-page/config-page.d.ts
feat: add cp chart dashboard
❎ No
| 🇺🇸 English | feat: add cp chart dashboard           |
| 🇨🇳 中文    |  feat: 组件化添加大盘组件            |
❎ No
Fixes #
> feat: add cp chart dashboard

- shell/app/modules/project/pages/test-plan/test-plan.tsx
- shell/app/modules/project/stores/test-plan.ts
fix manual test filter issue
❎ No
release/1.3
Fixes #
https://erda-org.app.terminus.io/erda/dop/projects/387/issues/all?id=222616&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTA5MTgiLCIxMDAwNTYyIiwiMTAwMTA3NSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
https://erda-org.app.terminus.io/erda/dop/projects/387/issues/all?id=222627&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZW …
> fix(dop): fix manual test filter issue

- shell/app/modules/addonPlatform/pages/common/components/addon-detail-drawer.tsx
- shell/app/modules/project/pages/test-plan/test-plan.tsx
fix: fix refresh test plan list after edit
❎ No
| 🇺🇸 English |  fix: fix refresh test plan list after edit            |
| 🇨🇳 中文    |   fix: 修复测试计划修改后刷新列表为当前页           |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222767&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=221144&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05UR …
> fix: fix refresh test plan list after edit

- shell/app/modules/org/common/audit-render.tsx
Add render scope type
❎ No
release/1.3
Fixes #
> feat: support epic type in audit template renderer

- modules/uc/package.json
- modules/uc/src/common/utils.ts
- modules/uc/src/locales/en.json
- modules/uc/src/locales/zh.json
- pnpm-lock.yaml
- scheduler/src/proxy.ts
fix: fix uc proxy
❎ No
release/1.3
Fixes #
> fix: fix uc proxy/password valid / 

- shell/app/modules/msp/env-setting/configuration/index.tsx
modify modal
❎ No
release/1.3
Fixes #
> Modify redundant code in modal

- shell/app/common/__tests__/components/edit-field.test.tsx
- shell/app/common/__tests__/components/tags-row.test.tsx
- shell/app/common/__tests__/utils/index.test.tsx
update test case
❎ No
❎ No
Fixes #
> update test case

- core/src/nusi/index.tsx
Remove useless nusi code.
❎ No
❎ No
Fixes #
> fix: remove useless nusi code

- core/src/nusi/wrapped-table.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
wrapped table action column add divider.
❎ No
release/1.3
Fixes #
> fix: wrapped table action column add divider

- shell/app/modules/project/common/components/pipeline-manage/run-detail/record-list.tsx
- shell/app/modules/project/services/auto-test-case.ts
fix: fix project-pipeline pageNo change error
❎ No
| 🇺🇸 English |    fix: fix project-pipeline pageNo change error          |
| 🇨🇳 中文    |   fix:修复项目级流水线翻页错误           |
release/1.2    release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222133&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
> fix: fix project-pipeline pageNo change error

- shell/app/common/components/tags-row.scss
- shell/app/common/components/tags-row.tsx
- shell/app/common/components/tiled-filter.scss
- shell/app/config-page/components/chart/chart.scss
- shell/app/config-page/components/chart/chart.spec.d.ts
- shell/app/config-page/components/chart/chart.tsx
- shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
- shell/app/modules/cmp/pages/cluster-manage/cluster-terminal.tsx
- shell/app/modules/cmp/router.js
- shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
- shell/app/modules/dop/router.js
fix: fix k8s style bugs
❎ No
| 🇺🇸 English |     fix: fix k8s style bugs         |
| 🇨🇳 中文    |   fix: 修复k8s页面样式问题           |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=222905&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
> fix: fix k8s style bugs

- cli/lib/build.ts
- shell/app/common/utils/go-to.tsx
- shell/app/layout/pages/page-container/components/menu-head.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
- shell/app/layout/stores/layout.ts
- shell/app/menus/appCenter.tsx
- shell/app/org-home/stores/org.tsx
- shell/webpack.config.js
entirely remove fdp mask
❎ No
❎ No
Fixes #
> refactor(common): entirely remove fdp mask

- shell/app/modules/msp/env-setting/configuration/index.tsx
- shell/app/modules/msp/types/configuration.d.ts
Access configuration page interface modification parameters
❎ No
release/1.3
Fixes #
> feat(msp): Access configuration page interface modification parameters

- pnpm-lock.yaml
- shell/package.json
copy table cell in dashboard
❎ No
❎ No
Fixes #
> feat: copy table cell in dashboard

- shell/app/common/stores/monitorCommon.ts
- shell/app/modules/cmp/stores/_common-custom-dashboard.ts
- shell/app/modules/msp/env-overview/topology/pages/topology-dashboard/index.tsx
- shell/app/modules/msp/env-overview/topology/pages/topology/topology.tsx
- shell/app/modules/msp/monitor/api-insight/common/components/filterNav.tsx
- shell/app/modules/msp/monitor/api-insight/pages/indices/index.tsx
- shell/app/modules/msp/monitor/application-insight/common/components/tab-right.tsx
- shell/app/modules/msp/monitor/browser-insight/pages/page/page.tsx
- shell/app/modules/msp/monitor/external-insight/common/components/tab-right.tsx
- shell/app/modules/msp/monitor/gateway-ingress/common/components/tab-right.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/ajax/ajax.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/app/app.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/browser/browser.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/comparative/comparative.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/geography/geography-china.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/overview/overview.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/page/page.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/position/position.tsx
- shell/app/modules/msp/monitor/mobile-insight/pages/script/script.tsx
- shell/app/modules/msp/monitor/monitor-common/components/appGroupSelector.tsx
- shell/app/modules/msp/monitor/monitor-common/components/moduleSelector.tsx
- shell/app/modules/msp/monitor/monitor-common/components/top-tab-right.tsx
- shell/app/modules/msp/monitor/service-insight/common/components/instanceSelector.tsx
- shell/app/modules/msp/monitor/service-insight/common/components/tab-right.tsx
replace all timeSelector in msp
according to query initialize timeSelector
❎ No
release/1.3
Fixes #
> replace all timeSelector in msp

- shell/app/modules/runtime/common/logs/components/container-log.jsx
fix the bug that log time repeated
❎ No
| 🇺🇸 English | fix the bug that log time repeated |
| 🇨🇳 中文    | 修复了日志时间重复的bug |
❎ No
Fixes #
> fix the bug that log time repeated

- core/package.json
- core/src/common/components/title.scss
- core/src/common/components/title.tsx
- core/src/nusi/index.tsx
Replace Nusi Title.
❎ No
❎ No
Fixes #
> refactor: replace Nusi Title

- shell/app/common/components/tags-row.scss
- shell/app/common/components/tags-row.tsx
- shell/app/common/components/tiled-filter.tsx
- shell/app/config-page/components/api-editor/api-editor.tsx
- shell/app/config-page/components/table/table.tsx
- shell/app/modules/dcos/pages/cluster-dashboard/index.scss
- shell/app/modules/dcos/pages/cluster-dashboard/index.tsx
fix: fix k8s styles
❎ No
release/1.3
Fixes #
> fix: fix k8s styles

- shell/app/config-page/components/table/table.tsx
- shell/app/layout/pages/page-container/components/sidebar.tsx
fix: fix cp table change page error
❎ No
| 🇺🇸 English |   fix: fix cp table change page error           |
| 🇨🇳 中文    |  fix: 修复组件化协议中table翻页错误            |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=223100&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
> fix: fix cp table change page error

- core/src/nusi/index.tsx
- shell/app/common/components/tree/tree.tsx
- shell/app/config-page/components/file-tree/file-tree.tsx
Replace Nusi Popover.
❎ No
❎ No
Fixes #
> refactor: replace Nusi Popover

- erda.yml
fix: delete useless env UC_PUBLIC_URL
❎ No
| 🇺🇸 English |    fix: delete useless env UC_PUBLIC_URL          |
| 🇨🇳 中文    |     fix: 去除UC_PUBLIC_URL环境变量       |
release/1.3
Fixes #
https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=223150&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAzOTAiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG
> fix: delete useless env UC_PUBLIC_URL

- shell/app/modules/runtime/common/logs/components/container-log.jsx
fix the bug that log time repeated
❎ No
| 🇺🇸 English | fix the bug that log time repeated |
| 🇨🇳 中文    | 修复了日志时间重复的bug |
release/1.3
Fixes #
> fix(msp): fix the bug that log time repeated

- core/webpack.config.js
fix core webpack config
❎ No
release/1.3
Fixes #
> fix core webpack config

- nginx.conf.template
- shell/app/common/components/time-select/common.ts
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
1. fix that organization starts with 'ta'
2. remove customMap , it excludes other time range
❎ No
❎ No
Fixes #
> fix: organization starts with ta

- core/package.json
- core/src/common/components/form-builder/readonly-field.tsx
- core/src/common/components/title.tsx
- pnpm-lock.yaml
Fix Title bugs caused by replace Nusi Title.
❎ No
❎ No
Fixes #
> fix: Title bugs caused by replace Nusi Title

- pnpm-lock.yaml
- shell/app/common/components/time-select/common.ts
- shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
- shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-graph/index.tsx
1. remove customMap, related with [https://github.com/erda-project/erda-ui/pull/1231](url)
2. refactor code, related with [https://github.com/erda-project/erda-ui/pull/1218](url)
❎ No
release/1.3
Fixes #
> fix: remove customMap and refactor code

- nginx.conf.template
- shell/app/views/index.ejs
modify '/ta' to '/static/ta' in nginx and ejs
❎ No
❎ No
Fixes #
> fix: modify '/ta' to '/static/ta' in nginx and ejs

- shell/app/modules/org/common/audit-templates.json
fix: add scaleRuntime audit key
❎ No
[【审计日志】runtime扩缩容操作日志显示错误](https://erda.cloud/erda/dop/projects/387/issues/all?id=224203&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls1MDZdLCJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyNjEiXX0%3D&issueGantt__urlQuery=eyJ0b3RhbCI6MzQsInBhZ2VObyI6MSwicGFnZVNpemUiOjIwMCwiaXNzdWVWaWV3R3JvdXBWYWx1ZSI6ImdhbnR0IiwiSXNzdWVUeXBlIjoiQUxMIn0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=BUG)
Fixes #
> fix: add scaleRuntime audit key

- shell/app/org-home/stores/org.tsx
orgName end of slash in url
❎ No
release/1.2
release/1.3
Fixes #
> fix: orgName end of slash in url
