erda-project/erda-ui

shell/app/layout/pages/page-container/components/announcement/index.tsx
shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.scss

Pipeline action and announcement scroll optimization.
Fixes #
- [Erda Cloud Issue Link1](https://erda.cloud/erda/dop/projects/387/issues/all?id=288995&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
- [Erda Cloud Issue Link2](https://erda.cloud/erda/dop/projects/387/issues/all?id=289275&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
✅ Yes(screenshot is …

fix(common): pipeline action and announcement scroll optimization

---

shell/app/common/components/load-more-selector/index.scss

(cherry picked from commit a29232f9fee8b055ae7e68fd6eb88d47a0f8382b)
fix(dop): revert load more selector style
Fixes #
❎ No
❎ No

fix(dop): revert load more selector style (#3079)

---

shell/app/common/components/edit-field/index.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/issue-drawer.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx

issue create relation style
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=290157&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOlsxMTE1XSwic3RhdGVzIjpbNzEwNCw3MTA1LDQ0MDMsNDQwMiw0NDA2LDQ0MDcsNDUzOCw0NDEyLDQ0MTVdLCJhc3NpZ25lZUlEcyI6WyIyNCIsIjEwMDAzMDAiLCIxMDAwNTYyIiwiMTAwMDcyMyIsIjEwMDEwNzUiLCIxMDAxMjE0IiwiMTAzOTAiLCIxMDkxOCIsIjEwMDE1NzkiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1115&type=BUG)
| 🇺🇸 English |  fix issue create relation input style   |
| 🇨🇳 中文    |  修复创建事项关联输入框样式问题|
❎ No

fix(dop): issue create relation style

---

shell/app/modules/application/tabs.tsx
shell/package.json

update application tab
Fixes #
| 🇺🇸 English |  update application tab order  |
| 🇨🇳 中文    |   更新应用 tab 顺序  |
❎ No

feat: update app tab order

---

shell/app/common/utils/go-to.tsx
shell/app/interface/global.d.ts
shell/app/modules/project/pages/release/components/application-detail.tsx
shell/app/modules/project/pages/release/components/form.tsx
shell/app/modules/project/pages/release/components/project-detail.tsx
shell/app/modules/project/router.tsx

Project release detail back list optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=289334&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=TASK)
❎ No
| 🇺🇸 English |  Project artifacts and driller pages in test management return to unity.   |
| 🇨🇳 中文    |  项目制品以及测试管理中的下钻页面返回统一。  |
❎ No

fix(dop): project release detail back list optimization

---

shell/app/modules/project/pages/release/release-protocol.tsx

Project release table reference release operation optimization.
Fixes #
❎ No
| 🇺🇸 English |  When jumping to the list of application products, filter "Show only latest version products" is set to no.  |
| 🇨🇳 中文    |  项目制品表格查看引用制品操作跳转至应用制品列表时，筛选项“只显示版本最新制品”置为否。  |
❎ No

fix(dop): project release table reference release operation optimization

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/yml-chart/common/pipeline-node-drawer.tsx

Fix pipeline action page error.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=290901&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English |  Fixed a bug where the action click interface of the project package release was incorrectly reported.  |
| 🇨🇳 中文    | 修复了项目打包发布制品的 action 点击界面报错的bug。  |
❎ No

fix(dop): pipeline action page error

---

shell/app/modules/project/pages/release/components/addon.scss
shell/app/modules/project/pages/release/components/addon.tsx
shell/app/modules/project/pages/release/components/project-detail.tsx
shell/app/modules/project/types/release.d.ts

Project release detail add addons.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=284451&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=REQUIREMENT)
| 🇺🇸 English |  Addons information added to Addon project level Artifacts Management details.  |
| 🇨🇳 中文    |  项目级制品管理详情中增加addons信息。  |
❎ No

feat(dop): project release detail add addons

---

shell/app/config-page/components/table/v2/utils.tsx

fix title display exception
Fixes #
❎ No
| 🇺🇸 English | fix title display exception |
| 🇨🇳 中文    | 修复 title 显示异常 |
❎ No

fix(common): fix title display exception

---

shell/app/modules/project/pages/release/release-protocol.tsx

Fix project release tabs change bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291315&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
❎ No
| 🇺🇸 English |   Clears the value of the filter when the item artifacts TAB switches.   |
| 🇨🇳 中文    |   当项目制品标签页切换时，清空筛选器的值。   |
❎ No

fix(dop): project release tabs change bug

---

shell/app/config-page/components/pie-chart/pie-chart.tsx

fix: fix cmp pods chart style
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=288916&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English |  fix: fix cmp pods chart style            |
| 🇨🇳 中文    |  fix: 修复cmp pods界面图标chart样式问题           |
❎ No

fix: fix cmp pods chart style

---

shell/app/config-page/config-page.d.ts
shell/app/config-page/index.tsx
shell/app/config-page/page-render.tsx

feat: add config page parallel load
Fixes #
mock场景，自动切换tab
| 🇺🇸 English |      feat: add config page parallel load        |
| 🇨🇳 中文    |     feat: 组件化协议添加parallel load处理         |
❎ No

feat: add config page parallel load

---

shell/app/common/components/markdown-editor/index.scss
shell/app/common/components/markdown-editor/index.tsx
shell/app/modules/project/common/components/issue/add-mr-relation.tsx
shell/app/modules/project/common/components/issue/comment-box.scss
shell/app/modules/project/common/components/issue/comment-box.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
shell/app/modules/project/common/components/issue/issue-activities.scss
shell/app/modules/project/common/components/issue/issue-activities.tsx
shell/app/modules/project/common/components/issue/issue-config.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/views/index.ejs
shell/index.html

update issue detail style
Fixes #
❎ No
| 🇺🇸 English |    update issue detail style   |
| 🇨🇳 中文    | 更新事项详情样式   |
❎ No

feat: update issue detail style

---

.github/workflows/codecov.yml
shell/app/common/components/tags-row/index.scss
shell/app/config-page/components/table/table.scss
shell/app/yml-chart/common/pipeline-node-drawer.tsx

Table columns text with tags width adjustment.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291702&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
->
| 🇺🇸 English |  Fixed a bug with special data column sizes in project artifacts tables.  |
| 🇨🇳 中文    |  修复了项目制品表格特殊数据列宽的bug。  |
❎ No

fix(common): table columns text with tags width adjustment

---

shell/app/modules/project/pages/release/release-protocol.tsx

Fix project release table double scroll bar bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291698&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
->
| 🇺🇸 English |   Fixed bug with double scrollbars on project artifacts page.   |
| 🇨🇳 中文    |  修复了项目制品页面双层滚动条的bug。  |
❎ No

fix(dop): project release table double scroll bar bug

---

shell/app/yml-chart/common/action-config-form.tsx

Pipeline action interface params add appId
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291383&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
❎ No
| 🇺🇸 English |  The application ID is added to the pass parameter of the pipeline node call interface, In order to solve the bug of not being able to select the handler when editing project level pipeline.  |
| 🇨🇳 中文    |  流水线节点调用接口的传参增加应用ID，为了解决项目级流水线编辑时不能选择处理人的bug。  |
❎ No

fix(dop): pipeline action interface params add appId   

---

shell/app/common/components/erda-icon/index.tsx
shell/app/common/components/tags-row/__tests__/index.test.tsx
shell/app/common/components/tags-row/index.tsx
shell/app/modules/org/pages/projects/project-list.tsx
shell/app/modules/project/pages/deploy/index.tsx
shell/app/modules/project/pages/release/release-protocol.tsx
shell/app/yml-chart/nodes/add-node.tsx

fix: fix icon tj1 is not exist
Fixes #
❎ No
| 🇺🇸 English |     fix: fix icon tj1 is not exist         |
| 🇨🇳 中文    |    fix:修复icon tj1不存在         |
❎ No

fix: fix icon tj1 is not exist

---

shell/app/common/components/configurable-filter/index.tsx

Fix configurable filter initial value bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=291847&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
| 🇺🇸 English | Fixed bug with initial values of project artifact filters.  |
| 🇨🇳 中文    |  修复了项目制品筛选器初始值的bug。  |
❎ No

fix(common): configurable filter initial value bug

---

shell/app/common/components/configurable-filter/config-selector.scss
shell/app/common/components/configurable-filter/config-selector.tsx
shell/app/common/components/configurable-filter/index.scss
shell/app/common/components/configurable-filter/index.tsx
shell/app/locales/en.json
shell/app/locales/zh.json

Configurable filter color optimization.
Fixes #
| 🇺🇸 English |  Filter color style adjustments can be configured.  |
| 🇨🇳 中文    | 可配置筛选器颜色风格调整。 |
❎ No

fix(common): configurable filter color optimization

---

shell/app/modules/application/common/app-selector.tsx

Apply for deployment modal style bug.
Fixes #
->
| 🇺🇸 English |  Fixed the bug of incorrect deployment style of network blocking application.  |
| 🇨🇳 中文    | 修复了封网申请部署样式错误的bug。  |
❎ No

fix(dop): apply for deployment modal style bug

---

erda.yml

remove expose port of enterprise-ui
Fixes #
[task](https://erda.cloud/erda/dop/projects/387/issues/all?id=291526&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDA2LDQ0MDddfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&type=TASK)
❎ No
| 🇺🇸 English |    remove expose port of enterprise-ui          |
| 🇨🇳 中文    |    移除enterprise-ui的公网暴露端口          |
❎ No

feat(common): remove expose port of enterprise-ui

---

shell/app/common/components/edit-field/index.scss
shell/app/common/components/edit-field/index.tsx
shell/app/common/components/markdown-editor/index.scss
shell/app/common/components/markdown-editor/index.tsx
shell/app/common/components/markdown-render/index.scss
shell/app/common/components/markdown-render/index.tsx
shell/app/interface/global.d.ts
shell/app/layout/stores/layout.ts
shell/app/modules/project/common/components/issue/add-mr-relation.tsx
shell/app/modules/project/common/components/issue/comment-box.scss
shell/app/modules/project/common/components/issue/comment-box.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
shell/app/modules/project/common/components/issue/issue-activities.scss
shell/app/modules/project/common/components/issue/issue-activities.tsx
shell/app/modules/project/common/components/issue/issue-drawer.scss
shell/app/modules/project/common/components/issue/issue-drawer.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/common/components/issue/issue-testCase-relation.tsx
shell/app/views/index.ejs
shell/index.html

update issue detail style
Fixes #
| 🇺🇸 English | update issue detail v3.1   |
| 🇨🇳 中文    |   更新修复事项详情样式问题   |
❎ No

feat(dop): update issue detail v3.1

---

shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx

fix alertRule option key
Fixes #
❎ No
| 🇺🇸 English | fix repeated alertRule option |
| 🇨🇳 中文    | 修复下拉列表重复 |
❎ No

fix(cmp): fix alertRule option key

---

shell/app/common/components/configurable-filter/index.scss
shell/app/modules/project/pages/backlog/backlog.tsx
shell/app/modules/project/pages/backlog/iteration-item.tsx
shell/app/modules/project/pages/ticket/index.tsx

Dop table optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=276159&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=TASK)
| 🇺🇸 English |  Unified optimization of to-do list, item list pager under uncompleted iteration to be processed, unified optimization of work list filter.  |
| 🇨🇳 中文    | 待处理列表、待处理未完成迭代下事项列表分页器统一优化，工单列表筛选器统一优化。  |
❎ No

fix(dop): dop table optimization

---

shell/app/common/components/configurable-filter/index.scss
shell/app/common/components/configurable-filter/index.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx

Issue detail relation table filter optimization
Fixes #
| 🇺🇸 English |  Item details reference filters containing item lists and item lists.  |
| 🇨🇳 中文    |  事项详情中引用包含事项列表的筛选器跟事项列表的统一。  |
❎ No

feat(dop): issue detail relation table filter optimization

---

shell/app/config-page/components/list/list.tsx

Auto test case pagination optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=276159&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=TASK)
| 🇺🇸 English |  The automated test case list pager style is uniform.  |
| 🇨🇳 中文    |  自动化测试用例列表分页器样式统一。  |
❎ No

fix(dop): auto test case pagination optimization

---

shell/app/modules/project/pages/backlog/backlog.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/pages/backlog/iteration-item.tsx
shell/app/modules/project/pages/data-source/index.tsx
shell/app/modules/project/pages/deploy/deploy-config/index.tsx
shell/app/modules/project/pages/deploy/deploy-config/list-edit.tsx
shell/app/modules/project/pages/deploy/deploy-config/text-edit.tsx
shell/app/modules/project/pages/issue/board.tsx
shell/app/modules/project/pages/issue/component/table-view.tsx
shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx
shell/app/modules/project/pages/iteration/table.tsx
shell/app/modules/project/pages/milestone/index.tsx
shell/app/modules/project/pages/milestone/milestone-group.tsx
shell/app/modules/project/pages/milestone/milestone-item.tsx
shell/app/modules/project/pages/plan-detail/index.tsx

Remove project any.
Fixes #
❎ No
| 🇺🇸 English | Remove any type from project.  |
| 🇨🇳 中文    |  移除部分project下的any类型。  |
❎ No

fix(dop): remove project any

---

shell/app/common/components/edit-field/index.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
shell/app/modules/project/common/components/issue/issue-activities.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/pages/backlog/issue-item.scss

fix(dop): issue detail page crash
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=293387&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English | fix issue detail page crash   |
| 🇨🇳 中文    |    修复事项详情页崩溃问题 |
release/2.1-beta.1

fix(dop): issue detail page crash

---

cli/lib/build-enterprise-online.ts
cli/lib/build-enterprise.ts
cli/lib/check-build-status.ts
cli/lib/util/i18n-config.ts
core/src/index.tsx
cspell.json
docs/introduction_en.md
docs/introduction_zh.md
pipeline.yml
pnpm-lock.yaml
scheduler/src/proxy.ts
shell/package.json
shell/vite.config.js

adjust architecture to remove qiankun
Fixes #
❎ No
| 🇺🇸 English |   refactor the way to connect fdp ui           |
| 🇨🇳 中文    |   重构fdp ui接入方式           |
❎ No

feat: remove qiankun

---

shell/app/config-page/components/table/v2/utils.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline edit pipeline name.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=290538&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=TASK)
| 🇺🇸 English | You can change the project pipeline name. |
| 🇨🇳 中文    | 项目流水线名称支持修改。  |
❎ No

feat(dop): project pipeline edit pipeline name

---

Dockerfile
scheduler/src/proxy.ts

Upgrade docker image node version to 14.x
Fixes #
❎ No
| 🇺🇸 English |      Upgrade docker image node version to 14.x        |
| 🇨🇳 中文    |    升级前端镜像node版本到14.x          |
❎ No

feat(common): upgrade node version

---

core/src/utils/event-hub.ts

fix: fix event hub once prevent duplicate register
Fixes #
❎ No
| 🇺🇸 English | fix: fix event hub once prevent duplicate register             |
| 🇨🇳 中文    |    fix: 修复event hub once组织重复注册问题          |
r

fix: fix event hub once prevent duplicate register

---

shell/app/common/components/render-form-item/index.tsx

Select warm optimization when options do not match value type.
Fixes #
❎ No
| 🇺🇸 English |  Alarm optimization when the drop-down list does not match the value type.   |
| 🇨🇳 中文    | 下拉框选项跟值类型不符合时的告警优化。 |
release/2.1-beta.1

fix(dop): select warm optimization when options do not match value type

---

shell/app/common/components/configurable-filter/index.tsx

Fix configurable filter style bug.
Fixes #
->
| 🇺🇸 English |  Fixed a style bug where the borders of configurable filters were truncated.  |
| 🇨🇳 中文    |   修复了可配置筛选器边框被截断的样式bug。  |
release/2.1-beta.1

fix(common): configurable filter style bug

---

shell/app/modules/project/pages/issue/issue-protocol.tsx

Fixes #
❎ No
| 🇺🇸 English | fix the bug that an issue cannot be created |
| 🇨🇳 中文    |  修复不能创建 issue 的 bug |

fix(dop): fix cannot create issue

---

shell/app/modules/project/pages/issue/issue-protocol.tsx

fix cannot open issue from sharelink
Fixes #
❎ No
| 🇺🇸 English | fix cannot open issue from sharelink |
| 🇨🇳 中文    | 修复不能从分享链接打开 issue |

fix(dop): fix cannot open issue from sharelink

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/msp/env-overview/service-list/pages/transaction-detail.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.scss
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/topology-comp.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/index.tsx
shell/app/views/index.ejs
shell/index.html

Fixes #
❎ No
| 🇺🇸 English | drill down to the link in the topology |
| 🇨🇳 中文    | 拓扑图下钻到服务详情 |
❎ No

feat(msp): drill down to the service in the topology

---

shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx

Fix pipeline action link bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=294643&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English |  Fixed bug where pipeline node jump link error occurred in project package release.  |
| 🇨🇳 中文    |  修复了项目打包发布制品的流水线节点跳转链接错误的bug。  |

fix(dop): pipeline action link bug

---

core/src/utils/event-hub.ts
shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/common/components/issue/subscribers-selector.tsx
shell/app/modules/project/pages/backlog/backlog.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/pages/backlog/iteration-item.tsx
shell/app/modules/project/pages/issue/all.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx
shell/app/org-home/stores/org.tsx

* fix tab is mixed with type in issue share link 
* fix not refresh relations list after quick add backlog in ticket
* remember assignee after create issue
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=295108&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English |    fix not refresh relations list in ticket after quick add backlog     |
| 🇨🇳 中文    |   工单转待办后没有自动刷新   |

fix(dop): fix issue share link and not refresh relations list in ticket

---

pnpm-lock.yaml
shell/app/common/components/time-select/time-select.tsx
shell/app/modules/cmp/common/custom-dashboard/custom-dashboard.tsx
shell/app/modules/cmp/pages/middleware-dashboard/index.tsx
shell/app/modules/cmp/types/dashboard-model.d.ts
shell/package.json

style: upgrade dashboard to unified style of charts
Fixes #
| 🇺🇸 English | unified style of charts |
| 🇨🇳 中文    | 统一图表样式 |
❎ No

feat(msp): upgrade dashboard to unified style of charts

---

shell/app/config-page/components/file-tree/file-tree.tsx

fix: file tree expand error after drag node
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=294297&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English |  fix: file tree expand error after drag node            |
| 🇨🇳 中文    |    fix: 修复file tree组件拖拽后展开节点错误         |

fix: file tree expand error after drag node

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx

In "ALL" tab page, url will include all type state in filter, after open link, state will not match.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=293424&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIyNCJdLCJmaW5pc2hlZEF0U3RhcnRFbmQiOltudWxsLG51bGxdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1115&type=BUG)
❎ No
| 🇺🇸 English |   fix state filed show number in issue filter   |
| 🇨🇳 中文    |修复事项筛选中状态字段展示数字的问题    |

fix(dop): fix state filed show number in issue filter

---

locales/en.json
locales/zh.json
shell/app/common/utils/index.ts
shell/app/modules/apiManagePlatform/pages/access-manage/list/index.tsx
shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.scss
shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx
shell/app/modules/apiManagePlatform/pages/api-market/list/index.tsx
shell/app/modules/apiManagePlatform/pages/client/list/index.tsx
shell/app/modules/apiManagePlatform/services/api-export.ts
shell/app/modules/apiManagePlatform/types/api-market.d.ts

Fixes #
❎ No
| 🇺🇸 English | API market supports the export of API asset |
| 🇨🇳 中文    | API 集市支持导出 API 资源 |
❎ No

feat(dop): export api asset

---

shell/app/common/components/table/__tests__/index.test.tsx
shell/app/common/components/table/index.tsx
shell/test/extend-expect.d.ts
shell/test/extend-expect.ts

fix table sort
Fixes #
❎ No
| 🇺🇸 English | -  |
❎ No

feat(dop): fix table sort

---

shell/app/common/components/markdown-editor/editor.tsx
shell/app/modules/application/pages/repo/repo-commit.tsx
shell/app/modules/application/pages/test/test-detail.scss
shell/app/modules/application/pages/test/test-detail.tsx
shell/app/modules/application/stores/repo.ts

* fix ut detail style
* fix markdown editor upload image bug
Fixes #
->
| 🇺🇸 English |  fix unit test detail style |
| 🇨🇳 中文    |    修复单元测试详情样式问题   |

fix(dop): fix ut detail style

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/runtime/common/components/instance-table.tsx
shell/app/modules/runtime/pages/overview/components/index.tsx
shell/app/modules/runtime/pages/overview/components/service-card.tsx
shell/app/modules/runtime/types/service.d.ts

add job task in runtime
Fixes #
before：
after：
| 🇺🇸 English | add job type in artifact|
| 🇨🇳 中文    | 制品添加 job 类型 |
❎ No

feat(dop): add job type in artifact

---

shell/app/modules/project/pages/pipelines/components/form.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.scss
shell/app/modules/project/pages/pipelines/index.tsx
shell/app/modules/project/services/pipeline.tsx

project pipeline guides list
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=290533&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=TASK)
| 🇺🇸 English | Added a list of branch messages to the top of the project-level pipeline list. |
| 🇨🇳 中文    |  项目级流水线列表顶部增加分支消息列表。  |
❎ No

feat(dop): project pipeline guides list

---

shell/app/modules/project/common/components/pipeline-manage/config-detail/index.tsx
shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/case-yml-graphic-editor.tsx

fix: fix config-sheet request loop
Fixes #
❎ No
| 🇺🇸 English |    fix: fix config-sheet request loop          |
| 🇨🇳 中文    |   fix: 修复配置单页面请求循环           |

fix: fix config-sheet request loop

---

pnpm-lock.yaml
shell/package.json

'textMap' is undefined in line chart option causing the console to report an error
Fixes #
❎ No
| 🇺🇸 English | 'textMap' is undefined in line chart option causing the console to report an error |
| 🇨🇳 中文    |  线状图的 option 文件中的 'textMap' 未定义，导致控制台报错  |
/cherry-pick release/2.1-beta.2

fix(msp): textMap is undefined in line option

---

shell/app/modules/application/pages/build-detail/index.scss
shell/app/modules/application/pages/pipeline/run-detail/build-detail.scss
shell/app/modules/project/common/components/pipeline-manage/run-detail/index.scss
shell/app/modules/project/common/components/pipeline-new/execute.scss
shell/app/modules/project/common/components/pipeline-new/index.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx

fix: fix project pipeline style
Fixes #
❎ No
| 🇺🇸 English |   fix: fix project pipeline style           |
| 🇨🇳 中文    |    fix: 修复项目流水线样式          |
\❎ No

fix: fix project pipeline style

---

shell/app/modules/runtime/pages/overview/components/domain-modal.tsx

fix that runtime page collapse
Fixes #
❎ No
| 🇺🇸 English | fix that runtime page collapse |
| 🇨🇳 中文    | 修复 runtime 页面崩溃问题 |
/cherry-pick release/2.1-beta.2

fix(dop): runtime page collapse

---

shell/app/common/components/contractive-filter/index.tsx
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/index.scss
shell/app/modules/msp/env-overview/topology/pages/topology/component/nodes/services-node.tsx

fix topology tip's style
Fixes #
❎ No
| 🇺🇸 English | fix topology tip's style |
| 🇨🇳 中文    | 修复拓扑图 提示 样式 |
❎ No

fix(msp): fix topology tip's style

---

scheduler/src/middlewares/guard.middleware.ts

redirect xx-org.erda.io/xx to erda.io/xx
Fixes #
❎ No
| 🇺🇸 English |   Redirect to root domain when accessing sub-domain organizations   |
| 🇨🇳 中文    |  访问子域名的组织时自动转到根域名   |
❎ No

feat: redirect sub org domain to root domain

---

scheduler/src/proxy.ts
shell/app/modules/application/pages/test/test-detail.tsx

Add error hander for proxy to prevent nestjs app crash.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/ticket?id=297176&pageNo=1)
❎ No
| 🇺🇸 English |  fix  ui server crash bug   |
| 🇨🇳 中文    |         修复 ui node 服务崩溃重启的问题     |

fix: fix scheduler crash caused by write after end error

---

shell/app/modules/project/common/components/pipeline-new/index.tsx

fix: fix project pipeline init mode error
Fixes #
❎ No
| 🇺🇸 English |  fix: fix project pipeline init mode error            |
| 🇨🇳 中文    |    fix: 修复项目流水线初始化模式错误          |
❎ No

fix: fix project pipeline init mode error

---

shell/app/modules/project/common/components/pipeline-manage/common/tree-category/tree.tsx
shell/app/modules/project/common/components/pipeline-manage/config-detail/pipeline-editor/index.tsx

fix: fix config sheet request loop
Fixes #
❎ No
| 🇺🇸 English | fix: fix config sheet request loop             |
| 🇨🇳 中文    |    fix: 修复配置单循环请求错误         |

fix: fix config sheet request loop

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search-detail.scss

fix that modify z-index to display tooltip
Fixes #
❎ No
| 🇺🇸 English | fix that modify z-index to display tooltip |
| 🇨🇳 中文    | 修改页面 z-index 使得其 tooltip 能显示 |
/cherry-pick release/2.1-beta.2

fix(msp): modify z-index to display tooltip

---

scheduler/src/proxy.ts

pick pr https://github.com/erda-project/erda-ui/pull/3189
Fixes #
❎ No
❎ No

fix: pick of fix scheduler crash caused by write after end error

---

shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx

fix export record sort
Fixes #
❎ No
| 🇺🇸 English | fix invalid sorting bug when turning pages |
| 🇨🇳 中文    | 修复翻页时排序无效的问题 |
❎ No

feat(dop): fix export record sort

---

shell/app/modules/project/common/components/pipeline-new/index.tsx

fix: fix project pipeline file changed
Fixes #
❎ No
| 🇺🇸 English |       fix: fix project pipeline file changed       |
| 🇨🇳 中文    |    fix: 修复项目流水线文件变更条件         |
❎ No

fix: fix project pipeline file changed

---

shell/app/modules/project/common/components/pipeline-new/execute.tsx

Fix project pipeline action link bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=294643&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English |  Fixed a bug where the link in pipelined execution records could jump to project level artifact detail data presentation errors.  |
| 🇨🇳 中文    | 修复了通过流水线执行记录中的 link 跳转到项目级制品详情数据展示错误的bug。  |
❎ No

fix(dop): project pipeline action link bug

---

shell/app/modules/application/pages/build-detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/application/pages/pipeline/run-detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/project/common/components/pipeline-manage/run-detail/pipeline-chart/run-case-node.tsx

fix: fix pipeline popover placement error
Fixes #
| 🇺🇸 English |     fix: fix pipeline popover placement error         |
| 🇨🇳 中文    |    fix: 修复流水线popover位置错误         |
❎ No

fix: fix pipeline popover placement error

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/pipelines/index.tsx

Project pipeline guides list optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=297706&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
| 🇺🇸 English |  Fold the prompt for the new assembly line.   |
| 🇨🇳 中文    |   将新建流水线的提示语折叠。   |
❎ No

fix(dop): project pipeline guides list optimization

---

shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.tsx

Clear filter when types are switched.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=297579&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1146&type=BUG)
❎ No
| 🇺🇸 English | Project pipeline switching directory clearing filter criteria. |
| 🇨🇳 中文    | 项目流水线切换目录清空筛选条件。 |
❎ No

fix(dop): clear filter when types are switched

---

scheduler/src/middlewares/guard.middleware.ts

fix: fix domain redirect error
Fixes #
❎ No
| 🇺🇸 English |     fix: fix domain redirect error         |
| 🇨🇳 中文    |   fix: 修复域名重定向错误       |
❎ No

fix: fix domain redirect error

---

shell/app/modules/project/common/components/pipeline-new/editor.tsx
shell/app/modules/project/common/components/pipeline-new/pipeline-node.scss
shell/app/modules/project/common/components/pipeline-new/pipeline-node.tsx

fix: add  project pipeline editor delete
Fixes #
❎ No
| 🇺🇸 English |  fix: add  project pipeline editor delete            |
| 🇨🇳 中文    |     fix: 修复项目流水线编辑中删除功能         |
❎ No

fix: add  project pipeline editor delete

---

shell/app/modules/apiManagePlatform/pages/api-market/components/export-record.tsx

remove apiId & version name column
Fixes #
❎ No
| 🇺🇸 English | remove apiId & version name column |
| 🇨🇳 中文    |  移除 apiId & version name 列 |

feat(dop): remove apiId & version name

---

shell/app/common/components/table/index.scss

Erda table td padding style optimization
Fixes #
->
| 🇺🇸 English |  Table cell interior margin optimization.  |
| 🇨🇳 中文    |  表格单元格的内边距优化。  |

fix(common): erda table td padding style optimization

---

core/src/framework/regist-router.tsx
core/src/stores/route.ts
core/src/types/shell.d.ts
shell/app/layout/pages/page-container/components/header.tsx

feat: add last search when back to up
Fixes #
| 🇺🇸 English |    feat: add last search when back to up          |
| 🇨🇳 中文    |    feat: 点击回到上一级时记录路由查询参数        |
❎ No

feat: add last search when back to up

---

shell/app/modules/project/common/components/pipeline-new/execute.tsx

feat: add pipeline refresh in project pipeline
Fixes #
| 🇺🇸 English |   feat: add pipeline refresh in project pipeline           |
| 🇨🇳 中文    |   feat:  项目流水线添加刷新           |
❎ No

feat: add pipeline refresh in project pipeline

---

shell/app/modules/project/common/components/pipeline-new/execute.tsx

fix: fix pipeline execute detail spinning
Fixes #
❎ No
| 🇺🇸 English |     fix: fix pipeline execute detail spinning         |
| 🇨🇳 中文    |    fix: 修复流水线执行详情spinning多余        |
cherry-pick release/2.1-beta.3

fix: fix pipeline execute detail spinning

---

shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/pages/deploy/index.tsx
shell/app/modules/project/pages/release/components/form.tsx
shell/app/modules/project/services/deploy.ts
shell/app/modules/project/types/deploy.d.ts
shell/app/modules/project/types/release.d.ts

Create deploy add modes.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298059&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=TASK)
| 🇺🇸 English | Environment Deployment Added Deployment mode selection. |
| 🇨🇳 中文    | 环境部署新增部署单增加模式选择。 |
❎ No

feat(dop): create deploy add modes

---

shell/app/common/constants.ts
shell/app/modules/org/common/config.ts
shell/app/modules/project/stores/issue-workflow.ts
shell/app/modules/project/tabs.tsx

Unified management of the visibility of milestones.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=299252&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=REQUIREMENT)
| 🇺🇸 English |  Unified management of the visibility of milestones  |
| 🇨🇳 中文    |  统一管理里程碑的显隐。  |
❎ No

fix(common): unified management of the visibility of milestones

---

shell/app/common/components/table/interface.ts
shell/app/common/utils/go-to.tsx
shell/app/modules/application/stores/pipeline-config.ts
shell/app/modules/application/types/pipeline-config.d.ts
shell/app/modules/project/common/components/params-config/config.ts
shell/app/modules/project/common/components/params-config/index.scss
shell/app/modules/project/common/components/params-config/index.tsx
shell/app/modules/project/common/components/params-config/list-edit.tsx
shell/app/modules/project/common/components/params-config/text-edit.tsx
shell/app/modules/project/pages/pipelines/pipeline-config.tsx
shell/app/modules/project/router.tsx
shell/app/modules/project/tabs.tsx

feat: add params config in project pipeline
Fixes #
| 🇺🇸 English |   feat: add params config in project pipeline           |
| 🇨🇳 中文    | feat: 添加项目流水线的配置            |
❎ No

feat: add params config in project pipeline

---

shell/app/modules/application/pages/settings/components/sonar-config.tsx
shell/app/modules/application/types/application.d.ts

fix: fix external repo app update error
Fixes #
❎ No
| 🇺🇸 English |    fix: fix external repo app update error        |
| 🇨🇳 中文    |     fix: 修复外置仓库应用修改错误    |
❎ No

fix: fix external repo app update error

---

shell/app/modules/project/pages/release/components/update.tsx

Edit release page display speed optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=299391&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxNzIzIl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=1164&type=BUG)
❎ No
| 🇺🇸 English |  Edit release page display speed optimization.   |
| 🇨🇳 中文    |  编辑制品页面展示速度优化。  |

fix(dop): edit release page display speed optimization

---

shell/app/modules/project/pages/pipelines/index.tsx

fix: fix project pipeline update search
Fixes #
❎ No
| 🇺🇸 English |    fix: fix project pipeline update search          |
| 🇨🇳 中文    |    fix: 修复项目流水线路由参数         |
❎ No

fix: fix project pipeline update search

---

shell/app/modules/project/common/components/pipeline-new/index.tsx

fix: fix base 64 convert error in project pipeline
Fixes #
❎ No
| 🇺🇸 English |      fix: fix base 64 convert not match api in project pipeline        |
| 🇨🇳 中文    |     fix: 修复项目流水线base64解码跟接口返回的不匹配问题         |
❎ No

fix: fix base 64 convert not match api in project pipeline

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.scss
shell/app/modules/project/pages/pipelines/index.tsx
shell/app/modules/project/services/pipeline.tsx

Project pipeline guides list add delete button.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=299554&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=TASK)
| 🇺🇸 English | Added remove button to project pipeline top message list. |
| 🇨🇳 中文    | 项目流水线顶部消息列表增加移除按钮。 |
❎ No

feat(dop): project pipeline guides list add delete button

---

shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/pages/issue/component/table-view.tsx

feat: edit issue relation list in issue-detail
Fixes #
| 🇺🇸 English |     feat: edit issue relation list in issue-detail         |
| 🇨🇳 中文    |    feat: 事项详情中支持编辑关联事项          |
❎ No

feat: edit issue relation list in issue-detail

---

shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/pages/deploy/index.tsx
shell/app/modules/project/pages/release/components/form.tsx
shell/app/modules/project/types/deploy.d.ts

Create deploy optimization.
Fixes #
❎ No
| 🇺🇸 English | When a deployment order is added, the first mode is selected by default and cannot be created without mode selection. Remove schema information from project artifact details. |
| 🇨🇳 中文    | 在新增部署单时，项目制品默认选中第一个模式，且不选择模式无法创建；项目制品详情去掉模式信息。 |
❎ No

fix(dop): create deploy optimization

---

shell/app/common/components/load-more-selector/index.scss
shell/app/modules/application/common/app-selector.tsx
shell/app/modules/project/common/components/iteration-selector.scss
shell/app/modules/project/common/components/iteration-selector.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx
shell/app/modules/project/tabs.tsx

Issue iteration fast switch.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298070&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjIsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=TASK)
| 🇺🇸 English |   In project collaboration - iteration, fast head switching iterations are supported.   |
| 🇨🇳 中文    | 项目协同-迭代中，支持头部快速切换迭代。  |
❎ No

feat(dop): issue iteration fast switch

---

shell/app/common/components/edit-field/index.tsx

Fxed edit button in issue detail.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298076&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=TASK)
❎ No
| 🇺🇸 English |  Fixed the edit button in event details.  |
| 🇨🇳 中文    |  固定事项详情中的编辑按钮。   |
❎ No

feat(dop): fixed edit button in issue detail

---

shell/app/layout/stores/layout.ts

Fix deploy runtime websocket bug.
Fixes #
❎ No
| 🇺🇸 English |  Fixed websocket failure in environment deployment.  |
| 🇨🇳 中文    |  修复了环境部署中websocket失效的问题。 |
❎ No

fix(dop): deploy runtime websocket bug

---

shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/pages/deploy/index.tsx

Fix create deploy bug.
Fixes #
❎ No
| 🇺🇸 English |  Fixed a bug where deployment orders could not be submitted when they were selected by default when created.  |
| 🇨🇳 中文    | 修复了部署单创建时默认选中却无法提交的bug。 |
❎ No

fix(dop): create deploy bug

---

shell/app/modules/project/pages/backlog/issue-item.scss
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/pages/issue/component/table-view.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.tsx

feat: fix issue item user too long style
Fixes #
| 🇺🇸 English |    feat: fix issue item user too long style  / keep query in project pipeline        |
| 🇨🇳 中文    |    feat: 修复事项包含用户数据过长问题  / 项目流水线保留query       |
❎ No

feat: fix issue item user too long style / keep query in project pipeline

---

shell/app/common/components/edit-field/index.tsx

Issue detail edit button optimization.
Fixes #
❎ No
| 🇺🇸 English |  Click the item details edit button, the page scroll to the top of the edit box.  |
| 🇨🇳 中文    |  点击事项详情编辑按钮时，页面滚动至编辑框顶端。   |
❎ No

fix(dop): issue detail edit button optimization

---

shell/app/common/components/member-selector/index.tsx
shell/app/modules/project/pages/pipelines/components/pipeline-protocol.tsx
shell/app/modules/project/pages/pipelines/index.tsx
shell/app/yml-chart/common/action-config-form.tsx

fix: fix action node member selector error
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=300936&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1164&type=BUG)
❎ No
| 🇺🇸 English |  fix: fix action node member selector error            |
| 🇨🇳 中文    |   fix: 修复流水线节点中用户选择器错误           |
❎ No

fix: fix action node member selector error

---

shell/app/modules/project/common/components/params-config/list-edit.tsx

fix: fix params config ellipsis
Fixes #
❎ No
| 🇺🇸 English |   fix: fix params config ellipsis           |
| 🇨🇳 中文    |   fix: 修复参数配置过长省略           |
❎ No

fix: fix params config ellipsis

---

shell/app/modules/project/pages/release/components/addon.tsx

Project release detail addons style optimization.
Fixes #
->
| 🇺🇸 English |  Item artifact details addons style optimization. |
| 🇨🇳 中文    |   项目制品详情addons样式优化。   |

fix(dop): project release detail addons style optimization

---

.codecov.yml
shell/app/common/components/configurable-filter/__tests__/config-selector.test.tsx
shell/app/common/components/configurable-filter/__tests__/index.test.tsx
shell/app/common/components/configurable-filter/index.tsx
shell/jest.config.js

add ConfigurableFilter test case
Fixes #
❎ No
❎ No

feat(test): add ConfigurableFilter test case

---

shell/app/modules/cmp/pages/domain-manage/index.tsx
shell/app/modules/cmp/types/domain-manage.d.ts

Domain list management operation add authority.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=288954&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTYsNDQxMyw0NDE0LDQ0MTVdLCJhc3NpZ25lZUlEcyI6WyIxMDAwNjQ1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MjB9&iterationID=1164&type=BUG)
| 🇺🇸 English |  Authority Added permission control for domain name list management.  |
| 🇨🇳 中文    | 域名列表管理操作增加权限控制。  |
❎ No

fix(cmp): domain list management operation add authority

---

shell/app/common/components/configurable-filter/__tests__/external-item.test.tsx
shell/app/common/components/configurable-filter/external-item.tsx

add ExternalIte test case
Fixes #
❎ No
❎ No

feat(test): add ExternalIte test case

---

shell/app/modules/project/common/components/params-config/index.tsx

fix: fix params config edit error
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=302153&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1164&type=BUG)
❎ No
| 🇺🇸 English |     fix: fix params config edit error         |
| 🇨🇳 中文    |   fix: 修复参数配置编辑错误          |
cherry-pick release/2.1-beta.3-2

fix: fix params config edit error

---

shell/app/modules/project/pages/release/components/form.tsx

Fix create release upload bug.
Fixes #
❎ No
| 🇺🇸 English |  Fixed a bug where Windows could not be created by uploading files.  |
| 🇨🇳 中文    |  修复了window下无法通过上传文件来创建制品的bug。   |

fix(dop): create release upload bug

---

shell/app/modules/project/pages/release/components/project-detail.tsx
shell/app/modules/project/types/release.d.ts

Project release detail optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=302009&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=TASK)
| 🇺🇸 English |  Item artifact details page added mode.  |
| 🇨🇳 中文    |  项目制品详情页增加模式。  |

feat(dop): project release detail optimization

---

shell/app/common/components/edit-field/index.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx

Fixes #
❎ No
| 🇺🇸 English |  fix: issue style            |
| 🇨🇳 中文    |      fix: 修复事项样式        |
❎ No

fix: fix issue style

---

.github/workflows/git-sync.yml

change remote
Fixes #
❎ No
| 🇺🇸 English |    change remote          |
| 🇨🇳 中文    |     修改源         |
❎ No

ci: change remote

---

shell/app/modules/cmp/common/alarm-strategy/index.tsx
shell/app/modules/cmp/common/custom-alarm/index.tsx

fix table cell minWidth
Fixes #
❎ No
| 🇺🇸 English | set the minWidth for table cell |
| 🇨🇳 中文    | 为 table 单元格设置最小宽度  |
❎ No

fix(msp): fix table cell minWidth

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx

fix: fix issue detail i18n
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=304394&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1164&type=BUG)
❎ No
| 🇺🇸 English |   fix: fix issue detail i18n           |
| 🇨🇳 中文    |    fix: 修复i18n错误  |
release/2.1-beta.3-3

fix: fix issue detail i18n

---

shell/app/common/components/tags-row/index.tsx
shell/app/common/components/tags/index.tsx

fix: fix compatibility style issue in chrome
Fixes #
❎ No
| 🇺🇸 English |  fix: fix compatibility style issue in chrome            |
| 🇨🇳 中文    |    fix: 修复chrome兼容性样式问题         |
❎ No

fix: fix compatibility style issue in chrome

---

locales/en.json
locales/zh.json
shell/app/modules/cmp/common/custom-dashboard/import-export.tsx
shell/app/modules/cmp/common/custom-dashboard/index.tsx

fix that error of i18n in the custom dashboard
❎ No
| 🇺🇸 English |  fix that error of i18n in the custom dashboard |
| 🇨🇳 中文    | 修复自定义大盘国际化错误问题  |
❎ No

fix(msp): i18n in custom dashboard

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx

Fix issue detail close bug after interface error.
Fixes #
❎ No
| 🇺🇸 English |  Fixed a bug where event details could not be closed after an interface error.  |
| 🇨🇳 中文    |  修复了事项详情在接口报错后无法关闭的bug。  |
release/2.1-beta.3-3

fix(dop): issue detail close bug after interface error

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/pages/settings/app-settings.tsx
shell/app/modules/dop/pages/projects/apply-unblock-modal.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.tsx
shell/app/modules/org/pages/projects/create-project.tsx
shell/app/modules/org/pages/projects/issue-type-manage.tsx
shell/app/modules/org/pages/projects/project-list.tsx
shell/app/modules/project/pages/plan-detail/columns/operation.tsx
shell/app/modules/project/pages/settings/components/project-settings.tsx
shell/app/modules/project/pages/test-manage/case/columns/more-operation/index.tsx
shell/app/modules/project/pages/test-manage/case/test-env-drawer/index.tsx
shell/app/modules/runtime/common/components/deployment-table.tsx
shell/app/modules/runtime/common/components/instance-table.tsx
shell/app/modules/runtime/common/components/pod-table.tsx
shell/app/modules/runtime/common/logs/components/container-log.jsx
shell/app/modules/runtime/common/logs/components/deploy-log.tsx
shell/app/modules/runtime/pages/overview/components/activity.tsx
shell/app/modules/runtime/pages/overview/components/domain-modal.tsx
shell/app/modules/runtime/pages/overview/components/index.tsx
shell/app/modules/runtime/pages/overview/components/info.tsx
shell/app/modules/runtime/pages/overview/components/resource-modal.tsx
shell/app/modules/runtime/pages/overview/components/rollback-list.tsx
shell/app/modules/runtime/pages/overview/components/service-card.tsx
shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx

fix(common): Some i18n are not displayed correctly in Chinese
* fix: runtime miss
* fix: \s miss
Some i18n are not displayed correctly in Chinese
Fixes #
❎ No
| 🇺🇸 English |       Fix some i18n are not displayed correctly in Chinese       |
| 🇨🇳 中文    |           修复部分i18n中文无法正确显示   |
✅ Yes(release/2.1-beta.3-3)

fix(common): Some i18n are not displayed correctly in Chinese

---

shell/app/modules/cmp/common/custom-dashboard/index.tsx

modify the placeholder in the filter to search by name
| 🇺🇸 English |  modify placeholder in the filter to search by name  |
| 🇨🇳 中文    | 修改筛选器文案为按名称搜索  |
❎ No

feat(msp): modify placeholder in filter to search by name

---

pnpm-lock.yaml
shell/app/modules/cmp/common/custom-dashboard/index.tsx
shell/package.json

1. remove useless icon
2. fix dataZoom style
Fixes #
❎ No
| 🇺🇸 English | modify some style in dashboard |
| 🇨🇳 中文    | 修正大盘的部分样式 |
❎ No

fix(msp): remove useless icon

---

shell/app/modules/project/tabs.tsx

Fix iteration tabs bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=305213&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&tab=ALL&type=BUG)
->
| 🇺🇸 English |  Fixed tabs display bug in iteration details.  |
| 🇨🇳 中文    |  修复了迭代详情内标签页显示的问题。  |
❎ No

fix(dop): iteration tabs bug

---

shell/app/modules/msp/services/log-analyze.ts
shell/app/modules/msp/stores/log-analyze.ts
shell/app/modules/msp/types/log-analyze.d.ts

add creator in log rule page
[**fix: log rule show creator**  erda-project/erda#4607 ](https://github.com/erda-project/erda/pull/4607)
Fixes #
❎ No
| 🇺🇸 English | add creator in log rule page |
| 🇨🇳 中文    | 在日志规则页面增加创建人 |
❎ No

feat(msp): add creator in log rule page

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/pages/release/components/application-detail.tsx
shell/app/modules/project/pages/release/components/project-detail.tsx
shell/app/modules/project/pages/settings/components/project-label.tsx
shell/app/modules/project/types/release.d.ts

Release labels optimization.
Fixes #
->
| 🇺🇸 English | Product details added commit message; Fixed a copywriting error when deleting product labels.  |
| 🇨🇳 中文    |  制品详情增加commit message；修复删除制品标签时的文案错误问题。  |
❎ No

fix(dop): release labels optimization

---

shell/app/common/components/edit-field/index.tsx
shell/app/common/components/setting-tabs/index.tsx
shell/app/common/components/switch-auto-scroll/index.tsx
shell/app/configForm/form/form.tsx
shell/app/modules/addonPlatform/pages/common/components/addon-card-list.tsx
shell/app/modules/addonPlatform/pages/common/components/addon-cards.scss
shell/app/modules/application/pages/repo/components/file-diff.tsx
shell/app/modules/cmp/pages/cluster-manage/deploy-cluster-form.tsx
shell/app/modules/project/common/components/issue/issue-activities.tsx

fix: fix scrollIntoView cause page move
Fixes #
| 🇺🇸 English |   fix: fix scrollIntoView cause page move           |
| 🇨🇳 中文    |     fix: 修复 scrollIntoView 导致的页面位移         |
❎ No

fix: fix scrollIntoView cause page move

---

core/src/stores/route.ts
shell/app/common/__tests__/use-hook.test.tsx
shell/app/common/use-hooks.tsx
shell/app/common/utils/go-to.tsx
shell/app/config-page/index.tsx
shell/app/modules/project/pages/ticket/index.tsx

fix: fix useUpdateSearch error
Fixes #
| 🇺🇸 English |     fix: fix useUpdateSearch error         |
| 🇨🇳 中文    |  fix:修复 useUpdateSearch 错误            |
❎ No

fix: fix useUpdateSearch error

---

shell/app/modules/project/pages/ticket/index.tsx

fix: fix ticket request params error
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=298566&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=-1&type=BUG)
❎ No
| 🇺🇸 English |  fix: fix ticket request params error            |
| 🇨🇳 中文    | fix: 修复工单页面翻页请求错误          |
❎ No

fix: fix ticket request params error

---

shell/app/modules/project/pages/release/components/project-detail.tsx
shell/app/modules/runtime/pages/overview/components/domain-modal.scss
shell/app/modules/runtime/pages/overview/components/domain-modal.tsx

Domain settings modal optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=305132&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1174&type=TASK)
->
| 🇺🇸 English |   Domain name setting style optimization  |
| 🇨🇳 中文    |   域名设置样式优化。   |
❎ No

fix(dop): domain settings modal optimization

---

shell/app/config-page/components/chart/chart.tsx

fix: fix treemap chart tooltip disappear
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=305189&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1174&type=BUG)
| 🇺🇸 English |   fix: fix treemap chart tooltip disappear           |
| 🇨🇳 中文    |    fix: 修复矩阵图tooltip消失       |
❎ No

fix: fix treemap chart tooltip disappear

---

shell/app/layout/pages/page-container/components/breadcrumb.tsx

fix: fix breadcrumd error
Fixes #
| 🇺🇸 English |       fix: fix breadcrumd error       |
| 🇨🇳 中文    |   fix: 修复面包屑错误        |
release/2.1-beta.4

fix: fix breadcrumd error

---

core/src/utils/global-space.ts
pnpm-lock.yaml
scheduler/package.json
scheduler/src/filters/not-found.filter.ts
scheduler/src/proxy.ts
scheduler/src/util.ts
scheduler/tsconfig.json
shell/app/App-vite.tsx
shell/app/App.tsx
shell/app/interface/common.d.ts
shell/app/layout/pages/page-container/page-container.tsx
shell/app/layout/stores/layout.ts
shell/app/org-home/stores/org.tsx
shell/app/views/index.ejs

move init requests to node to optimize first page paint time
Fixes #
❎ No
| 🇺🇸 English | move init requests to node to optimize first page paint time  |
| 🇨🇳 中文    |  移动初始化请求到 node 端以提高页面加载速度 |
❎ No

feat: move init requests to node to optimize first page paint time

---

shell/app/views/index.ejs
shell/index.html

fix the org manage page style exception and icon missing
[erda-ui-enterprise#241](https://github.com/erda-project/erda-ui-enterprise/pull/241)
Fixes #
| 🇺🇸 English | fix the org manage page style exception |
| 🇨🇳 中文    | 修复组织管理页面样式异常 |
release/2.1-beta.4

fix(org): fix the org manage page style exception

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/menus/project.tsx

fix devops side menu Collaboration translation
Fixes #3332 
| 🇺🇸 English |       fix devops side menu Collaboration translation       |
| 🇨🇳 中文    |         修改devops侧边栏一级菜单Collaboration中文翻译为项目管理  |
❎ No

fix: devops side menu Collaboration translation

---

scheduler/src/filters/not-found.filter.ts

chore: add debug test logs
Fixes #
❎ No
❎ No

fix: add test log

---

scheduler/src/filters/not-found.filter.ts

Fix Invalid value "undefined" for header "cookie"
Fixes #
❎ No
❎ No

fix: Invalid value "undefined" for header "cookie"

---

scheduler/src/filters/not-found.filter.ts

fix: api should remove orgName part in online mode
Fixes #
❎ No
| 🇺🇸 English | fix: api should remove orgName part in online mode   |
| 🇨🇳 中文    |  修复线上模式的 api 调用没有移除 orgName 的问题   |
❎ No

fix: api should remove orgName part in online mode

---

scheduler/src/filters/not-found.filter.ts

fix: fix login referer and remove debug log
Fixes #
❎ No
| 🇺🇸 English |  fix: fix login referer and remove debug log  |
| 🇨🇳 中文    |  修复登录请求 referer 头错误的问题  |
❎ No

fix: fix login referer and remove debug log

---

.github/workflows/codecov.yml

run test workflow as needed
Fixes #
❎ No
❎ No

chore: run unit test as needed

---

package.json
shell/app/modules/application/pages/test/test-list.tsx
shell/app/modules/msp/env-overview/service-list/pages/index.tsx
shell/app/modules/msp/pages/micro-service/overview.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx
shell/app/modules/project/common/components/issue/time-trace.tsx

- removes the deprecated property of the progress
- add uniq for Comp
Fixes #
❎ No
| 🇺🇸 English | replace the deprecated property of the Progress  |
| 🇨🇳 中文    | 替换 Progress 中已弃用的属性 |
❎ No

feat: replace the deprecated property of the progress

---

shell/app/common/components/render-form-item/index.tsx
shell/app/config-page/components/table/v2/utils.tsx
shell/app/modules/project/common/components/pipeline-new/form.tsx
shell/app/modules/project/common/components/pipeline-new/index.tsx
shell/app/modules/project/common/components/pipeline-new/list.tsx
shell/app/modules/project/services/pipeline.tsx

project pipeline edit source.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=305441&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&type=TASK)
| 🇺🇸 English |  Project pipelining supports editing sources.  |
| 🇨🇳 中文    |  项目流水线支持编辑源。 |
❎ No

feat(dop): project pipeline edit source

---

erda.yml
scheduler/src/filters/not-found.filter.ts

fix admin user get full org list in personal workbench.
Fixes #
❎ No
| 🇺🇸 English |   fix admin user get full org list in personal workbench.  |
| 🇨🇳 中文    |  修复管理员角色在个人工作台获得全部列表的问题   |
❎ No

fix: add special org header and remove debug log

---

shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx

replace antd Pagination with erda Pagination
Fixes #
❎ No
| 🇺🇸 English | replace antd Pagination with erda Pagination |
| 🇨🇳 中文    | 用 erda Pagination 替换 antd Pagination  |
❎ No

feat(msp): replace antd Pagination with erda Pagination

---

shell/app/modules/application/pages/test/test-detail.tsx

show function classname in unit test result
Fixes #
| 🇺🇸 English |  show function classname in unit test result   |
| 🇨🇳 中文    |   单元测试结果中增加类名展示  |
❎ No

feat(dop): show function classname in unit test result

---

shell/app/modules/project/pages/release/components/release-select.tsx

Create release filter add tags.
Fixes #
| 🇺🇸 English |   Create artifact filters to add label filters.  |
| 🇨🇳 中文    |  创建制品筛选器增加标签筛选。  |
❎ No

feat(dop): create release filter add tags

---

shell/app/modules/msp/monitor/error-insight/stores/error.ts

compatible with null eventIds
Fixes #
❎ No
| 🇨🇳 中文    |  -  |
❎ No

fix(msp): compatible with null eventIds

---

scheduler/src/filters/not-found.filter.ts

init org access data is wrong
Fixes #
❎ No
| 🇺🇸 English |  fix page not render after login   |
| 🇨🇳 中文    |       修复登录后页面不渲染的问题        |
❎ No

fix: init org access data is wrong

---

shell/app/common/components/table/index.tsx
shell/app/config-page/components/table/render-types.tsx
shell/app/config-page/components/table/v2/utils.tsx

Table actions color optimization.
Fixes #
->
| 🇺🇸 English | Table operation column font color modification.  |
| 🇨🇳 中文    |  表格操作列字体颜色修改。  |
❎ No

fix(common): table actions color optimization

---

shell/app/org-home/stores/org.tsx

local use raw access response, but server returned inner data. update local logic
Fixes #
❎ No
| 🇺🇸 English |   fix auto redirect to root page bug   |
| 🇨🇳 中文    |     修复自动调整到首屏的问题     |
❎ No

fix: auto redirect to root page bug

---

shell/app/modules/application/common/yml-editor/pipeline-editor.tsx
shell/app/yml-chart/pipeline-editor.tsx

fix: fix yml file editor file extension error
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=306170&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1174&type=BUG)
❎ No
| 🇺🇸 English |      fix: fix yml file editor file extension error        |
| 🇨🇳 中文    |    fix: 修复yml文件编辑格式错误       |
cherry-pick release/2.1-beta.4

fix: fix yml file editor file extension error

---

shell/app/common/components/pagination/__tests__/index.test.tsx
shell/app/common/components/pagination/index.tsx

replace antd Pagination with Pagination
**[erda-ui-enterprise#247](https://github.com/erda-project/erda-ui-enterprise/pull/247)**
Fixes #
❎ No
| 🇺🇸 English | replace antd Pagination with erda Pagination |
| 🇨🇳 中文    | 用 erda Pagination 替换 antd Pagination |
❎ No

feat(msp): replace antd Pagination with Pagination

---

shell/app/modules/runtime/pages/overview/components/index.tsx

fix: fix runtime detail menu fold icon error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix runtime detail menu fold icon error           |
| 🇨🇳 中文    |    fix: 修复runtime详情icon错误         |
❎ No

fix: fix runtime detail menu fold icon error

---

pnpm-lock.yaml
shell/app/App-vite.tsx
shell/app/App.tsx
shell/mf.config.js
shell/package.json
shell/webpack.config.js

introduce erda-ui components to setup config provider
Fixes #
❎ No
| 🇺🇸 English |   introduce erda-ui components           |
| 🇨🇳 中文    |     引入@erda-ui/components         |
❎ No

feat(common): introduce erda-ui components

---

shell/app/App.tsx

fix: fix first login page unLoad
Fixes #
❎ No
| 🇺🇸 English |      fix: fix first login page unLoad        |
| 🇨🇳 中文    |     fix: 修复第一次登录页面未加载        |
❎ No

fix: fix first login page unLoad

---

shell/app/modules/msp/alarm-manage/overview/base-overview.tsx

fix styling issues caused by upgrading TopButtonGroup
Fixes #
| 🇺🇸 English | fix styling issues caused by upgrading TopButtonGroup |
| 🇨🇳 中文    | 修复升级 TopButtonGroup 导致的样式问题 |
❎ No

fix(msp): fix styling issues caused by upgrading TopButtonGroup

---

pnpm-lock.yaml
shell/package.json

update pkg version
Fixes #
❎ No
| 🇺🇸 English |       update conponent lib       |
| 🇨🇳 中文    |     更新组件库         |
❎ No

feat(common): update pkg version

---

shell/app/modules/org/pages/announcement/index.tsx
shell/app/modules/org/pages/projects/issue-field-manage.tsx
shell/app/modules/org/pages/safety/index.tsx
shell/app/modules/org/router.ts

replace antdTable with erdaTable
Fixes #
❎ No
| 🇺🇸 English | replace antdTable with erdaTable |
| 🇨🇳 中文    | 使用 erdaTable 替换 antd Table |
❎ No

feat(dop): replace antdTable with erdaTable

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/config-page/components/api-editor/api-editor.tsx
shell/app/configForm/nusi-form/form-items/array-obj.tsx
shell/app/configForm/nusi-form/form-items/inputNumber.tsx
shell/app/configForm/nusi-form/form-items/map.tsx
shell/app/configForm/nusi-form/form-items/textarea.tsx
shell/app/modules/apiManagePlatform/pages/api-market/components/api-resource/resource.tsx
shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx
shell/app/modules/application/pages/settings/components/app-info.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx
shell/app/modules/cmp/pages/cluster-manage/cluster-list.tsx
shell/app/modules/cmp/pages/domain-manage/index.tsx
shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
shell/app/modules/org/common/cluster-quota.tsx
shell/app/modules/org/common/field-options-setting.tsx
shell/app/modules/org/pages/projects/issue-field-modal.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx
shell/app/modules/project/common/components/issue/text-field-input.tsx
shell/app/modules/project/common/components/params-config/list-edit.tsx
shell/app/modules/project/common/components/pipeline-new/form.tsx
shell/app/modules/project/common/components/workflow-state-form.tsx
shell/app/modules/project/pages/release/components/application-detail.tsx
shell/app/modules/project/pages/release/components/form.tsx
shell/app/modules/project/pages/settings/components/project-info.tsx
shell/app/modules/publisher/pages/statistics/index.tsx
shell/app/org-home/pages/land/index.tsx
shell/app/yml-chart/common/out-params-drawer.tsx

fix please enter in i18n
Fixes #3382
| 🇺🇸 English |     fix please enter in i18n         |
| 🇨🇳 中文    |          修复i18n中pease enter {name} -> please enter   {name} |
✅ Yes(release 2.1)

fix(#3382): fix please enter in i18n

---

shell/app/modules/org/pages/projects/issue-field-manage.tsx

add reload event on field table
Fixes #
❎ No
| 🇺🇸 English | add reload event on field table  |
| 🇨🇳 中文    |  字段列表增加 reload 事件 |
❎ No

feat(dop): add reload event on field table

---

scheduler/src/filters/not-found.filter.ts

fix: fix node request header error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix node request header error           |
| 🇨🇳 中文    |  fix: 修复node端请求接口header错误         |
❎ No

fix: fix node request header error

---

scheduler/src/filters/not-found.filter.ts

add log to trace scheduler issue
Fixes #
❎ No
| 🇺🇸 English |     fix get org access issue         |
| 🇨🇳 中文    |     修复集成环境无法刷首页的问题         |
❎ No

fix(scheduler): fix get org access issue

---

shell/app/config-page/components/table/v2/table.tsx
shell/app/config-page/components/table/v2/utils.tsx

fix: fix table user type error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix table user type error           |
| 🇨🇳 中文    |    fix: 修复table组件用户头像错误         |
release/2.1

fix: fix table user type error

---

shell/app/modules/msp/monitor/monitor-common/components/resource-usage/resource-usage-charts.tsx
shell/app/modules/runtime/types/service.d.ts

Fixes #
❎ No
| 🇺🇸 English | use pod_uid to query network monitoring |
| 🇨🇳 中文    | 使用 pod_uid 查询网络监控 |
❎ No

feat(dop): add filter_pod_uid for query containerNet

---

shell/app/modules/project/pages/backlog/issue-item.tsx

Fix issue detail style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=307576&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=-1&tab=BUG&type=BUG)
->
| 🇺🇸 English |   Fixed problems with quick creation of collaborative items and abnormal front-end display.  |
| 🇨🇳 中文    |  修复了快捷创建协同事项，前端显示异常的问题。 |
release/2.1

fix(dop): issue detail style bug

---

scheduler/src/filters/not-found.filter.ts

fix: cookie on request maybe undefined
Fixes #
❎ No
| 🇺🇸 English |  fix: cookie on request maybe undefined   |
| 🇨🇳 中文    |    未登录时请求上的 cookie 可能不存在    |
release/2.1

fix: cookie on request maybe undefined

---

shell/app/antd-overwrite/avatar/index.tsx

fix: fix avatar img error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix avatar img error           |
| 🇨🇳 中文    |  fix: 修复avatar图片显示错误         |
release/2.1

fix: fix avatar img error

---

scheduler/src/filters/not-found.filter.ts
shell/app/org-home/stores/org.tsx

fix: fix support user access error in unjoined org
Fixes #
❎ No
| 🇺🇸 English |    fix: fix support user access error in unjoined org          |
| 🇨🇳 中文    |     fix: 修复support用户在未加入组织中的权限错误        |
release/2.1

fix: fix support user access error in unjoined org

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx

fix: fix iteration sync error
Fixes #
❎ No
| 🇺🇸 English |  fix: fix iteration sync error            |
| 🇨🇳 中文    |      fix: 修复事项同步迭代错误        |
release/2.1

fix: fix iteration sync error

---

shell/app/App-vite.tsx

fix: fix support access in vite
Fixes #
❎ No
| 🇺🇸 English |  fix: fix support access in vite            |
| 🇨🇳 中文    |   fix: 修复vite模式下support用户权限        |
release/2.1

fix: fix support access in vite

---

shell/app/App-vite.tsx

fixed moment locale issue in vite mode
Fixes #
❎ No
❎ No

feat(dop): fixed moment locale issue in vite mode

---

shell/app/modules/dop/pages/form-editor/components/api-test.tsx

fix: fix api test action select style error
Fixes #
| 🇺🇸 English |   fix: fix api test action select style error           |
| 🇨🇳 中文    |  fix: 修复api测试节点的select样式错误           |
release/2.1

fix: fix api test action select style error

---

shell/app/locales/utils.ts
shell/app/modules/application/router.ts
shell/app/modules/project/router.tsx

Deploy runtime detail breadcrumb optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=307759&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=TASK)
->
| 🇺🇸 English |  Breadcrumb optimization at the top of the Runtime details page for environment deployment and application deployment.  |
| 🇨🇳 中文    |  环境部署以及应用部署的runtime详情页的顶部面包屑优化。  |
❎ No

feat(dop): deploy runtime detail breadcrumb optimization

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/menus/project.tsx
shell/app/modules/project/router.tsx
shell/app/modules/project/tabs.tsx

Project collaboration menu optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=307067&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=0&tab=ALL&type=REQUIREMENT)
->
| 🇺🇸 English |   The Project Management menu in DevOps platform has been adjusted.  |
| 🇨🇳 中文    |  DevOps 平台中项目管理菜单调整。 |
❎ No

feat(dop): project collaboration menu optimization

---

shell/app/config-page/components/file-tree/file-tree.tsx
shell/app/config-page/components/sort-drag-group/pure-sort-drag-group-list/index.tsx
shell/app/layout/pages/page-container/components/org-selector.tsx
shell/app/layout/pages/page-container/layout.tsx
shell/app/org-home/stores/org.tsx

fix: fix invite to org error
Fixes #
| 🇺🇸 English |  fix: fix invite to org error            |
| 🇨🇳 中文    |  fix: 修复邀请加入组织错误            |
release/2.1

fix: fix invite to org error

---

shell/app/App.tsx
shell/app/org-home/stores/org.tsx
shell/app/user/stores/permission.ts

fix: fix access error when switch org
Fixes #
❎ No
| 🇺🇸 English |    fix: fix access error when switch org          |
| 🇨🇳 中文    |    fix: 修复切换org后权限错误          |
release/2.1

fix: fix access error when switch org

---

shell/app/App-vite.tsx
shell/app/App.tsx
shell/app/org-home/stores/org.tsx

fix: fix announcement request timing
Fixes #
❎ No
| 🇺🇸 English |   fix: fix announcement request timing           |
| 🇨🇳 中文    |  fix: 修复通知请求的时机       |
cherry-pick release/2.1

fix: fix announcement request timing

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/modules/project/pages/deploy/add-deploy/add-release.scss
shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx
shell/app/modules/project/pages/deploy/add-deploy/release-list.tsx
shell/app/modules/project/pages/release/components/release-select.tsx
shell/app/modules/project/services/release.ts

Create deploy add tags filter.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=307771&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=TASK)
->
| 🇺🇸 English | Added tags filters when creating deployment menu selection artifacts |
| 🇨🇳 中文    |   创建部署单选择制品时增加标签的筛选；  |
❎ No

feat(dop): create deploy add tags filter

---

shell/app/modules/project/common/issue-config.ts

feat: update issue template
Fixes #
| 🇺🇸 English |  feat: update issue template  |
| 🇨🇳 中文    |     更新事项模板  |
❎ No

feat: update issue template

---

shell/app/common/utils/i18n-replace-link.tsx
shell/app/modules/application/pages/settings/app-settings.tsx
shell/app/modules/org/pages/projects/settings/member/index.tsx
shell/app/modules/org/pages/setting/org-setting.tsx
shell/app/modules/project/pages/release/components/release-select.tsx
shell/app/modules/project/pages/settings/components/project-settings.tsx

fix setting page collapse
Fixes #
❎ No
❎ No

fix(dop): fix setting page collapse

---

shell/app/common/utils/index.ts
shell/app/modules/project/pages/release/components/release-select.tsx

fix allWordsFirstLetterUpper in common/utils
Fixes #
❎ No
| 🇺🇸 English |     fix allWordsFirstLetterUpper in common/utils         |
| 🇨🇳 中文    |      修复公共函数 allWordsFirstLetterUpper      |
❎ No

fix: allWordsFirstLetterUpper in common/utils

---

shell/app/modules/project/pages/deploy/add-deploy/release-list.tsx
shell/app/modules/project/types/deploy.d.ts

Create deploy release list add tags.
Fixes #
| 🇺🇸 English |  Added deployment sheet artifact list added TAB display.  |
| 🇨🇳 中文    |  添加部署单的制品列表增加标签的显示。  |
❎ No

feat(dop): create deploy release list add tags

---

shell/app/common/services/index.ts
shell/app/common/stores/common.ts
shell/app/modules/runtime/common/logs/components/container-log.tsx

feat: log fallback v2
Fixes #
❎ No
| 🇺🇸 English |    feat: runtime container log fallback v2          |
| 🇨🇳 中文    |   feat: runtime 容器日志降级 v2           |
❎ No

feat:  runtime container log fallback v2

---

shell/app/modules/runtime/common/logs/components/container-log.tsx

fix: runtime container log first query params
Fixes #
❎ No
| 🇺🇸 English |    fix: runtime container log first query params          |
| 🇨🇳 中文    |     fix:  修复runtime容器日志第一次请求参数        |
❎ No

fix: runtime container log first query params

---

shell/app/modules/runtime/common/logs/components/container-log.tsx

fix: fix runtime container log fallback request params
Fixes #
❎ No
| 🇺🇸 English |   fix: fix runtime container log fallback request params           |
| 🇨🇳 中文    |   fix: 容器日志降级参数           |
❎ No

fix: fix runtime container log fallback request params

---

shell/app/modules/cmp/router.ts
shell/app/modules/dcos/pages/service-manager/index.tsx
shell/app/modules/dcos/services/service.ts

fix: fix cmp service request error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix cmp service request error           |
| 🇨🇳 中文    |   fix: 修复cmp服务列表请求错误           |
release/2.1

fix: fix cmp service request error

---

shell/app/common/components/crud-table/index.tsx

Fix mobile safety management table reload bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=309092&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=BUG)
❎ No
| 🇺🇸 English | Fixed an issue where the mobile development Platform - Security Management click refresh data did not update. |
| 🇨🇳 中文    | 修复了移动开发平台-安全管理点击刷新数据没有更新的问题。 |
release/2.1

fix(dop): mobile safety management table reload bug

---

shell/app/modules/project/pages/backlog/issue-item.scss
shell/app/modules/project/pages/backlog/issue-item.tsx

feat: issue name inline edit
Fixes #
| 🇺🇸 English |     feat: related issue name inline edit         |
| 🇨🇳 中文    |     feat: 关联事项名称占位编辑        |
❎ No

feat: related issue name inline edit

---

shell/app/modules/runtime/common/logs/components/container-log.tsx

fix: fix runtime log params
Fixes #
❎ No
| 🇺🇸 English |  fix: fix runtime log params     |
| 🇨🇳 中文    |    fix: 修复容器日志参数错误     |
❎ No

fix: fix runtime log params

---

shell/app/modules/project/common/components/runtime-selector.scss
shell/app/modules/project/common/components/runtime-selector.tsx
shell/app/modules/project/services/deploy.ts
shell/app/modules/project/tabs.tsx
shell/app/modules/project/types/deploy.d.ts
shell/app/modules/runtime/stores/runtime.ts

Runtime fast switch.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=309785&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=TASK)
| 🇺🇸 English |  On the environment deployment runtimes details page, runtimes supports fast switching.  |
| 🇨🇳 中文    |  环境部署runtime详情页中，runtime支持快速切换。  |
❎ No

feat(dop): runtime fast switch

---

shell/app/modules/msp/env-overview/service-list/pages/index.scss
shell/app/modules/msp/env-overview/service-list/pages/process.tsx

add instance status
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=310729&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl0sImNyZWF0b3JJRHMiOlsiMTAwMDU2NSJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English | add instance status |
| 🇨🇳 中文    | 实例列表显示状态 |
❎ No

fix(msp): add instance status

---

shell/app/common/components/edit-field/index.tsx

Fix ticket detail style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=310491&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=BUG)
->
| 🇺🇸 English | Fixed style errors when workorders are long. |
| 🇨🇳 中文    |  修复了工单内容比较长的时候的样式错误。 |
❎ No

fix(dop): ticket detail style bug

---

cli/package.json
pipeline.yml

fix pipeline issue
Fixes #
❎ No
| 🇺🇸 English |      fix pipeline issue        |
| 🇨🇳 中文    |    修复集成打包失败问题          |
❎ No

fix(common): fix pipeline issue

---

cli/lib/util/env.ts

add log to track pipeline issue
Fixes #
❎ No
| 🇺🇸 English |     add log to track pipeline issue         |
| 🇨🇳 中文    |    定位流水线打包问题          |
❎ No

fix(common): add cli log

---

pnpm-lock.yaml

fix lock issue
Fixes #
❎ No
| 🇺🇸 English |    update lock file          |
| 🇨🇳 中文    |   更新lock文件           |
❎ No

fix(cli): fix lock issue

---

core/src/i18n.ts

fix: i18n nsSeparator fail
Fixes # 
| 🇺🇸 English |      i18n nsSeparator fail        |
| 🇨🇳 中文    |        修复i18n配置nsSeparator      |
❎ No

fix: i18n nsSeparator fail

---

shell/app/org-home/pages/land/index.tsx

Fixes #
❎ No
| 🇺🇸 English |    fix: fix land page button style          |
| 🇨🇳 中文    |    fix: 修复着陆页按钮样式          |
❎ No

fix: fix land page button style

---

.npmrc
modules/components/.npmrc
modules/components/package.json
package.json
pnpm-lock.yaml
scheduler/package.json

fix scheduler build issue
Fixes #
❎ No
| 🇺🇸 English |    fix scheduler build issue          |
| 🇨🇳 中文    |     修复集成环境scheduler打包失败问题         |
❎ No

fix(scheduler): fix scheduler build issue

---

pnpm-lock.yaml
shell/package.json

change antd version
Fixes #
❎ No
| 🇺🇸 English |      change antd version        |
| 🇨🇳 中文    |    修正antd的版本          |
❎ No

feat(common): change antd version

---

package.json
pnpm-lock.yaml

fix build issue
Fixes #
❎ No
| 🇺🇸 English |      fix build issue        |
| 🇨🇳 中文    |     修复编译问题         |
❎ No

fix(common): fix build issue

---

cli/lib/util/env.ts
cspell.json
package.json
pipeline.yml

remove log & move script to preinstall
Fixes #
❎ No
| 🇺🇸 English |       remove log       |
| 🇨🇳 中文    |      移除Log        |
❎ No

feat(common): remove log

---

package.json
pipeline.yml

rollback code due to preinstall has bug
Fixes #
❎ No
| 🇺🇸 English |   rollback code due to preinstall has bug            |
| 🇨🇳 中文    |   preinstall hook不符合预期，回滚代码           |
❎ No

chore(common): rollback code due to preinstall has bug

---

modules/components/package.json
pnpm-lock.yaml
shell/package.json

rollback antd version
Fixes #
❎ No
| 🇺🇸 English |   rollback antd version           |
| 🇨🇳 中文    |      降级antd版本        |
❎ No

fix(common): fix antd style issue

---

shell/app/modules/extra/entry.js

fix: redo shell/app/modules/extra/entry.js
Fixes #
❎ No
| 🇺🇸 English |     redo shell/app/modules/entry.js         |
| 🇨🇳 中文    |      撤销更改 shell/app/modules/entry.js       |
❎ No

fix: redo shell/app/modules/extra/entry.js

---

shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx

fix i18n issue
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311595&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English | fix i18n issue |
| 🇨🇳 中文    | 修复 i18n issue |
❎ No

fix(msp): fix i18n issue

---

shell/app/modules/application/router.ts

Commit detail header add app name.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311442&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&tab=ALL&type=TASK)
| 🇺🇸 English |  Add application name display to submit details header.  |
| 🇨🇳 中文    |   提交详情头部增加应用名称显示。   |
❎ No

feat(dop): commit detail header add app name

---

scheduler/src/filters/not-found.filter.ts

Fixes #
| 🇺🇸 English |    fix: fix missing header from node request          |
| 🇨🇳 中文    | fix: 修复node端请求缺少的header           |
release/2.1

fix: fix missing header from node request

---

pnpm-lock.yaml
shell/package.json

fix antd version
Fixes #
❎ No
| 🇺🇸 English |      fix antd version        |
| 🇨🇳 中文    |     修复antd版本         |
❎ No

fix(common): fix antd version

---

shell/app/modules/project/pages/settings/components/project-workflow.tsx

fix field name
Fixes #
❎ No
| 🇺🇸 English | fix field name  |
| 🇨🇳 中文    | 修改字段名 |
❎ No

fix(dop): fix field name

---

shell/app/modules/application/tabs.tsx
shell/app/modules/project/common/components/runtime-selector.tsx
shell/app/modules/project/services/deploy.ts

App runtimes fast switch.
Fixes #
❎ No
| 🇺🇸 English |  Application deployment details added runtime quick switching.  |
| 🇨🇳 中文    |   应用的部署详情增加runtime快速切换。 |
❎ No

feat(dop): app runtimes fast switch

---

shell/app/modules/project/common/components/pipeline-new/form.tsx

Fix project pipeline add form bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=312029&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=BUG)
❎ No
| 🇺🇸 English |  Fixed bugs added to project pipeline. |
| 🇨🇳 中文    |  修复了项目流水线新增的bug。  |
❎ No

fix(dop): project pipeline add form bug

---

shell/app/config-page/components/table/render-types.tsx
shell/app/config-page/components/table/v2/utils.tsx

Fix project release list operations style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=311996&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1190&type=BUG)
->
| 🇺🇸 English |  Item artifact list operation column style repair.  |
| 🇨🇳 中文    |  项目制品列表操作列样式修复。  |
❎ No

fix(dop): project release list operations style bug

---

shell/app/modules/runtime/common/components/deployment-table.tsx

Fix rollback list style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=312197&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&type=BUG)
->
| 🇺🇸 English | Fix rollback list style issues. |
| 🇨🇳 中文    |  修复回滚列表样式问题。   |
release/2.2-beta.1-2

fix(dop): rollback list style bug

---

locales/en.json
locales/zh.json
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/pages/repo/components/mr-comments.tsx
shell/app/modules/application/pages/repo/mr-detail.tsx

feat(dop): remove mr score
Fixes #
❎ No
| 🇺🇸 English | remove mr detail score |
| 🇨🇳 中文    | 移除mr详情中评分  |
❎ No

feat(dop): remove mr score

---

shell/app/modules/project/pages/third-service/components/instance-form.tsx

Hide "select existing" and "new purchase" of addon.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=312791&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&type=TASK)
❎ No
| 🇺🇸 English |  Addon features hide the "select existing", "new purchase" features.  |
| 🇨🇳 中文    |  addon功能隐藏"选择现有"， “新购买”的功能。 |
❎ No

fix(dop): hide "select existing" and "new purchase" of addon

---

shell/app/common/types/pipeline.d.ts
shell/app/modules/application/pages/build-detail/index.tsx
shell/app/modules/application/pages/pipeline/run-detail/build-detail.tsx
shell/app/modules/application/types/build.d.ts
shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
shell/app/modules/project/pages/plan-detail/test-record/pipeline-detail.tsx

feat: hide pipeline pre check warning
Fixes #
❎ No
| 🇺🇸 English |    feat: hide pipeline pre check warning          |
| 🇨🇳 中文    |    feat: 隐藏流水线的检查警告          |
❎ No

feat: hide pipeline pre check warning

---

locales/en.json
locales/zh.json
shell/app/modules/org/pages/projects/project-list.tsx

data is in real time now.
Fixes #
| 🇺🇸 English |  remove useless tip in project list |
| 🇨🇳 中文    |     移除项目列表上无用的提示  |
❎ No

feat: remove useless tip in project list

---

pipeline.yml

decrease cpu usage for resource shortage
Fixes #
❎ No
| 🇺🇸 English |   decrease pipeline cpu usage  |
| 🇨🇳 中文    |   缩小流水线资源申请   |
❎ No

chore: decrease pipeline cpu usage

---

.github/workflows/codecov.yml

fix ut running error after PR merged
Fixes #
❎ No
❎ No

feat(chore): fix ut running error after PR merged

---

shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx
shell/app/views/index.ejs
shell/index.html

project pipeline actions operations icons change
Fixes #
| 🇺🇸 English | Project level pipeline node action icon changed. |
| 🇨🇳 中文    |  项目级流水线节点操作图标更改。 |
❎ No

fix(dop): project pipeline actions operations icons change

---

shell/app/modules/addonPlatform/pages/common/components/addon-detail-drawer.tsx
shell/app/modules/cmp/common/addon-detail/detail.tsx

feat: i18n in msp 1%
Fixes #
❎ No
| 🇺🇸 English |     feat: i18n in msp 1%         |
| 🇨🇳 中文    |      多云管理国际化文案修改1%      |
❎ No

feat: i18n in msp 1%

---

shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.scss
shell/app/modules/project/common/components/pipeline-new/detail/pipeline-node.tsx

Project pipeline actions operations icons style optimization.
Fixes #
| 🇺🇸 English |  The operation of project-level pipeline node will be displayed when the mouse is suspended.  |
| 🇨🇳 中文    |  项目级流水线节点操作等鼠标悬浮上去再显示。 |
❎ No

fix(dop): project pipeline actions operations icons style optimization

---

shell/app/modules/project/common/components/workflow/mr-workflow.tsx
shell/app/modules/project/common/components/workflow/steps/add-flow.tsx

Fixes #
- [【集成环境】研发工作流-变更分支名称修改](https://erda.cloud/erda/dop/projects/387/issues/all?id=313388&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English | modify the temporary branch naming policy |
| 🇨🇳 中文    | 修改临时分支命名策略 |
❎ No

fix(dop): modify the temporary branch naming policy

---

locales/en.json
locales/zh.json
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/marketplace/pages/detail.tsx
shell/app/modules/marketplace/pages/index.tsx
shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx

fix: marketplace style fix
Fixes #
| 🇺🇸 English |    fix: marketplace style fix          |
| 🇨🇳 中文    |    fix: 应用市场样式调整          |
❎ No

fix: marketplace style fix

---

shell/app/common/stores/common.ts

fix: keep log fallback status
Fixes #
❎ No
| 🇺🇸 English |   fix: when log fallback, keep status           |
| 🇨🇳 中文    |    fix: 日志降级后，保持降级状态        |
❎ No

fix: when log fallback, keep status

---

shell/app/modules/marketplace/pages/detail.tsx

fix: fix marketplace detail style
Fixes #
❎ No
| 🇺🇸 English |  fix: fix marketplace detail style            |
| 🇨🇳 中文    |     fix: 修复应用市场详情样式         |
❎ No

fix: fix marketplace detail style

---

shell/app/modules/project/common/components/workflow/steps/add-flow.tsx

remove two_branch type
Fixes #
❎ No
❎ No

feat(dop): remove two_branch type

---

shell/app/modules/cmp/pages/domain-manage/index.tsx

Fix domain management pagination bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=313224&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjE0Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&tab=ALL&type=BUG)
❎ No
| 🇺🇸 English |  Fixed cloud management platform - domain management list initialization page failure. |
| 🇨🇳 中文    |  修复了云管平台-域名管理列表初始化分页失效的问题。  |
❎ No

fix(cmp): domain management pagination bug

---

shell/app/common/components/base-list/index.scss
shell/app/config-page/components/list-new/list/index.scss

fix: fix dropdown menu disabled style
Fixes #
❎ No
| 🇺🇸 English |     fix: fix dropdown menu disabled style         |
| 🇨🇳 中文    |  fix: 修复dropdown菜单无权限样式            |
❎ No

fix: fix dropdown menu disabled style

---

shell/app/modules/application/pages/repo/components/compare-detail.tsx
shell/app/modules/project/common/components/workflow/index.tsx
shell/app/modules/project/common/components/workflow/issue-workflow.tsx
shell/app/modules/project/common/components/workflow/steps/base-step.scss
shell/app/modules/project/common/components/workflow/steps/base-step.tsx
shell/app/modules/project/common/components/workflow/steps/code.tsx
shell/app/modules/project/common/components/workflow/steps/index.tsx
shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
shell/app/modules/project/common/components/workflow/steps/temp-merge.tsx
shell/app/views/index.ejs
shell/index.html

optimize dev workflow style
Fixes #
❎ No

feat(dop): optimize dev workflow style

---

shell/app/modules/cmp/pages/middleware-detail/monitor.tsx

fix add-on monitor chart error
Fixes #
- [【集成环境】多云管理-应用资源-addon，监控详情页面图表显示有问题](https://erda.cloud/erda/dop/projects/387/issues/all?id=314554&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDEyLDQ1MzgsNDQxMyw0NDE0LDQ0MTUsNDQxNl19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English | fix add-on monitoring chart display error |
| 🇨🇳 中文    | 修复 add-on 监控图表显示错误 |
release/2.2-beta.2

fix(cmp): fix add-on monitoring chart display error

---

shell/app/modules/project/common/components/workflow/steps/add-flow.tsx

fix error when opening pages by sharing links
add flowName field
Fixes #
❎ No
| 🇺🇸 English |  - |
❎ No

feat(dop): add flowName field when create flow

---

locales/en.json
locales/zh.json
shell/app/modules/org/pages/setting/block-network.tsx

feat: add label tip in block network setting
Fixes #
| 🇺🇸 English |   feat: add label tip in block network setting           |
| 🇨🇳 中文    |    feat: 封网设置添加提示          |
❎ No

feat: add label tip in block network setting

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx

fix: fix ticket label render error
Fixes #
❎ No
| 🇺🇸 English |    fix: fix ticket label render error          |
| 🇨🇳 中文    |    fix: 修复工单标签渲染错误       |
release/2.2-beta.2

fix: fix ticket label render error

---

shell/app/modules/project/common/components/workflow/index.tsx

fix: fix pipeline config path
Fixes #
❎ No
| 🇺🇸 English |  fix: fix pipeline config path            |
| 🇨🇳 中文    |   fix: 修复流水线config文件路径          |
❎ No

fix: fix pipeline config path

---

shell/app/modules/cmp/common/alarm-strategy/strategy-form.tsx

fix: i18n critical to serious
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=315004&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XSwiYXNzaWduZWVJRHMiOlsiMTAwMzE0NiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1218&type=BUG)
✅ Yes(![Uploading image.png…]())
| 🇺🇸 English |      fix: i18n critical to serious        |
| 🇨🇳 中文    |      修复国际化文案  critical to serious    |
❎ No

fix: i18n 'critical' to 'serious'

---

pnpm-lock.yaml
shell/package.json

fix i18n plugin error
Fixes #
❎ No
| 🇺🇸 English |        -      |
| 🇨🇳 中文    |   -           |
❎ No

fix(common): fix i18n plugin error

---

pnpm-lock.yaml
shell/package.json

fix i18n plugin error
Fixes #
❎ No
❎ No

fix(common): fix i18n plugin issue

---

pnpm-lock.yaml
shell/babel.config.js
shell/package.json

fix pipeline hang issue
Fixes #
❎ No
❎ No

fix(common): fix pipeline hang issue

---

package.json
pnpm-lock.yaml

fix: rollback vite version
Fixes #
❎ No
| 🇺🇸 English |      fix: vite full page reload, rollback vite version        |
| 🇨🇳 中文    |     fix: vite 页面重载问题，回退vite版本        |
❎ No

fix: rollback vite version

---

shell/app/modules/project/pages/deploy/add-deploy/release-list.tsx
shell/app/modules/project/types/deploy.d.ts

Create deploy releases list optimization.
Fixes #
❎ No
| 🇺🇸 English |  Field changes to create a list of deployment artifacts.  |
| 🇨🇳 中文    | 创建部署单时制品列表的字段变更。 |
❎ No

fix(dop): create deploy releases list optimization

---

shell/app/modules/msp/env-overview/service-list/pages/transaction.scss
shell/app/modules/msp/env-overview/service-list/pages/transaction.tsx
shell/app/styles/antd-extension.scss

fix style issue
Fixes #
❎ No
| 🇺🇸 English | fix style issue |
| 🇨🇳 中文    | 修复样式问题 |
❎ No

fix: fix style issue

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/pages/pipeline/index.tsx
shell/app/modules/application/pages/pipeline/obsoleted-pipeline.tsx
shell/app/modules/application/router.ts

fix: app obsoleted pipeline menu href error
Fixes #
❎ No
| 🇺🇸 English |    fix: app obsoleted pipeline menu href error          |
| 🇨🇳 中文    |      fix: 修复应用旧版流水线菜单链接错误         |
release/2.2-beta.2-2

fix: app obsoleted pipeline menu href error

---

shell/app/common/stores/common.ts
shell/app/modules/runtime/common/logs/components/container-log.tsx

fix: fix container log fallback error
Fixes #
❎ No
| 🇺🇸 English |       fix: fix container log fallback error       |
| 🇨🇳 中文    |     fix: 修复容器日志降级错误        |
release/2.2-beta.2-2

fix: fix container log fallback error

---

core/src/i18n.ts
pnpm-lock.yaml
shell/package.json

downgrade translation to free call when secret file not provided
Fixes #
❎ No
❎ No

fix(common): downgrade translation to free call when secret file not provided

---

shell/app/modules/application/router.ts
shell/app/modules/application/stores/application.tsx
shell/app/modules/application/tabs.tsx
shell/app/modules/project/common/components/iteration-selector.tsx
shell/app/modules/project/router.tsx
shell/app/modules/project/tabs.tsx

feat: hold head menu position
Fixes #
| 🇺🇸 English |  feat: hold head menu position            |
| 🇨🇳 中文    |      feat: 页头菜单保留焦点       |
❎ No

feat: hold head menu position

---

shell/app/common/components/log-roller/index.tsx
shell/app/common/components/pure-log-roller/download-log-modal.tsx
shell/app/common/components/pure-log-roller/log-roller.tsx
shell/app/modules/runtime/common/logs/components/container-log.tsx

feat: add fallback log download
Fixes #
❎ No
| 🇺🇸 English |    feat: add fallback log download          |
| 🇨🇳 中文    |   feat:添加日志回滚后的下载      |
❎ No

feat: add fallback log download

---

shell/app/modules/application/router.ts

fix: fix dataTask menu
Fixes #
❎ No
| 🇺🇸 English |     fix: fix dataTask menu         |
| 🇨🇳 中文    |    fix: 修复数据任务菜单错误      |
release/2.1

fix: fix dataTask menu

---

shell/app/locales/en.json
shell/app/locales/zh.json

Safety policy config text optimization.
Fixes #
| 🇺🇸 English | Security policy copy optimization.  |
| 🇨🇳 中文    | 安全策略文案优化。 |
❎ No

fix(msp): safety policy config text optimization

---

shell/app/common/components/log-roller/index.tsx
shell/app/common/components/pure-log-roller/log-roller.tsx

fix: disabled fallback log download
Fixes #
❎ No
| 🇺🇸 English |    fix: disabled fallback log download          |
| 🇨🇳 中文    |    fix: 回滚日志不可下载         |
❎ No

fix: disabled fallback log download

---

shell/app/modules/project/pages/deploy/index.tsx

fix env style issue
Fixes #
| 🇺🇸 English |    fix env style issue          |
| 🇨🇳 中文    |     修复环境列表显示不全问题         |
❎ No

fix(dop): fix env style issue

---

shell/app/modules/project/common/components/pipeline-new/list.tsx

fix: fix empty pipeline record
Fixes #
❎ No
| 🇺🇸 English |  fix: fix empty pipeline record            |
| 🇨🇳 中文    |    fix: 修复pipeline记录为空问题          |
❎ No

fix: fix empty pipeline record

---

shell/app/modules/publisher/pages/artifacts/upload-modal.tsx

enlarge upload limit size
Fixes #
❎ No
| 🇺🇸 English |      enlarge upload limit size        |
| 🇨🇳 中文    |   增加上传大小限制           |
release/1.4

feat(common): enlarge upload limit size

---

shell/app/common/components/image-upload/index.tsx
shell/app/modules/publisher/pages/artifacts/artifacts-form-modal.tsx
shell/app/modules/publisher/pages/artifacts/artifacts-info.tsx

fix yankuang publisher issue
Fixes #
| 🇺🇸 English |     fix yankuang publisher issue         |
| 🇨🇳 中文    |      回滚兖矿需求        |
release/1.4

fix(dop): fix yankuang publisher issue

---

scheduler/src/filters/not-found.filter.ts

add dingding User-Agent to show title in dingding link
Fixes #
❎ No
| 🇺🇸 English |       add dingding User-Agent to show title in dingding link       |
| 🇨🇳 中文    |  添加钉钉ua以在钉钉链接中显示erda的名称            |
❎ No

feat(common): add dingding User-Agent to show title in dingding link

---

scheduler/src/filters/not-found.filter.ts

update dingtalk ua
Fixes #
❎ No
❎ No

feat(scheduler): update dingtalk ua

---

shell/app/modules/project/common/components/pipeline-new/list.tsx
shell/app/modules/project/services/pipeline.tsx

fix: fix pipeline record params error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix pipeline record params error           |
| 🇨🇳 中文    |  fix: 流水线记录参数错误           |
cherry-pick release/2.2-beta.3

fix: fix pipeline record params error

---

shell/app/i18n-easy-edit/utils/overwrite-i18n.tsx
shell/app/i18n.ts

fix duplicate i18n-wrapper bug
Fixes #3577 
✅ Yes(![image](https://user-images.githubusercontent.com/72543663/173512835-8178ceea-f0d8-46f3-9d7d-b79087e8f32d.png))
| 🇺🇸 English |     fix duplicate i18n-wrapper bug         |
| 🇨🇳 中文    |     修复 bug：出现嵌套的i18n-wrapper        |

fix: duplicate i18n-wrapper bug

---

README.md
shell/app/common/components/cards-layout/index.tsx
shell/app/common/components/configurable-filter/__tests__/external-item.test.tsx
shell/app/common/components/contractive-filter/__tests__/index.test.tsx
shell/app/common/components/form-modal/index.tsx
shell/app/common/components/k-v-pair/__tests__/index.test.tsx
shell/app/common/components/render-form-item/index.tsx
shell/app/modules/project/common/components/workflow/steps/pipeline.tsx
shell/app/modules/project/common/components/workflow/steps/temp-merge.tsx
shell/package.json

fix some unit test warning 
Fixes #
❎ No
| 🇺🇸 English |     fix: unit test warning log   |
| 🇨🇳 中文    |   修复部分单测警告日志     |
❎ No

fix: unit test warning log

---

shell/app/views/index.ejs

close links for now
Fixes #
❎ No
| 🇺🇸 English |       close links for not ready yet       |
| 🇨🇳 中文    |       暂时关闭聆提入口等对接好再开放       |
❎ No

feat: close links for not ready yet

---

shell/app/common/components/edit-field/index.tsx

fix: fix issue detail markdown expand error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix issue detail markdown expand error           |
| 🇨🇳 中文    |    fix: 事项详情markdown展开错误         |
❎ No

fix: fix issue detail markdown expand error

---

shell/app/modules/application/pages/repo/components/add-pipelineyml.tsx

fix: fix pipeline template add error
Fixes #
| 🇺🇸 English |      fix: fix pipeline template add error        |
| 🇨🇳 中文    |    fix: 修复流水线添加模板错误       |
❎ No

fix: fix pipeline template add error

---

pnpm-lock.yaml
shell/app/common/components/markdown-render/index.tsx
shell/package.json

fix: fix markdown html tag render
Fixes #
to
to
| 🇺🇸 English |    fix: fix markdown html tag render          |
| 🇨🇳 中文    |   fix: 修复markdown中对于html标签的渲染           |
❎ No

fix: fix markdown html tag render

---

erda.yml
shell/app/layout/pages/page-container/components/navigation/index.tsx

feat: add gallery enable config
Fixes #
❎ No
| 🇺🇸 English |  feat: add gallery enable config            |
| 🇨🇳 中文    |   feat: 添加gallery入口控制           |
❎ No

feat: add gallery enable config

---

shell/app/modules/application/pages/repo/branch-compare-detail.tsx
shell/app/modules/application/pages/repo/components/compare-detail.tsx
shell/app/modules/application/pages/repo/repo-mr-creation.tsx

fix: hide workflow in create MR & in branch compare
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=316590&issueFilter__urlQuery=eyJhc3NpZ25lZUlEcyI6WyIxMDAzMTQ2Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1280&type=BUG)
❎ No
| 🇺🇸 English |     hide workflow in create MR & in branch compare         |
| 🇨🇳 中文    |        在新建mr以及比较分支时隐藏工作流      |
❎ No

fix: hide workflow in create MR & in branch compare

---

erda.yml

fix: gallery default config
Fixes #
❎ No
| 🇺🇸 English |    fix: gallery default config          |
| 🇨🇳 中文    |   fix: 修复gallery入口默认配置         |
❎ No

fix: gallery default config

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/common/components/workflow/index.tsx

fix: disable merge when tempBranch is not exist
Fixes #
❎ No
| 🇺🇸 English |  fix: disable merge when tempBranch is not exist            |
| 🇨🇳 中文    |    fix: 当tempBranch 不存在时，禁止合并         |
❎ No

fix: disable merge when tempBranch is not exist

---

shell/vite.config.js
shell/webpack.config.js

fix: gallery entry config
Fixes #
❎ No
| 🇺🇸 English |     fix: gallery entry config         |
| 🇨🇳 中文    |  fix: 修复gallery入口配置           |
❎ No

fix: gallery entry config

---

shell/app/common/components/log-roller/index.tsx
shell/app/common/components/pure-log-roller/log-roller.tsx

fix: log fallback download
Fixes #
❎ No
| 🇺🇸 English | fix: log fallback download             |
| 🇨🇳 中文    |    fix: 日志降级下载      |
release/2.2-beta.3

fix: log fallback download

---

scheduler/src/filters/not-found.filter.ts
shell/app/locales/en.json
shell/app/locales/zh.json

fix: fix uc redirect url
Fixes #
❎ No
| 🇺🇸 English |   fix: fix uc redirect url           |
| 🇨🇳 中文    |    fix: 修复uc重定向链接         |
❎ No

fix: fix uc redirect url

---

scheduler/src/filters/not-found.filter.ts

hotfix: fix uc redirect url error
Fixes #
❎ No
| 🇺🇸 English |   hotfix: fix uc redirect url error           |
| 🇨🇳 中文    |   hotfix: 修复uc重定向路径错误       |
❎ No

fix: fix uc redirect url error

---

shell/app/common/components/pure-log-roller/log-roller.scss
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/runtime/common/logs/components/container-log.tsx

feat: add fallback log type and tip
Fixes #
| 🇺🇸 English |   feat: add fallback log type and tip           |
| 🇨🇳 中文    |   feat:  添加日志降级类型及提示       |
❎ No

feat: add fallback log type and tip

---

pnpm-lock.yaml
scheduler/package.json
scheduler/src/app.module.ts
scheduler/src/controllers/linkS-token.controller.ts
shell/app/App.tsx
shell/app/views/index.ejs

add links entry
Fixes #
❎ No
| 🇺🇸 English |     add links entry         |
| 🇨🇳 中文    |        添加聆提入口      |
❎ No

feat(scheduler): add links entry

---

pnpm-lock.yaml
shell/app/App.tsx
shell/app/common/utils/go-to.tsx
shell/package.json
shell/webpack.config.js

add ga
Fixes #
❎ No
| 🇺🇸 English |      add ga        |
| 🇨🇳 中文    |      添加ga        |
❎ No

feat(common): add ga

---

shell/app/App.tsx

typo
Fixes #
❎ No
| 🇺🇸 English |         -     |
❎ No

fix(common): typo

---

shell/app/config-page/page-render.tsx
shell/app/modules/project/pages/release/components/application-detail.tsx

fix: add custom click goto in config-page
Fixes #
❎ No
| 🇺🇸 English |   fix: add custom click goto in config-page           |
| 🇨🇳 中文    |    fix: 组件化协议中支持自定义跳转         |
release/2.2

fix: add custom click goto in config-page

---

pnpm-lock.yaml
shell/package.json

fix(common): typo package

---

shell/app/common/components/pure-log-roller/download-log-modal.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/runtime/common/logs/components/container-log.tsx

fix: fix fallback log download params error
Fixes #
❎ No
| 🇺🇸 English |  fix: fix fallback log download params error            |
| 🇨🇳 中文    |    fix: 降级日志下载参数错误          |
❎ No

fix: fix fallback log download params error

---

shell/app/modules/project/pages/settings/components/project-workflow.tsx

fix: fix project workflow tips
Fixes #
❎ No
| 🇺🇸 English |    fix: fix project workflow tips          |
| 🇨🇳 中文    |     fix: 修复研发工作流提示语句     |
release/2.2

fix: fix project workflow tips

---

shell/app/modules/msp/monitor/trace-insight/stores/trace-querier.ts

fix: fix trace request params error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix trace request params error           |
| 🇨🇳 中文    |     fix: 修复trace 参数错误         |
release/2.2

fix: fix trace request params error

---

shell/app/modules/project/common/components/pipeline-new/list.tsx
shell/app/modules/project/services/pipeline.tsx

fix: fix pipeline history params error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix pipeline history params error           |
| 🇨🇳 中文    |  fix: 修复流水线历史参数错误         |
release/2.2

fix: fix pipeline history params error

---

erda.yml

adjust enterprise-ui resource 
erda-ui release is error render result now，request is bigger than limit.
reviewer: @McDaddy 
Fixes #
❎ No
| 🇺🇸 English |   adjust enterprise-ui resource            |
| 🇨🇳 中文    |    调整企业 ui 资源配比          |
❎ No

fix(ui): adjust enterprise-ui resource 

---

shell/app/config-page/components/table/render-types.tsx

fix: fix table render style
Fixes #
| 🇺🇸 English |  fix: fix table render style            |
| 🇨🇳 中文    |    fix: 修复table单元格渲染样式        |
release/2.2

fix: fix table render style

---

pnpm-lock.yaml

Fixes #
❎ No
| 🇺🇸 English |        -      |
❎ No

fix(common): fix missing lock file

---

modules/market/src/pages/download.tsx

fix: api error
Fixes #3632 
❎ No
| 🇺🇸 English |     fix api error in market/download     |
| 🇨🇳 中文    |      修复接口错误        |
❎ No

fix: api error in market/download

---

shell/app/config-page/components/simple-chart/simple-chart.tsx
shell/app/modules/project/pages/issue/issue-dashboard.tsx
shell/app/modules/project/pages/issue/statistics.tsx
shell/app/modules/project/pages/issue/task-summary.tsx

fix: fix issue measure refresh error
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=321472&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDM5MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTAwfQ%3D%3D&iterationID=1297&type=BUG)
❎ No
| 🇺🇸 English |   fix: fix issue measure refresh error           |
| 🇨🇳 中文    |    fix: 修复事项统计页面刷新后错误          |
release/2.2

fix: fix issue measure refresh error

---

shell/webpack.config.js

change var name
Fixes #
❎ No
| 🇨🇳 中文    |        -      |
❎ No

feat(common): change var name

---

shell/app/common/components/menu/__tests__/index.test.tsx
shell/app/common/components/menu/index.tsx
shell/app/common/utils/__tests__/index.test.tsx
shell/app/common/utils/go-to.tsx
shell/app/common/utils/index.ts
shell/app/modules/application/pages/repo/components/branch-compare.tsx
shell/app/modules/application/pages/repo/components/repo-breadcrumb.tsx
shell/app/modules/application/pages/repo/components/repo-nav.tsx
shell/app/modules/application/pages/repo/repo-branch.tsx
shell/app/modules/application/pages/repo/repo-commit.tsx
shell/app/modules/application/pages/repo/repo-tree.tsx
shell/app/modules/application/services/repo.ts
shell/app/modules/application/tabs.tsx

fix: encode # in app/repo
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=317559&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XSwiYXNzaWduZWVJRHMiOlsiMTAwMzE0NiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1297&type=BUG)
❎ No
| 🇺🇸 English |        fix(repo): encode # before get request      |
| 🇨🇳 中文    |     在网络请求之前转义#         |
❎ No

fix(repo): encode # before get request

---

modules/market/src/pages/download.tsx
shell/app/App.tsx

fix(common): hide Links

---

shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx

fix: fix notify dingtalk api path
Fixes #
❎ No
| 🇺🇸 English |     fix: fix notify dingtalk api path         |
| 🇨🇳 中文    |   fix:  钉钉通知api调整        |
❎ No

fix: fix notify dingtalk api path

---

shell/app/modules/application/pages/repo/repo-tree.tsx
shell/app/modules/application/services/repo.ts

fix: fix branch with hash tab error
Fixes #
❎ No
| 🇺🇸 English |     fix: fix branch with hash tab error         |
| 🇨🇳 中文    |  fix: 修复分支带#错误         |
❎ No

fix: fix branch with hash tab error

---

core/src/service/index.ts
modules/components/src/form/index.tsx
modules/components/src/form/utils.tsx
modules/components/src/table/index.tsx
modules/components/src/table/interface.ts
modules/components/src/table/utils.tsx
pnpm-lock.yaml
shell/app/modules/runtime/pages/overview/components/elastic-scaling.scss
shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx
shell/app/modules/runtime/pages/overview/components/service-card.tsx
shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
shell/app/modules/runtime/services/runtime.ts
shell/app/modules/runtime/types/runtime.d.ts
shell/app/modules/runtime/types/service.d.ts
shell/package.json

elastic sacaling feature
- [] I18n is finished and updated by cli
- [ x] Display normally in english mode
Fixes #
| 🇺🇸 English |       elastic sacaling       |
| 🇨🇳 中文    |     弹性伸缩         |
❎ No

feat(dop): elastic sacaling

---

shell/app/config-page/index.tsx

fix: hide loading when asyncAtInit in Config-page
Fixes #
❎ No
| 🇺🇸 English |     fix: hide loading when asyncAtInit in Config-page         |
| 🇨🇳 中文    |    fix:  组件化协议中异步加载时去掉loading        |
❎ No

fix: hide loading when asyncAtInit in Config-page

---

shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy-card.tsx
shell/app/modules/project/pages/settings/components/workflow-setting/branch-policy.tsx

fix: fix branch policy valid error
Fixes #
❎ No
| 🇺🇸 English |       fix: fix branch policy valid error       |
| 🇨🇳 中文    |    fix: 修复分支策略校验错误        |
❎ No

fix: fix branch policy valid error

---

shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-detail.tsx
shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx

minor fix for elastic scale
Fixes #
❎ No
❎ No

fix(dop): minor fix for elastic scale

---

shell/app/common/utils/go-to.tsx
shell/app/modules/project/common/components/issue/add-mr-relation.tsx
shell/app/modules/project/common/components/issue/issue-activities.tsx
shell/app/modules/project/common/components/workflow/add-flow.tsx
shell/app/modules/project/common/components/workflow/cards/base.tsx
shell/app/modules/project/common/components/workflow/cards/code.tsx
shell/app/modules/project/common/components/workflow/cards/merge-request.tsx
shell/app/modules/project/common/components/workflow/cards/merge.tsx
shell/app/modules/project/common/components/workflow/cards/pipeline.tsx
shell/app/modules/project/common/components/workflow/index.tsx
shell/app/modules/project/types/devops-workflow.d.ts

feat: add devops workflow mr step
Fixes #
| 🇺🇸 English |   feat: add devops workflow mr step           |
| 🇨🇳 中文    |     feat: 添加研发工作流mr步骤      |
❎ No

feat: add devops workflow mr step

---

modules/components/src/form/utils.tsx
shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-detail.tsx
shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx

elastic scale issue fix
Fixes #
❎ No
❎ No

fix(dop): elastic scale issue fix

---

shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx

fix elastic scale issue
Fixes #
❎ No
| 🇨🇳 中文    |         -     |
❎ No

fix(dop): fix elastic scale issue

---

shell/app/modules/msp/services/log-analyze.ts

feat: add log regexp parse service
Fixes #
❎ No
| 🇺🇸 English |    feat: add log regexp parse service          |
| 🇨🇳 中文    |   feat: 添加日志分析正则后端service       |
❎ No

feat(msp): add log regexp parse service

---

shell/app/modules/runtime/pages/overview/components/elastic-scaling.scss
shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx

fix elastic scale form issue
Fixes #
❎ No
| 🇺🇸 English |        -      |
❎ No

fix(dop): fix elastic scale form issue

---

shell/app/modules/project/common/components/workflow/add-flow.tsx
shell/app/modules/project/common/components/workflow/cards/merge-request.tsx
shell/app/modules/project/common/components/workflow/cards/merge.tsx
shell/app/modules/project/common/components/workflow/cards/pipeline.tsx

fix: fix devops commit empty error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix devops commit empty error           |
| 🇨🇳 中文    |      fix: 修复工作流commit为空错误      |
❎ No

fix(dop): fix devops commit empty error

---

modules/market/src/pages/download.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/application/pages/obsoleted-pipeline/run-detail/build-detail.tsx
shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx
shell/app/modules/runtime/pages/overview/components/elastic-scaling.tsx

enable disable node func
Fixes #
❎ No
| 🇨🇳 中文    |        -      |

fix(dop): enable disable node func

---

shell/app/modules/cmp/pages/cluster-container/cluster-nodes-detail.tsx
shell/app/modules/cmp/pages/cluster-container/cluster-pod-detail.tsx
shell/app/modules/publisher/pages/statistics/detail.tsx
shell/app/modules/publisher/pages/statistics/index.tsx

fix: fix timespan refresh when init
Fixes #
❎ No
| 🇺🇸 English |     fix: fix timespan refresh when init         |
| 🇨🇳 中文    |    fix: 修复时间选择在初始化的时候刷新      |
release/2.3-beta.2

fix: fix timespan refresh when init

---

shell/app/common/use-hooks.tsx
shell/app/common/utils/go-to.tsx
shell/app/modules/application/pages/problem/problem-list.tsx
shell/app/modules/application/pages/quality/entry.tsx
shell/app/modules/application/pages/quality/index.scss
shell/app/modules/application/pages/quality/index.tsx
shell/app/modules/application/pages/test/test-list.tsx

fix test report url issue 
Fixes #
❎ No
| 🇺🇸 English |     fix test report url issue         |
| 🇨🇳 中文    |     【答疑】钉钉通知中单元测试报告详情不能正常打开         |
❎ No

feat(common): add tab & pop component hook

---

shell/app/modules/application/pages/repo/components/source-target-select.tsx

show target brach base on branch policy when create mr
Fixes #
❎ No
| 🇺🇸 English |         show target brach base on branch policy     |
| 🇨🇳 中文    |    【研发自动化】应用中的分支合并请求要按分支策略进行          |
❎ No

feat(dop): show target brach base on branch policy

---

shell/app/modules/project/common/components/pipeline-new/list.tsx
shell/app/modules/project/services/pipeline.tsx

fix: fix pipeline record params
Fixes #
❎ No
| 🇺🇸 English |     fix: fix pipeline record params         |
| 🇨🇳 中文    |    fix: 修复流水线接口参数      |
❎ No

fix: fix pipeline record params

---

shell/app/common/utils/index.ts
shell/app/config-page/components/table/render-types.tsx
shell/app/config-page/components/table/v2/utils.tsx

feat: add string auto formater
Fixes #
❎ No
| 🇺🇸 English |  feat: add string auto formatter            |
| 🇨🇳 中文    |    feat: 添加字符串自动转换          |
❎ No

feat: add string auto formatter

---

shell/app/modules/project/common/components/pipeline-new/form.tsx

fix: fix pipeline create form init error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix pipeline create form init error           |
| 🇨🇳 中文    |   fix: 修复流水线表单初始化错误          |
❎ No

fix: fix pipeline create form init error

---

shell/app/common/utils/index.ts

fix: fix time format
Fixes #
❎ No
| 🇺🇸 English |      fix: fix time format        |
| 🇨🇳 中文    |      fix: 修复时间转换        |
❎ No

fix: fix time format

---

shell/app/modules/project/pages/settings/components/workflow-setting/devops-workflow.tsx

fix: firefox popover style compatible
Fixes #
❎ No
| 🇺🇸 English |   fix: firefox popover style compatible           |
| 🇨🇳 中文    |   fix: firefox中popover样式兼容       |
❎ No

fix: firefox popover style compatible

---

scheduler/src/filters/not-found.filter.ts

fix: fix api orgs header
Fixes #
❎ No
| 🇺🇸 English |   fix: fix api orgs header           |
| 🇨🇳 中文    |   fix: 修复api/orgs的请求header           |
❎ No

fix: fix api orgs header

---

shell/app/App-vite.tsx
shell/app/common/utils/__tests__/index.test.tsx
shell/app/common/utils/index.ts
shell/app/org-home/pages/land/index.tsx
shell/app/org-home/services/org.tsx
shell/app/org-home/stores/org.tsx

fix: fix org joined list
Fixes #
❎ No
| 🇺🇸 English |    fix: fix org joined list          |
| 🇨🇳 中文    |     fix: 修复已加入组织列表数据       |
❎ No

fix: fix org joined list

---

shell/app/views/index.ejs

add csp for links
Fixes #
❎ No
❎ No

feat(common): add csp for links

---

shell/app/views/index.ejs

add 'unsafe-inline'
Fixes #
❎ No
| 🇨🇳 中文    |        -      |
❎ No

fix(common): add 'unsafe-inline'

---

shell/app/views/index.ejs

add csp policy
Fixes #
❎ No
❎ No

fix(common): add csp policy

---

shell/app/common/components/pure-log-roller/__tests__/log-roller.test.tsx
shell/app/common/components/pure-log-roller/index.ts
shell/app/common/components/pure-log-roller/log-roller.tsx
shell/app/links-service.ts
shell/app/org-home/stores/org.tsx

Fixes #
❎ No
| 🇺🇸 English |       fix logger crash in safari issue       |
| 🇨🇳 中文    |      流水线页面某跳转逻辑不兼容 Safari 浏览器        |
❎ No

fix(common): fix logger crash issue

---

scheduler/src/proxy.ts

fix: fix domain header in proxy
Fixes #
❎ No
| 🇺🇸 English |        -      |
| 🇨🇳 中文    |    -          |
❎ No

fix: fix domain header in proxy

---

scheduler/src/proxy.ts

fix: fix local domain header
Fixes #
❎ No
| 🇨🇳 中文    |   -           |
❎ No

fix: fix local domain header

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/backlog/backlog.tsx
shell/app/modules/project/pages/backlog/iteration-item.tsx
shell/app/modules/project/pages/issue/board.tsx
shell/app/modules/project/pages/issue/gantt/index.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx
shell/app/modules/project/pages/milestone/index.tsx
shell/app/modules/runtime/pages/overview/components/service-card.tsx
shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx

add elastic sacling text
Fixes #
❎ No
| 🇺🇸 English |        add elastic sacling text      |
| 🇨🇳 中文    |      添加弹性伸缩开启提示        |
❎ No

feat(dop): add elastic sacling text

---

erda.yml

fix: fix openapi addr
Fixes #
❎ No
| 🇨🇳 中文    |  -            |
❎ No

fix: fix openapi addr

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/flow/records.tsx
shell/app/modules/project/router.tsx

feat: add flow records
Fixes #
❎ No
| 🇺🇸 English |   feat: add flow records           |
| 🇨🇳 中文    |   feat: 添加工作流记录页面          |
❎ No

feat: add flow records

---

core/package.json
modules/market/package.json
modules/uc/package.json
pnpm-lock.yaml
shell/package.json

support 360 browser
Fixes #
❎ No
| 🇺🇸 English |       support 360 browser       |
| 🇨🇳 中文    |      支持360浏览器        |
❎ No

fix(common): support 360 browser

---

cli/lib/service-generator.ts

1) add "AUTO" to each api path;
2) deal with the unrequired data in response data
Fixes #
none
none
❎ No
fix some problem
❎ No

feat: optimize service-generator

---

shell/app/links-service.ts

change links api
Fixes #
❎ No
| 🇨🇳 中文    |           -   |
❎ No

feat(dop): change links api

---

shell/app/common/components/cards-layout/index.tsx
shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx

fix: addon key duplicate
Fixes #
❎ No
| 🇺🇸 English |    fix: addon key duplicate          |
| 🇨🇳 中文    |  fix:addon 卡片key重复           |
❎ No

fix: addon key duplicate

---

shell/app/common/components/table/index.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx

feat: issue table row highlight
Fixes #
❎ No
| 🇺🇸 English |    feat: issue table row highlight          |
| 🇨🇳 中文    |      feat: 事项列表行高亮      |
❎ No

feat: issue table row highlight

---

scheduler/src/filters/not-found.filter.ts

fix: fix admin joined org error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix admin joined org error           |
| 🇨🇳 中文    |  fix:  修复admin已加入组织数据错误         |
❎ No

fix: fix admin joined org error

---

shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx

add k8s Restriction for elastic scale
Fixes #
❎ No
| 🇺🇸 English |   add k8s Restriction for elastic scale           |
| 🇨🇳 中文    |     弹性伸缩根据集群类型决定入口是否要打开         |
❎ No

feat(dop): add k8s Restriction for elastic scale

---

shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/pages/backlog/issue-item.scss
shell/app/modules/project/pages/backlog/issue-item.tsx

feat: add requirement flow in todolist
Fixes #
| 🇺🇸 English |     feat: add requirement flow in todolist         |
| 🇨🇳 中文    |    feat: 需求下todolist中添加工作流          |
❎ No

feat: add requirement flow in todolist

---

shell/app/common/components/edit-field/index.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/addonPlatform/pages/common/components/addon-cards.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/pages/issue/board.tsx

avoid mistake close editing content
Fixes #
❎ No
| 🇺🇸 English |      avoid mistake close editing content        |
| 🇨🇳 中文    |   【答疑】事项编辑内容支持缓存，再次开启后提示是否需要进入上次编辑内容           |
❎ No

feat(dop): avoid mistake close editing content

---

shell/app/common/utils/index.ts
shell/app/modules/project/common/components/pipeline-new/list.tsx

fix: fix pipeline record refresh
Fixes #
❎ No
| 🇺🇸 English |      fix: fix pipeline record refresh        |
| 🇨🇳 中文    |    fix: 修复流水线记录        |
❎ No

fix: fix pipeline record refresh

---

shell/app/modules/cmp/pages/middleware-dashboard/usage-chart.tsx

fix: fix cmp addon data empty error
Fixes #
❎ No
| 🇺🇸 English |    fix: fix cmp addon data empty error          |
| 🇨🇳 中文    |   fix: cmp中addon数据为空错误           |
❎ No

fix: fix cmp addon data empty error

---

shell/app/modules/project/pages/backlog/issue-item.tsx

fix: fix requirement flow request error
Fixes #
❎ No
| 🇺🇸 English |  fix: fix requirement flow request error            |
| 🇨🇳 中文    |     fix: 修复需求工作流下请求错误      |
❎ No

fix: fix requirement flow request error

---

shell/app/modules/application/common/components/list-input-group.tsx

fix: fix pipeline input group form value type
Fixes #
❎ No
| 🇺🇸 English |  fix: fix pipeline input group form value type            |
| 🇨🇳 中文    |    fix: 修复流水线字符串数组值类型错误          |
❎ No

fix: fix pipeline input group form value type

---

shell/app/modules/application/common/components/list-input-group.tsx

fix: fix pipeline list input group change
Fixes #
❎ No
| 🇺🇸 English |      fix: fix pipeline list input group change        |
| 🇨🇳 中文    |  fix: 修复流水线字符串数组转换            |
❎ No

fix: fix pipeline list input group change

---

locales/en.json
locales/zh.json

Fixes #
❎ No
| 🇺🇸 English |         -     |
❎ No

feat(dop): i18n

---

modules/market/src/pages/download.tsx

remove jingxuan
Fixes #
❎ No
| 🇺🇸 English |         remove jingxuan      |
| 🇨🇳 中文    |     移除精选         |
release/2.3-beta.3

fix(market): remove jingxuan

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx

fix: fix issue properties empty error
Fixes #
❎ No
| 🇺🇸 English |  fix: fix issue properties empty error            |
| 🇨🇳 中文    |    fix: 修复事项属性为空错误     |
❎ No

fix: fix issue properties empty error

---

shell/app/menus/cmp.tsx
shell/app/modules/dcos/pages/cluster-dashboard/machineTabs.tsx
shell/app/modules/project/pages/resource/components/resource.jsx

feat: hide cmp resource menu 
Fixes #
❎ No
| 🇺🇸 English |  feat: hide cmp resource menu             |
| 🇨🇳 中文    |    feat: 隐藏cmp资源相关菜单           |
❎ No

feat: hide cmp resource menu 

---

modules/components/README.md
modules/components/package.json

feat(components): update version

---

shell/app/common/utils/go-to.tsx
shell/app/org-home/stores/org.tsx

modify the default route path of fdp
Fixes #
modify the default route path of fdp
❎ No
| 🇺🇸 English |        modify the default route path of fdp      |
| 🇨🇳 中文    |     修改fdp的默认跳转路径         |
❎ No

feat: modify default route path of fdp

---

shell/app/common/components/markdown-render/index.tsx

my last commit LOL
Fixes #
❎ No
| 🇺🇸 English |      fix pre tag in md issue        |
| 🇨🇳 中文    |      修复在md中使用pre tag崩溃的问题        |
release/2.2

fix(dop): fix pre tag in md issue

---

locales/en.json
locales/zh.json
shell/app/config-page/components/scale-card/scale-card.scss
shell/app/config-page/components/scale-card/scale-card.spec.d.ts
shell/app/config-page/components/scale-card/scale-card.tsx
shell/app/modules/runtime/pages/overview/components/service-card.tsx
shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
shell/app/modules/runtime/types/service.d.ts

feat: global search style
Fixes #
❎ No
| 🇺🇸 English |    feat: global search style          |
| 🇨🇳 中文    |  feat: 全局搜索样式          |
❎ No

feat: global search style

---

shell/app/modules/msp/monitor/monitor-common/components/resource-usage/resource-usage-charts.tsx

feat: add runtime container dashboard
Fixes #
❎ No
| 🇺🇸 English |    feat: add runtime container dashboard          |
| 🇨🇳 中文    |   feat: runtime容器监控大盘           |
❎ No

feat: add runtime container dashboard

---

shell/app/modules/application/pages/repo/components/repo-mr-form.tsx

fix: fix create mr error
Fixes #
❎ No
| 🇺🇸 English |    fix: fix create mr error          |
| 🇨🇳 中文    |    fix: fix create mr error          |
❎ No

fix: fix create mr error

---

shell/app/modules/project/common/components/issue/subscribers-selector.tsx

fix: issue detail subscribers
Fixes #
❎ No
| 🇺🇸 English |    fix: issue detail subscribers          |
| 🇨🇳 中文    |     fix: issue detail subscribers         |
❎ No

fix: issue detail subscribers

---

shell/app/modules/application/pages/test/test-list.tsx
shell/app/modules/application/stores/test.ts

fix: code test list pagination error
Fixes #
❎ No
| 🇺🇸 English |  fix: code test list pagination error            |
| 🇨🇳 中文    |    fix: code test list pagination error          |
❎ No

fix: code test list pagination error

---

shell/app/modules/application/pages/repo/components/compare-detail.tsx
shell/app/modules/project/common/components/workflow/mr-workflow.tsx
shell/app/modules/project/services/project-workflow.ts

fix: fix mr workflow-params
Fixes #
❎ No
| 🇺🇸 English |   fix: fix mr workflow-params           |
| 🇨🇳 中文    |      fix: fix mr workflow-params        |
❎ No

fix: fix mr workflow-params

---

shell/app/modules/application/common/components/list-input-group.tsx

fix: fix list input to textarea
Fixes #
❎ No
| 🇺🇸 English | fix: fix list input to textarea             |
| 🇨🇳 中文    |  fix: fix list input to textarea            |
❎ No

fix: fix list input to textarea

---

shell/app/antd-overwrite/avatar/index.tsx

fix: fix avatar load time
Fixes #
❎ No
| 🇺🇸 English |      fix: fix avatar load time        |
| 🇨🇳 中文    |      fix: fix avatar load time        |
❎ No

fix: fix avatar load time

---

shell/app/modules/project/pages/backlog/backlog.tsx

fix: fix backlog add issue style
Fixes #
❎ No
| 🇺🇸 English |     fix: fix backlog add issue style         |
| 🇨🇳 中文    |    fix: fix backlog add issue style          |
❎ No

fix: fix backlog add issue style

---

modules/components/__tests__/table/index.test.tsx
modules/components/docs/components/table/demos/row-action.tsx
modules/components/package.json
modules/components/src/table/interface.ts
modules/components/src/table/style/index.less
modules/components/src/table/utils.tsx

WIP: actions width
Fixes #
❎ No
| 🇺🇸 English |   modify components table    |
| 🇨🇳 中文    |   修改 components table 组件   |
❎ No

feat(components): modify components table

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/issue-drawer.tsx

fix: fix issue subscribers
Fixes #
❎ No
| 🇺🇸 English |     fix: fix issue subscribers         |
| 🇨🇳 中文    |     fix: fix issue subscribers         |
❎ No

fix: fix issue subscribers

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/runtime/pages/overview/components/service-card.tsx
shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx
shell/app/modules/runtime/services/runtime.ts
shell/app/modules/runtime/types/runtime.d.ts

feat: runtime pod list
Fixes #
❎ No
| 🇺🇸 English |     feat: runtime pod list         |
| 🇨🇳 中文    |     feat: runtime pod list         |
❎ No

feat: runtime pod list

---

shell/app/modules/project/pages/deploy/index.tsx
shell/app/modules/project/services/deploy.ts

feat: add deploy create params
Fixes #
❎ No
| 🇺🇸 English |    feat: add deploy create params          |
| 🇨🇳 中文    |  feat: add deploy create params            |
❎ No

feat: add deploy create params

---

shell/app/config-page/components/panel/panel.tsx
shell/app/modules/addonPlatform/pages/addon-resource/addon-resource.tsx
shell/app/modules/dcos/pages/cluster-dashboard/machine-detail.tsx

feat: add cmp dashboard
Fixes #
❎ No
| 🇺🇸 English |   feat: add cmp dashboard           |
| 🇨🇳 中文    |     feat: add cmp dashboard         |
❎ No

feat: add cmp dashboard

---

shell/app/modules/dcos/pages/cluster-dashboard/machine-detail.tsx

fix: fix dashboard key
Fixes #
❎ No
| 🇺🇸 English |   fix: fix dashboard key           |
| 🇨🇳 中文    |   fix: fix dashboard key           |
❎ No

fix: fix dashboard key

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/issue-relation.tsx
shell/app/modules/project/common/components/workflow/add-flow.tsx
shell/app/modules/project/common/components/workflow/index.tsx
shell/app/modules/project/common/components/workflow/issue-workflow.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/services/project-workflow.ts

feat: issue detail flow optimize
Fixes #
❎ No
| 🇺🇸 English |      feat: issue detail flow optimize        |
| 🇨🇳 中文    |      feat: issue detail flow optimize        |
❎ No

feat: issue detail flow optimize

---

shell/app/modules/project/pages/deploy/add-deploy/index.tsx
shell/app/modules/project/types/deploy.d.ts

fix: fix deploy get params
Fixes #
❎ No
| 🇺🇸 English |  fix: fix deploy get params            |
| 🇨🇳 中文    |     fix: fix deploy get params         |
❎ No

fix: fix deploy get params

---

shell/app/App.tsx

feat: add ga user id
Fixes #
❎ No
| 🇺🇸 English |    feat: add ga user id          |
| 🇨🇳 中文    |     feat: add ga user id         |
❎ No

feat: add ga user id

---

scheduler/package.json
shell/app/links-service.ts

feat: forbidden linkS request when ak sk not exits
Fixes #
❎ No
| 🇺🇸 English |   feat: forbidden linkS request when ak sk not exits           |
| 🇨🇳 中文    |  feat: forbidden linkS request when ak sk not exits            |
❎ No

feat: forbidden linkS request when ak sk not exits

---

shell/app/modules/runtime/pages/overview/components/service-card.tsx

feat: pod list optimize
Fixes #
❎ No
| 🇺🇸 English |      feat: pod list optimize        |
| 🇨🇳 中文    |   feat: pod list optimize           |
❎ No

feat: pod list optimize

---

shell/app/modules/msp/monitor/browser-insight/pages/ajax/config/apiConfig.ts
shell/app/modules/msp/monitor/browser-insight/pages/script/config/apiConfig.ts

fix: fix params
Fixes #
❎ No
| 🇺🇸 English |    fix: fix params          |
| 🇨🇳 中文    |     fix: fix params         |
❎ No

fix: fix params in dashboard

---

shell/app/modules/apiManagePlatform/pages/access-manage/detail/authorization-user.tsx
shell/app/modules/apiManagePlatform/pages/access-manage/detail/index.tsx

fix: delete some chart in api platform
Fixes #
❎ No
| 🇺🇸 English |      fix: delete some chart in api platform        |
| 🇨🇳 中文    |     fix: delete some chart in api platform         |
❎ No

fix: delete some chart in api platform

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/runtime/pages/overview/components/service-card.tsx

fix: fix runtime style
Fixes #
❎ No
| 🇺🇸 English |       fix: fix runtime style       |
| 🇨🇳 中文    |       fix: fix runtime style       |
❎ No

fix: fix runtime style

---

shell/app/modules/org/pages/projects/import-project-template.tsx
shell/app/modules/project/pages/release/components/form.tsx
shell/app/modules/runtime/pages/overview/components/service-card.tsx

fix: upload zip error in windows
Fixes #
❎ No
| 🇺🇸 English |    fix: upload zip error in windows          |
| 🇨🇳 中文    |      fix: upload zip error in windows        |
❎ No

fix: upload zip error in windows

---

shell/app/modules/apiManagePlatform/pages/client/detail/index.tsx
shell/app/modules/application/pages/settings/components/app-info.tsx

fix: api platform monitor remove
Fixes #
❎ No
| 🇺🇸 English |     fix: api platform monitor remove         |
| 🇨🇳 中文    |     fix: api platform monitor remove         |
❎ No

fix: api platform monitor remove

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx

fix: fix issue detail custom field error
Fixes #
❎ No
| 🇺🇸 English |   fix: fix issue detail custom field error           |
| 🇨🇳 中文    |   fix: fix issue detail custom field error           |
❎ No

fix: fix issue detail custom field error

---

shell/app/modules/msp/monitor/status-insight/pages/status/status-detail.tsx
shell/app/modules/runtime/pages/overview/components/service-card.tsx

fix: remove monitor last 3 month data empty
Fixes #
❎ No
| 🇺🇸 English |  fix: remove monitor last 3 month data empty            |
| 🇨🇳 中文    |    fix: remove monitor last 3 month data empty          |
❎ No

fix: remove monitor last 3 month data empty

---

shell/app/common/components/pure-log-roller/download-log-modal.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx

fix: fix issue create error
Fixes #
❎ No
| 🇺🇸 English |  fix: fix issue create error            |
| 🇨🇳 中文    |     fix: fix issue create error         |
❎ No

fix: fix issue create error

---

shell/app/common/components/log/download-log-modal.tsx

fix: Update download-log-modal.tsx
Fixes #
❎ No
| 🇺🇸 English |  fix: Update download-log-modal.tsx            |
| 🇨🇳 中文    |     fix: Update download-log-modal.tsx         |
❎ No

fix: Update download-log-modal.tsx

---

modules/components/package.json
modules/components/src/table/sorter.tsx

modify table sort text color
Fixes #
❎ No
| 🇺🇸 English |  modify erda-compoennts table sorter text color |
| 🇨🇳 中文    | 修改 erda-compoennts 的sorter下拉框文本颜色 |
❎ No

feat(components): modify table sort text color

---

locales/en.json
locales/zh.json
pnpm-lock.yaml
shell/app/modules/msp/monitor/error-insight/pages/errors/error-overview.tsx

feat: add error board grid
Fixes #
❎ No
| 🇺🇸 English |     feat: add error board grid         |
| 🇨🇳 中文    |   feat: add error board grid           |
❎ No

feat: add error board grid

---

shell/app/modules/application/pages/obsoleted-pipeline/index.tsx
shell/app/modules/application/pages/pipeline/index.tsx
shell/app/modules/application/pages/pipeline/obsoleted-pipeline.tsx

Fixes #
❎ No
| 🇺🇸 English |      fix: fix pipeline style        |
| 🇨🇳 中文    |      fix: fix pipeline style        |
❎ No

fix: fix pipeline style

---

shell/app/config-page/components/api-editor/api-editor.tsx

fix: fix api-editor body data convert error
Fixes #
❎ No
| 🇺🇸 English |    fix: fix api-editor body data convert error          |
| 🇨🇳 中文    |      fix: fix api-editor body data convert error        |
❎ No

fix: fix api-editor body data convert error

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/pipeline-manage/common/config-env-selector.tsx

fix: fix pipeline config chosen
Fixes #
❎ No
| 🇺🇸 English |     fix: fix pipeline config chosen         |
| 🇨🇳 中文    |    fix: fix pipeline config chosen          |
❎ No

fix: fix pipeline config chosen

---

shell/app/styles/app.scss

Fixes #
❎ No
| 🇺🇸 English |   fix: fix links default style           |
| 🇨🇳 中文    |fix: fix links default style              |
❎ No

fix: fix links default style

---

shell/app/modules/application/pages/build-detail/config.tsx
shell/app/modules/application/pages/obsoleted-pipeline/run-detail/config.tsx
shell/app/modules/project/common/components/pipeline-manage/run-detail/config.ts
shell/app/modules/project/common/components/pipeline-new/config.tsx

feat: add pipeline canceling
Fixes #
❎ No
| 🇺🇸 English |    feat: add pipeline canceling          |
| 🇨🇳 中文    |      feat: add pipeline canceling        |
❎ No

feat: add pipeline canceling

---

shell/app/common/components/markdown-render/index.tsx

Fixes #
❎ No
| 🇺🇸 English |   fix:fix xss           |
| 🇨🇳 中文    |     fix:fix xss         |
❎ No

fix:fix xss

---

.npmrc

Fixes #
❎ No
| 🇺🇸 English |    fix: fix npm rc          |
| 🇨🇳 中文    |     fix: fix npm rc         |
❎ No

fix: fix npm rc

---

shell/app/modules/org/pages/projects/create-project.tsx

feat: delete project type
Fixes #
❎ No
| 🇺🇸 English |       feat: delete project type       |
| 🇨🇳 中文    |    feat: delete project type          |
❎ No

feat: delete project type

---

shell/app/modules/org/pages/projects/create-project.tsx

fix: fix project create styles

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx
shell/app/modules/runtime/pages/overview/components/service-dropdown.tsx

fix: fix runtime env show error

---

shell/app/modules/application/common/components/create-add-on.tsx
shell/app/modules/dcos/common/containers/terminal.tsx
shell/app/modules/msp/services/zkproxy.ts
shell/app/modules/runtime/pages/overview/components/service-card.tsx

fix: fix cluster request in runtime

---

shell/app/modules/msp/monitor/trace-insight/pages/trace-querier/trace-search.tsx

fix: fix contractive filter

---

shell/app/common/components/base-list/list-item.tsx
shell/app/common/utils/__tests__/upload-props.test.tsx

Fixes #
❎ No
| 🇺🇸 English |    fix: fix checkbox trigger          |
| 🇨🇳 中文    |    fix: fix checkbox trigger          |
❎ No

fix: fix checkbox trigger

---

shell/app/modules/project/common/components/pipeline-new/detail/build-log.scss
shell/app/modules/project/common/components/pipeline-new/detail/build-log.tsx

Fixes #
❎ No
| 🇺🇸 English |    fix: fix log style in pipeline          |
| 🇨🇳 中文    |     fix: fix log style in pipeline         |
❎ No

fix: fix log style in pipeline

---

shell/app/modules/addonPlatform/pages/addon-resource/addon-resource.tsx
shell/app/modules/msp/types/gateway.d.ts

Fixes #
❎ No
| 🇺🇸 English | feat: add api gateway mse support             |
| 🇨🇳 中文    |   feat: add api gateway mse support           |
❎ No

feat: add api gateway mse support

---

shell/app/modules/msp/env-overview/service-list/pages/process.tsx
shell/app/modules/project/services/test-case.ts
shell/app/modules/project/stores/test-case.ts
shell/app/modules/project/types/test.d.ts

Fixes #
❎ No
| 🇺🇸 English |   feat: add projectID in testcase           |
| 🇨🇳 中文    |      feat: add projectID in testcase        |
❎ No

feat: add projectID in testcase

---

shell/app/modules/application/services/repo.ts

Fixes #
❎ No
| 🇺🇸 English |    fix: fix repo compare commit limit          |
| 🇨🇳 中文    |     fix: fix repo compare commit limit         |
❎ No

fix: fix repo compare commit limit

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx

Fixes #
❎ No
| 🇺🇸 English |    fix: fix config filter clear          |
| 🇨🇳 中文    |    fix: fix config filter clear          |
❎ No

fix: fix config filter clear

---

shell/app/common/components/configurable-filter/index.tsx
shell/app/modules/project/pages/deploy/add-deploy/add-release.tsx

fix: fix config filter clear (#3794)

---

shell/app/modules/runtime/common/logs/components/container-log.tsx

Fix bug of runtime log format conversion.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=368545&iterationID=1580&tab=BUG&type=BUG)
| 🇺🇸 English |  Fix bug of runtime log format conversion. |
| 🇨🇳 中文    |  修复了runtime日志格式转换的问题、  |
release/2.3

fix: runtime log format conversion bug

---

shell/app/modules/application/pages/settings/components/app-variable-config.tsx

Application setting pipeline variables table optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=371277&iterationID=1628&type=TASK)
| 🇺🇸 English |  Application setting pipeline variables table optimization.  |
| 🇨🇳 中文    |  应用设置-流水线变量列表优化。  |
release/2.3

fix: application setting pipeline variables table optimization

---

shell/app/modules/runtime/pages/overview/components/resource-modal.tsx

fix: fix resource adjust max limit
Fixes #
❎ No
| 🇺🇸 English |     fix: fix resource adjust max limit         |
| 🇨🇳 中文    |     fix: fix resource adjust max limit         |
❎ No

fix: fix resource adjust max limit

---

modules/uc/package.json
package.json
pnpm-lock.yaml

Fixes #
❎ No
| 🇺🇸 English |    fix: fix uc build error          |
| 🇨🇳 中文    |    fix: fix uc build error          |
❎ No

fix: fix uc build error

---

shell/app/modules/project/pages/test-env/protocol-input.tsx

Interface test params config environmental domain length optimization.
Fixes #
❎ No
| 🇺🇸 English | Interface test params config environmental domain length optimization. |
| 🇨🇳 中文    |  接口测试-参数配置-环境域名长度优化。  |
release/2.3
release/2.2
release/2.1

fix: interface test params config environmental domain length optimization

---

Dockerfile
pipeline.yml

Fixes #
❎ No
| 🇺🇸 English |     feat: multiarch pipeline         |
| 🇨🇳 中文    |    feat: multiarch pipeline          |
❎ No

feat: multiarch pipeline

---

shell/app/modules/project/pages/ticket/index.tsx

feat: add ticket import
Fixes #
❎ No
| 🇺🇸 English |   feat: add ticket import           |
| 🇨🇳 中文    |    feat: add ticket import          |
❎ No

feat: add ticket import

---

pnpm-lock.yaml
shell/package.json

Update erda-pyroscope to fix version conflict.
Fixes #
❎ No
| 🇺🇸 English |  Update erda-pyroscope to fix version conflict.  |
| 🇨🇳 中文    |  更新erda-pyroscope来解决版本冲突问题。  |
❎ No

fix: update erda-pyroscope

---

core/src/index.tsx
modules/market/src/App.tsx
modules/uc/src/router.tsx

Fix dependency version conflict.
Fixes #
❎ No
| 🇺🇸 English | Fix dependency version conflict. |
| 🇨🇳 中文    | 修复依赖项版本冲突。  |
❎ No

fix: dependency version conflict

---

modules/market/src/App.tsx
modules/uc/src/router.tsx

Fix pnpm run build-online bug.
Fixes #
❎ No
| 🇺🇸 English |  FIx pnpm run build-online bug. |
| 🇨🇳 中文    | 修复了pnpm run build-online 命令的报错。 |
❎ No

fix: pnpm run build-online bug

---

modules/market/src/App.tsx
modules/market/src/pages/download-pc.tsx
modules/market/src/pages/download.tsx
modules/uc/src/router.tsx
shell/package.json

Fix build online bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix build online bug.  |
| 🇨🇳 中文    |  修复了在线打包的bug。  |
❎ No

fix: build online bug

---

pnpm-lock.yaml

Update pnpm-pock.yaml.
Fixes #
❎ No
| 🇺🇸 English |   Update pnpm-pock.yaml.   |
| 🇨🇳 中文    |  更新pnpm-lock.yaml。  |
❎ No

fix: update pnpm-pock

---

shell/app/styles/antd-extension.scss

Fix org setting style bug.
Fixes #
->
| 🇺🇸 English |  Fix org setting style bug.  |
| 🇨🇳 中文    |   修复了组织设置里的样式问题。   |
release/2.3

fix: org setting style bug

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/pages/iteration/iteration-modal.tsx
shell/app/modules/project/pages/iteration/table.tsx

Iteration add work hours.
Fixes #
| 🇺🇸 English |  Iteration add work hours.  |
| 🇨🇳 中文    |  迭代增加工时。  |
❎ No

feat: iteration add work hours

---

package.json
pnpm-lock.yaml
shell/app/locales/zh.json
shell/app/modules/project/pages/iteration/iteration-modal.tsx
shell/package.json

Fix iteration work hours bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=386431&iterationID=1628&type=BUG)
❎ No
| 🇺🇸 English |  Fix iteration work hours bug. |
| 🇨🇳 中文    |  修复了迭代中工时的bug。 |
❎ No

fix: iteration work hours bug

---

core/src/framework/regist-router.tsx

Fix index page layout bug.
Fixes #
| 🇺🇸 English | Fix index page layout bug.  |
| 🇨🇳 中文    | 修复了首页布局的bug。 |
❎ No

fix: index page layout bug

---

shell/app/modules/project/pages/issue/import-export.tsx
shell/app/modules/project/pages/issue/issue-protocol.tsx

All issues add import button.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=382465&iterationID=1737&type=TASK)
| 🇺🇸 English |  All issues add import button. |
| 🇨🇳 中文    |  全部事项增加导入按钮。 |
❎ No

feat: all issues add import button

---

shell/app/config-page/components/line-graph/index.tsx
shell/app/modules/project/pages/iteration/iteration-modal.tsx

Fix iteration work hours validator bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix iteration work hours validator bug.   |
| 🇨🇳 中文    |  修复了迭代中工时校验的bug。  |
❎ No

fix: iteration work hours validator bug

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/meta-fields.tsx

Issue estimated time required.
Fixes #
| 🇺🇸 English |  Issue estimated time required.  |
| 🇨🇳 中文    |  事项中预估时间必填。  |
❎ No

feat: issue estimated time required

---

shell/app/modules/project/common/components/issue/time-input.tsx
shell/app/modules/project/pages/iteration/iteration-modal.tsx

Iteration work hours optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/1628/all?id=386472&iterationID=1628&type=BUG)
❎ No
| 🇺🇸 English |  Iteration work hours optimization, input immediately change the value.  |
| 🇨🇳 中文    |  迭代中工时优化，输入即改值.  |
❎ No

fix: iteration work hours optimization

---

modules/market/src/pages/download.tsx

Temporary fix market download page bug.
Fixes #
❎ No
| 🇺🇸 English | Temporary fix market download page bug.  |
| 🇨🇳 中文    |  临时解决下载移动应用页面报错问题。  |
release/2.4-beta.1

fix: market download page bug

---

shell/app/charts/components/echarts.jsx

Fix service monitoring charts click bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix service monitoring charts click bug.  |
| 🇨🇳 中文    |   修复了服务监控图表点击的bug。   |
❎ No

fix: service monitoring charts click bug

---

shell/app/charts/components/echarts.jsx

Service monitoring charts click bug test.
Fixes #
❎ No
| 🇺🇸 English |  Service monitoring charts click bug test.  |
| 🇨🇳 中文    |   服务监控图表点击bug尝试修复。  |
❎ No

fix: service monitoring charts click bug test

---

shell/app/charts/components/echarts.jsx
shell/app/modules/dop/services/index.ts

Fix service monitoring chart click bug.
Fixes #
❎ No
| 🇺🇸 English |   Fix service monitoring chart click bug.  |
| 🇨🇳 中文    |   修复了服务监控图表点击的bug。  |
❎ No

feat: service monitoring chart click bug

---

shell/app/common/components/menu/index.tsx
shell/app/common/components/pure-log-roller/log-content.tsx
shell/app/common/components/pure-log-roller/log-roller.tsx

Fix trace search log bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=431787&iterationID=1737&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |   Fix trace search log bug.   |
| 🇨🇳 中文    |   修复了链路查询日志的bug。  |
❎ No

fix: trace search log bug

---

shell/app/common/components/menu/index.tsx

Fix breadcrumb menu click bug.
Fixes #
❎ No
| 🇺🇸 English |   Fix breadcrumb menu click bug.  |
| 🇨🇳 中文    |  修复了面包屑菜单点击的bug。  |
❎ No

fix: breadcrumb menu click bug

---

shell/app/charts/components/echarts.jsx

Service monitoring charts select optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=431925&iterationID=1737&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |  Service monitoring charts select optimization.  |
| 🇨🇳 中文    |   服务监控图表选择优化。   |
❎ No

fix: service monitoring charts select optimization

---

shell/app/charts/components/echarts.jsx

Charts remove brush tool.
Fixes #
| 🇺🇸 English |  Charts remove brush tool.  |
| 🇨🇳 中文    |  图表删除选取工具  |
❎ No

fix: charts remove brush tool

---

shell/app/modules/addonPlatform/pages/addon-resource/addon-resource.tsx

Kafka monitoring acquisition optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=372121&iterationID=1737&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |  Kafka monitoring acquisition optimization.  |
| 🇨🇳 中文    |  kafka监控采集优化。  |
❎ No

fix: kafka monitoring acquisition optimization

---

shell/package.json

Fix pyroscope graphViz display bug.
Fixes #
| 🇺🇸 English |  Fix pyroscope graphViz display bug. |
| 🇨🇳 中文    |  修复了pyroscope中graphViz的展示问题。   |
❎ No

fix: pyroscope graphViz display bug

---

shell/app/modules/application/pages/repo/components/repo-mr-table.tsx

Mr table optimization.
Fixes #
| 🇺🇸 English |  Mr table optimization.  |
| 🇨🇳 中文    |  合并请求列表优化。  |
❎ No

fix: mr table optimization

---

shell/app/layout/stores/layout.ts
shell/app/layout/types/layout.d.ts

Fix msp display bug when switch bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=469109&iterationID=-1&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English | Fix msp display bug when switch bug. |
| 🇨🇳 中文    |  修复了切换组织后微服务模块的展示问题。  |
release/2.4-beta.2

fix: msp display bug when switch bug

---

scheduler/src/proxy.ts
shell/app/agent.js
shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/pages/page-container/components/chat-GPT/gpt-item.tsx
shell/app/layout/pages/page-container/components/chat-GPT/index.tsx
shell/app/layout/pages/page-container/components/chat-GPT/sidebar.tsx
shell/app/layout/pages/page-container/components/chat-GPT/user-item.tsx
shell/app/layout/pages/page-container/page-container.tsx
shell/app/layout/services/ai-chat.ts
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/views/index.ejs
shell/index.html
shell/vite.config.js

Add ai chat.
Fixes #
| 🇺🇸 English |  Add ai chat.  |
| 🇨🇳 中文    |  新增了ai聊天框。  |
❎ No

feat: ai chat

---

scheduler/src/proxy.ts
shell/app/layout/pages/page-container/components/chat-GPT/index.tsx
shell/app/layout/pages/page-container/page-container.tsx
shell/app/layout/services/ai-chat.ts

Fix ai center bug.
Fixes #
❎ No
| 🇺🇸 English |   Fixed ai chat box proxy and domain issues. |
| 🇨🇳 中文    |  修复ai聊天框代理和域名的问题。  |
❎ No

fix: ai chat bug

---

scheduler/src/proxy.ts
scheduler/src/util.ts
shell/app/layout/pages/page-container/components/chat-GPT/index.tsx

Fix ai chat proxy bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix ai chat proxy bug. |
| 🇨🇳 中文    |  修复了ai聊天框的代理问题。  |
❎ No

fix: ai chat proxy bug

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/pages/page-container/components/chat-GPT/gpt-item.tsx
shell/app/layout/pages/page-container/components/chat-GPT/user-item.tsx
shell/app/layout/services/ai-chat.ts
shell/vite.config.js
shell/webpack.config.js

AI chat proxy optimization.
Fixes #
❎ No
| 🇺🇸 English |  AI chat proxy optimization.   |
| 🇨🇳 中文    |  AI聊天框代理优化。  |
❎ No

fix: ai chat proxy optimization

---

shell/app/common/constants.ts
shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/services/ai-chat.ts

AI chat env variable optimization.
Fixes #
❎ No
| 🇺🇸 English |   AI chat env variable optimization.   |
| 🇨🇳 中文    |  AI聊天框环境变量优化。   |
❎ No

fix: ai chat env variable optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/pages/page-container/components/chat-GPT/gpt-item.tsx
shell/app/layout/pages/page-container/components/chat-GPT/index.tsx
shell/app/layout/pages/page-container/page-container.tsx
shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/views/index.ejs
shell/index.html

AI chat icon optimization.
Fixes #
| 🇺🇸 English |  AI chat icon optimization.  |
| 🇨🇳 中文    |  AI聊天框图标优化。   |
❎ No

fix: ai chat icon optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/pages/page-container/components/chat-GPT/gpt-item.tsx
shell/app/layout/pages/page-container/components/chat-GPT/index.tsx

AI chat optimization.
Fixes #
| 🇺🇸 English |    AI chat optimization.    |
| 🇨🇳 中文    |    AI聊天框优化。    |
❎ No

fix: ai chat optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/pages/page-container/components/chat-GPT/user-item.tsx
shell/app/layout/services/ai-chat.ts

AI chat input optimization.
Fixes #
❎ No
| 🇺🇸 English |   AI chat input optimization.  |
| 🇨🇳 中文    |  AI聊天框输入优化。  |
❎ No

fix: ai chat input optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/pages/page-container/components/chat-GPT/sidebar.tsx
shell/app/layout/services/ai-chat.ts

Fix ai chat add session bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix ai chat add session bug.   |
| 🇨🇳 中文    |    修复了AI聊天框新增会话的bug。  |
❎ No

fix: ai chat add session bug

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx
shell/app/layout/pages/page-container/components/chat-GPT/sidebar.tsx
shell/app/layout/services/ai-chat.ts

Fix ai chat request params bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix ai chat request params bug.  |
| 🇨🇳 中文    |  修复了ai聊天框请求参数的问题。  |
❎ No

fix: ai chat request params bug

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx

Fix ai chat params session id bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix ai chat params session id bug.  |
| 🇨🇳 中文    |  修复了ai聊天框session id的bug。  |
❎ No

fix: ai chat params session id bug

---

shell/app/modules/dop/pages/report/index.tsx

Fix project report detail display bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix project report detail display bug.  |
| 🇨🇳 中文    |  修复项目报表详情页的展示bug。 |
❎ No

fix: project report detail display bug

---

shell/app/common/components/configurable-filter/index.scss
shell/app/modules/dop/pages/report/index.tsx
shell/app/modules/dop/pages/report/rate-select.tsx
shell/app/modules/dop/services/index.ts

Fix project report select style bug, detail data display bug and table filter bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix project report select style bug, detail data display bug and table filter bug.  |
| 🇨🇳 中文    |  修复了项目报表下拉框样式bug，详情页数据展示bug以及列表筛选bug。  |
❎ No

fix: project report select style bug and detail data display bug

---

shell/app/modules/dop/pages/report/index.tsx

Fix project report table data bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix project report table data bug.  |
| 🇨🇳 中文    |  修复了项目报表列表数据的问题。  |
❎ No

fix: project report table data bug

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/dop/pages/report/chart-column.tsx
shell/app/modules/dop/pages/report/index.tsx
shell/app/modules/dop/services/index.ts

Project report table add sort.
Fixes #
❎ No
| 🇺🇸 English |  Project report table add sort.   |
| 🇨🇳 中文    |  项目报表列表增加排序。  |
❎ No

fix: project report table add sort

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/dop/pages/report/index.tsx
shell/app/modules/dop/services/index.ts

Fix project report detail data bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix project report detail data bug.  |
| 🇨🇳 中文    |  修复了项目报表详情数据的问题。  |
❎ No

fix: project report detail data bug

---

shell/app/common/utils/go-to.tsx
shell/app/menus/orgCenter.tsx
shell/app/modules/dop/pages/report/chart-column.tsx
shell/app/modules/dop/pages/report/index.tsx
shell/app/modules/dop/pages/report/rate-select.tsx
shell/app/modules/org/router.ts

Project report table filter optimization.
Fixes #
❎ No
| 🇺🇸 English |  Project report table filter optimization.  |
| 🇨🇳 中文    |  项目报表列表筛选优化。  |
❎ No

fix: project report table filter optimization

---

shell/app/menus/dop.tsx
shell/app/menus/orgCenter.tsx
shell/app/modules/dop/pages/report/index.tsx
shell/app/user/stores/_perm-org.ts

Project report add authority point.
Fixes #
❎ No
| 🇺🇸 English |  Project report add authority point.  |
| 🇨🇳 中文    |   项目报表增加权限点。  |
❎ No

fix: project report add authority point

---

shell/app/modules/dop/pages/report/chart-column.tsx
shell/app/modules/dop/pages/report/index.tsx
shell/app/modules/dop/services/index.ts

Project report detail add iterations filter.
Fixes #
| 🇺🇸 English |   Project report detail add iterations filter.   |
| 🇨🇳 中文    | 项目报表详情新增迭代筛选。  |
❎ No

fix: project report detail add iterations filter

---

shell/app/modules/dop/pages/report/index.tsx

Fix project report detail iteration filter bug.
Fixes #
❎ No
| 🇺🇸 English |   Fix project report detail iteration filter bug.   |
| 🇨🇳 中文    |   修复了项目报表详情跌掉筛选的bug。  |
❎ No

fix: project report detail iteration filter bug

---

shell/app/locales/en.json
shell/app/locales/zh.json
shell/app/modules/dop/pages/report/chart-column.tsx

Project report table chart optimization.
Fixes #
| 🇺🇸 English |   Project report table chart optimization.   |
| 🇨🇳 中文    |   项目报表表格中的图表优化。  |
❎ No

fix: project report table chart optimization

---

shell/app/modules/dop/pages/report/index.tsx

Org center project report table data optimization.
Fixes #
❎ No
| 🇺🇸 English |   Org center project report table data optimization.  |
| 🇨🇳 中文    |   管理中心项目报表列表数据优化。   |
❎ No

fix: org center project report table data optimization

---

shell/app/modules/dop/pages/report/chart-column.tsx
shell/app/modules/dop/pages/report/index.tsx

Project report project code filter optimization.
Fixes #
❎ No
| 🇺🇸 English |  Project report project code filter optimization. |
| 🇨🇳 中文    |  项目报表项目编号筛选优化。  |
❎ No

fix: project report project code filter optimization

---

shell/app/modules/dop/pages/report/index.tsx

Fix project report detail page jump iteration filter bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix project report detail page jump iteration filter bug.  |
| 🇨🇳 中文    |  修复了项目报表详情页跳转时迭代筛选的问题。  |
❎ No

fix: project report detail page jump iteration filter bug

---

shell/app/layout/pages/page-container/components/chat-GPT/index.tsx
shell/app/layout/services/ai-chat.ts
shell/app/modules/dop/pages/report/index.tsx

Ai chat add historical messages.
Fixes #
❎ No
| 🇺🇸 English |  AI chat add historical messages. |
| 🇨🇳 中文    |  AI聊天框增加历史消息。  |
❎ No

fix: ai chat add historical messages

---

shell/app/layout/pages/page-container/components/chat-GPT/index.tsx
shell/app/layout/pages/page-container/components/chat-GPT/sidebar.tsx
shell/app/layout/services/ai-chat.ts

AI chat add reset.
Fixes #
| 🇺🇸 English |  AI chat add reset.  |
| 🇨🇳 中文    |  AI聊天框增加重置。 |
❎ No

fix: ai chat add reset

---

shell/app/layout/pages/page-container/components/chat-GPT/index.tsx
shell/app/modules/dop/pages/report/index.tsx

Project report detail optimization.
Fixes #
❎ No
| 🇺🇸 English |   Project report detail optimization.  |
| 🇨🇳 中文    |   项目报表详情页优化。  |
❎ No

fix: project report detail optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/index.scss
shell/app/layout/pages/page-container/components/chat-GPT/index.tsx
shell/app/layout/pages/page-container/components/chat-GPT/sidebar.tsx
shell/app/layout/services/ai-chat.ts

AI chat sidebar style optimization.
Fixes #
| 🇺🇸 English |   AI chat sidebar style optimization.   |
| 🇨🇳 中文    |   AI聊天框菜单栏样式优化。   |
❎ No

fix: ai chat sidebar style optimization

---

shell/app/modules/application/pages/repo/components/repo-mr-table.tsx

Fix mr table page jump bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix mr table page jump bug.  |
| 🇨🇳 中文    |    修复了合并请求列表的跳转bug。   |
❎ No

fix: mr table page jump bug

---

shell/app/layout/pages/page-container/components/chat-GPT/index.tsx

Fix AI test bug outside project.
Fixes #
❎ No
| 🇺🇸 English |   Fix AI test bug outside project.   |
| 🇨🇳 中文    |  修复了AI测试在项目之外的报错。  |
❎ No

fix: ai test bug outside project

---

locales/en.json
locales/zh.json
shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/desc-list.tsx
shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/index.tsx

Fix bug of AI test batch apply.
Fixes #
❎ No
| 🇺🇸 English |   Fix bug of AI test batch apply.   |
| 🇨🇳 中文    |  修复了AI测试批量应用的bug。  |
❎ No

fix: ai test batch apply bug

---

shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/index.tsx

AI test style optimization.
Fixes #
❎ No
| 🇺🇸 English |  AI test style optimization.  |
| 🇨🇳 中文    |   AI测试样式优化。   |
❎ No

fix: ai test style optimization

---

shell/app/modules/project/pages/issue/import-export.tsx

Issues export optimization.
Fixes #
❎ No
| 🇺🇸 English |   Issues export optimization.   |
| 🇨🇳 中文    |   项目协同导出优化。   |
❎ No

fix: issues export optimization

---

shell/app/modules/project/pages/issue/import-export.tsx

Issues export internationalization optimization.
Fixes #
❎ No
| 🇺🇸 English |   Issues export internationalization optimization.  |
| 🇨🇳 中文    |   事项导出国际化优化。  |
❎ No

fix: issues export internationalization optimization

---

shell/app/modules/project/pages/issue/import-export.tsx

Issues import internationalization optimization.
Fixes #
❎ No
| 🇺🇸 English |  Issues import internationalization optimization.  |
| 🇨🇳 中文    |  事项导入国际化优化。  |
❎ No

fix: issues import internationalization optimization

---

shell/app/modules/org/pages/projects/create-project.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx
shell/app/modules/project/pages/settings/components/project-info.tsx

Project label optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12560/all?id=502426&iterationID=12560&type=REQUIREMENT)
❎ No
| 🇺🇸 English |   Project label optimization.  |
| 🇨🇳 中文    |   项目标签优化。   |
❎ No

fix: project label optimization

---

locales/zh.json
shell/app/modules/org/pages/projects/create-project.tsx
shell/app/modules/org/pages/projects/settings/info/index.tsx
shell/app/modules/project/pages/settings/components/project-info.tsx

Project label verification rule optimization.
Fixes #
❎ No
| 🇺🇸 English |  Project label verification rule optimization.  |
| 🇨🇳 中文    |   项目标签校验规则优化。  |
❎ No

fix: project label verification rule optimization

---

shell/app/modules/dop/pages/report/index.tsx

Project report detail link jump bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12560/all?id=505181&iterationID=12560&type=BUG)
❎ No
| 🇺🇸 English |  Project report detail link jump bug.  |
| 🇨🇳 中文    |  项目报表详情链接跳转bug。  |
❎ No

fix: project report detail link jump bug

---

shell/app/modules/dop/pages/report/index.tsx

Project report detail time range optimization.
Fixes #
❎ No
| 🇺🇸 English |  Project report detail time range optimization.  |
| 🇨🇳 中文    | 项目报表详情时间范围优化。  |
❎ No

fix: project report detail time range optimization

---

shell/app/modules/dop/pages/report/index.tsx
shell/app/modules/dop/services/index.ts

Project report detail add function point information.
Fixes #
| 🇺🇸 English |   Project report detail add function point information.  |
| 🇨🇳 中文    |  项目报表详情新增功能点信息。  |
❎ No

feat: project report detail add function point information

---

locales/en.json

Workbench personal report style optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12560/all?id=531942&iterationID=12560&type=BUG)
| 🇺🇸 English |   Workbench personal report style optimization.  |
| 🇨🇳 中文    |  工作台个人报表样式优化。  |
❎ No

fix: workbench personal report style optimization

---

shell/app/modules/project/common/components/issue/time-input.tsx
shell/app/modules/project/pages/iteration/table.tsx

Issues iteration table work hours optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12560/all?id=470224&iterationID=12560&type=TASK)
❎ No
| 🇺🇸 English |   Issues iteration table work hours optimization.  |
| 🇨🇳 中文    |  协同迭代列表人天预算展示优化。   |
❎ No

fix: issues iteration table work hours optimization

---

shell/app/modules/project/stores/project.tsx

Project menus load time optimization.
Fixes #
❎ No
| 🇺🇸 English |   Project menus load time optimization.  |
| 🇨🇳 中文    |   项目菜单加载时间优化。   |
❎ No

fix: project menus load time optimization

---

shell/app/modules/dop/pages/report/index.tsx

Project report detail reopen rate page jump optimization.
Fixes #
❎ No
| 🇺🇸 English |  Project report detail reopen rate page jump optimization.  |
| 🇨🇳 中文    |  项目报表详情重开率页面跳转优化。  |
❎ No

fix: project report detail reopen rate page jump optimization

---

shell/app/modules/project/pages/backlog/issue-item.scss
shell/app/modules/project/pages/backlog/issue-item.tsx

Backlog table add issue style bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12560/all?id=501979&iterationID=12560&tab=ALL&type=BUG)
| 🇺🇸 English |   Backlog table add issue style bug.  |
| 🇨🇳 中文    |   待规划列表新增事项样式问题。   |
❎ No

fix: backlog table add issue style bug

---

shell/app/modules/project/pages/backlog/issue-item.tsx

Requirement detail todo list time selector bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/iteration/12560/all?id=502431&iterationID=12560&tab=ALL&type=BUG)
❎ No
| 🇺🇸 English |  Requirement detail todo list time selector bug.  |
| 🇨🇳 中文    |  需求详情待办事项时间选择器的bug。  |
❎ No

fix: requirement detail todo list time selector bug

---

shell/app/modules/project/common/components/issue/time-input.tsx

Iteration add form validate optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=533832&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |   Iteration add form validate optimization.   |
| 🇨🇳 中文    |   迭代新增表单校验优化。   |
❎ No

fix: iteration add form validate optimization

---

shell/app/modules/project/pages/iteration/iteration-modal.tsx

Fix iteration edit form bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=533830&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |   Fix iteration edit form bug.    |
| 🇨🇳 中文    |   修复了迭代编辑表单的bug。   |
❎ No

fix: iteration edit form bug

---

shell/app/modules/project/pages/iteration/iteration-modal.tsx

Fix iteration add form work hours required bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=540502&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |    
Fix iteration add form work hours required bug.    |
| 🇨🇳 中文    |   修复了迭代新增表单人天预算必填时的bug。  |
❎ No

fix: iteration add form work hours required bug

---

shell/app/modules/project/pages/iteration/iteration-modal.tsx

Fix bug of iteration add form data residue.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=540503&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |  Fix bug of iteration add form data residue.  |
| 🇨🇳 中文    |   修复了迭代新增表单数据残留的问题。  |
❎ No

fix: iteration add form data residue

---

shell/app/modules/project/common/components/issue/time-input.tsx

Iteration add form work hours validate optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=540696&iterationID=12783&type=BUGe)
❎ No
| 🇺🇸 English |    Iteration add form work hours validate optimization.    |
| 🇨🇳 中文    | 迭代新增表单人天预算校验优化。   |
❎ No

fix: iteration add form work hours validate optimization

---

shell/app/modules/cmp/pages/cluster-container/cluster-terminal.tsx

fix namespace param typo in log file url
Fixes # namespace param typo in log file url
❎ No
| 🇺🇸 English |  fix namespace param typo in log file url           |
| 🇨🇳 中文    |    修复下载链接中namespace参数名称错误的问题         |
❎ No

fix: namespace param typo in log file url

---

shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/requirements-list.tsx

AI test requirement list optimization.
Fixes #
| 🇺🇸 English |   AI test requirement list optimization.   |
| 🇨🇳 中文    |   AI测试需求列表优化。  |
❎ No

fix: ai test requirement list optimization

---

shell/app/modules/cmp/pages/cluster-manage/operation-history.tsx

Fix clusters history table pagination bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=548679&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |   Fix clusters history table operation pagination bug.   |
| 🇨🇳 中文    |  修复了集群历史操作列表分页器的问题。  |
❎ No

fix: clusters history table pagination bug

---

shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/requirements-list.tsx

AI test requirement list bug in msp.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=547945&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |   AI test requirement list bug in msp.  |
| 🇨🇳 中文    |   AI测试需求列表在微服务平台的bug。 |
❎ No

fix: ai test requirement list bug in msp

---

shell/app/modules/project/common/components/pipeline-new/detail/build-log.tsx
shell/app/modules/project/common/components/pipeline-new/detail/execute.tsx

Project pipeline logs interface params optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=541040&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |  Project pipeline logs interface params optimization.  |
| 🇨🇳 中文    |   项目流水线日志接口传参优化。   |
❎ No

fix: project pipeline logs interface params optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/desc-list.tsx
shell/app/layout/pages/page-container/components/chat-GPT/functional-test-cases/index.tsx
shell/app/layout/services/ai-test.ts

AI test system prompt optimization.
Fixes #
❎ No
| 🇺🇸 English |   AI test system prompt optimization.   |
| 🇨🇳 中文    |   AI测试系统提示词优化。  |
❎ No

fix: ai test system prompt optimization

---

locales/en.json
locales/zh.json
shell/app/modules/application/pages/repo/components/compare-detail.tsx
shell/app/modules/application/pages/repo/components/file-diff.tsx
shell/app/modules/application/pages/repo/components/mr-comments.tsx
shell/app/modules/application/services/repo.ts
shell/app/modules/application/types/repo.d.ts

AI file level code review.
Fixes #
| 🇺🇸 English |   AI file level code review.  |
| 🇨🇳 中文    |   AI文件级的代码审查。   |
❎ No

feat: ai file level code review

---

shell/app/modules/runtime/pages/overview/components/index.tsx

fix log analyze console url application_id missing `dice` prefix
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=553663&iterationID=-1&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |  fix log analyze console url application_id missing `dice` prefix            |
| 🇨🇳 中文    |    修复日志服务addon跳转日志分析界面报错的问题          |
❎ No

fix: log analyze console url application_id missing `dice` prefix

---

shell/app/modules/application/pages/repo/components/mr-comments.tsx
shell/app/modules/dop/pages/report/index.tsx

Fix mr ai comment user display bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=552829&iterationID=-1&type=BUG)
| 🇺🇸 English |  Fix mr ai comment user display bug.  |
| 🇨🇳 中文    |   修复了mr的AI评论用户名显示问题。   |
❎ No

fix: mr ai comment user display bug

---

shell/app/modules/application/types/repo.d.ts

Fix mr ai comment type error.
Fixes #
❎ No
| 🇺🇸 English |   Fix mr ai comment type error.  |
| 🇨🇳 中文    |  修复了mr的AI评论类型错误。  |
❎ No

fix: mr ai comment type error

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

Mr AI comment file review optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=552842&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |  Mr AI comment file review optimization.   |
| 🇨🇳 中文    |   Mr的AI评论中文件审查优化。   |
❎ No

fix: mr ai comment file review optimization

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

AI code block level code review optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=556917&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |   AI code block level code review optimization.   |
| 🇨🇳 中文    |  AI代码块级审查优化。 |
❎ No

fix: ai code block level code review optimization

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

AI code block level code review single check bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=557307&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |  AI code block level code review single check bug.  |
| 🇨🇳 中文    |   AI代码块级审查单行选中bug。   |
❎ No

fix: ai code block level code review single check bug

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

Fix AI file level code review bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix AI file level code review bug.   |
| 🇨🇳 中文    |    修复了Ai文件级代码审查的bug。   |
❎ No

fix: ai file level code review bug

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

Only one code comment is allowed.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=552602&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |   Only one code comment is allowed.  |
| 🇨🇳 中文    |   同时只允许一个代码评论。    |
❎ No

fix: only one code comment is allowed

---

locales/en.json
locales/zh.json
shell/app/modules/application/pages/repo/components/file-diff.tsx

AI code review regenerate bug.
Fixes #
❎ No
| 🇺🇸 English |   AI code review regenerate bug.  |
| 🇨🇳 中文    |   AI代码审查重新生成bug。  |
❎ No

fix: ai code review regenerate bug

---

locales/en.json
locales/zh.json
shell/app/modules/application/pages/repo/components/file-diff.tsx

Closed mr disable review.
Fixes #
❎ No
| 🇺🇸 English |   Closed mr disable review.  |
| 🇨🇳 中文    |   已关闭的mr禁用审查。  |

fix: closed mr disable review

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

Mr AI review optimization.
Fixes #
❎ No
| 🇺🇸 English |  Mr AI review optimization. |
| 🇨🇳 中文    |  Mr的ai审查优化。  |
❎ No

fix: mr ai review optimization

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

Mr review show style change bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=558702&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |   Mr review show style change bug.   |
| 🇨🇳 中文    |  Mr审查时展示方式切换的bug。 |

fix: mr review show style change bug

---

shell/app/modules/application/pages/repo/components/mr-comments.tsx

Mr review comments location optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=558805&iterationID=12560&type=TASK)
❎ No
| 🇺🇸 English |    Mr review comments location optimization.    |
| 🇨🇳 中文    |    Mr审查的评论位置优化。    |

fix: mr review comments location optimization

---

shell/app/modules/application/pages/repo/components/file-diff.tsx
shell/app/modules/application/types/repo.d.ts

Mr review comments line index display optimization.
Fixes #
| 🇺🇸 English |   Mr review comments line index display optimization.  |
| 🇨🇳 中文    |  Mr审查的评论行行号展示方式优化。  |

fix: mr review comments line index display optimization

---

shell/app/modules/application/pages/repo/components/file-diff.tsx

Mr file review style optimization.
Fixes #
| 🇺🇸 English |  Mr file review style optimization.  |
| 🇨🇳 中文    |    Mr文件级的审查样式优化。  |

fix: mr file review style optimization

---

locales/en.json
locales/zh.json
shell/app/modules/application/pages/repo/components/compare-detail.tsx
shell/app/modules/application/pages/repo/components/repo-mr-form.tsx
shell/app/modules/application/stores/repo.ts

Mr AI review creating optimization.
Fixes #
❎ No
| 🇺🇸 English |   Mr AI review creating optimization.  |
| 🇨🇳 中文    |   Mr的AI审查创建中的优化。   |

fix: mr ai review creating optimization

---

locales/en.json
locales/zh.json
shell/app/layout/pages/page-container/components/chat-GPT/sidebar.tsx
shell/app/layout/services/ai-chat.ts
shell/app/modules/application/pages/repo/components/file-diff.tsx

Mr AI review and AI chat optimization.
Fixes #
❎ No
| 🇺🇸 English |   Mr AI review and AI chat optimization.    |
| 🇨🇳 中文    |     Mr的AI审查和AI聊天优化。    |

fix: mr ai review and ai chat optimization

---

pnpm-lock.yaml
shell/package.json

AI components update.
Fixes #
❎ No
| 🇺🇸 English |   AI components update   |
| 🇨🇳 中文    |  AI组件更新。  |
❎ No

fix: ai components update

---

shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx

AI knowledge input bug.
Fixes #
❎ No
| 🇺🇸 English |   AI knowledge input bug.   |
| 🇨🇳 中文    |   AI知识库输入框bug。  |
❎ No

fix: ai knowledge input bug

---

scheduler/src/proxy.ts

Fix AI knowledge proxy bug.
Fixes #
❎ No
| 🇺🇸 English |   Fix AI knowledge proxy bug.   |
| 🇨🇳 中文    |    修复了AI知识库代理问题。  |
❎ No

fix: ai knowledge proxy bug

---

shell/app/layout/pages/page-container/components/chat-GPT/gpt-item.tsx
shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/index.tsx
shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx

Fix AI knowledge bug.
Fixes #
❎ No
| 🇺🇸 English |  Fix AI knowledge bug.    |
| 🇨🇳 中文    |   修复了AI知识库的bug。   |
❎ No

fix: ai knowledge bug

---

shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/index.tsx
shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx

AI knowledge question list style optimization.
Fixes #
->
| 🇺🇸 English |  AI knowledge question list style optimization.   |
| 🇨🇳 中文    |   AI知识库问题列表样式优化。  |
❎ No

fix: ai knowledge question list style optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/index.tsx

AI knowledge question list optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=562633&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |   AI knowledge question list optimization.    |
| 🇨🇳 中文    |   AI知识库问题列表优化。   |
❎ No

fix: ai knowledge question list optimization

---

locales/en.json
locales/zh.json
shell/app/layout/pages/page-container/components/chat-GPT/gpt-item.tsx
shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx
shell/app/layout/services/ai-knowledge.ts

AI knowledge add extended answer.
Fixes #
| 🇺🇸 English |   AI knowledge add extended answer.  |
| 🇨🇳 中文    |   AI知识库增加延展回答。  |
❎ No

feat: ai knowledge add extended answer

---

locales/en.json
locales/zh.json
shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/index.tsx
shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx
shell/app/layout/services/ai-knowledge.ts

AI knowledge question list add search.
Fixes #
| 🇺🇸 English |  AI knowledge question list add search.  |
| 🇨🇳 中文    |   AI知识库问题列表增加搜索   |
❎ No

fix: ai knowledge question list add search

---

shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx

AI knowledge input empty bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=562859&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |   AI knowledge input empty bug.   |
| 🇨🇳 中文    |   AI知识库输入框空时的bug。   |
❎ No

fix: ai knowledge input empty bug

---

shell/app/layout/pages/page-container/components/chat-GPT/chat.tsx

AI chat param optimization.
Fixes #
❎ No
| 🇺🇸 English |  AI chat param optimization.   |
| 🇨🇳 中文    |   AI聊天框参数优化。  |

fix: ai chat param optimization

---

shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx

AI chat input blank bug.
Fixes #
❎ No
| 🇺🇸 English |    AI chat input blank bug.  |
| 🇨🇳 中文    |   AI聊天框输入框空白bug。 |
❎ No

fix: ai chat input blank bug

---

shell/app/layout/pages/page-container/components/chat-GPT/knowledge-base/simple-chat.tsx

AI chat input multiple spaces bug.
Fixes #
❎ No
| 🇺🇸 English |   AI chat input multiple spaces bug.   |
| 🇨🇳 中文    |   AI聊天框输入框多个空格的bug。  |
❎ No

fix: ai chat input multiple spaces bug

---

shell/app/modules/gallery/pages/detail.tsx

Gallery detail download version select style optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=565528&iterationID=12783&tab=BUG&type=BUG)
| 🇺🇸 English |  Gallery detail download version select style optimization.   |
| 🇨🇳 中文    |   Gallery详情下载版本下拉框样式优化。    |

fix: gallery detail download version select style optimization

---

shell/app/modules/gallery/pages/detail.tsx

Gallery detail download version select height optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=565528&iterationID=12783&tab=BUG&type=BUG)
| 🇺🇸 English |  Gallery detail download version select height optimization.   |
| 🇨🇳 中文    |   Gallery详情下载版本下拉框高度优化。    |

fix: gallery detail download version select height optimization

---

shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
shell/app/modules/org/stores/issue-field.ts
shell/app/modules/project/pages/settings/components/project-settings.tsx

Project level custom fields.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=531974&iterationID=12783&type=REQUIREMENT)
❎ No
| 🇺🇸 English |   Project level custom fields.  |
| 🇨🇳 中文    |   项目级的自定义字段。  |
❎ No

feat: project level custom fields

---

shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
shell/app/modules/org/stores/issue-field.ts

Project level custom fields params name change.
Fixes #
❎ No
| 🇺🇸 English |   Project level custom fields params name change.   |
| 🇨🇳 中文    |   项目级自定义字段参数名改动。 |
❎ No

fix: project level custom fields params name change

---

shell/app/modules/org/stores/issue-field.ts

Project level custom fields interface params change.
Fixes #
❎ No
| 🇺🇸 English |   Project level custom fields interface params change.   |
| 🇨🇳 中文    |   项目级自定义字段接口参数改变。  |
❎ No

fix: project level custom fields interface params change

---

shell/app/modules/org/pages/projects/issue-field-manage.tsx
shell/app/modules/org/stores/issue-field.ts

Project level custom fields remove fixed fields.
Fixes #
❎ No
| 🇺🇸 English |   Project level custom fields remove fixed fields.   |
| 🇨🇳 中文    |    项目级自定义字段去掉固定字段。  |
❎ No

fix: project level custom fields remove fixed fields

---

shell/app/modules/org/pages/projects/issue-field-manage.tsx
shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
shell/app/modules/org/pages/projects/issue-type-manage.tsx
shell/app/modules/org/stores/issue-field.ts

Project level custom fields params optimization.
Fixes #
❎ No
| 🇺🇸 English |   Project level custom fields params optimization.   |
| 🇨🇳 中文    |   项目级自定义字段参数优化。   |
❎ No

fix: project level custom fields params optimization

---

shell/app/modules/org/pages/projects/issue-field-manage.tsx

Project level custom fields params bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=567670&iterationID=12783&tab=ALL&type=BUG)
❎ No
| 🇺🇸 English |   Project level custom fields params bug.    |
| 🇨🇳 中文    |    项目级自定义字段参数错误。   |
❎ No

fix: project level custom fields params bug

---

shell/app/modules/application/pages/settings/components/app-notify/common-notify-group.tsx
shell/app/modules/application/services/notify-group.ts

Alarm management notify group delete bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=559498&iterationID=12783&type=BUG)
❎ No
| 🇺🇸 English |    Alarm management notify group delete bug.   |
| 🇨🇳 中文    |   告警管理通知组删除bug。   |
❎ No

fix: alarm management notify group delete bug

---

shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
shell/app/modules/org/pages/projects/issue-type-manage.tsx

Org level custom fields params bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=567793&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |  Org level custom fields params bug.   |
| 🇨🇳 中文    |   组织级自定义字段参数问题。   |
❎ No

fix: org level custom fields params bug

---

shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx

Org level issue type params bug.
Fixes #
❎ No
| 🇺🇸 English |  Org level issue type params bug.   |
| 🇨🇳 中文    |   组织级事项类型传参问题。   |
❎ No

fix: org level issue type params bug

---

shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/types/issue.d.ts

Issues custom fields bug.
Fixes #
❎ No
| 🇺🇸 English |   Issues custom fields bug.    |
| 🇨🇳 中文    |    事项自定义字段bug。   |
❎ No

fix: issues custom fields bug

---

shell/app/modules/org/stores/issue-field.ts

Fix issues custom fields move bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=568525&iterationID=12783&tab=ALL&type=TASK)
❎ No
| 🇺🇸 English |   Fix issues custom fields move bug.   |
| 🇨🇳 中文    |   修复项目自定义字段移动的问题。   |
❎ No

fix: issues custom fields move bug

---

shell/app/modules/project/pages/iteration/table.tsx

Iteration delete permission optimization.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=569823&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |   Iteration delete permission optimization.    |
| 🇨🇳 中文    |   迭代删除权限优化。    |
❎ No

fix: iteration delete permission optimization

---

shell/app/modules/project/pages/settings/components/project-settings.tsx

Project level custom fields permission optimization.
Fixes #
❎ No
| 🇺🇸 English |   Project level custom fields permission optimization.   |
| 🇨🇳 中文    |   项目级自定义字段权限优化。    |
❎ No

fix: project level custom fields permission optimization

---

shell/app/modules/project/services/project-iteration.ts

Iteration delete interface params optimization.
Fixes #
❎ No
| 🇺🇸 English |   Iteration delete interface params optimization.   |
| 🇨🇳 中文    |    迭代删除接口参数优化。   |
❎ No

fix: iteration delete interface params optimization

---

shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx

Issues custom fields hide default fields.
Fixes #
❎ No
| 🇺🇸 English |   Issues custom fields hide default fields.   |
| 🇨🇳 中文    |   事项自定义字段隐藏默认字段。  |
❎ No

fix: issues custom fields hide default fields

---

shell/app/modules/org/pages/projects/issue-field-manage.tsx
shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
shell/app/modules/org/pages/projects/issue-type-manage.tsx
shell/app/modules/org/stores/issue-field.ts

Issues custom fields interface params optimization.
Fixes #
❎ No
| 🇺🇸 English |   Issues custom fields interface params optimization.   |
| 🇨🇳 中文    |   协同自定义字段接口参数优化。   |
❎ No

fix: issues custom fields interface params optimization

---

shell/app/modules/org/pages/projects/issue-field-manage.tsx
shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
shell/app/modules/org/pages/projects/issue-type-manage.tsx
shell/app/modules/org/stores/issue-field.ts
shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/pages/backlog/issue-item.tsx
shell/app/modules/project/types/issue.d.ts

Fix issues custom fields interface params bug.
Fixes #
❎ No
| 🇺🇸 English |   Fix issues custom fields interface params bug.    |
| 🇨🇳 中文    |    修复协同自定义字段接口参数bug。   |
❎ No

fix: issues custom fields interface params bug

---

shell/app/layout/stores/layout.ts
shell/app/modules/org/pages/projects/issue-field-manage.tsx
shell/app/modules/org/pages/projects/issue-field-setting-modal.tsx
shell/app/modules/org/pages/projects/issue-type-manage.tsx
shell/app/modules/org/stores/issue-field.ts

Fix config debug page bug caused by license.
Fixes #
❎ No
| 🇺🇸 English |  Fix config debug page bug caused by license.   |
| 🇨🇳 中文    |   修复了证书导致的组件话调试页面的bug。   |
❎ No

fix: config debug page bug caused by license

---

shell/app/modules/project/common/components/issue/iteration-select.tsx

Create issue hide archived iterations.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=552275&iterationID=12783&type=TASK)
❎ No
| 🇺🇸 English |   Create issue hide archived iterations.  |
| 🇨🇳 中文    |    创建事项隐藏归档的迭代。   |
❎ No

fix: create issue hide archived iterations

---

shell/app/modules/org/pages/setting/license-info.tsx
shell/app/modules/org/pages/setting/org-setting.tsx
shell/app/modules/org/services/license.ts

Licenses management in org center.
Fixes #
❎ No
| 🇺🇸 English |  Licenses management in org center.   |
| 🇨🇳 中文    |   在管理中心的证书管理。  |
❎ No

fix: licenses management in org center

---

shell/app/layout/stores/layout.ts

No licenses bug.
Fixes #
❎ No
| 🇺🇸 English |    No licenses bug.    |
| 🇨🇳 中文    |   没有证书时的bug。  |
❎ No

fix: no licenses bug

---

shell/app/modules/application/pages/repo/components/mr-comments.tsx

Mr commits display bug.
Fixes #
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=586490&iterationID=12783&tab=BUG&type=BUG)
❎ No
| 🇺🇸 English |   Mr commits display bug.  |
| 🇨🇳 中文    |    合并请求的评论展示问题。  |
❎ No

fix: mr commits display bug

---

core/src/stores/route.ts
shell/babel.config.js
shell/vite.config.js

Fixes #
❎ No
| 🇺🇸 English |    fix: fix fdp location no auth          |
| 🇨🇳 中文    |   fix: fix fdp location no auth           |
❎ No

fix: fix fdp location no auth

---

pnpm-lock.yaml

Fixes #
❎ No
| 🇺🇸 English |    fix: fix request to nlark error          |
| 🇨🇳 中文    |    fix: fix request to nlark error          |
❎ No

fix: fix request to nlark error

---

shell/app/config-page/components/api-editor/api-editor.scss
shell/app/config-page/components/bubble-graph/index.tsx
shell/app/config-page/components/line-graph/index.tsx
shell/app/modules/application/pages/pipeline/index.tsx
shell/app/modules/application/pages/pipeline/obsoleted-pipeline.tsx
shell/app/modules/project/common/components/issue/edit-issue-drawer/index.tsx
shell/app/modules/project/common/components/issue/issue-config.tsx
shell/app/modules/project/common/components/pipeline-new/detail/info.tsx
shell/app/modules/project/common/components/pipeline-new/form.tsx
shell/app/modules/project/common/components/pipeline-new/list.tsx
shell/app/modules/project/common/components/pipeline-new/record-detail.tsx
shell/app/modules/project/common/components/workflow/add-flow.tsx
shell/app/modules/project/common/issue-config.ts
shell/app/modules/project/pages/deploy/index.tsx
shell/app/modules/project/router.tsx

Fixes #
❎ No
| 🇺🇸 English |       fix: fix i18n in dop       |
| 🇨🇳 中文    |  fix: fix i18n in dop            |
❎ No

fix: fix i18n in dop

---

shell/app/common/components/markdown-editor/upload-plugin.tsx

Fixes #
❎ No
| 🇺🇸 English |    fix: fix mr editor loading plugin          |
| 🇨🇳 中文    |     fix: fix mr editor loading plugin         |
❎ No

fix: fix mr editor loading plugin

---

shell/app/modules/project/common/components/params-config/index.tsx

修复环境变量参数加密配置
- [ x ] I18n is finished and updated by cli
- [ x ] Form fields validation is added and length is limited
- [ x ] Display normally on small screen
- [ x ] Display normally when some data is empty or null
- [ x ] Display normally in english mode
Fixes #
https://erda.cloud/erda/dop/projects/387/issues/all?id=588196&iterationID=12783&tab=BUG&type=BUG
❎ No
| 🇺🇸 English |       make project params config's  encrypt   correct when first params is encrypt    |
| 🇨🇳 中文    |       修复项目环境变量设置是否加密变量传递       |
❎ No

fix(dop): fix encrypt in project params config

---

shell/app/modules/application/pages/build-detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/application/pages/obsoleted-pipeline/run-detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/project/common/components/pipeline-new/detail/pipeline-chart/pipeline-node.tsx
shell/app/modules/project/pages/test-plan/plan-modal.tsx

Fixes #
❎ No
| 🇺🇸 English |      fix: fix plan jump error        |
| 🇨🇳 中文    |     fix: fix plan jump error         |
❎ No

fix: fix plan jump error

---

shell/mf.config.js

Fixes #
❎ No
| 🇺🇸 English |      fix: fix mf_share        |
| 🇨🇳 中文    |   fix: fix mf_share           |
❎ No

fix: fix mf_share

---

scheduler/src/filters/not-found.filter.ts

Fixes #
❎ No
| 🇺🇸 English |     fix: fix node header refer         |
| 🇨🇳 中文    |     fix: fix node header refer         |
❎ No

fix: fix node header refer

---

shell/app/modules/dcos/common/containers/terminal.tsx
shell/app/modules/project/pages/addon/addon-category.tsx
shell/app/modules/project/pages/third-service/components/third-addon-form.tsx
shell/app/modules/project/types/custom-addon.d.ts

Fixes #
❎ No
| 🇺🇸 English |      fix: fix addon opt version        |
| 🇨🇳 中文    |    fix: fix addon opt version          |
❎ No

fix: fix addon opt version

---

shell/app/modules/org/common/audit-templates.json

Add kill pod audit template.
@sfwn @luobily 
- [ x ] I18n is finished and updated by cli
- [ x ] Form fields validation is added and length is limited
- [ x ] Display normally on small screen
- [ x ] Display normally when some data is empty or null
- [ x ] Display normally in english mode
Fixes #
❎ No
| 🇺🇸 English |add kill pod audit template              |
| 🇨🇳 中文    | 增加删除 pod 审计模板             |
❎ No

chore: add kill pod audit template

---

shell/app/modules/org/pages/projects/settings/info/index.tsx

Fixes #
❎ No
| 🇺🇸 English |   fix: fix project info edit           |
| 🇨🇳 中文    |    fix: fix project info edit          |
❎ No

fix: fix project info edit

---

.github/workflows/codecov.yml
erda.yml
scheduler/src/proxy.ts
scheduler/src/util.ts
shell/app/common/components/pure-log-roller/download-log-modal.tsx
shell/app/common/services/index.ts
shell/app/locales/en.json
shell/app/locales/zh.json

❎ No
| 🇺🇸 English |       The log download supports custom duration.       |
| 🇨🇳 中文    |         日志下载功能支持自定义时长     |
❎ No

feat: The log download supports custom duration.
